Gwion dev-docs: lang/analys.c File Reference
--- layout: homepage title: analys.c image: feature: abstract-1.jpg ---
analys.c File Reference
#include <stdlib.h>
#include <math.h>
#include "defs.h"
#include "vm.h"
#include "type.h"
#include "import.h"
#include "bbq.h"
#include "ugen.h"
#include "array.h"
#include "object.h"
#include "err_msg.h"
Data Structures
struct sp_buffer
struct FFT
struct _FFT
Typedefs
typedef struct _FFT _FFT
typedef double(* f_analys) (_FFT *fft)
Functions
static m_int sp_buffer_create (sp_buffer **p, m_uint size)
static m_int sp_buffer_destroy (sp_buffer *buffer)
static m_int sp_buffer_add (sp_buffer *buffer, m_float f)
static m_float * sp_buffer_get (sp_buffer *buffer)
static m_bool fft_tick (UGen u)
static void fft_ctor (M_Object o, VM_Shred shred)
static DTOR (fft_dtor)
static MFUN (fft_init)
static MFUN (fft_compute)
static m_bool import_fft (Env env)
m_float array_max (m_float *f, unsigned int size, unsigned int *index)
m_float compute_centroid (_FFT *fft)
m_float compute_spread (_FFT *fft)
m_float compute_skewness (_FFT *fft)
m_float compute_kurtosis (_FFT *fft)
m_float compute_rms (_FFT *fft)
m_float compute_rolloff (_FFT *fft)
m_float compute_freq (_FFT *fft)
m_float compute_asc (_FFT *fft)
m_float compute_ass (_FFT *fft)
static m_float ana_dummy (FFT *fft)
static MFUN (ana_compute)
static MFUN (ana_get_fft)
static MFUN (ana_set_fft)
static void ana_ctor (M_Object o, VM_Shred shred)
static void ana_dtor (M_Object o, VM_Shred shred)
static m_bool import_ana (Env env)
static void centroid_ctor (M_Object o, VM_Shred shred)
static m_bool import_centroid (Env env)
static void spread_ctor (M_Object o, VM_Shred shred)
static m_bool import_spread (Env env)
static void skewness_ctor (M_Object o, VM_Shred shred)
static m_bool import_skewness (Env env)
static void kurtosis_ctor (M_Object o, VM_Shred shred)
static m_bool import_kurtosis (Env env)
static void rms_ctor (M_Object o, VM_Shred shred)
static m_bool import_rms (Env env)
static void rolloff_ctor (M_Object o, VM_Shred shred)
static MFUN (rolloff_get_percent)
static MFUN (rolloff_set_percent)
static m_bool import_rolloff (Env env)
static void freq_ctor (M_Object o, VM_Shred shred)
static m_bool import_freq (Env env)
static void asc_ctor (M_Object o, VM_Shred shred)
static m_bool import_asc (Env env)
static void ass_ctor (M_Object o, VM_Shred shred)
static m_bool import_ass (Env env)
static void fc_ctor (M_Object o, VM_Shred shred)
static void fc_dtor (M_Object o, VM_Shred shred)
static MFUN (fc_compute)
static MFUN (fc_add)
static MFUN (fc_rem)
INSTR (fc_connect)
INSTR (fc_disconnect)
static m_bool import_fc (Env env)
m_bool import_analys (Env env)
Variables
static struct Type_ t_fft = { "FFT", SZ_INT, &t_ugen}
static struct Type_ t_ana = { "ANA", SZ_INT, &t_object}
m_int o_ana__fft
m_int o_ana_fft
m_int o_ana_fn
static struct Type_ t_centroid = { "Centroid", SZ_INT, &t_ana }
static struct Type_ t_spread = { "Spread", SZ_INT, &t_ana }
static struct Type_ t_skewness = { "Skewness", SZ_INT, &t_ana }
static struct Type_ t_kurtosis = { "Kurtosis", SZ_INT, &t_ana }
static struct Type_ t_rms = { "RMS", SZ_INT, &t_ana }
static struct Type_ t_rolloff = { "Rolloff", SZ_INT, &t_ana }
static struct Type_ t_freq = { "Freq", SZ_INT, &t_ana }
static struct Type_ t_asc = { "ASC", SZ_INT, &t_ana }
static struct Type_ t_ass = { "ASS", SZ_INT, &t_ana }
static struct Type_ t_fc = { "FC", SZ_INT, &t_object }
static m_int o_fc_vector
Typedef Documentation
_FFT
typedef struct _FFT _FFT
f_analys
typedef double(* f_analys) (_FFT *fft)
Definition at line 182 of file analys.c.
Function Documentation
ana_ctor()
static void ana_ctor (M_Object o, VM_Shred shred) static
Definition at line 483 of file analys.c.
References ana_dummy(), VM::bbq, M_Object_::d, M_Object_::data, malloc(), o_ana__fft, o_ana_fn, _FFT::percent, BBQ_::sp, _FFT::sr, and VM_Shred_::vm_ref.
Referenced by import_ana().
 {
   _FFT* _fft = *(_FFT**)(o->d.data + o_ana__fft) = malloc(sizeof(_FFT));
   _fft->sr = shred->vm_ref->bbq->sp->sr;
   _fft->percent = 50; // rolloff;
   *(f_analys*)(o->d.data + o_ana_fn) = (f_analys)ana_dummy;
 }
ana_dtor()
static void ana_dtor (M_Object o, VM_Shred shred) static
Definition at line 491 of file analys.c.
References M_Object_::d, M_Object_::data, free(), and o_ana__fft.
Referenced by import_ana().
 {
   free(*(_FFT**)(o->d.data + o_ana__fft));
 }
ana_dummy()
static m_float ana_dummy (FFT * fft) static
Definition at line 438 of file analys.c.
Referenced by ana_ctor().
 {
   return 0.0;
 }
array_max()
m_float array_max (m_float * f, unsigned int size, unsigned int * index)
Definition at line 184 of file analys.c.
References Type_::size.
 {
   unsigned int i;
   m_float max = -INFINITY;
   for(i = 0; i < size; i++) {
     if(f[i] > max) {
       max = f[i];
       *index = i;
     }
   }
   return max;
 }
asc_ctor()
static void asc_ctor (M_Object o, VM_Shred shred) static
Definition at line 626 of file analys.c.
References compute_asc(), M_Object_::d, M_Object_::data, and o_ana_fn.
Referenced by import_asc().
 {
   *(f_analys*)(o->d.data + o_ana_fn) = (f_analys)compute_asc;
 }
ass_ctor()
static void ass_ctor (M_Object o, VM_Shred shred) static
Definition at line 639 of file analys.c.
References compute_ass(), M_Object_::d, M_Object_::data, and o_ana_fn.
Referenced by import_ass().
 {
   *(f_analys*)(o->d.data + o_ana_fn) = (f_analys)compute_ass;
 }
centroid_ctor()
static void centroid_ctor (M_Object o, VM_Shred shred) static
Definition at line 519 of file analys.c.
References compute_centroid(), M_Object_::d, M_Object_::data, and o_ana_fn.
Referenced by import_centroid().
 {
   *(f_analys*)(o->d.data + o_ana_fn) = (f_analys)compute_centroid;
 }
compute_asc()
m_float compute_asc (_FFT * fft)
Definition at line 295 of file analys.c.
References compute_freq(), _FFT::fval, and _FFT::size.
Referenced by asc_ctor(), and compute_ass().
 {
   unsigned int i;
   m_float ret = 0.0;
   m_float sum = 0.0;
   for(i = 0; i < fft->size / 2; i++) {
     ret += log2( ( compute_freq(fft) / 1000. ) ) * fft->fval[i];
     sum += fft->fval[i];
   }
   return ret / sum;
 }
compute_ass()
m_float compute_ass (_FFT * fft)
Definition at line 307 of file analys.c.
References compute_asc(), compute_freq(), _FFT::fval, and _FFT::size.
Referenced by ass_ctor().
 {
   unsigned int i;
   m_float ret = 0.0;
   m_float sum = 0.0;
   m_float asc = compute_asc(fft);
   for(i = 0; i < fft->size / 2; i++) {
     m_float f;
     f = log2(compute_freq(fft) / 1000.) - asc;
     f *= f;
     f *= fft->fval[i];
     ret += f;
     sum += fft->fval[i];
   }
   return ret / sum;
 }
compute_centroid()
m_float compute_centroid (_FFT * fft)
Definition at line 197 of file analys.c.
References _FFT::fval, and _FFT::size.
Referenced by centroid_ctor(), compute_kurtosis(), compute_skewness(), and compute_spread().
 {
   m_float m0 = 0.0;
   m_float m1 = 0.0;
   m_float centroid = 0.0;
   unsigned int i;
   /* Compute centroid using moments */
   for( i = 0; i < fft->size / 2; i++ ) {
     m1 += i * fft->fval[i];
     m0 += fft->fval[i];
   }
   if( m0 != 0.0 )
     centroid = m1 / m0;
   else
     centroid = fft->size / 2.0; /* Perfectly balanced */
   return centroid / fft->size;
 }
compute_freq()
m_float compute_freq (_FFT * fft)
Definition at line 279 of file analys.c.
References _FFT::fval, _FFT::size, and _FFT::sr.
Referenced by compute_asc(), compute_ass(), and freq_ctor().
 {
   unsigned int i;
   m_float max = -0;
   m_float where = 0;
   for(i = 0; i < fft->size / 2; i++) {
     /*      if(fft->cval[i][0] > max)*/
     if(fft->fval[i] > max) {
       /*            max = fft->cval[i][0];*/
       max = fft->fval[i];
       where = i;
     }
   }
   return where / fft->size * fft->sr;
 }
compute_kurtosis()
m_float compute_kurtosis (_FFT * fft)
Definition at line 235 of file analys.c.
References compute_centroid(), _FFT::fval, and _FFT::size.
Referenced by kurtosis_ctor().
 {
   unsigned int i;
   m_float ret = 0;
   m_float mu = compute_centroid(fft);
   for(i = 0; i < fft->size / 2; i++)
     ret += ( (i - mu) * (i - mu) * (i - mu) * (i - mu)) * fft->fval[i];
   return ret / fft->size;
 }
compute_rms()
m_float compute_rms (_FFT * fft)
Definition at line 246 of file analys.c.
References _FFT::fval, and _FFT::size.
Referenced by rms_ctor().
 {
   m_float rms = 0.0;
   m_uint  i;
   /* get sum of squares */
   for(i = 0; i < fft->size / 2; i++)
     rms += (fft->fval[i] * fft->fval[i]);
   rms /= fft->size;
   rms = sqrt(rms);
   return rms;
 }
compute_rolloff()
m_float compute_rolloff (_FFT * fft)
Definition at line 258 of file analys.c.
References _FFT::fval, _FFT::percent, Type_::size, and _FFT::size.
Referenced by rolloff_ctor().
 {
   m_float sum = 0.0, target;
   unsigned int i;
   /* sanity check */
   /* assert( percent >= 0 && percent <= 1 ); */
   /* iterate */
   for( i = 0; i < fft->size / 2; i++ )
     sum += fft->fval[i];
   /* the target */
   target = sum * fft->percent / 100.;
   sum = 0.0;
   /* iterate */
   for( i = 0; i < fft->size; i++ ) {
     sum += fft->fval[i];
     if( sum >= target )
       break;
   }
   return i / (m_float)fft->size;
 }
compute_skewness()
m_float compute_skewness (_FFT * fft)
Definition at line 225 of file analys.c.
References compute_centroid(), _FFT::fval, and _FFT::size.
Referenced by skewness_ctor().
 {
   unsigned int i;
   m_float ret = 0;
   m_float mu = compute_centroid(fft);
   for(i = 0; i < fft->size / 2; i++)
     ret += ( (i - mu) * (i - mu) * (i - mu) ) * fft->fval[i];
   return ret / fft->size;
 }
compute_spread()
m_float compute_spread (_FFT * fft)
Definition at line 215 of file analys.c.
References compute_centroid(), _FFT::fval, and _FFT::size.
Referenced by spread_ctor().
 {
   unsigned int i;
   m_float ret = 0;
   m_float mu = compute_centroid(fft);
   for(i = 0; i < fft->size / 2; i++)
     ret += ( (i - mu) * (i - mu) ) * fft->fval[i];
   return ret / fft->size;
 }
DTOR()
static DTOR (fft_dtor) static
Definition at line 94 of file analys.c.
References FFT::buf, FFT::fft, free(), FFT::frq, and sp_buffer_destroy().
 {
   FFT* ana = (FFT*)o->ugen->ug;
   if(ana->buf)
     sp_buffer_destroy(ana->buf);
   if(ana->frq) {
     deleteFFTFREQS(ana->frq);
     free(ana->frq);
   }
   if(ana->fft)
     FFTwrapper_destroy(&ana->fft);
   free(ana);
 }
fc_ctor()
static void fc_ctor (M_Object o, VM_Shred shred) static
Definition at line 653 of file analys.c.
References M_Object_::d, M_Object_::data, new_Vector(), and o_fc_vector.
Referenced by import_fc().
 {
   *(Vector*)(o->d.data + o_fc_vector) = new_Vector();
 }
fc_dtor()
static void fc_dtor (M_Object o, VM_Shred shred) static
Definition at line 657 of file analys.c.
References M_Object_::d, M_Object_::data, free_Vector(), and o_fc_vector.
Referenced by import_fc().
 {
   free_Vector(*(Vector*)(o->d.data + o_fc_vector));
 }
fft_ctor()
static void fft_ctor (M_Object o, VM_Shred shred) static
Definition at line 87 of file analys.c.
References assign_ugen(), fft_tick(), UGen_::tick, UGen_::ug, and M_Object_::ugen.
Referenced by import_fft().
 {
   FFT* ana = o->ugen->ug = calloc(1, sizeof(FFT));
   assign_ugen(o->ugen, 1, 1, 1, ana);
   o->ugen->tick = fft_tick;
 }
fft_tick()
static m_bool fft_tick (UGen u) static
Definition at line 69 of file analys.c.
References base_tick(), FFT::buf, FFT::fft, free(), FFT::frq, UGen_::in, UGen_::out, sp_buffer_add(), sp_buffer_get(), UGen_::trig, UGen_::ug, and M_Object_::ugen.
Referenced by fft_ctor().
 {
   m_float* smp;
   FFT* ana = (FFT*)u->ug;
   base_tick(u);                         // compute inputs
   if(!ana->buf)
     return 1;
   sp_buffer_add(ana->buf, u->in);      // add them to buffer
   if(u->trig && u->trig->ugen->out) {  // if trigged, compute fft
     smp = sp_buffer_get(ana->buf);
     /*    if(ana->win)*/                  // do windowing
     /*      ana->win(smp, ana->buf->size);*/
     smps2freqs(ana->fft, smp, ana->frq);
     free(smp);
   }
   return 1;
 }
freq_ctor()
static void freq_ctor (M_Object o, VM_Shred shred) static
Definition at line 613 of file analys.c.
References compute_freq(), M_Object_::d, M_Object_::data, and o_ana_fn.
Referenced by import_freq().
 {
   *(f_analys*)(o->d.data + o_ana_fn) = (f_analys)compute_freq;
 }
import_ana()
static m_bool import_ana (Env env) static
Definition at line 496 of file analys.c.
References add_global_type(), ana_ctor(), ana_dtor(), CHECK_BB, CHECK_OB, dl_func_add_arg(), Env_::global_nspc, import_class_begin(), import_class_end(), import_mfun(), import_mvar(), new_DL_Func(), o_ana__fft, o_ana_fft, and o_ana_fn.
Referenced by import_analys().
 {
   DL_Func* fun;
   CHECK_BB(add_global_type(env, &t_ana))
   CHECK_OB(import_class_begin(env, &t_ana, env->global_nspc, ana_ctor, ana_dtor))
   o_ana_fft = import_mvar(env, "int", "@_fft", 0, 0, "internal _fft");
   CHECK_BB(o_ana__fft)
   o_ana_fft = import_mvar(env, "FFT", "@fft",  0, 1, "fft reference");
   CHECK_BB(o_ana_fft)
   o_ana_fn = import_mvar(env,  "int", "@fn",   0, 0, "internal compute fonction");
   CHECK_BB(o_ana_fn)
   fun = new_DL_Func("float", "compute", (m_uint)ana_compute);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("FFT", "fft", (m_uint)ana_get_fft);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("FFT", "fft", (m_uint)ana_set_fft);
   dl_func_add_arg(fun, "FFT", "arg");
   CHECK_OB(import_mfun(env, fun))
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_analys()
m_bool import_analys (Env env)
Definition at line 756 of file analys.c.
References add_binary_op(), CHECK_BB, import_ana(), import_asc(), import_ass(), import_centroid(), import_fc(), import_fft(), import_freq(), import_kurtosis(), import_rms(), import_rolloff(), import_skewness(), import_spread(), op_chuck, and op_unchuck.
Referenced by type_engine_init().
 {
   CHECK_BB(import_fft(env))
   CHECK_BB(import_ana(env))
   CHECK_BB(import_centroid(env))
   CHECK_BB(import_spread(env))
   CHECK_BB(import_skewness(env))
   CHECK_BB(import_kurtosis(env))
   CHECK_BB(import_rms(env))
   CHECK_BB(import_rolloff(env))
   CHECK_BB(import_freq(env))
   CHECK_BB(import_asc(env))
   CHECK_BB(import_ass(env))
   CHECK_BB(import_fc(env))
   CHECK_BB(add_binary_op(env, op_chuck,   &t_ana, &t_fc, &t_fc, fc_connect,    1, 0))
   CHECK_BB(add_binary_op(env, op_unchuck, &t_ana, &t_fc, &t_fc, fc_disconnect, 1, 0))
   return 1;
 }
import_asc()
static m_bool import_asc (Env env) static
Definition at line 630 of file analys.c.
References add_global_type(), asc_ctor(), CHECK_BB, CHECK_OB, Env_::global_nspc, import_class_begin(), and import_class_end().
Referenced by import_analys().
 {
   CHECK_BB(add_global_type(env, &t_asc))
   CHECK_OB(import_class_begin(env, &t_asc, env->global_nspc, asc_ctor, NULL))
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_ass()
static m_bool import_ass (Env env) static
Definition at line 643 of file analys.c.
References add_global_type(), ass_ctor(), CHECK_BB, CHECK_OB, Env_::global_nspc, import_class_begin(), and import_class_end().
Referenced by import_analys().
 {
   CHECK_BB(add_global_type(env, &t_ass))
   CHECK_OB(import_class_begin(env, &t_ass, env->global_nspc, ass_ctor, NULL))
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_centroid()
static m_bool import_centroid (Env env) static
Definition at line 523 of file analys.c.
References add_global_type(), centroid_ctor(), CHECK_BB, CHECK_OB, Env_::global_nspc, import_class_begin(), and import_class_end().
Referenced by import_analys().
 {
   CHECK_BB(add_global_type(env, &t_centroid))
   CHECK_OB(import_class_begin(env, &t_centroid, env->global_nspc, centroid_ctor, NULL))
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_fc()
static m_bool import_fc (Env env) static
Definition at line 737 of file analys.c.
References add_global_type(), CHECK_BB, CHECK_OB, dl_func_add_arg(), fc_ctor(), fc_dtor(), Env_::global_nspc, import_class_begin(), import_class_end(), import_mfun(), import_mvar(), new_DL_Func(), and o_fc_vector.
Referenced by import_analys().
 {
   DL_Func* fun;
   CHECK_BB(add_global_type(env, &t_fc))
   CHECK_OB(import_class_begin(env, &t_fc, env->global_nspc, fc_ctor, fc_dtor))
   o_fc_vector = import_mvar(env, "int", "@vector", 0, 0, "internal ANA clients");
   CHECK_BB(o_fc_vector)
   fun = new_DL_Func("float[]", "compute", (m_uint)fc_compute);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("ANA", "add", (m_uint)fc_add);
   dl_func_add_arg(fun, "ANA", "arg");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("ANA", "rem", (m_uint)fc_rem);
   dl_func_add_arg(fun, "ANA", "arg");
   CHECK_OB(import_mfun(env, fun))
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_fft()
static m_bool import_fft (Env env) static
Definition at line 144 of file analys.c.
References add_global_type(), CHECK_BB, CHECK_OB, dl_func_add_arg(), fft_ctor(), Env_::global_nspc, import_class_begin(), import_class_end(), import_mfun(), and new_DL_Func().
Referenced by import_analys().
 {
   DL_Func* fun;
   CHECK_BB(add_global_type(env, &t_fft))
   CHECK_OB(import_class_begin(env, &t_fft, env->global_nspc, fft_ctor, fft_dtor))
   fun = new_DL_Func("int", "init", (m_uint)fft_init);
   dl_func_add_arg(fun, "int", "size");
   CHECK_OB(import_mfun(env, fun))
   /*  fun = new_DL_Func("int", "init", (m_uint)fft_init2);*/
   /*    dl_func_add_arg(fun, "int", "size");*/
   /*    dl_func_add_arg(fun, "float[]", "window");*/
   /*  CHECK_OB(import_mfun(env, fun))*/
   /*  fun = new_DL_Func("int", "init", (m_uint)fft_init3);*/
   /*    dl_func_add_arg(fun, "int", "size");*/
   /*    dl_func_add_arg(fun, "string", "window");*/
   /*  CHECK_OB(import_mfun(env, fun))*/
   /*  fun = new_DL_Func("int", "window", (m_uint)fft_win);*/
   /*    dl_func_add_arg(fun, "float[]", "window");*/
   /*  CHECK_OB(import_mfun(env, fun))*/
   /*  fun = new_DL_Func("int", "window", (m_uint)fft_win_name);*/
   /*    dl_func_add_arg(fun, "string", "name");*/
   /*  CHECK_OB(import_mfun(env, fun))*/
   /*  fun = new_DL_Func("complex[]", "compute", (m_uint)fft_compute);*/
   fun = new_DL_Func("void", "compute", (m_uint)fft_compute);
   CHECK_OB(import_mfun(env, fun))
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_freq()
static m_bool import_freq (Env env) static
Definition at line 617 of file analys.c.
References add_global_type(), CHECK_BB, CHECK_OB, freq_ctor(), Env_::global_nspc, import_class_begin(), and import_class_end().
Referenced by import_analys().
 {
   CHECK_BB(add_global_type(env, &t_freq))
   CHECK_OB(import_class_begin(env, &t_freq, env->global_nspc, freq_ctor, NULL))
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_kurtosis()
static m_bool import_kurtosis (Env env) static
Definition at line 562 of file analys.c.
References add_global_type(), CHECK_BB, CHECK_OB, Env_::global_nspc, import_class_begin(), import_class_end(), and kurtosis_ctor().
Referenced by import_analys().
 {
   CHECK_BB(add_global_type(env, &t_kurtosis))
   CHECK_OB(import_class_begin(env, &t_kurtosis, env->global_nspc, kurtosis_ctor, NULL))
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_rms()
static m_bool import_rms (Env env) static
Definition at line 575 of file analys.c.
References add_global_type(), CHECK_BB, CHECK_OB, Env_::global_nspc, import_class_begin(), import_class_end(), and rms_ctor().
Referenced by import_analys().
 {
   CHECK_BB(add_global_type(env, &t_rms))
   CHECK_OB(import_class_begin(env, &t_rms, env->global_nspc, rms_ctor, NULL))
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_rolloff()
static m_bool import_rolloff (Env env) static
Definition at line 598 of file analys.c.
References add_global_type(), CHECK_BB, CHECK_OB, dl_func_add_arg(), Env_::global_nspc, import_class_begin(), import_class_end(), import_mfun(), new_DL_Func(), and rolloff_ctor().
Referenced by import_analys().
 {
   DL_Func* fun;
   CHECK_BB(add_global_type(env, &t_rolloff))
   CHECK_OB(import_class_begin(env, &t_rolloff, env->global_nspc, rolloff_ctor, NULL))
   fun = new_DL_Func("float", "percent", (m_uint)rolloff_get_percent);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("float", "percent", (m_uint)rolloff_set_percent);
   dl_func_add_arg(fun, "float", "arg");
   CHECK_OB(import_mfun(env, fun))
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_skewness()
static m_bool import_skewness (Env env) static
Definition at line 549 of file analys.c.
References add_global_type(), CHECK_BB, CHECK_OB, Env_::global_nspc, import_class_begin(), import_class_end(), and skewness_ctor().
Referenced by import_analys().
 {
   CHECK_BB(add_global_type(env, &t_skewness))
   CHECK_OB(import_class_begin(env, &t_skewness, env->global_nspc, skewness_ctor, NULL))
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_spread()
static m_bool import_spread (Env env) static
Definition at line 536 of file analys.c.
References add_global_type(), CHECK_BB, CHECK_OB, Env_::global_nspc, import_class_begin(), import_class_end(), and spread_ctor().
Referenced by import_analys().
 {
   CHECK_BB(add_global_type(env, &t_spread))
   CHECK_OB(import_class_begin(env, &t_spread, env->global_nspc, spread_ctor, NULL))
   CHECK_BB(import_class_end(env))
   return 1;
 }
INSTR() [1/2]
INSTR (fc_connect)
Definition at line 703 of file analys.c.
References M_Object_::d, M_Object_::data, o_fc_vector, Type_::obj, POP_REG, PUSH_REG, release(), and vector_append().
 {
   POP_REG(shred, SZ_INT * 2);
   M_Object o   = *(M_Object*)(shred->reg);
   M_Object obj = **(M_Object**)(shred->reg + SZ_INT);
   if(o) {
     if(obj) {
       Vector v = *(Vector*)(obj->d.data + o_fc_vector);
       vector_append(v, (vtype)o);
       release(obj, shred);
     }
     release(o, shred);
   }
   *(M_Object*)shred->reg = obj;
   PUSH_REG(shred, SZ_INT);
 }
INSTR() [2/2]
INSTR (fc_disconnect)
Definition at line 720 of file analys.c.
References M_Object_::d, M_Object_::data, o_fc_vector, Type_::obj, POP_REG, PUSH_REG, release(), vector_find(), and vector_remove().
 {
   POP_REG(shred, SZ_INT * 2);
   M_Object o   = *(M_Object*)(shred->reg);
   M_Object obj = *(M_Object*)(shred->reg + SZ_INT); // WARN inconsistency
   if(o) {
     if(obj) {
       Vector v = *(Vector*)(obj->d.data + o_fc_vector);
       vector_remove(v, vector_find(v, (vtype)o));
       release(obj, shred);
     }
     release(o, shred);
   }
   *(M_Object*)shred->reg = obj;
   PUSH_REG(shred, SZ_INT);
 }
kurtosis_ctor()
static void kurtosis_ctor (M_Object o, VM_Shred shred) static
Definition at line 558 of file analys.c.
References compute_kurtosis(), M_Object_::d, M_Object_::data, and o_ana_fn.
Referenced by import_kurtosis().
 {
   *(f_analys*)(o->d.data + o_ana_fn) = (f_analys)compute_kurtosis;
 }
MFUN() [1/10]
static MFUN (fft_init) static
Definition at line 108 of file analys.c.
References FFT::buf, FFT::fft, free(), FFT::frq, RETURN, Type_::size, sp_buffer_create(), and sp_buffer_destroy().
 {
   FFT* ana = (FFT*)o->ugen->ug;
   m_int size = *(m_int*)(shred->mem + SZ_INT);
   if(ana->buf)
     sp_buffer_destroy(ana->buf);
   if(ana->frq) {
     deleteFFTFREQS(ana->frq);
     free(ana->frq);
   }
   if(ana->fft)
     FFTwrapper_destroy(&ana->fft);
   sp_buffer_create(&ana->buf, size);
   ana->frq = calloc(size, sizeof(FFTFREQS));
   newFFTFREQS(ana->frq, size);
   FFTwrapper_create(&ana->fft, size);
   ana->frq->size = size;
   RETURN->d.v_uint = size;
 }
MFUN() [2/10]
static MFUN (fft_compute) static
Definition at line 129 of file analys.c.
References FFT::buf, FFT::fft, free(), FFT::frq, RETURN, and sp_buffer_get().
 {
   m_float* smp;
   FFT* ana = (FFT*)o->ugen->ug;
   if(!ana)
     return;
   if(!ana->buf) {
     RETURN->d.v_uint = 0;
     return;
   }
   smp = sp_buffer_get(ana->buf);
   smps2freqs(ana->fft, smp, ana->frq);
   free(smp);
 }
MFUN() [3/10]
static MFUN (ana_compute) static
Definition at line 442 of file analys.c.
References o_ana__fft, o_ana_fft, o_ana_fn, and RETURN.
 {
   M_Object   fft = *(M_Object*) (o->d.data + o_ana_fft);
   _FFT* _fft = *(_FFT**)(o->d.data + o_ana__fft);
   f_analys f = *(f_analys*)(o->d.data + o_ana_fn);
   if(!fft)
     return;
   RETURN->d.v_float = f(_fft);
 }
MFUN() [4/10]
static MFUN (ana_get_fft) static
Definition at line 452 of file analys.c.
References o_ana_fft, and RETURN.
 {
   RETURN->d.v_uint = (m_uint)*(M_Object*) (o->d.data + o_ana_fft);
 }
MFUN() [5/10]
static MFUN (ana_set_fft) static
Definition at line 457 of file analys.c.
References FFT::buf, err_msg(), FFT::fft, FFT::frq, _FFT::fval, INSTR_, o_ana__fft, o_ana_fft, M_Object_::ref, RETURN, _FFT::size, UGen_::ug, and M_Object_::ugen.
 {
   FFT* ana;
   M_Object fft = *(M_Object*) (o->d.data + o_ana_fft);
   _FFT* _fft = *(_FFT**)(o->d.data + o_ana__fft);
 //  if(fft)
 //    release(fft, shred);
   fft = *(M_Object*)(shred->mem + SZ_INT);
   if(!fft) {
     _fft->size = 0;
     _fft->fval = NULL;
     RETURN->d.v_uint = 0;
     return;
   }
   fft->ref++;
   ana = (FFT*)fft->ugen->ug;
   if(!ana || !ana->buf) {
     err_msg(INSTR_, 0, "FFT probably not initialised.");
     return;
   }
   _fft->size = ana->fft->fftsize;
   _fft->fval = ana->frq->s;
   *(M_Object*) (o->d.data + o_ana_fft) = fft;
   RETURN->d.v_uint = (m_uint) * (M_Object*)(shred->mem + SZ_INT);
 }
MFUN() [6/10]
static MFUN (rolloff_get_percent) static
Definition at line 588 of file analys.c.
References o_ana__fft, _FFT::percent, and RETURN.
 {
   _FFT* _fft = *(_FFT**)(o->d.data + o_ana__fft);
   RETURN->d.v_float = _fft->percent;
 }
MFUN() [7/10]
static MFUN (rolloff_set_percent) static
Definition at line 593 of file analys.c.
References o_ana__fft, _FFT::percent, and RETURN.
 {
   _FFT* _fft = *(_FFT**)(o->d.data + o_ana__fft);
   RETURN->d.v_float = (_fft->percent = *(m_float*)(shred->mem + SZ_INT));
 }
MFUN() [8/10]
static MFUN (fc_compute) static
Definition at line 662 of file analys.c.
References M_Object_::array, M_Object_::d, M_Object_::data, f_vector_set(), new_M_Array(), o_ana__fft, o_ana_fft, o_ana_fn, o_fc_vector, Type_::obj, RETURN, vector_at(), and vector_size().
 {
   m_uint i;
   M_Object ret;
   Vector v = *(Vector*)(o->d.data + o_fc_vector);
   ret = new_M_Array(SZ_FLOAT, vector_size(v), 1);
   for(i = 0; i < vector_size(v); i++) {
     M_Object obj = (M_Object)vector_at(v, i);
     if(!obj)
       continue;
     _FFT* _fft   = *(_FFT**)(obj->d.data + o_ana__fft);
     if(!_fft)
       continue;
     FFT* fft   = *(FFT**)(obj->d.data + o_ana_fft);
     if(!fft)
       continue;
     f_analys fn  = *(f_analys*)(obj->d.data + o_ana_fn);
     m_float f = fn(_fft);
     f_vector_set(ret->d.array, i, f);
   }
   RETURN->d.v_uint = (m_uint)ret;
 }
MFUN() [9/10]
static MFUN (fc_add) static
Definition at line 685 of file analys.c.
References o_fc_vector, Type_::obj, RETURN, and vector_append().
 {
   Vector v = *(Vector*)(o->d.data + o_fc_vector);
   M_Object obj = *(M_Object*)(shred->mem + SZ_INT);
   if(obj)
     vector_append(v, (vtype)obj);
   RETURN->d.v_uint = (m_uint)obj;
 }
MFUN() [10/10]
static MFUN (fc_rem) static
Definition at line 694 of file analys.c.
References o_fc_vector, Type_::obj, RETURN, vector_find(), and vector_remove().
 {
   Vector v = *(Vector*)(o->d.data + o_fc_vector);
   M_Object obj = *(M_Object*)(shred->mem + SZ_INT);
   if(obj)
     vector_remove(v, vector_find(v, (vtype)obj));
   RETURN->d.v_uint = (m_uint)obj;
 }
rms_ctor()
static void rms_ctor (M_Object o, VM_Shred shred) static
Definition at line 571 of file analys.c.
References compute_rms(), M_Object_::d, M_Object_::data, and o_ana_fn.
Referenced by import_rms().
 {
   *(f_analys*)(o->d.data + o_ana_fn) = (f_analys)compute_rms;
 }
rolloff_ctor()
static void rolloff_ctor (M_Object o, VM_Shred shred) static
Definition at line 584 of file analys.c.
References compute_rolloff(), M_Object_::d, M_Object_::data, and o_ana_fn.
Referenced by import_rolloff().
 {
   *(f_analys*)(o->d.data + o_ana_fn) = (f_analys)compute_rolloff;
 }
skewness_ctor()
static void skewness_ctor (M_Object o, VM_Shred shred) static
Definition at line 545 of file analys.c.
References compute_skewness(), M_Object_::d, M_Object_::data, and o_ana_fn.
Referenced by import_skewness().
 {
   *(f_analys*)(o->d.data + o_ana_fn) = (f_analys)compute_skewness;
 }
sp_buffer_add()
static m_int sp_buffer_add (sp_buffer * buffer, m_float f) static
Definition at line 43 of file analys.c.
References sp_buffer::data, sp_buffer::pos, and sp_buffer::size.
Referenced by fft_tick().
 {
   buffer->data[ buffer->pos ] = f;
   buffer->pos++;
   buffer->pos %= buffer->size;
   return SP_OK;
 }
sp_buffer_create()
static m_int sp_buffer_create (sp_buffer ** p, m_uint size) static
Definition at line 27 of file analys.c.
References malloc().
Referenced by MFUN().
 {
   *p = malloc(sizeof(sp_buffer));
   (*p)->size = size;
   (*p)->pos = 0;
   (*p)->data = calloc(size, sizeof(m_float));
   return SP_OK;
 }
sp_buffer_destroy()
static m_int sp_buffer_destroy (sp_buffer * buffer) static
Definition at line 36 of file analys.c.
References sp_buffer::data, and free().
Referenced by DTOR(), and MFUN().
 {
   free(buffer->data);
   free(buffer);
   return SP_OK;
 }
sp_buffer_get()
static m_float* sp_buffer_get (sp_buffer * buffer) static
Definition at line 51 of file analys.c.
References sp_buffer::data, sp_buffer::pos, and sp_buffer::size.
Referenced by fft_tick(), and MFUN().
 {
   m_uint i;
   m_float* ret = calloc(buffer->size, sizeof(m_float));
   for(i = 0; i < buffer->size; i++)
     ret[i] = buffer->data[(buffer->pos + i) % buffer->size];
   return ret;
 }
spread_ctor()
static void spread_ctor (M_Object o, VM_Shred shred) static
Definition at line 532 of file analys.c.
References compute_spread(), M_Object_::d, M_Object_::data, and o_ana_fn.
Referenced by import_spread().
 {
   *(f_analys*)(o->d.data + o_ana_fn) = (f_analys)compute_spread;
 }
Variable Documentation
o_ana__fft
m_int o_ana__fft
Definition at line 434 of file analys.c.
Referenced by ana_ctor(), ana_dtor(), import_ana(), and MFUN().
o_ana_fft
m_int o_ana_fft
Definition at line 435 of file analys.c.
Referenced by import_ana(), and MFUN().
o_ana_fn
m_int o_ana_fn
Definition at line 436 of file analys.c.
Referenced by ana_ctor(), asc_ctor(), ass_ctor(), centroid_ctor(), freq_ctor(), import_ana(), kurtosis_ctor(), MFUN(), rms_ctor(), rolloff_ctor(), skewness_ctor(), and spread_ctor().
o_fc_vector
m_int o_fc_vector static
Definition at line 652 of file analys.c.
Referenced by fc_ctor(), fc_dtor(), import_fc(), INSTR(), and MFUN().
t_ana
struct Type_ t_ana = { "ANA", SZ_INT, &t_object} static
Definition at line 433 of file analys.c.
t_asc
struct Type_ t_asc = { "ASC", SZ_INT, &t_ana } static
Definition at line 625 of file analys.c.
t_ass
struct Type_ t_ass = { "ASS", SZ_INT, &t_ana } static
Definition at line 638 of file analys.c.
t_centroid
struct Type_ t_centroid = { "Centroid", SZ_INT, &t_ana } static
Definition at line 518 of file analys.c.
t_fc
struct Type_ t_fc = { "FC", SZ_INT, &t_object } static
Definition at line 651 of file analys.c.
t_fft
struct Type_ t_fft = { "FFT", SZ_INT, &t_ugen} static
Definition at line 60 of file analys.c.
t_freq
struct Type_ t_freq = { "Freq", SZ_INT, &t_ana } static
Definition at line 612 of file analys.c.
t_kurtosis
struct Type_ t_kurtosis = { "Kurtosis", SZ_INT, &t_ana } static
Definition at line 557 of file analys.c.
t_rms
struct Type_ t_rms = { "RMS", SZ_INT, &t_ana } static
Definition at line 570 of file analys.c.
t_rolloff
struct Type_ t_rolloff = { "Rolloff", SZ_INT, &t_ana } static
Definition at line 583 of file analys.c.
t_skewness
struct Type_ t_skewness = { "Skewness", SZ_INT, &t_ana } static
Definition at line 544 of file analys.c.
t_spread
struct Type_ t_spread = { "Spread", SZ_INT, &t_ana } static
Definition at line 531 of file analys.c.