emit.h – Gwion
Gwion
A strongly timed musical programming language
emit.h
emit.h File Reference
#include "type.h"
#include "frame.h"
Data Structures
struct Code
struct Emitter_
Functions
m_bool get_instr (Emitter emit, Operator op, Type rhs, Type lhs)
Code * new_Code ()
void free_Code (Code *code)
Emitter new_Emitter (Env env)
void free_Emitter (Emitter emit)
VM_Code emit_to_code (Emitter emit)
m_bool emit_Ast (Emitter emit, Ast ast, m_str filename)
Vector emit_lookup_label (Emitter emit, S_Symbol xid, int climb)
void emit_add_label (Emitter emit, S_Symbol xid, void *value)
void emit_push_label (Emitter emit)
void emit_pop_label (Emitter emit)
m_bool emit_Func_Call1 (Emitter emit, Func func, Type type, int pos)
Instr add_instr (Emitter emit, f_instr f)
Function Documentation
add_instr()
Instr add_instr (Emitter emit, f_instr f)
Definition at line 26 of file emit.c.
References Code::code, Emitter_::code, Instr_::execute, new_Instr(), and vector_append().
Referenced by compile(), emit_Array(), emit_array_lit(), emit_Binary_Expression(), emit_Break(), emit_Cast_Expression(), emit_Cast_Expression1(), emit_Class_Def(), emit_Continue(), emit_Decl_Expression(), emit_Do_Until(), emit_Do_While(), emit_Dot_Member(), emit_Dur(), emit_exp_if(), emit_Expression(), emit_For(), emit_Func_Args(), emit_Func_Call1(), emit_Func_Def(), emit_Goto_Label(), emit_If(), emit_implicit_cast(), emit_instantiate_object(), emit_Loop(), emit_pop_scope(), emit_Postfix_Expression(), emit_pre_constructor_array(), emit_Pre_Ctor(), emit_Primary_Expression(), emit_Return(), emit_spork(), emit_Stmt(), emit_Switch(), emit_symbol(), emit_Unary(), emit_Until(), emit_Vec(), emit_While(), and get_instr().
 {
   Instr instr = new_Instr();
   instr->execute = f;
   vector_append(emit->code->code, (vtype)instr);
   return instr;
 }
emit_add_label()
void emit_add_label (Emitter emit, S_Symbol xid, void * value)
emit_Ast()
m_bool emit_Ast (Emitter emit, Ast ast, m_str filename)
Definition at line 2483 of file emit.c.
References ae_section_class, ae_section_func, ae_section_stmt, Emitter_::array, Section::class_def, Emitter_::code, Env_::context, Emitter_::context, Env_::curr, Section::d, emit_Class_Def(), emit_filename, emit_Func_Def(), emit_pop_scope(), emit_Stmt_List(), Emitter_::env, Code::frame, frame_push_scope(), free(), free_Ast(), free_Vector(), NameSpace_::func, Emitter_::func, Section::func_def, Emitter_::funcs, new_Code(), new_Vector(), Ast_::next, Context_::nspc, Emitter_::nspc, Type_::obj, scope_rem(), Ast_::section, Emitter_::stack, Section::stmt_list, Section::type, vector_at(), vector_clear(), vector_size(), and Func_Ptr::xid.
Referenced by compile().
 {
 #ifdef DEBUG_EMIT
   debug_msg("emit", "Ast %p", emit->env->context);
 #endif
   Ast prog = ast;
   vtype i;
   int ret = 1;
   emit_filename = filename;
   emit->code = new_Code();
   emit->context = emit->env->context;
   emit->nspc = emit->context->nspc;
   emit->func = NULL;
   free_Vector(emit->stack);
   emit->stack = new_Vector();
   //  emit->code->name = strdup(emit_filename);
   frame_push_scope(emit->code->frame);
   while (prog && ret > 0) {
     if (!prog->section)
       return 1;
     switch (prog->section->type) {
     case ae_section_stmt:
       ret = emit_Stmt_List(emit, prog->section->d.stmt_list);
       break;
     case ae_section_func:
       ret = emit_Func_Def(emit, prog->section->d.func_def);
       break;
     case ae_section_class:
       ret = emit_Class_Def(emit, prog->section->d.class_def);
       break;
     }
     prog = prog->next;
   }
   // handle func pointer
   for(i = 0; i < vector_size(emit->funcs); i++) {
     Func_Ptr* ptr = (Func_Ptr*)vector_at(emit->funcs, i);
     scope_rem(emit->env->curr->func, ptr->xid);
   }
   // handle empty array type
   for(i = 0; i < vector_size(emit->array); i++) {
     Type t = (Type)vector_at(emit->array, i);
     free(t->obj);
     free(t); // all this should be:na
     // rem_ref(t->obj, t);
   }
   vector_clear(emit->array);
   if (ret < 0) {
     free_Ast(ast);
   }
   emit_pop_scope(emit);
   return ret;
 }
emit_Func_Call1()
m_bool emit_Func_Call1 (Emitter emit, Func func, Type type, int pos)
Definition at line 778 of file emit.c.
References add_instr(), ae_func_builtin, Func_Def_::arg_list, Func_::code, Emitter_::code, Env_::curr, Frame::curr_offset, Func_::def, EMIT_, emit_Func_Args(), emit_Func_Def(), Emitter_::env, err_msg(), Instr_::execute, Code::frame, frame_alloc_local(), free(), Func_Def_::func, insert_symbol(), Instr_Func_Call(), Instr_Func_Call_Member(), Instr_Func_Call_Static(), Func_::is_member, Func_Def_::is_template, isa(), kindof(), Instr_::m_val, Instr_::m_val2, Mem_Push_Imm(), Func_::name, Func_Def_::name, namespace_lookup_func(), Arg_List_::next, Local::offset, Value_::offset, Func_Def_::pos, Instr_::ptr, Reg_Push_Code(), Reg_Push_Imm(), Reg_Push_Ptr(), Func_Def_::ret_type, S_name(), Func_Def_::s_type, Code::stack_depth, t_object, Arg_List_::type, and Func_::value_ref.
Referenced by emit_Binary_Expression(), emit_Func_Call(), emit_spork(), and get_instr().
 {
 #ifdef DEBUG_EMIT
   debug_msg("emit", "func call1. '%s' offset: %i", func->name, emit->code->frame->curr_offset);
 #endif
   m_bool is_ptr = 0;
   Instr code, offset, call;
   if (!func->code) { // calling function pointer in func
     Func f = namespace_lookup_func(emit->env->curr, insert_symbol(func->name), -1);
 // [todo] emit_exp_func1 remove template stuff
     if (!f) { //template with no list
       if (!func->def->is_template) {
         err_msg(EMIT_, func->def->pos, "function not emitted yet");
         return -1;
       }
       if(emit_Func_Def(emit, func->def) < 0) {
         err_msg(EMIT_, 0, "can't emit func.");
         return -1;
       }
       func->code = func->def->func->code;
       code = add_instr(emit, Reg_Push_Ptr);
       code->ptr = func->code;
     } else {
       code = add_instr(emit, Reg_Push_Code);
       code->m_val = func->value_ref->offset;
       is_ptr = 1;
     }
   } else {
     code = add_instr(emit, Reg_Push_Ptr);
     code->ptr = func->code;
   }
   if(!emit->code->stack_depth && !emit->code->frame->curr_offset)
     add_instr(emit, Mem_Push_Imm);
   offset = add_instr(emit, Reg_Push_Imm);
   offset->m_val = emit->code->frame->curr_offset;
   call = add_instr(emit, Instr_Func_Call);
   call->m_val = emit->code->stack_depth;
   if (func->def->s_type == ae_func_builtin) {
     call->m_val = kindof(type);
     if (func->is_member)
       call->execute = Instr_Func_Call_Member;
     else
       call->execute = Instr_Func_Call_Static;
   }
   else if(!strcmp(S_name(func->def->name), "chuck")) { // should also handle other ops
     call->execute = Instr_Op_Call_Binary;
     call->m_val2  = (m_uint)func->def->arg_list->type;
     call->ptr     = func->def->arg_list->next->type;
   }
   if (func->def->is_template) {
     Instr clear = add_instr(emit, Free_Func);
     clear->m_val = (m_uint)func;
   }
   // test on 13/01/17 'Keep track of returned Object'
   if(isa(func->def->ret_type, &t_object) > 0) {
     Local* l = frame_alloc_local(emit->code->frame, SZ_INT, func->name, 0, 1);
     Instr instr = add_instr(emit, Mem_Push_Ret);
     instr->m_val = l->offset;
   }
   if(is_ptr)
     free(func);
   return 1;
 }
emit_lookup_label()
Vector emit_lookup_label (Emitter emit, S_Symbol xid, int climb)
emit_pop_label()
void emit_pop_label (Emitter emit)
emit_push_label()
void emit_push_label (Emitter emit)
emit_to_code()
VM_Code emit_to_code (Emitter emit)
Definition at line 221 of file emit.c.
References Code::code, Emitter_::code, Code::filename, free_Code(), Code::name, Code::need_this, new_VM_Code(), and Code::stack_depth.
Referenced by compile(), emit_Class_Def(), emit_Func_Def(), emit_spork(), and emit_Unary().
 {
 #ifdef DEBUG_EMIT
   debug_msg("emit", "emit to code");
 #endif
   Code* c = emit->code;
   VM_Code code = new_VM_Code(c->code, c->stack_depth, c->need_this, c->name, c->filename);
   free_Code(c);
   return code;
 }
free_Code()
void free_Code (Code * code)
Definition at line 79 of file emit.c.
References Code::code, Code::filename, Code::frame, free(), free_Frame(), free_Vector(), Code::name, Code::stack_break, Code::stack_cont, and Code::stack_return.
Referenced by emit_to_code().
 {
   free_Vector(code->code);
   free_Vector(code->stack_break);
   free_Vector(code->stack_cont);
   free_Vector(code->stack_return);
   free_Frame(code->frame);
   free(code->name);
   free(code->filename);
   free(code);
 }
free_Emitter()
void free_Emitter (Emitter emit)
Definition at line 52 of file emit.c.
References Emitter_::array, free(), free_Vector(), Emitter_::funcs, Func_::obj, rem_ref(), Emitter_::spork, Emitter_::stack, vector_at(), and vector_size().
Referenced by rem_ref().
 {
   vtype i;
   for(i = 0; i < vector_size(a->spork); i++) {
     Func f = (Func)vector_at(a->spork, i);
     rem_ref(f->obj, f);
   }
   free_Vector(a->spork);
   free_Vector(a->stack);
   free_Vector(a->funcs);
   free_Vector(a->array);
   free(a);
 }
get_instr()
m_bool get_instr (Emitter emit, Operator op, Type rhs, Type lhs)
Definition at line 296 of file operator.c.
References add_instr(), Emitter_::code, Env_::curr, Func_::def, emit_Func_Call1(), Emitter_::env, Code::frame, frame_alloc_local(), M_Operator::func, get_instr(), M_Operator::instr, M_Operator::is_new, Instr_::m_val, map_get(), Type_::name, Local::offset, op2str(), NameSpace_::operator, operator_find(), NameSpace_::parent, Type_::parent, Reg_Push_Imm(), and Func_Def_::ret_type.
Referenced by emit_Binary_Expression(), and get_instr().
 {
 #ifdef DEBUG_OPERATOR
   debug_msg(" op", "get instr for operator '%s', for type '%s' and '%s'",
             op2str(op), lhs->name, rhs->name);
 #endif
   Type l = lhs, r = rhs;
   Vector v;
   NameSpace nspc = emit->env->curr;
   while(nspc) {
     M_Operator* mo;
     v = (Vector)map_get(nspc->operator, (vtype)op);
     if((mo = operator_find(v, lhs, rhs))) {
       if(mo->func) {
         add_instr(emit, Reg_Push_Imm); //do we need to set offset ?
         if(emit_Func_Call1(emit, mo->func, mo->func->def->ret_type, 0) < 0)
           return -1;
         return 1;
       } else {
         Instr instr = add_instr(emit, mo->instr);
         if(mo->is_new) {
           // should only be M_Object, so use SZ_INT
           Local* l = frame_alloc_local(emit->code->frame, SZ_INT, "operator return value", 0, 1);
           instr->m_val = l->offset;
         }
       }
       return 1;
     }
     if(l && l->parent)
       if(get_instr(emit, op, l->parent, rhs) > 0)
         return 1;
     if(r && r->parent)
       if(get_instr(emit, op, lhs, r->parent) > 0)
         return 1;
     nspc = nspc->parent;
   }
   return -1;
 }
new_Code()
Code* new_Code ()
Definition at line 66 of file emit.c.
References Code::code, Code::frame, Code::need_this, new_Frame(), new_Vector(), Code::stack_break, Code::stack_cont, Code::stack_depth, and Code::stack_return.
Referenced by emit_Ast(), emit_Class_Def(), emit_Func_Def(), emit_spork(), and emit_Unary().
 {
   Code* code = calloc(1, sizeof(Code));
   code->stack_depth = 0;
   code->need_this = 0;
   code->code = new_Vector();
   code->stack_break = new_Vector();
   code->stack_cont = new_Vector();
   code->stack_return = new_Vector();
   code->frame = new_Frame();
   return code;
 }
new_Emitter()
Emitter new_Emitter (Env env)
Definition at line 34 of file emit.c.
References Emitter_::array, Emitter_::cases, Emitter_::code, Emitter_::context, e_emit_obj, Emitter_::env, Emitter_::func, Emitter_::funcs, new_Vector(), new_VM_Object(), Emitter_::nspc, Emitter_::obj, Emitter_::spork, and Emitter_::stack.
Referenced by main().
 {
   Emitter emit = calloc(1, sizeof(struct Emitter_));
   emit->env = NULL;
   emit->code = NULL;
   emit->stack = new_Vector();
   emit->spork = new_Vector();
   emit->funcs = new_Vector();
   emit->array = new_Vector();
   emit->context = NULL;
   emit->nspc = NULL;
   emit->func = NULL;
   emit->cases = NULL;
   emit->obj = new_VM_Object(e_emit_obj);
   emit->env = env;
   return emit;
 }