Gwion dev-docs: core/env.c File Reference
--- layout: homepage title: env.c image: feature: abstract-1.jpg ---
env.c File Reference
#include <stdlib.h>
#include "env.h"
#include "context.h"
#include "namespace.h"
Functions
Env new_Env ()
void env_reset (Env env)
void free_Env (Env a)
Function Documentation
env_reset()
void env_reset (Env env)
Definition at line 30 of file env.c.
References Env_::class_def, Env_::class_scope, Env_::class_stack, Env_::curr, free_Vector(), Env_::func, Env_::global_nspc, new_Vector(), Env_::nspc_stack, and vector_append().
Referenced by new_Env(), and type_engine_check_prog().
 {
   // TODO: release stack items?
   free_Vector(env->nspc_stack);
   env->nspc_stack = new_Vector();
   vector_append(env->nspc_stack, (vtype)env->global_nspc);
 //  if(env->user_nspc)
 //    vector_append(env->nspc_stack, (vtype)env->user_nspc);
   free_Vector(env->class_stack);
   env->class_stack = new_Vector();
   vector_append(env->class_stack, (vtype)NULL);
   // should be at top level
 //  if(env->user_nspc)
 //    env->curr = env->user_nspc;
 //  else
   env->curr = env->global_nspc;
   env->class_def = NULL;
   env->func = NULL;
   env->class_scope = 0;
 }
free_Env()
void free_Env (Env a)
Definition at line 55 of file env.c.
References Env_::breaks, Env_::class_stack, Env_::contexts, Env_::conts, free(), free_Map(), free_Vector(), Env_::global_context, Env_::known_ctx, map_at(), map_size(), Env_::nspc_stack, Context_::obj, NameSpace_::obj, rem_ref(), Context_::tree, vector_back(), vector_pop(), and vector_size().
Referenced by rem_ref().
 {
   m_uint i;
   free(a->global_context->tree);
   for(i = 0; i < map_size(a->known_ctx); i++) {
     Context ctx = (Context)map_at(a->known_ctx, i);
     rem_ref(ctx->obj, ctx);
   }
   free_Vector(a->contexts);
   free_Map(a->known_ctx);
   for(i = 0; i < vector_size(a->nspc_stack); i++) {
     NameSpace  nspc = (NameSpace)vector_back(a->nspc_stack);
     vector_pop(a->nspc_stack);
     rem_ref(nspc->obj, nspc);
   }
   free_Vector(a->nspc_stack);
   free_Vector(a->class_stack);
   free_Vector(a->breaks);
   free_Vector(a->conts);
   free(a);
 }
new_Env()
Env new_Env ()
Definition at line 6 of file env.c.
References add_ref(), Env_::breaks, Env_::class_scope, Env_::class_stack, Env_::context, Env_::contexts, Env_::conts, Env_::curr, e_env_obj, env_reset(), NameSpace_::filename, Env_::global_context, Env_::global_nspc, Env_::known_ctx, NameSpace_::name, new_Context(), new_Map(), new_NameSpace(), new_Vector(), new_VM_Object(), Env_::nspc_stack, Context_::obj, NameSpace_::obj, and Env_::obj.
Referenced by type_engine_init().
 {
   Env env = calloc(1, sizeof(struct Env_));
   env->global_context = new_Context(NULL, "global_context");
   add_ref(env->global_context->obj);
   env->context = env->global_context;
   env->contexts = new_Vector();
   env->class_stack = new_Vector();
   env->nspc_stack = new_Vector();
   env->class_scope = 0;
   env->obj = new_VM_Object(e_env_obj);
   env->global_nspc = new_NameSpace();
   env->global_nspc->name = "global_nspc";
   env->global_nspc->filename = "global_nspc";
   env->curr = env->global_nspc;
   add_ref(env->global_nspc->obj);
   env->breaks = new_Vector();
   env->conts = new_Vector();
 //  env->user_nspc = NULL;
   env->known_ctx = new_Map();
   env_reset(env);
   return env;
 }