Gwion dev-docs: include/import.h File Reference
--- layout: homepage title: import.h image: feature: abstract-1.jpg ---
import.h File Reference
#include "env.h"
#include "dl.h"
Typedefs
typedef m_bool(* Import_fun) (Env env, DL_Func *f)
Functions
Func import_mfun (Env env, DL_Func *fun)
Func import_sfun (Env env, DL_Func *fun)
Func_Def make_dll_as_fun (DL_Func *dl_fun, m_bool is_static)
m_int import_svar (Env env, const m_str type, const m_str name, m_bool is_const, m_bool is_ref, m_uint *addr, const m_str doc)
m_int import_mvar (Env env, const m_str type, const m_str name, const m_bool is_const, const m_bool is_ref, const m_str doc)
m_bool import_class_end (Env env)
Type import_class_begin (Env env, Type type, NameSpace where, f_ctor pre_ctor, f_dtor dtor)
Typedef Documentation
Import_fun
typedef m_bool(* Import_fun) (Env env, DL_Func *f)
Definition at line 4 of file import.h.
Function Documentation
import_class_begin()
Type import_class_begin (Env env, Type type, NameSpace where, f_ctor pre_ctor, f_dtor dtor)
Definition at line 98 of file import.c.
References add_ref(), Env_::class_def, Env_::class_stack, Env_::curr, err_msg(), NameSpace_::filename, free_Vector(), Type_::has_constructor, Type_::has_destructor, Type_::info, Type_::is_complete, mk_xtor(), NameSpace_::name, Type_::name, NATIVE_CTOR, NATIVE_DTOR, new_NameSpace(), Env_::nspc_stack, NameSpace_::obj, Type_::obj, Type_::obj_size, NameSpace_::obj_v_table, NameSpace_::offset, Type_::owner, NameSpace_::parent, Type_::parent, TYPE_, vector_append(), and vector_copy().
Referenced by import_ana(), import_array(), import_asc(), import_ass(), import_centroid(), import_complex(), import_event(), import_fc(), import_fft(), import_fileio(), import_freq(), import_fullrect(), import_gain(), import_halfrect(), import_impulse(), import_kurtosis(), import_lib(), import_machine(), import_object(), import_rms(), import_rolloff(), import_shred(), import_sinosc(), import_skewness(), import_spread(), import_step(), import_string(), import_ugen(), import_vec3(), import_vec4(), and import_zerox().
 {
   if(type->info) {
     err_msg(TYPE_, 0, "during import: class '%s' already imported...", type->name);
     return NULL;
   }
   type->info = new_NameSpace();
   type->info->filename = "global_nspc";
   // add reference
   /*    SAFE_ADD_REF(type->info);*/
   add_ref(type->info->obj);
   type->info->name = type->name;
   type->info->parent = where;
   add_ref(type->info->parent->obj);
   if(pre_ctor)
     type->has_constructor = mk_xtor(type, (m_uint)pre_ctor, NATIVE_CTOR);
   if(dtor)
     type->has_destructor  = mk_xtor(type, (m_uint)dtor,     NATIVE_DTOR);
   if(type->parent) {
     type->info->offset = type->parent->obj_size;
     free_Vector(type->info->obj_v_table);
     type->info->obj_v_table = vector_copy(type->parent->info->obj_v_table);
   }
   type->owner = where;
   /*    SAFE_ADD_REF(type->owner);*/
   add_ref(type->owner->obj);
 //  type->size = SZ_INT;
 //    type->size = 1;
   // set the object size
   type->obj_size = 0; // TODO
   type->is_complete = 1;
 //    type_type = type_copy(env, &t_class);
 //    type_type->actual_type = type;
   // SAFE_REF_ASSIGN( type_type->actual_type, type );
   vector_append(env->nspc_stack, (vtype)env->curr);
   env->curr = type->info;
   vector_append(env->class_stack, (vtype)env->class_def);
   env->class_def = type;
 //    type->obj = new_VM_Object(e_type_obj);
   // ref count
   add_ref(type->obj);
   return type;
 }
import_class_end()
m_bool import_class_end (Env env)
Definition at line 144 of file import.c.
References Env_::class_def, Env_::class_stack, Env_::curr, err_msg(), Type_::info, Env_::nspc_stack, Type_::obj_size, NameSpace_::offset, TYPE_, vector_back(), and vector_pop().
Referenced by import_ana(), import_array(), import_asc(), import_ass(), import_centroid(), import_complex(), import_event(), import_fc(), import_fft(), import_fileio(), import_freq(), import_fullrect(), import_gain(), import_halfrect(), import_impulse(), import_kurtosis(), import_lib(), import_machine(), import_object(), import_rms(), import_rolloff(), import_shred(), import_sinosc(), import_skewness(), import_spread(), import_step(), import_string(), import_ugen(), import_vec3(), import_vec4(), and import_zerox().
 {
   if(!env->class_def) {
     err_msg(TYPE_, 0, "import: too many class_end called..." );
     return -1;
   }
   env->class_def->obj_size = env->class_def->info->offset;
   env->class_def = (Type)vector_back(env->class_stack);
   vector_pop(env->class_stack);
   env->curr = (NameSpace)vector_back(env->nspc_stack);
   vector_pop(env->nspc_stack);
   return 1;
 }
import_mfun()
Func import_mfun (Env env, DL_Func * fun)
Definition at line 322 of file import.c.
References import_fun().
Referenced by import_ana(), import_array(), import_event(), import_fc(), import_fft(), import_fileio(), import_gain(), import_impulse(), import_rolloff(), import_shred(), import_sinosc(), import_step(), import_string(), import_ugen(), import_vec3(), and import_vec4().
 { return import_fun(env, fun, 0); }
import_mvar()
m_int import_mvar (Env env, const m_str type, const m_str name, const m_bool is_const, const m_bool is_ref, const m_str doc)
Definition at line 202 of file import.c.
References import_var().
Referenced by import_ana(), import_complex(), import_event(), import_fc(), import_fileio(), import_object(), import_shred(), import_string(), import_vec3(), and import_vec4().
 { return import_var(env, type, name, 0, is_const, is_ref, NULL, doc); }
import_sfun()
Func import_sfun (Env env, DL_Func * fun)
Definition at line 323 of file import.c.
References import_fun().
Referenced by import_fileio(), import_lib(), import_machine(), and import_shred().
 { return import_fun(env, fun, 1); }
import_svar()
m_int import_svar (Env env, const m_str type, const m_str name, m_bool is_const, m_bool is_ref, m_uint * addr, const m_str doc)
Definition at line 205 of file import.c.
References import_var().
 { return import_var(env, type, name, 1, is_const, is_ref, addr, doc); }
make_dll_as_fun()
Func_Def make_dll_as_fun (DL_Func * dl_fun, m_bool is_static)
Definition at line 262 of file import.c.
References add_type_decl_array(), ae_func_builtin, ae_key_func, ae_key_instance, ae_key_static, DL_Func::d, Func_Def_::dl_func_ptr, err_msg(), free_DL_Func(), make_dll_arg_list(), DL_Func::mfun, DL_Func::name, new_array_sub(), new_Func_Def(), new_Type_Decl(), prepend_array_sub(), Func_Def_::s_type, str2list(), DL_Func::type, TYPE_, and type_path().
Referenced by import_fun().
 {
   Func_Def func_def = NULL;
   ae_Keyword func_decl = ae_key_func;
   ae_Keyword static_decl = is_static ? ae_key_static : ae_key_instance;
   ID_List type_path = NULL;
   Type_Decl* type_decl = NULL;
   m_str name = NULL;
   Arg_List arg_list = NULL;
   m_uint i, array_depth = 0;
   type_path = str2list(dl_fun->type, &array_depth);
   if(!type_path) {
     // error
     err_msg(TYPE_, 0, "...during function import '%s' (type)...", dl_fun->name);
     goto error;
   }
   type_decl = new_Type_Decl(type_path, 0, 0);
   if(!type_decl) {
     // error
     err_msg(TYPE_, 0, "...during function import '%s' (type)...", dl_fun->name);
     goto error;
   }
   if(array_depth) {
     Array_Sub array_sub = new_array_sub(NULL, 0);
     for(i = 1; i < array_depth; i++ )
       array_sub = prepend_array_sub(array_sub, NULL, 0);
     type_decl = add_type_decl_array(type_decl, array_sub, 0);
   }
   name = dl_fun->name;
   arg_list = make_dll_arg_list(dl_fun);
   func_def = new_Func_Def(func_decl, static_decl, type_decl, name, arg_list, NULL, 0);
   func_def->s_type = ae_func_builtin;
   func_def->dl_func_ptr = (void*)(m_uint)dl_fun->d.mfun;
   free_DL_Func(dl_fun);
   return func_def;
 error:
   // clean up
   // if( !func_def ) delete_type_decl( type_decl );
   // else delete_func_def( func_def );
   return NULL;
 }