map.h – Gwion
Gwion
A strongly timed musical programming language
map.h
map.h File Reference
#include "defs.h"
#include <symbol.h>
Macros
#define MAP_MAX 1024
Typedefs
typedef m_uint vtype
typedef struct Vector_ * Vector
typedef struct Map_ * Map
Functions
Vector new_Vector ()
Vector new_Vector_fixed (const vtype len)
Vector vector_copy (Vector v)
void vector_set (Vector vector, const vtype i, vtype data)
long int vector_find (Vector vector, vtype data)
void vector_append (Vector vector, vtype data)
void vector_remove (Vector vector, const vtype index)
void vector_pop (Vector vector)
vtype vector_front (Vector vector)
vtype vector_at (Vector vector, const vtype)
vtype vector_back (Vector vector)
vtype vector_size (Vector vector)
void vector_clear (Vector vector)
void free_Vector (Vector vector)
Map new_Map ()
vtype map_get (Map map, vtype key)
vtype map_at (Map map, const vtype index)
vtype map_key (Map map, const vtype index)
void map_set (Map map, vtype key, vtype ptr)
void map_remove (Map map, vtype key)
void map_commit (Map map, Map commit)
void map_rollback (Map map, void(*_free)(vtype))
vtype map_size (Map map)
void free_Map (Map map)
Scope new_Scope ()
Vector scope_get (Scope a)
vtype scope_lookup (Scope scope, S_Symbol xid, int climb)
void scope_add (Scope scope, S_Symbol xid, vtype value)
void scope_rem (Scope scope, S_Symbol xid)
void scope_commit (Scope scope)
void scope_rollback (Scope scope, void(*_free)(vtype arg))
void scope_push (Scope scope)
void scope_pop (Scope scope)
void free_Scope (Scope a)
Macro Definition Documentation
MAP_MAX
#define MAP_MAX 1024
Definition at line 6 of file map.h.
Typedef Documentation
Map
typedef struct Map_* Map
Definition at line 10 of file map.h.
Vector
typedef struct Vector_* Vector
Definition at line 9 of file map.h.
vtype
typedef m_uint vtype
Definition at line 8 of file map.h.
Function Documentation
free_Map()
void free_Map (Map map)
Definition at line 228 of file map.c.
References free().
Referenced by free_Env(), free_NameSpace(), free_Operator_Map(), free_Scope(), main(), scope_commit(), and scope_pop().
 {
 //  free(map->key);
 //  free(map->ptr);
   free(map);
 }
free_Scope()
void free_Scope (Scope a)
Definition at line 323 of file map.c.
References Scope_::commit_map, free(), free_Map(), free_Vector(), Scope_::vector, and vector_front().
Referenced by free_NameSpace().
 {
   free_Map((Map)vector_front(a->vector));
   free_Vector(a->vector);
   free_Map(a->commit_map);
   free(a);
 }
free_Vector()
void free_Vector (Vector vector)
Definition at line 123 of file map.c.
References free().
Referenced by check_Class_Def(), emit_Ast(), emit_Func_Def(), emit_pop_scope(), env_reset(), event_dtor(), fc_dtor(), free_Code(), free_Context(), free_DL_Func(), free_Emitter(), free_Env(), free_Frame(), free_NameSpace(), free_Operator_Map(), free_Scope(), free_Stmt_Enum(), free_Stmt_Union(), free_UGen(), free_VM(), free_VM_Code(), import_class_begin(), INSTR(), main(), make_dll_arg_list(), mk_type_list(), mkadt_nspc(), mkdoc_nspc(), parse(), release(), scan2_Goto_Label(), and stop_plug().
 {
   free(v);
   v = NULL;
 }
map_at()
vtype map_at (Map map, const vtype index)
Definition at line 147 of file map.c.
References Map_::len, and Map_::ptr.
Referenced by free_Env(), and free_NameSpace().
 {
   if(index > map->len)
     return 0;
   return map->ptr[index];
 }
map_commit()
void map_commit (Map map, Map commit)
Definition at line 204 of file map.c.
References Map_::key, Map_::len, map_set(), and Map_::ptr.
Referenced by scope_commit().
 {
   vtype i;
   for(i = 0; i < commit->len; i++)
     map_set(map, commit->key[i], commit->ptr[i]);
 }
map_get()
vtype map_get (Map map, vtype key)
Definition at line 138 of file map.c.
References Map_::key, Map_::len, and Map_::ptr.
Referenced by add_binary_op(), append_doc(), check_Goto_Label(), emit_Case(), find_context(), free_Operator_Map(), get_doc(), get_instr(), get_pos(), get_return_type(), if(), INSTR(), newline(), operator_set_func(), scan2_Goto_Label(), and scope_lookup().
 {
   vtype i;
   for(i = 0; i < map->len; i++)
     if(map->key[i] == key)
       return (vtype)map->ptr[i];
   return 0;
 }
map_key()
vtype map_key (Map map, const vtype index)
Definition at line 154 of file map.c.
References Map_::key, and Map_::len.
 {
   if(index > map->len)
     return 0;
   return map->key[index];
 }
map_remove()
void map_remove (Map map, vtype key)
Definition at line 193 of file map.c.
References free(), Map_::key, Map_::len, map_set(), new_Map(), and Map_::ptr.
Referenced by scope_rem().
 {
   vtype i;
   Map tmp = new_Map();
   for(i = 0; i < map->len; i++)
     if(map->key[i] != key)
       map_set(tmp, key, map->ptr[i]);
   *map = *tmp;
   free(tmp);
 }
map_rollback()
void map_rollback (Map map, void(*)(vtype) _free)
map_set()
void map_set (Map map, vtype key, vtype ptr)
Definition at line 161 of file map.c.
References Map_::key, Map_::len, Vector_::ptr, and Map_::ptr.
Referenced by emit_Case(), map_commit(), map_remove(), new_Operator_Map(), parse(), scan2_Goto_Label(), scope_add(), type_engine_check_prog(), and type_engine_init().
 {
   vtype i;
   for(i = 0; i < map->len; i++) {
     if(map->key[i] == key) {
       map->ptr[i] = ptr;
       return;
     }
   }
   map->len++;
   /*
   void* tmp = map->key;
   tmp = realloc(map->key, map->len * sizeof(vtype));
   if(!tmp)
     exit(2);
     map->key = tmp;
   tmp = realloc(map->ptr, map->len * sizeof(vtype));
   if(tmp)
     map->ptr = tmp;
   */
 //if(map->len > 1) {
 //  map->key = realloc(map->key, map->len * sizeof(vtype));
 //  map->ptr = realloc(map->ptr, map->len * sizeof(vtype));
 //}
   map->key[map->len - 1] = key;
   map->ptr[map->len - 1] = ptr;
 }
map_size()
vtype map_size (Map map)
Definition at line 223 of file map.c.
References Map_::len.
Referenced by free_Env(), and free_NameSpace().
 {
   return map->len;
 }
new_Map()
Map new_Map ()
Definition at line 129 of file map.c.
References Map_::len, and malloc().
Referenced by emit_Switch(), main(), map_remove(), new_Env(), new_NameSpace(), new_Operator_Map(), new_Scope(), scan2_Goto_Label(), scope_commit(), and scope_push().
 {
   Map map  = malloc(sizeof(struct Map_));
 //  map->key = calloc(1, sizeof(vtype));
 //  map->ptr = calloc(1, sizeof(vtype));
   map->len = 0;
   return map;
 }
new_Scope()
Scope new_Scope ()
Definition at line 314 of file map.c.
References Scope_::commit_map, malloc(), new_Map(), new_Vector(), scope_push(), and Scope_::vector.
Referenced by new_NameSpace().
 {
   Scope a = malloc(sizeof(struct Scope_));
   a->commit_map = new_Map();
   a->vector = new_Vector();
   scope_push(a);
   return a;
 }
new_Vector()
Vector new_Vector ()
Definition at line 15 of file map.c.
References Vector_::len, and malloc().
Referenced by assign_ugen(), compile(), emit_Ast(), emit_Func_Args(), emit_Func_Def(), emit_pop_scope(), emit_Primary_Expression(), env_reset(), event_ctor(), fc_ctor(), free_NameSpace(), getfull(), INSTR(), main(), mk_type_list(), mkadt_nspc(), mkdoc_nspc(), new_Code(), new_Context(), new_DL_Func(), new_Emitter(), new_Env(), new_Frame(), new_NameSpace(), new_Operator_Map(), new_Scope(), new_stmt_from_enum(), new_UGen(), new_Union(), new_VM(), parse(), scan2_Goto_Label(), scope_get(), and start_plug().
 {
   Vector v = malloc(sizeof(struct Vector_));
   v->len = 0;
   return v;
 }
new_Vector_fixed()
Vector new_Vector_fixed (const vtype len)
Definition at line 22 of file map.c.
References Vector_::len, and malloc().
Referenced by vector_copy(), and vector_remove().
 {
   Vector v = malloc(sizeof(struct Vector_));
   v->len   = len;
   return v;
 }
scope_add()
void scope_add (Scope scope, S_Symbol xid, vtype value)
Definition at line 267 of file map.c.
References Scope_::commit_map, map_set(), Scope_::vector, vector_back(), and vector_front().
Referenced by namespace_add_func(), namespace_add_type(), and namespace_add_value().
 {
   Map map;
   if(vector_front(scope->vector) != vector_back(scope->vector))
     map = (Map)vector_back(scope->vector);
   else
     map = scope->commit_map;
   map_set(map, (vtype)xid, (vtype)value);
   /*  add_ref(((struct Value_*)value)->obj);*/
 }
scope_commit()
void scope_commit (Scope scope)
Definition at line 289 of file map.c.
References Scope_::commit_map, free_Map(), map_commit(), new_Map(), Scope_::vector, and vector_front().
Referenced by namespace_commit().
 {
   Map map = (Map)vector_front(scope->vector);
   map_commit(map, scope->commit_map);
 //  map_clean(scope->commit_map);
   free_Map(scope->commit_map);
   scope->commit_map = new_Map();
 }
scope_get()
Vector scope_get (Scope a)
Definition at line 331 of file map.c.
References Scope_::commit_map, Map_::len, new_Vector(), Map_::ptr, Scope_::vector, vector_append(), vector_at(), and vector_size().
Referenced by free_NameSpace(), mkadt_nspc(), mkdoc_nspc(), and release().
 {
   vtype i, j;
   Vector ret = new_Vector();
   for(j = 0; j < vector_size(s->vector); j++) {
     Map map = (Map)vector_at(s->vector, j);
     for(i = 0; i < map->len; i++)
       vector_append(ret, map->ptr[i]);
   }
   for(i = 0; i < s->commit_map->len; i++)
     vector_append(ret, (vtype)s->commit_map->ptr[i]);
   return ret;
 }
scope_lookup()
vtype scope_lookup (Scope scope, S_Symbol xid, int climb)
Definition at line 240 of file map.c.
References Scope_::commit_map, map_get(), Scope_::vector, vector_at(), vector_back(), vector_front(), and vector_size().
Referenced by namespace_lookup_func(), namespace_lookup_type(), and namespace_lookup_value().
 {
   unsigned int i;
   vtype ret = 0;
   Map map;
   if(climb == 0) {
     map = (Map)vector_back(scope->vector);
     ret = map_get(map, (vtype)xid);
     if(!ret && vector_back(scope->vector) == vector_front(scope->vector))
       ret = map_get(scope->commit_map, (vtype)xid);
   } else if(climb > 0) {
     for(i = vector_size(scope->vector); i > 0; i--) {
       map = (Map)vector_at(scope->vector, i - 1);
       if((ret = map_get(map, (vtype)xid)))
         break;
     }
     if(!ret)
       ret = map_get(scope->commit_map, (vtype)xid);
   } else {
     map = (Map)vector_front(scope->vector);
     ret = map_get(map, (vtype)xid);
     if(!ret)
       ret = map_get(scope->commit_map, (vtype)xid);
   }
   return ret;
 }
scope_pop()
void scope_pop (Scope scope)
Definition at line 308 of file map.c.
References free_Map(), Scope_::vector, vector_back(), and vector_pop().
Referenced by namespace_pop_type(), and namespace_pop_value().
 {
   free_Map((Map)vector_back(scope->vector));
   vector_pop(scope->vector);
 }
scope_push()
void scope_push (Scope scope)
Definition at line 303 of file map.c.
References new_Map(), Scope_::vector, and vector_append().
Referenced by namespace_push_type(), namespace_push_value(), and new_Scope().
 {
   vector_append(scope->vector, (vtype)new_Map());
 }
scope_rem()
void scope_rem (Scope scope, S_Symbol xid)
Definition at line 278 of file map.c.
References Scope_::commit_map, map_remove(), Scope_::vector, vector_back(), and vector_front().
Referenced by emit_Ast(), free_Section(), and scan2_Func_Def().
 {
   Map map;
   if(vector_front(scope->vector) != vector_back(scope->vector))
     map = (Map)vector_back(scope->vector);
   else
     map = scope->commit_map;
   map_remove(map, (vtype)xid);
   /*  rem_ref(((struct Value_*)value)->obj);*/
 }
scope_rollback()
void scope_rollback (Scope scope, void(*)(vtype arg) _free)
Definition at line 298 of file map.c.
References Scope_::commit_map, and map_rollback().
Referenced by namespace_rollback().
 {
   map_rollback(scope->commit_map, _free);
 }
vector_append()
void vector_append (Vector vector, vtype data)
Definition at line 29 of file map.c.
References Vector_::len, and Vector_::ptr.
Referenced by add_binary_op(), add_instr(), append_doc(), check_Class_Def(), check_For(), check_Func_Def(), check_Goto_Label(), check_Loop(), check_Until(), check_While(), compile(), context_add_class(), context_add_func(), context_add_type(), context_add_value(), dl_func_add_arg(), emit_add_break(), emit_add_code(), emit_add_cont(), emit_add_return(), emit_Class_Def(), emit_Decl_Expression(), emit_Do_Until(), emit_Do_While(), emit_For(), emit_Func_Args(), emit_Func_Call(), emit_Func_Def(), emit_Func_Ptr(), emit_Loop(), emit_Primary_Expression(), emit_spork(), emit_Unary(), emit_Until(), env_reset(), find_template_match(), frame_alloc_local(), frame_pop_scope(), frame_push_scope(), getfull(), import_class_begin(), INSTR(), load_context(), main(), MFUN(), mk_type_list(), mkadt_nspc(), mkdoc_nspc(), release(), scan0_Class_Def(), scan1_Class_Def(), scan1_Enum(), scan2_Class_Def(), scope_get(), scope_push(), type_engine_init(), ugen_ctor(), and vm_add_shred().
 {
   v->len++;
   v->ptr[v->len - 1] = (vtype)data;
 }
vector_at()
vtype vector_at (Vector vector, const vtype)
Definition at line 94 of file map.c.
References Vector_::len, and Vector_::ptr.
Referenced by base_tick(), broadcast(), channel_compute(), emit_Ast(), emit_Enum(), emit_Func_Def(), emit_Goto_Label(), emit_pop_scope(), free_Context(), free_Emitter(), free_Frame(), free_NameSpace(), free_Operator_Map(), free_Stmt_Enum(), free_VM_Code(), getfull(), INSTR(), main(), make_dll_arg_list(), MFUN(), mk_type_list(), mkadt_context(), mkadt_nspc(), mkdoc_context(), mkdoc_nspc(), operator_doc(), operator_find(), release(), scope_get(), scope_lookup(), server_thread(), SFUN(), stop_plug(), ugen_compute(), ugen_dtor(), and vm_run().
 {
   if(i >= v->len)
     return 0;
   return (vtype)v->ptr[i];
 }
vector_back()
vtype vector_back (Vector vector)
Definition at line 108 of file map.c.
References Vector_::len, and Vector_::ptr.
Referenced by check_Class_Def(), emit_Class_Def(), emit_Decl_Expression(), emit_Do_Until(), emit_Do_While(), emit_For(), emit_Func_Call(), emit_Func_Def(), emit_Loop(), emit_spork(), emit_Switch(), emit_Unary(), emit_Until(), emit_While(), find_template_match(), frame_pop_scope(), free_Env(), free_VM_Code(), getfull(), import_class_end(), scan0_Class_Def(), scan1_Class_Def(), scan2_Class_Def(), scope_add(), scope_lookup(), scope_pop(), scope_rem(), and unload_context().
 {
   return (vtype)v->ptr[v->len - 1];
 }
vector_clear()
void vector_clear (Vector vector)
Definition at line 118 of file map.c.
References Vector_::len.
Referenced by broadcast(), and emit_Ast().
 {
   v->len = 0;
 }
vector_copy()
Vector vector_copy (Vector v)
Definition at line 35 of file map.c.
References Vector_::len, new_Vector_fixed(), and Vector_::ptr.
Referenced by check_Class_Def(), import_class_begin(), and new_VM_Code().
 {
   Vector ret = new_Vector_fixed(v->len);
   vtype i;
   for(i = 0; i < v->len; i++)
     ret->ptr[i] = v->ptr[i];
   return ret;
 }
vector_find()
long int vector_find (Vector vector, vtype data)
Definition at line 44 of file map.c.
References Vector_::len, and Vector_::ptr.
Referenced by INSTR(), MFUN(), shreduler_remove(), and ugen_dtor().
 {
   vtype i;
   for(i = 0; i < v->len; i++)
     if(v->ptr[i] == (vtype)data)
       return i;
   return -1;
 }
vector_front()
vtype vector_front (Vector vector)
Definition at line 87 of file map.c.
References Vector_::len, and Vector_::ptr.
Referenced by free_Scope(), get_doc(), MFUN(), parse(), scope_add(), scope_commit(), scope_lookup(), scope_rem(), and shreduler_remove().
 {
   if(!v->len)
     return 0;
   return (vtype)v->ptr[0];
 }
vector_pop()
void vector_pop (Vector vector)
Definition at line 82 of file map.c.
References Vector_::len, and vector_remove().
Referenced by check_Class_Def(), check_For(), check_Loop(), check_Until(), check_While(), emit_Class_Def(), emit_Do_Until(), emit_Do_While(), emit_For(), emit_Func_Call(), emit_Func_Def(), emit_Loop(), emit_spork(), emit_Switch(), emit_Unary(), emit_Until(), emit_While(), find_template_match(), frame_pop_scope(), free_Env(), import_class_end(), release(), scan0_Class_Def(), scan1_Class_Def(), scan2_Class_Def(), scope_pop(), and unload_context().
 {
   vector_remove(v, v->len - 1);
 }
vector_remove()
void vector_remove (Vector vector, const vtype index)
Definition at line 60 of file map.c.
References free(), Vector_::len, new_Vector_fixed(), and Vector_::ptr.
Referenced by get_doc(), INSTR(), MFUN(), parse(), shreduler_remove(), ugen_dtor(), and vector_pop().
 {
   Vector tmp;
   vtype i, j = 0;
   if(!v->len || index >= v->len)
     return;
   if(v->len == 1 && !index) {
     v->len--;
     return;
   }
   tmp = new_Vector_fixed(v->len - 1);
   for(i = 0; i < v->len; i++) {
     if(i != index) {
       tmp->ptr[j] = v->ptr[i];
       j++;
     }
   }
   *v = *tmp;
   free(tmp);
 }
vector_set()
void vector_set (Vector vector, const vtype i, vtype data)
Definition at line 53 of file map.c.
References Vector_::len, and Vector_::ptr.
Referenced by check_Func_Def().
 {
   if(i >= v->len)
     return;
   v->ptr[i] = (vtype)arg;
 }
vector_size()
vtype vector_size (Vector vector)
Definition at line 113 of file map.c.
References Vector_::len.
Referenced by base_tick(), broadcast(), channel_compute(), check_Break(), check_Continue(), check_Func_Def(), emit_Ast(), emit_Case(), emit_Do_Until(), emit_Do_While(), emit_Dot_Member(), emit_Enum(), emit_exp_if(), emit_For(), emit_Func_Def(), emit_Goto_Label(), emit_If(), emit_Loop(), emit_pop_scope(), emit_pre_constructor_array(), emit_Switch(), emit_Until(), emit_While(), frame_pop_scope(), free_Context(), free_Emitter(), free_Env(), free_Frame(), free_NameSpace(), free_Operator_Map(), free_Stmt_Enum(), free_VM_Code(), getfull(), INSTR(), main(), make_dll_arg_list(), MFUN(), mk_type_list(), mkadt_context(), mkadt_nspc(), mkdoc_context(), mkdoc_nspc(), operator_doc(), operator_find(), release(), scope_get(), scope_lookup(), SFUN(), shreduler_get(), shreduler_remove(), stop_plug(), ugen_compute(), ugen_dtor(), vm_add_shred(), and vm_run().
 {
   return v->len;
 }