object.h – Gwion
Gwion
A strongly timed musical programming language
object.h
object.h File Reference
Macros
#define Except(s) { NullException(s);return; }
Functions
void object_dtor (M_Object o, VM_Shred shred)
m_bool import_object (Env env)
m_bool initialize_object (M_Object o, Type type)
M_Object new_String (m_str str)
void release (M_Object obj, VM_Shred shred)
void NullException (VM_Shred shred)
Macro Definition Documentation
Except
#define Except (s) { NullException(s);return; }
Definition at line 7 of file object.h.
Referenced by INSTR().
Function Documentation
import_object()
m_bool import_object (Env env)
Definition at line 243 of file object.c.
References add_binary_op(), add_global_type(), add_global_value(), Assign_Object(), CHECK_BB, CHECK_OB, Env_::class_def, Type_::doc, Env_::global_nspc, import_class_begin(), import_class_end(), import_mvar(), object_dtor(), op_at_chuck, op_eq, op_neq, and t_int.
Referenced by type_engine_init().
 {
   CHECK_BB(add_global_type(env, &t_object))
   CHECK_OB(import_class_begin(env, &t_object, env->global_nspc, NULL, object_dtor))
   env->class_def->doc = "the base class";
   CHECK_BB(add_binary_op(env, op_at_chuck, &t_null, &t_object, &t_object, Assign_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_at_chuck, &t_object, &t_object, &t_object, Assign_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_eq,  &t_object, &t_object, &t_int,  eq_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_neq, &t_object, &t_object, &t_int, neq_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_eq,  &t_null,   &t_object, &t_int,  eq_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_neq, &t_null,   &t_object, &t_int, neq_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_eq,  &t_object, &t_null, &t_int,  eq_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_neq, &t_object, &t_null, &t_int, neq_Object, 1, 0))
   add_global_value(env, "NULL", &t_object, 1, 0);
   CHECK_BB(import_class_end(env))
   CHECK_BB(add_global_type(env, &t_vararg))
   CHECK_BB(add_global_type(env, &t_varobj))
   CHECK_OB(import_class_begin(env, &t_vararg, env->global_nspc, NULL, NULL))
   import_mvar(env, "int", "start", 1, 0, "start vararg loop");
   import_mvar(env, "int", "end", 1, 0, "end vararg loop");
   import_mvar(env, "int", "i", 1, 0, "vararg int");
   import_mvar(env, "float", "f", 1, 0, "vararg float");
   import_mvar(env, "time", "t", 1, 0, "vararg time");
   import_mvar(env, "dur", "d", 1, 0, "vararg dur");
   import_mvar(env, "complex", "c", 1, 0, "vararg complex");
   import_mvar(env, "polar", "p", 1, 0, "vararg polar");
   import_mvar(env, "Vec3", "v3", 1, 0, "vararg Vec3");
   import_mvar(env, "Vec4", "v4", 1, 0, "vararg Vec4");
   import_mvar(env, "VarObject", "o", 1, 0, "vararg object");
   CHECK_BB(import_class_end(env))
   return 1;
 }
initialize_object()
m_bool initialize_object (M_Object o, Type type)
Definition at line 44 of file object.c.
References M_Object_::d, M_Object_::data, err_msg(), Type_::info, Type_::name, Type_::obj_size, NameSpace_::obj_v_table, Type_::size, M_Object_::size, and TYPE_.
Referenced by import_fileio(), instantiate_object(), new_M_Array(), new_M_UGen(), new_Shred(), and new_String().
 {
   if (!type->info) {
     err_msg(TYPE_, 0, "internal error: no type->info for type '%s'", type->name);
     return -1;
   }
   object->vtable = type->info->obj_v_table;
   object->type_ref = type;
   object->size = type->obj_size;
   if (object->size) {
     object->d.data = calloc(object->size, sizeof(unsigned char));
     if (!object->d.data)
       goto out_of_memory;
     memset(object->d.data, 0, object->size);
   } else
     object->d.data = NULL;
   return 1;
 out_of_memory:
   err_msg(TYPE_, 0, "OutOfMemory: while instantiating object '%s'\n", type->name);
   return -1;
 }
new_String()
M_Object new_String (m_str str)
Definition at line 36 of file object.c.
References initialize_object(), insert_symbol(), new_M_Object(), S_name(), STRING, and t_string.
Referenced by INSTR(), MFUN(), and SFUN().
 {
   M_Object o = new_M_Object();
   initialize_object(o, &t_string);
   STRING(o) = S_name(insert_symbol(str));
   return o;
 }
NullException()
void NullException (VM_Shred shred)
Definition at line 16 of file object.c.
References err_msg(), INSTR_, VM_Shred_::is_done, VM_Shred_::is_running, VM_Shred_::name, VM_Shred_::pc, and VM_Shred_::xid.
 {
   err_msg(INSTR_, 0, "NullPointerException: shred[id=%lu:%s], PC=[%lu]\n",
           shred->xid, shred->name, shred->pc);
   shred->is_running = 0;
   shred->is_done = 1;
 }
object_dtor()
void object_dtor (M_Object o, VM_Shred shred)
Definition at line 105 of file object.c.
References M_Object_::d, M_Object_::data, and free().
Referenced by import_object().
 {
   free(o->d.data);
   free(o);
 }
release()
void release (M_Object obj, VM_Shred shred)
Definition at line 67 of file object.c.
References M_Object_::d, M_Object_::data, NameSpace_::dtor, EOC(), Instr_::execute, free_Vector(), Type_::has_destructor, Type_::info, VM_Code_::instr, isprim(), Value_::m_type, VM_Shred_::me, VM_Shred_::mem, Type_::name, VM_Code_::native_func, new_Instr(), new_Shred(), new_VM_Code(), new_VM_Shred(), Type_::obj, Value_::offset, Type_::parent, M_Object_::ref, release(), scope_get(), SIZEOF_MEM, M_Object_::type_ref, NameSpace_::value, vector_append(), vector_at(), vector_pop(), vector_size(), vm_add_shred(), and VM_Shred_::vm_ref.
Referenced by INSTR(), and release().
 {
   if (!obj)
     return;
   if (!--obj->ref) {
     Type t = obj->type_ref;
     while (t) {
 #ifdef DEBUG_INSTR
       debug_msg("instr", "dtor loop %p %s", obj, t->name);
 #endif
       m_uint i;
       Vector v = scope_get(t->info->value);
       for(i = 0; i < vector_size(v); i++) {
         Value value = (Value)vector_at(v, i);
         if(isprim(value->m_type) < 0)
           release(*(M_Object*)(obj->d.data + value->offset), shred);
       }
       free_Vector(v);
       if (t->has_destructor) {
         if (t->info->dtor->native_func)
           ((f_dtor)t->info->dtor->native_func)(obj, shred);
         else {
           VM_Code code = new_VM_Code(t->info->dtor->instr, SZ_INT, 1, "[dtor]", "[in code dtor exec]");
           VM_Shred sh = new_VM_Shred(code);
           sh->me = new_Shred(shred->vm_ref, sh);
           memcpy(sh->mem, shred->mem, SIZEOF_MEM);
           vector_pop(code->instr);
           Instr eoc = new_Instr();
           eoc->execute = EOC;
           vector_append(code->instr, (vtype)eoc);
           vm_add_shred(shred->vm_ref, sh);
         }
       }
       t = t->parent;
     }
   }
 }