Gwion dev-docs: drvr/raw.c File Reference
--- layout: homepage title: raw.c image: feature: abstract-1.jpg ---
raw.c File Reference
#include <stdlib.h>
#include "vm.h"
#include "bbq.h"
#include "driver.h"
Functions
static m_bool raw_ini (VM *vm, DriverInfo *di)
static void raw_run (VM *vm, DriverInfo *di)
static void raw_del (VM *vm)
Driver * raw_driver (VM *vm)
Variables
static sp_audio spa
Function Documentation
raw_del()
static void raw_del (VM * vm) static
Definition at line 27 of file raw.c.
References spa.
Referenced by raw_driver().
 {
   spa_close(&spa);
 }
raw_driver()
Driver* raw_driver (VM * vm)
Definition at line 32 of file raw.c.
References driver_wrapper::del, driver_wrapper::ini, malloc(), no_wakeup(), raw_del(), raw_ini(), raw_run(), driver_wrapper::run, and VM::wakeup.
Referenced by no_wakeup(), and select_driver().
 {
   Driver* d = malloc(sizeof(Driver));
   d->ini = raw_ini;
   d->run = raw_run;
   d->del = raw_del;
   vm->wakeup = no_wakeup;
   return d;
 }
raw_ini()
static m_bool raw_ini (VM * vm, DriverInfo * di) static
Definition at line 7 of file raw.c.
References VM::bbq, containing_driver_info::card, BBQ_::sp, and spa.
Referenced by raw_driver().
 {
   char tmp[104];
   sprintf(tmp, "%s.raw", di->card);
   if(spa_open(vm->bbq->sp, &spa, tmp, SPA_WRITE) == SP_NOT_OK) {
     fprintf(stderr, "Error: could not open file %s.\n", di->card);
     return -1;
   }
   return 1;
 }
raw_run()
static void raw_run (VM * vm, DriverInfo * di) static
Definition at line 18 of file raw.c.
References VM::bbq, VM::is_running, BBQ_::sp, spa, and vm_run().
Referenced by raw_driver().
 {
   while(vm->is_running) {
     vm_run(vm);
     spa_write_buf(vm->bbq->sp, &spa, vm->bbq->sp->out, vm->bbq->sp->nchan);
     vm->bbq->sp->pos++;
   }
 }
Variable Documentation
spa
sp_audio spa static
Definition at line 6 of file raw.c.
Referenced by raw_del(), raw_ini(), and raw_run().