shred.c – Gwion
Gwion
A strongly timed musical programming language
shred.c
shred.c File Reference
#include <libgen.h>
#include "defs.h"
#include "vm.h"
#include "type.h"
#include "err_msg.h"
#include "instr.h"
#include "lang.h"
#include "import.h"
Functions
M_Object new_Shred (VM *vm, VM_Shred shred)
static MFUN (vm_shred_exit)
static MFUN (vm_shred_id)
static MFUN (vm_shred_is_running)
static MFUN (vm_shred_is_done)
static MFUN (shred_yield)
static SFUN (vm_shred_from_id)
static MFUN (shred_args)
static MFUN (shred_arg)
static MFUN (shred_path)
static MFUN (shred_dir)
static DTOR (shred_dtor)
m_bool import_shred (Env env)
Variables
struct Type_ t_shred = { "Shred", sizeof(m_uint), &t_object, te_shred}
m_int o_shred_me
Function Documentation
DTOR()
static DTOR (shred_dtor) static
Definition at line 99 of file shred.c.
References release().
 {
   release(o, shred);
 }
import_shred()
m_bool import_shred (Env env)
Definition at line 104 of file shred.c.
References add_global_type(), CHECK_BB, CHECK_OB, Env_::class_def, dl_func_add_arg(), Func_::doc, Type_::doc, DL_Value::doc, Env_::global_nspc, import_class_begin(), import_class_end(), import_mfun(), import_mvar(), import_sfun(), new_DL_Func(), and o_shred_me.
Referenced by type_engine_init().
 {
   DL_Func* fun;
   DL_Value* arg;
   Func f;
   CHECK_BB(add_global_type(env, &t_shred))
   CHECK_OB(import_class_begin(env, &t_shred, env->global_nspc, NULL, shred_dtor))
   env->class_def->doc = "Shred is the type for processes, allowing to handle concurrency";
   o_shred_me = import_mvar(env, "int", "@me",   0, 0, "shred placeholder");
   CHECK_BB(o_shred_me)
   fun = new_DL_Func("void", "exit", (m_uint)vm_shred_exit);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "make the shred exit";
   fun = new_DL_Func("int", "running", (m_uint)vm_shred_is_running);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "return 1 if shred is done, 0 otherwise";
   fun = new_DL_Func("int", "done", (m_uint)vm_shred_is_done);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "return 1 if shred is done, 0 otherwise";
   fun = new_DL_Func("int", "id", (m_uint)vm_shred_id);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "return shred id";
   fun = new_DL_Func("Shred", "fromId", (m_uint)vm_shred_from_id);
   arg = dl_func_add_arg(fun, "int", "arg1");
   arg->doc = "id of the shred";
   CHECK_OB((f = import_sfun(env, fun)))
   f->doc = "get a shred from id";
   fun = new_DL_Func("int", "yield", (m_uint)shred_yield);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "let other shreds a chance to compute";
   fun = new_DL_Func("int", "args", (m_uint)shred_args);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "return shred arguments number";
   fun = new_DL_Func("string", "arg", (m_uint)shred_arg);
   dl_func_add_arg(fun, "int", "n");
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "return shred nth argument";
   fun = new_DL_Func("string", "path", (m_uint)shred_path);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "return shred basename";
   fun = new_DL_Func("string", "dir", (m_uint)shred_dir);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "return shred dirname";
   CHECK_BB(import_class_end(env))
   return 1;
 }
MFUN() [1/9]
static MFUN (vm_shred_exit) static
Definition at line 21 of file shred.c.
References VM_Shred_::is_done, VM_Shred_::is_running, and ME.
 {
   VM_Shred  s = ME(o);
   s->is_running = 0;
   s->is_done = 1;
 }
MFUN() [2/9]
static MFUN (vm_shred_id) static
Definition at line 28 of file shred.c.
References ME, RETURN, and VM_Shred_::xid.
 {
   VM_Shred  s = ME(o);
   RETURN->d.v_uint = s ? s->xid : -1;
 }
MFUN() [3/9]
static MFUN (vm_shred_is_running) static
Definition at line 34 of file shred.c.
References VM_Shred_::is_running, ME, and RETURN.
 {
   VM_Shred  s = ME(o);
   RETURN->d.v_uint = s ? s->is_running : 0;
 }
MFUN() [4/9]
static MFUN (vm_shred_is_done) static
Definition at line 40 of file shred.c.
References VM_Shred_::is_done, ME, and RETURN.
 {
   VM_Shred  s = ME(o);
   RETURN->d.v_uint = s ? s->is_done : 0;
 }
MFUN() [5/9]
static MFUN (shred_yield) static
Definition at line 46 of file shred.c.
References get_now(), ME, RETURN, shredule(), and shreduler_remove().
 {
   VM_Shred  s = ME(o);
   Shreduler sh = shred->vm_ref->shreduler;
   shreduler_remove(sh, s, 0);
   shredule(sh, s, get_now(sh) + .5);
   RETURN->d.v_uint = 1;
 }
MFUN() [6/9]
static MFUN (shred_args) static
Definition at line 66 of file shred.c.
References VM_Shred_::args, ME, RETURN, and vector_size().
 {
   VM_Shred  s = ME(o);
   RETURN->d.v_uint = s->args ? vector_size(s->args) : 0;
 }
MFUN() [7/9]
static MFUN (shred_arg) static
Definition at line 72 of file shred.c.
References VM_Shred_::args, ME, new_String(), RETURN, and vector_at().
 {
   m_str str;
   VM_Shred  s = ME(o);
   if(!s->args) {
     RETURN->d.v_uint = 0;
     return;
   }
   str = (m_str)vector_at(s->args, *(m_uint*)(shred->mem + SZ_INT));
   RETURN->d.v_uint = str ? (m_uint)new_String(str) : 0;
 }
MFUN() [8/9]
static MFUN (shred_path) static
Definition at line 84 of file shred.c.
References VM_Shred_::code, VM_Code_::filename, ME, new_String(), and RETURN.
 {
   VM_Shred  s = ME(o);
   RETURN->d.v_uint = (m_uint)new_String(s->code->filename);
 }
MFUN() [9/9]
static MFUN (shred_dir) static
Definition at line 90 of file shred.c.
References VM_Shred_::code, VM_Code_::filename, ME, new_String(), and RETURN.
 {
   VM_Shred  s = ME(o);
   char c[strlen(s->code->filename) + 1];
   memset(c, 0, strlen(s->code->filename) + 1);
   strncpy(c, s->code->filename, strlen(s->code->filename));
   RETURN->d.v_uint = (m_uint)new_String(dirname(c));
 }
new_Shred()
M_Object new_Shred (VM * vm, VM_Shred shred)
Definition at line 13 of file shred.c.
References initialize_object(), ME, new_M_Object(), and Type_::obj.
Referenced by compile(), INSTR(), and release().
 {
   M_Object obj = new_M_Object();
   initialize_object(obj, &t_shred);
   ME(obj) = shred;
   return obj;
 }
SFUN()
static SFUN (vm_shred_from_id) static
Definition at line 55 of file shred.c.
References VM_Shred_::me, M_Object_::ref, RETURN, and vector_at().
 {
   VM_Shred s = (VM_Shred)vector_at(shred->vm_ref->shred, *(m_uint*)(shred->mem + SZ_INT) - 1);
   if(!s)
     RETURN->d.v_uint = 0;
   else {
     RETURN->d.v_uint = (m_uint)s->me;
     s->me->ref++;
   }
 }
Variable Documentation
o_shred_me
m_int o_shred_me
Definition at line 11 of file shred.c.
Referenced by import_shred().
t_shred
struct Type_ t_shred = { "Shred", sizeof(m_uint), &t_object, te_shred}
Definition at line 10 of file shred.c.
Referenced by check_Primary_Expression(), check_Unary(), and scan2_Decl_Expression().