soundio.c – Gwion
Gwion
A strongly timed musical programming language
soundio.c
soundio.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <soundio/soundio.h>
#include "defs.h"
#include "vm.h"
#include "driver.h"
#include "bbq.h"
Functions
void sio_wakeup ()
static void write_sample_s16ne (char *ptr, double sample)
static void write_sample_s32ne (char *ptr, double sample)
static void write_sample_float32ne (char *ptr, double sample)
static void write_sample_float64ne (char *ptr, double sample)
static void read_sample_s16ne (char *ptr, double *sample)
static void read_sample_s32ne (char *ptr, double *sample)
static void read_sample_float32ne (char *ptr, double *sample)
static void read_sample_float64ne (char *ptr, double *sample)
static void underflow_callback (struct SoundIoOutStream *outstream)
static void overflow_callback (struct SoundIoInStream *stream)
static void write_callback (struct SoundIoOutStream *outstream, int frame_count_min, int frame_count_max)
static void read_callback (struct SoundIoInStream *instream, int frame_count_min, int frame_count_max)
static m_bool sio_ini (VM *vm, DriverInfo *di)
void sio_run ()
void sio_del (VM *vm)
Driver * sio_driver (VM *vm)
Variables
static struct SoundIo * soundio = NULL
static struct SoundIoOutStream * outstream = NULL
static struct SoundIoInStream * instream = NULL
static struct SoundIoDevice * out_device = NULL
static struct SoundIoDevice * in_device = NULL
static enum SoundIoBackend backend = SoundIoBackendNone
static m_str device_id = NULL
static m_bool raw = false
static void(* write_sample)(char *ptr, double sample)
static void(* read_sample)(char *ptr, double *sample)
Function Documentation
overflow_callback()
static void overflow_callback (struct SoundIoInStream * stream) static
Definition at line 92 of file soundio.c.
Referenced by sio_ini().
 {
   static int count = 0;
   fprintf(stderr, "overflow %d\n", count++);
 }
read_callback()
static void read_callback (struct SoundIoInStream * instream, int frame_count_min, int frame_count_max) static
Definition at line 144 of file soundio.c.
References VM::bbq, BBQ_::in, VM::is_running, read_sample, and vm.
Referenced by sio_ini().
 {
   struct SoundIoChannelArea *areas;
   int err;
   int frames_left = frame_count_max;
   VM* vm = (VM*)instream->userdata;
   for (;;) {
     int frame_count = frames_left;
     if ((err = soundio_instream_begin_read(instream, &areas, &frame_count))) {
       vm->is_running = 0;
       fprintf(stderr, "begin read error: %s", soundio_strerror(err));
       return;
     }
     if (!frame_count)
       break;
     if (!areas) {
 //            memset(data, 0, frame_count * instream->bytes_per_frame);
       fprintf(stderr, "Dropped %d frames due to internal overflow\n", frame_count);
     } else {
 //frame_count= 256;
       char* data[SZ_FLOAT];
       for (int frame = 0; frame < frame_count; frame += 1) {
         for (int ch = 0; ch < instream->layout.channel_count; ch += 1) {
 //                    memcpy(data, areas[ch].ptr, instream->bytes_per_sample);
 // FIXME
 //vm->bbq->in[ch] = *(m_float*)data;
           read_sample(areas[ch].ptr, &vm->bbq->in[ch]);
           areas[channel].ptr += areas[channel].step;
         }
       }
     }
     if ((err = soundio_instream_end_read(instream))) {
       fprintf(stderr, "end read error: %s", soundio_strerror(err));
       vm->is_running = 0;
       return;
     }
     frames_left -= frame_count;
     if (frames_left <= 0)
       break;
   }
 }
read_sample_float32ne()
static void read_sample_float32ne (char * ptr, double * sample) static
Definition at line 73 of file soundio.c.
Referenced by sio_ini().
 {
   *sample = *(float *)ptr;
 }
read_sample_float64ne()
static void read_sample_float64ne (char * ptr, double * sample) static
Definition at line 78 of file soundio.c.
Referenced by sio_ini().
 {
   *sample = *(double *)ptr;
 }
read_sample_s16ne()
static void read_sample_s16ne (char * ptr, double * sample) static
Definition at line 57 of file soundio.c.
References INT16_MAX, and INT16_MIN.
Referenced by sio_ini().
 {
   int16_t *buf = (int16_t *)ptr;
   double range = (double)INT16_MAX - (double)INT16_MIN;
   double val = *buf * range / 2.0;
   *sample = val;
 }
read_sample_s32ne()
static void read_sample_s32ne (char * ptr, double * sample) static
Definition at line 65 of file soundio.c.
References INT32_MAX, and INT32_MIN.
Referenced by sio_ini().
 {
   int32_t *buf = (int32_t *)ptr;
   double range = (double)INT32_MAX - (double)INT32_MIN;
   double val = *buf * range / 2.0;
   *sample = val;
 }
sio_del()
void sio_del (VM * vm)
Definition at line 346 of file soundio.c.
References in_device, instream, out_device, outstream, and soundio.
Referenced by sio_driver().
 {
   soundio_outstream_destroy(outstream);
   soundio_instream_destroy(instream);
   soundio_device_unref(in_device);
   soundio_device_unref(out_device);
   soundio_destroy(soundio);
 }
sio_driver()
Driver* sio_driver (VM * vm)
Definition at line 355 of file soundio.c.
References driver_wrapper::del, driver_wrapper::ini, malloc(), driver_wrapper::run, sio_del(), sio_ini(), sio_run(), sio_wakeup(), and VM::wakeup.
Referenced by no_wakeup(), select_driver(), and select_format().
 {
   Driver* d = malloc(sizeof(Driver));
   d->ini = sio_ini;
   d->run = sio_run;
   d->del = sio_del;
   vm->wakeup = sio_wakeup;
   return d;
 }
sio_ini()
static m_bool sio_ini (VM * vm, DriverInfo * di) static
Definition at line 191 of file soundio.c.
References backend, containing_driver_info::card, device_id, in_device, instream, out_device, outstream, overflow_callback(), raw, read_callback(), read_sample, read_sample_float32ne(), read_sample_float64ne(), read_sample_s16ne(), read_sample_s32ne(), soundio, containing_driver_info::sr, underflow_callback(), vm, write_callback(), write_sample, write_sample_float32ne(), write_sample_float64ne(), write_sample_s16ne(), and write_sample_s32ne().
Referenced by sio_driver().
 {
   soundio = soundio_create();
   device_id = di->card;
   if (!soundio) {
     fprintf(stderr, "out of memory\n");
     return -1;
   }
   int err = (backend == SoundIoBackendNone) ?
             soundio_connect(soundio) : soundio_connect_backend(soundio, backend);
   if (err) {
     fprintf(stderr, "Unable to connect to backend: %s\n", soundio_strerror(err));
     return -1;
   }
   soundio_flush_events(soundio);
   int selected_device_index = -1;
   if (device_id) {
     int device_count = soundio_output_device_count(soundio);
     for (int i = 0; i < device_count; i += 1) {
       struct SoundIoDevice *device = soundio_get_output_device(soundio, i);
       bool select_this_one = strcmp(device->id, device_id) == 0 && device->is_raw == raw;
       soundio_device_unref(device);
       if (select_this_one) {
         selected_device_index = i;
         break;
       }
     }
   } else {
     selected_device_index = soundio_default_output_device_index(soundio);
   }
   if (selected_device_index < 0) {
     fprintf(stderr, "Output device not found\n");
     return -1;
   }
   out_device = soundio_get_output_device(soundio, selected_device_index);
   if (!out_device) {
     fprintf(stderr, "out of memory\n");
     return -1;
   }
   in_device = soundio_get_input_device(soundio, selected_device_index);
   if (!in_device) {
     fprintf(stderr, "out of memory\n");
     return -1;
   }
   if(out_device->probe_error) {
     fprintf(stderr, "Cannot probe device: %s\n", soundio_strerror(out_device->probe_error));
     return -1;
   }
   if(in_device->probe_error) {
     fprintf(stderr, "Cannot probe device: %s\n", soundio_strerror(out_device->probe_error));
     return -1;
   }
   outstream = soundio_outstream_create(out_device);
   if (!outstream) {
     fprintf(stderr, "out of memory\n");
     return -1;
   }
   outstream->write_callback = write_callback;
   outstream->underflow_callback = underflow_callback;
   outstream->name = "Gwion output";
   outstream->software_latency = 0;
   outstream->sample_rate = di->sr;
   instream = soundio_instream_create(in_device);
   if (!instream) {
     fprintf(stderr, "out of memory\n");
     return -1;
   }
   instream->read_callback = read_callback;
   instream->overflow_callback = overflow_callback;
   instream->name = "Gwion input";
   instream->software_latency = 0;
   instream->sample_rate = di->sr;
   if (soundio_device_supports_format(out_device, SoundIoFormatFloat64NE)) {
     outstream->format = SoundIoFormatFloat64NE;
     write_sample = write_sample_float64ne;
   } else if (soundio_device_supports_format(out_device, SoundIoFormatFloat32NE)) {
     outstream->format = SoundIoFormatFloat32NE;
     write_sample = write_sample_float32ne;
   } else if (soundio_device_supports_format(out_device, SoundIoFormatS32NE)) {
     outstream->format = SoundIoFormatS32NE;
     write_sample = write_sample_s32ne;
   } else if (soundio_device_supports_format(out_device, SoundIoFormatS16NE)) {
     outstream->format = SoundIoFormatS16NE;
     write_sample = write_sample_s16ne;
   } else {
     fprintf(stderr, "No suitable device format available.\n");
     return -1;
   }
   if (soundio_device_supports_format(in_device, SoundIoFormatFloat64NE)) {
     instream->format = SoundIoFormatFloat64NE;
     read_sample = read_sample_float64ne;
   } else if (soundio_device_supports_format(in_device, SoundIoFormatFloat32NE)) {
     instream->format = SoundIoFormatFloat32NE;
     read_sample = read_sample_float32ne;
   } else if (soundio_device_supports_format(in_device, SoundIoFormatS32NE)) {
     instream->format = SoundIoFormatS32NE;
     read_sample = read_sample_s32ne;
   } else if (soundio_device_supports_format(in_device, SoundIoFormatS16NE)) {
     instream->format = SoundIoFormatS16NE;
     read_sample = read_sample_s16ne;
   } else {
     fprintf(stderr, "No suitable device format available.\n");
     return -1;
   }
   if ((err = soundio_outstream_open(outstream))) {
     fprintf(stderr, "unable to open output device: %s", soundio_strerror(err));
     return -1;
   }
   if ((err = soundio_instream_open(instream))) {
     fprintf(stderr, "unable to open input device: %s", soundio_strerror(err));
     return -1;
   }
   if (outstream->layout_error) {
     fprintf(stderr, "unable to set output channel layout: %s\n", soundio_strerror(outstream->layout_error));
     return -1;
   }
   if (instream->layout_error) {
     fprintf(stderr, "unable to set input channel layout: %s\n", soundio_strerror(instream->layout_error));
     return -1;
   }
   outstream->userdata = vm;
   instream->userdata = vm;
   return 1;
 }
sio_run()
void sio_run ()
Definition at line 330 of file soundio.c.
References instream, VM::is_running, outstream, soundio, and vm.
Referenced by sio_driver().
 {
   int err;
   if((err = soundio_instream_start(instream))) {
     fprintf(stderr, "unable to start input device: %s\n", soundio_strerror(err));
     return;
   }
   if((err = soundio_outstream_start(outstream))) {
     fprintf(stderr, "unable to start ouput device: %s\n", soundio_strerror(err));
     return;
   }
   while(vm->is_running)
     soundio_wait_events(soundio);
 }
sio_wakeup()
void sio_wakeup ()
Definition at line 25 of file soundio.c.
References soundio.
Referenced by sio_driver().
 {
   soundio_wakeup(soundio);
 }
underflow_callback()
static void underflow_callback (struct SoundIoOutStream * outstream) static
Definition at line 86 of file soundio.c.
Referenced by sio_ini().
 {
   static int count = 0;
   fprintf(stderr, "underflow %d\n", count++);
 }
write_callback()
static void write_callback (struct SoundIoOutStream * outstream, int frame_count_min, int frame_count_max) static
Definition at line 98 of file soundio.c.
References VM::bbq, VM::is_running, BBQ_::sp, vm, vm_run(), and write_sample.
Referenced by sio_ini().
 {
 //  double sr = outstream->sample_rate;
 //  double seconds_per_frame = 1.0 / sr;
   struct SoundIoChannelArea *areas;
   int    err;
   int    left = frame_count_max;
   const struct SoundIoChannelLayout *layout = &outstream->layout;
   VM* vm = (VM*)outstream->userdata;
   double* data = vm->bbq->sp->out;
   for (;;) {
     int count = left;
     if ((err = soundio_outstream_begin_write(outstream, &areas, &count))) {
       fprintf(stderr, "unrecoverable stream error: %s\n", soundio_strerror(err));
       vm->is_running = 0;
       return;
     }
     if (!count)
       break;
     for (int frame = 0; frame < count; frame++) {
 //          for (int channel = 0; channel < instream->layout.channel_count; channel++)
 //              vm->bbq->in[channel] = *(double*)instream->areas[channel].ptr;
       vm_run(vm);
       for (int channel = 0; channel < layout->channel_count; channel++) {
         write_sample(areas[channel].ptr, data[channel]);
         areas[channel].ptr += areas[channel].step;
       }
       vm->bbq->sp->pos++;
     }
     if ((err = soundio_outstream_end_write(outstream))) {
       if (err == SoundIoErrorUnderflow)
         return;
       fprintf(stderr, "unrecoverable stream error: %s\n", soundio_strerror(err));
       vm->is_running = 0;
     }
     left -= count;
     if (left <= 0)
       break;
   }
   soundio_outstream_pause(outstream, 0);
 }
write_sample_float32ne()
static void write_sample_float32ne (char * ptr, double sample) static
Definition at line 45 of file soundio.c.
Referenced by sio_ini().
 {
   float *buf = (float *)ptr;
   *buf = sample;
 }
write_sample_float64ne()
static void write_sample_float64ne (char * ptr, double sample) static
Definition at line 51 of file soundio.c.
Referenced by sio_ini().
 {
   double *buf = (double *)ptr;
   *buf = sample;
 }
write_sample_s16ne()
static void write_sample_s16ne (char * ptr, double sample) static
Definition at line 29 of file soundio.c.
References INT16_MAX, and INT16_MIN.
Referenced by sio_ini().
 {
   int16_t *buf = (int16_t *)ptr;
   double range = (double)INT16_MAX - (double)INT16_MIN;
   double val = sample * range / 2.0;
   *buf = val;
 }
write_sample_s32ne()
static void write_sample_s32ne (char * ptr, double sample) static
Definition at line 37 of file soundio.c.
References INT32_MAX, and INT32_MIN.
Referenced by sio_ini().
 {
   int32_t *buf = (int32_t *)ptr;
   double range = (double)INT32_MAX - (double)INT32_MIN;
   double val = sample * range / 2.0;
   *buf = val;
 }
Variable Documentation
backend
enum SoundIoBackend backend = SoundIoBackendNone static
Definition at line 21 of file soundio.c.
Referenced by sio_ini().
device_id
m_str device_id = NULL static
Definition at line 22 of file soundio.c.
Referenced by sio_ini().
in_device
struct SoundIoDevice* in_device = NULL static
Definition at line 16 of file soundio.c.
Referenced by sio_del(), and sio_ini().
instream
struct SoundIoInStream* instream = NULL static
Definition at line 14 of file soundio.c.
Referenced by sio_del(), sio_ini(), and sio_run().
out_device
struct SoundIoDevice* out_device = NULL static
Definition at line 15 of file soundio.c.
Referenced by sio_del(), and sio_ini().
outstream
struct SoundIoOutStream* outstream = NULL static
Definition at line 13 of file soundio.c.
Referenced by sio_del(), sio_ini(), and sio_run().
raw
m_bool raw = false static
Definition at line 23 of file soundio.c.
Referenced by sio_ini().
read_sample
void(* read_sample) (char *ptr, double *sample) static
Definition at line 84 of file soundio.c.
Referenced by read_callback(), and sio_ini().
soundio
struct SoundIo* soundio = NULL static
Definition at line 12 of file soundio.c.
Referenced by sio_del(), sio_ini(), sio_run(), and sio_wakeup().
write_sample
void(* write_sample) (char *ptr, double sample) static
Definition at line 83 of file soundio.c.
Referenced by sio_ini(), and write_callback().