vec.c – Gwion
Gwion
A strongly timed musical programming language
vec.c
vec.c File Reference
#include <math.h>
#include "defs.h"
#include "vm.h"
#include "type.h"
#include "err_msg.h"
#include "instr.h"
#include "import.h"
Functions
MFUN (vec3_set)
MFUN (vec3_setAll)
MFUN (vec3_magnitude)
MFUN (vec3_normalize)
MFUN (vec3_interp)
MFUN (vec3_float)
MFUN (vec3_dur)
MFUN (vec3_update)
MFUN (vec3_update_slew)
MFUN (vec3_update_set)
MFUN (vec3_update_set_slew)
INSTR (vec3_add)
INSTR (vec3_minus)
INSTR (vec3_xproduct)
INSTR (float_times_vec3)
INSTR (vec3_times_float)
INSTR (vec3_divide_float)
INSTR (vec3_r_assign)
INSTR (vec3_x)
INSTR (vec3_y)
INSTR (vec3_z)
INSTR (vec4_x)
INSTR (vec4_y)
INSTR (vec4_z)
INSTR (vec4_w)
m_bool import_vec3 (Env env)
MFUN (vec4_set)
MFUN (vec4_setAll)
MFUN (vec4_magnitude)
MFUN (vec4_normalize)
INSTR (vec4_add)
INSTR (vec4_minus)
INSTR (vec4_xproduct)
INSTR (float_times_vec4)
INSTR (vec4_times_float)
INSTR (vec4_divide_float)
INSTR (vec4_r_assign)
m_bool import_vec4 (Env env)
Variables
struct Type_ t_vec3 = { "Vec3", SZ_VEC3, NULL, te_vec3}
struct Type_ t_vec4 = { "Vec4", SZ_VEC4, NULL, te_vec4}
Function Documentation
import_vec3()
m_bool import_vec3 (Env env)
Definition at line 299 of file vec.c.
References add_binary_op(), add_global_type(), CHECK_BB, CHECK_OB, dl_func_add_arg(), Env_::global_nspc, import_class_begin(), import_class_end(), import_mfun(), import_mvar(), new_DL_Func(), op_chuck, op_divide, op_minus, op_plus, op_times, Type_::size, and t_float.
Referenced by type_engine_init().
 {
   DL_Func* fun;
   CHECK_BB(add_global_type(env, &t_vec3))
   CHECK_OB(import_class_begin(env, &t_vec3, env->global_nspc, NULL, NULL))
   import_mvar(env, "float", "x",   0, 0, "real part");
   import_mvar(env, "float", "y",   0, 0, "real part");
   import_mvar(env, "float", "z",   0, 0, "real part");
   fun = new_DL_Func("void", "set", (m_uint)vec3_set);
   dl_func_add_arg(fun, "float", "x");
   dl_func_add_arg(fun, "float", "y");
   dl_func_add_arg(fun, "float", "z");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "setAll", (m_uint)vec3_setAll);
   dl_func_add_arg(fun, "float", "x");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("float", "magnitude", (m_uint)vec3_magnitude);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "normalize", (m_uint)vec3_normalize);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("float", "interp", (m_uint)vec3_interp);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("float", "interp", (m_uint)vec3_float);
   dl_func_add_arg(fun, "float", "delta");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("float", "interp", (m_uint)vec3_dur);
   dl_func_add_arg(fun, "dur", "delta");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "update", (m_uint)vec3_update);
   dl_func_add_arg(fun, "float", "goal");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "update", (m_uint)vec3_update_slew);
   dl_func_add_arg(fun, "float", "goal");
   dl_func_add_arg(fun, "float", "slew");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "supdate", (m_uint)vec3_update_set);
   dl_func_add_arg(fun, "float", "goalAndValue");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "supdate", (m_uint)vec3_update_set_slew);
   dl_func_add_arg(fun, "float", "goalAndValue");
   dl_func_add_arg(fun, "float", "slew");
   CHECK_OB(import_mfun(env, fun))
   CHECK_BB(add_binary_op(env, op_plus,   &t_vec3,   &t_vec3, &t_vec3,  vec3_add, 1, 0))
   CHECK_BB(add_binary_op(env, op_minus,  &t_vec3,   &t_vec3, &t_vec3,  vec3_minus, 1, 0))
   CHECK_BB(add_binary_op(env, op_times,  &t_vec3,   &t_vec3, &t_vec3,  vec3_xproduct, 1, 0))
   CHECK_BB(add_binary_op(env, op_times,  &t_vec3,   &t_float, &t_vec3, vec3_times_float, 1, 0))
   CHECK_BB(add_binary_op(env, op_divide, &t_vec3,   &t_float, &t_vec3, vec3_divide_float, 1, 0))
   CHECK_BB(add_binary_op(env, op_times,  &t_float,  &t_vec3, &t_vec3,  float_times_vec3, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck,  &t_vec3,   &t_vec3, &t_vec3,  vec3_r_assign, 1, 0))
   CHECK_BB(import_class_end(env))
   t_vec3.size = SZ_VEC3;
   return 1;
 }
import_vec4()
m_bool import_vec4 (Env env)
Definition at line 516 of file vec.c.
References add_binary_op(), add_global_type(), CHECK_BB, CHECK_OB, dl_func_add_arg(), Env_::global_nspc, import_class_begin(), import_class_end(), import_mfun(), import_mvar(), new_DL_Func(), op_chuck, op_divide, op_minus, op_plus, op_times, Type_::size, and t_float.
Referenced by type_engine_init().
 {
   DL_Func* fun;
   CHECK_BB(add_global_type(env, &t_vec4))
   CHECK_OB(import_class_begin(env, &t_vec4, env->global_nspc, NULL, NULL))
   import_mvar(env, "float", "x",   0, 0, "real part");
   import_mvar(env, "float", "y",   0, 0, "real part");
   import_mvar(env, "float", "z",   0, 0, "real part");
   import_mvar(env, "float", "w",   0, 0, "real part");
   fun = new_DL_Func("void", "set", (m_uint)vec4_set);
   dl_func_add_arg(fun, "float", "x");
   dl_func_add_arg(fun, "float", "y");
   dl_func_add_arg(fun, "float", "z");
   dl_func_add_arg(fun, "float", "w");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "setAll", (m_uint)vec4_setAll);
   dl_func_add_arg(fun, "float", "x");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("float", "magnitude", (m_uint)vec4_magnitude);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "normalize", (m_uint)vec4_normalize);
   CHECK_OB(import_mfun(env, fun))
   CHECK_BB(add_binary_op(env, op_plus,   &t_vec4,   &t_vec4,  &t_vec4,  vec4_add, 1, 0))
   CHECK_BB(add_binary_op(env, op_minus,  &t_vec4,   &t_vec4,  &t_vec4,  vec4_minus, 1, 0))
   CHECK_BB(add_binary_op(env, op_times,  &t_vec4,   &t_vec4,  &t_vec4,  vec4_xproduct, 1, 0))
   CHECK_BB(add_binary_op(env, op_times,  &t_vec4,   &t_float, &t_vec4,  vec4_times_float, 1, 0))
   CHECK_BB(add_binary_op(env, op_divide, &t_vec4,   &t_float, &t_vec4,  vec4_divide_float, 1, 0))
   CHECK_BB(add_binary_op(env, op_times,  &t_float,  &t_vec4,  &t_vec4,  float_times_vec4, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck,   &t_vec4,   &t_vec4,  &t_vec4,  vec4_r_assign, 1, 0))
   CHECK_BB(import_class_end(env))
   t_vec4.size = SZ_VEC4;
   return 1;
 }
INSTR() [1/21]
INSTR (vec3_add)
Definition at line 92 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   VEC3_T r, * t = (VEC3_T*)shred->reg;
   POP_REG(shred, SZ_VEC3 * 2);
   r.x = t->x + (t + 1)->x;
   r.y = t->y + (t + 1)->y;
   r.z = t->z + (t + 1)->z;
   *(m_float*)shred->reg = r.x;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.y;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.z;
   PUSH_REG(shred,  SZ_FLOAT);
 }
INSTR() [2/21]
INSTR (vec3_minus)
Definition at line 107 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   VEC3_T r, * t = (VEC3_T*)shred->reg;
   POP_REG(shred, SZ_VEC3 * 2);
   r.x = t->x - (t + 1)->x;
   r.y = t->y - (t + 1)->y;
   r.z = t->z - (t + 1)->z;
   *(m_float*)shred->reg = r.x;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.y;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.z;
   PUSH_REG(shred,  SZ_FLOAT);
 }
INSTR() [3/21]
INSTR (vec3_xproduct)
Definition at line 122 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   VEC3_T r, * t = (VEC3_T*)shred->reg;
   POP_REG(shred, SZ_VEC3 * 2);
   r.x = t->x * (t + 1)->x;
   r.y = t->y * (t + 1)->y;
   r.z = t->z * (t + 1)->z;
   *(m_float*)shred->reg = r.x;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.y;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.z;
   PUSH_REG(shred,  SZ_FLOAT);
 }
INSTR() [4/21]
INSTR (float_times_vec3)
Definition at line 137 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   POP_REG(shred, SZ_FLOAT + SZ_VEC3);
   m_float f = *(m_float*)(shred->reg);
   VEC3_T r = *(VEC3_T*)(shred->reg + SZ_FLOAT);
   r.x *= f;
   r.y *= f;
   r.z *= f;
   *(m_float*)shred->reg = r.x;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.y;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.z;
   PUSH_REG(shred,  SZ_FLOAT);
 }
INSTR() [5/21]
INSTR (vec3_times_float)
Definition at line 152 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   POP_REG(shred, SZ_FLOAT + SZ_VEC3);
   VEC3_T r = *(VEC3_T*)(shred->reg);
   m_float f = *(m_float*)(shred->reg + SZ_VEC3);
   r.x *= f;
   r.y *= f;
   r.z *= f;
   *(m_float*)shred->reg = r.x;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.y;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.z;
   PUSH_REG(shred,  SZ_FLOAT);
 }
INSTR() [6/21]
INSTR (vec3_divide_float)
Definition at line 168 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   POP_REG(shred, SZ_FLOAT + SZ_VEC3);
   VEC3_T r = *(VEC3_T*)(shred->reg);
   m_float f = *(m_float*)(shred->reg + SZ_VEC3);
   r.x /= f;
   r.y /= f;
   r.z /= f;
   *(m_float*)shred->reg = r.x;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.y;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.z;
   PUSH_REG(shred,  SZ_FLOAT);
 }
INSTR() [7/21]
INSTR (vec3_r_assign)
Definition at line 184 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   POP_REG(shred, SZ_VEC3 + SZ_INT);
   VEC3_T r = *(VEC3_T*)(shred->reg + SZ_VEC3);
   r.x = *(m_float*)(shred->reg);
   r.y = *(m_float*)(shred->reg + SZ_FLOAT);
   r.z = *(m_float*)(shred->reg + SZ_FLOAT * 2);
   *(VEC3_T*)shred->reg = r;
   PUSH_REG(shred, SZ_VEC3);
 }
INSTR() [8/21]
INSTR (vec3_x)
Definition at line 195 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   if(instr->m_val) {
     POP_REG(shred, SZ_INT);
     VEC3_T* v = *(VEC3_T**)(shred->reg);
     *(m_float**)shred->reg = &v->x;
     PUSH_REG(shred,  SZ_INT);
   } else {
     POP_REG(shred, SZ_INT);
     VEC3_T* v = *(VEC3_T**)(shred->reg);
     *(m_float*)shred->reg = v->x;
     PUSH_REG(shred,  SZ_INT);
   }
 }
INSTR() [9/21]
INSTR (vec3_y)
Definition at line 210 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   if(instr->m_val) {
     POP_REG(shred, SZ_INT);
     VEC3_T* v = *(VEC3_T**)(shred->reg);
     *(m_float**)shred->reg = &v->y;
     PUSH_REG(shred,  SZ_INT);
   } else {
     POP_REG(shred, SZ_INT);
     VEC3_T* v = *(VEC3_T**)(shred->reg);
     *(m_float*)shred->reg = v->y;
     PUSH_REG(shred,  SZ_INT);
   }
 }
INSTR() [10/21]
INSTR (vec3_z)
Definition at line 225 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   if(instr->m_val) {
     POP_REG(shred, SZ_INT);
     VEC3_T* v = *(VEC3_T**)(shred->reg);
     *(m_float**)shred->reg = &v->y;
     PUSH_REG(shred,  SZ_INT);
   } else {
     POP_REG(shred, SZ_INT);
     VEC3_T* v = *(VEC3_T**)(shred->reg);
     *(m_float*)shred->reg = v->y;
     PUSH_REG(shred,  SZ_INT);
   }
 }
INSTR() [11/21]
INSTR (vec4_x)
Definition at line 240 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   if(instr->m_val) {
     POP_REG(shred, SZ_INT);
     VEC4_T* v = *(VEC4_T**)(shred->reg);
     *(m_float**)shred->reg = &v->x;
     PUSH_REG(shred,  SZ_INT);
   } else {
     POP_REG(shred, SZ_INT);
     VEC4_T* v = *(VEC4_T**)(shred->reg);
     *(m_float*)shred->reg = v->x;
     PUSH_REG(shred,  SZ_FLOAT);
   }
 }
INSTR() [12/21]
INSTR (vec4_y)
Definition at line 255 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   if(instr->m_val) {
     POP_REG(shred, SZ_INT);
     VEC4_T* v = *(VEC4_T**)(shred->reg);
     *(m_float**)shred->reg = &v->y;
     PUSH_REG(shred,  SZ_INT);
   } else {
     POP_REG(shred, SZ_INT);
     VEC4_T* v = *(VEC4_T**)(shred->reg);
     *(m_float*)shred->reg = v->y;
     PUSH_REG(shred,  SZ_FLOAT);
   }
 }
INSTR() [13/21]
INSTR (vec4_z)
Definition at line 270 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   if(instr->m_val) {
     POP_REG(shred, SZ_INT);
     VEC4_T* v = *(VEC4_T**)(shred->reg);
     *(m_float**)shred->reg = &v->z;
     PUSH_REG(shred,  SZ_INT);
   } else {
     POP_REG(shred, SZ_INT);
     VEC4_T* v = *(VEC4_T**)(shred->reg);
     *(m_float*)shred->reg = v->z;
     PUSH_REG(shred,  SZ_FLOAT);
   }
 }
INSTR() [14/21]
INSTR (vec4_w)
Definition at line 285 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   if(instr->m_val) {
     POP_REG(shred, SZ_INT);
     VEC4_T* v = *(VEC4_T**)(shred->reg);
     *(m_float**)shred->reg = &v->z;
     PUSH_REG(shred,  SZ_INT);
   } else {
     POP_REG(shred, SZ_INT);
     VEC4_T* v = *(VEC4_T**)(shred->reg);
     *(m_float*)shred->reg = v->z;
     PUSH_REG(shred,  SZ_FLOAT);
   }
 }
INSTR() [15/21]
INSTR (vec4_add)
Definition at line 394 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   VEC4_T r, * t = (VEC4_T*)shred->reg;
   POP_REG(shred, SZ_VEC4 * 2);
   r.x = t->x + (t + 1)->x;
   r.y = t->y + (t + 1)->y;
   r.z = t->z + (t + 1)->z;
   r.w = t->w + (t + 1)->w;
   *(m_float*)shred->reg = r.x;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.y;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.z;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.w;
   PUSH_REG(shred,  SZ_FLOAT);
 }
INSTR() [16/21]
INSTR (vec4_minus)
Definition at line 412 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   VEC4_T r, * t = (VEC4_T*)shred->reg;
   POP_REG(shred, SZ_VEC4 * 2);
   r.x = t->x - (t + 1)->x;
   r.y = t->y - (t + 1)->y;
   r.z = t->z - (t + 1)->z;
   r.w = t->w - (t + 1)->w;
   *(m_float*)shred->reg = r.x;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.y;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.z;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.w;
   PUSH_REG(shred,  SZ_FLOAT);
 }
INSTR() [17/21]
INSTR (vec4_xproduct)
Definition at line 430 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   VEC4_T r, * t = (VEC4_T*)shred->reg;
   POP_REG(shred, SZ_VEC4 * 2);
   r.x = t->x * (t + 1)->x;
   r.y = t->y * (t + 1)->y;
   r.z = t->z * (t + 1)->z;
   r.w = t->w * (t + 1)->w;
   *(m_float*)shred->reg = r.x;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.y;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.z;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.w;
   PUSH_REG(shred,  SZ_FLOAT);
 }
INSTR() [18/21]
INSTR (float_times_vec4)
Definition at line 448 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   POP_REG(shred, SZ_FLOAT + SZ_VEC4);
   m_float f = *(m_float*)(shred->reg);
   VEC4_T r = *(VEC4_T*)(shred->reg + SZ_FLOAT);
   r.x *= f;
   r.y *= f;
   r.z *= f;
   *(m_float*)shred->reg = r.x;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.y;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.z;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.w;
   PUSH_REG(shred,  SZ_FLOAT);
 }
INSTR() [19/21]
INSTR (vec4_times_float)
Definition at line 466 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   POP_REG(shred, SZ_FLOAT + SZ_VEC4);
   VEC4_T r = *(VEC4_T*)(shred->reg);
   m_float f = *(m_float*)(shred->reg + SZ_VEC4);
   r.x *= f;
   r.y *= f;
   r.z *= f;
   r.w *= f;
   *(m_float*)shred->reg = r.x;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.y;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.z;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.w;
   PUSH_REG(shred,  SZ_FLOAT);
 }
INSTR() [20/21]
INSTR (vec4_divide_float)
Definition at line 485 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   POP_REG(shred, SZ_FLOAT + SZ_VEC4);
   VEC4_T r = *(VEC4_T*)(shred->reg);
   m_float f = *(m_float*)(shred->reg + SZ_VEC4);
   r.x /= f;
   r.y /= f;
   r.z /= f;
   r.w /= f;
   *(m_float*)shred->reg = r.x;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.y;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.z;
   PUSH_REG(shred,  SZ_FLOAT);
   *(m_float*)shred->reg = r.w;
   PUSH_REG(shred,  SZ_FLOAT);
 }
INSTR() [21/21]
INSTR (vec4_r_assign)
Definition at line 504 of file vec.c.
References POP_REG, and PUSH_REG.
 {
   POP_REG(shred, SZ_VEC4 + SZ_INT);
   VEC4_T r = *(VEC4_T*)(shred->reg + SZ_VEC4);
   r.x = *(m_float*)(shred->reg);
   r.y = *(m_float*)(shred->reg + SZ_FLOAT);
   r.z = *(m_float*)(shred->reg + SZ_FLOAT * 2);
   r.w = *(m_float*)(shred->reg + SZ_FLOAT * 3);
   *(VEC4_T*)shred->reg = r;
   PUSH_REG(shred, SZ_VEC4);
 }
MFUN() [1/15]
MFUN (vec3_set)
Definition at line 10 of file vec.c.
 {
   VEC3_T* v =  &*(VEC3_T*)(shred->mem);
   v->x = *(m_float*)(shred->mem + SZ_INT);
   v->y = *(m_float*)(shred->mem + SZ_INT + SZ_FLOAT);
   v->z = *(m_float*)(shred->mem + SZ_INT + SZ_FLOAT * 2);
 }
MFUN() [2/15]
MFUN (vec3_setAll)
Definition at line 18 of file vec.c.
 {
   VEC3_T* v =  &**(VEC3_T**)(shred->mem);
   v->x = *(m_float*)(shred->mem + SZ_INT);
   v->y = *(m_float*)(shred->mem + SZ_INT);
   v->z = *(m_float*)(shred->mem + SZ_INT);
 }
MFUN() [3/15]
MFUN (vec3_magnitude)
Definition at line 26 of file vec.c.
References RETURN.
 {
   VEC3_T* v =  &**(VEC3_T**)(shred->mem);
   RETURN->d.v_float = sqrt(v->x * v->x + v->y * v->y + v->z * v->z);
 }
MFUN() [4/15]
MFUN (vec3_normalize)
Definition at line 32 of file vec.c.
 {
   VEC3_T* v =  &**(VEC3_T**)(shred->mem);
   m_float mag = sqrt( v->x * v->x + v->y * v->y + v->z * v->z);
   if(mag  > 0) {
     v->x /= mag;
     v->y /= mag;
     v->z /= mag;
   }
 }
MFUN() [5/15]
MFUN (vec3_interp)
Definition at line 43 of file vec.c.
References RETURN.
 {
   VEC3_T* v =  &**(VEC3_T**)(shred->mem);
   v->x = (v->y - v->x) * v->z + v->x;
   RETURN->d.v_float = v->x;
 }
MFUN() [6/15]
MFUN (vec3_float)
Definition at line 50 of file vec.c.
References RETURN.
 {
   VEC3_T* v =  &**(VEC3_T**)(shred->mem);
   v->x = (v->y - v->x) * v->z * (*(m_float*)(shred->mem + SZ_INT)) + v->x;
   RETURN->d.v_float = v->x;
 }
MFUN() [7/15]
MFUN (vec3_dur)
Definition at line 57 of file vec.c.
References RETURN.
 {
   VEC3_T* v =  &**(VEC3_T**)(shred->mem);
   v->x = (v->y - v->x) * v->z * (*(m_float*)(shred->mem + SZ_INT) / shred->vm_ref->bbq->sp->sr) + v->x;
   RETURN->d.v_float = v->x;
 }
MFUN() [8/15]
MFUN (vec3_update)
Definition at line 64 of file vec.c.
 {
   VEC3_T* v =  &**(VEC3_T**)(shred->mem);
   v->y = *(m_float*)(shred->mem + SZ_INT);
 }
MFUN() [9/15]
MFUN (vec3_update_slew)
Definition at line 70 of file vec.c.
 {
   VEC3_T* v =  &**(VEC3_T**)(shred->mem);
   v->y = *(m_float*)(shred->mem + SZ_INT);
   v->z = *(m_float*)(shred->mem + SZ_INT + SZ_FLOAT);
 }
MFUN() [10/15]
MFUN (vec3_update_set)
Definition at line 77 of file vec.c.
 {
   VEC3_T* v =  &**(VEC3_T**)(shred->mem);
   v->x = *(m_float*)(shred->mem + SZ_INT);
   v->y = *(m_float*)(shred->mem + SZ_INT);
 }
MFUN() [11/15]
MFUN (vec3_update_set_slew)
Definition at line 84 of file vec.c.
 {
   VEC3_T* v =  &**(VEC3_T**)(shred->mem);
   v->x = *(m_float*)(shred->mem + SZ_INT);
   v->y = *(m_float*)(shred->mem + SZ_INT);
   v->z = *(m_float*)(shred->mem + SZ_INT + SZ_FLOAT);
 }
MFUN() [12/15]
MFUN (vec4_set)
Definition at line 358 of file vec.c.
 {
   VEC4_T* v =  &**(VEC4_T**)(shred->mem);
   v->x = *(m_float*)(shred->mem + SZ_INT);
   v->y = *(m_float*)(shred->mem + SZ_INT + SZ_FLOAT);
   v->z = *(m_float*)(shred->mem + SZ_INT + SZ_FLOAT * 2);
   v->w = *(m_float*)(shred->mem + SZ_INT + SZ_FLOAT * 3);
 }
MFUN() [13/15]
MFUN (vec4_setAll)
Definition at line 367 of file vec.c.
 {
   VEC4_T* v =  &**(VEC4_T**)(shred->mem);
   v->x = *(m_float*)(shred->mem + SZ_INT);
   v->y = *(m_float*)(shred->mem + SZ_INT);
   v->z = *(m_float*)(shred->mem + SZ_INT);
   v->w = *(m_float*)(shred->mem + SZ_INT);
 }
MFUN() [14/15]
MFUN (vec4_magnitude)
Definition at line 376 of file vec.c.
References RETURN.
 {
   VEC4_T* v =  &**(VEC4_T**)(shred->mem);
   RETURN->d.v_float = sqrt( v->x * v->x + v->y * v->y + v->z * v->z + v->w * v->w);
 }
MFUN() [15/15]
MFUN (vec4_normalize)
Definition at line 382 of file vec.c.
 {
   VEC4_T* v =  &**(VEC4_T**)(shred->mem);
   m_float mag = sqrt( v->x * v->x + v->y * v->y + v->z * v->z + v->w * v->w);
   if(mag  > 0) {
     v->x /= mag;
     v->y /= mag;
     v->z /= mag;
     v->w /= mag;
   }
 }
Variable Documentation
t_vec3
struct Type_ t_vec3 = { "Vec3", SZ_VEC3, NULL, te_vec3}
Definition at line 9 of file vec.c.
Referenced by check_Vec(), emit_Decl_Expression(), emit_Dot_Member(), import_string(), INSTR(), and kindof().
t_vec4
struct Type_ t_vec4 = { "Vec4", SZ_VEC4, NULL, te_vec4}
Definition at line 356 of file vec.c.
Referenced by check_Vec(), emit_Decl_Expression(), emit_Dot_Member(), import_string(), INSTR(), and kindof().