['i', ['i', ['../global_nspc.html#Class_Test_inner_inner_class_c_i', 1, ' [variable] in <b>c</b> <em></em> '] ]],
['c', ['c', ['../_home_djay_src_minimal_test_doc_ssp.html#Class_Test_inner_inner_class_c', 1, ' [type] in <b>inner_class</b> <em></em> '] ]],
['f', ['f', ['../global_nspc.html#Class_Test_inner_inner_class_f', 1, ' [variable] in <b>inner_class</b> <em></em> '] ]],
['inner_class', ['inner_class', ['../_home_djay_src_minimal_test_doc_ssp.html#Class_Test_inner_inner_class', 1, ' [type] in <b>inner</b> <em></em> '] ]],
['i', ['i', ['../global_nspc.html#Class_Test_inner_i', 1, ' [variable] in <b>inner</b> <em></em> '] ]],
['s_func_test', ['s_func_test', ['../_home_djay_src_minimal_test_doc_ssp.html#Class_Test_inner_s_func_test_0_inner', 1, ' [function] in <b>inner</b> <em> class doc</em> '] ]],
['inner', ['inner', ['../_home_djay_src_minimal_test_doc_ssp.html#Class_Test_inner', 1, ' [type] in <b>Class_Test</b> <em></em> '] ]],
['o', ['o', ['../global_nspc.html#Class_Test_o', 1, ' [variable] in <b>Class_Test</b> <em></em> '] ]],
['f', ['f', ['../global_nspc.html#Class_Test_f', 1, ' [variable] in <b>Class_Test</b> <em> doc for float f</em> '] ]],
['i', ['i', ['../global_nspc.html#Class_Test_i', 1, ' [variable] in <b>Class_Test</b> <em></em> '] ]],
['s_i', ['s_i', ['../global_nspc.html#Class_Test_s_i', 1, ' [variable] in <b>Class_Test</b> <em> static int doc</em> '] ]],
['func_test', ['func_test', ['../_home_djay_src_minimal_test_doc_ssp.html#Class_Test_func_test_0_Class_Test', 1, ' [function] in <b>Class_Test</b> <em></em> '] ]],
['i', ['i', ['../_home_djay_src_minimal_test_doc_ssp.html#Class_Test_func_test_1_Class_Test_i', 1, ' [argument] in <b>Class_Test</b> <em></em> '] ]],
['func_test', ['func_test', ['../_home_djay_src_minimal_test_doc_ssp.html#Class_Test_func_test_1_Class_Test', 1, ' [function] in <b>Class_Test</b> <em></em> '] ]],
['s_func_test', ['s_func_test', ['../_home_djay_src_minimal_test_doc_ssp.html#Class_Test_s_func_test_0_Class_Test', 1, ' [function] in <b>Class_Test</b> <em></em> '] ]],
['i', ['i', ['../_home_djay_src_minimal_test_doc_ssp.html#Class_Test_s_func_test_1_Class_Test_i', 1, ' [argument] in <b>Class_Test</b> <em></em> '] ]],
['s_func_test', ['s_func_test', ['../_home_djay_src_minimal_test_doc_ssp.html#Class_Test_s_func_test_1_Class_Test', 1, ' [function] in <b>Class_Test</b> <em> arg</em> '] ]],
['Class_Test', ['Class_Test', ['../_home_djay_src_minimal_test_doc_ssp.html#Class_Test', 1, ' [type] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em></em> '] ]],
['i', ['i', ['../global_nspc.html#i', 1, ' [variable] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em> this is  a multiline doc for global int ;-)</em> '] ]],
['h', ['h', ['../global_nspc.html#h', 1, ' [variable] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em></em> '] ]],
['ineer', ['ineer', ['../_home_djay_src_minimal_test_doc_ssp.html#ineer', 1, ' [variable] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em></em> '] ]],
['func_test', ['func_test', ['../_home_djay_src_minimal_test_doc_ssp.html#func_test_0__home_djay_src_minimal_test_doc_ssp', 1, ' [function] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em> global func doc</em> '] ]],
['i', ['i', ['../_home_djay_src_minimal_test_doc_ssp.html#func_test_1__home_djay_src_minimal_test_doc_ssp_i', 1, ' [argument] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em></em> '] ]],
['func_test', ['func_test', ['../_home_djay_src_minimal_test_doc_ssp.html#func_test_1__home_djay_src_minimal_test_doc_ssp', 1, ' [function] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em> global func doc override</em> '] ]],
['i', ['i', ['../_home_djay_src_minimal_test_doc_ssp.html#func_test_2__home_djay_src_minimal_test_doc_ssp_i', 1, ' [argument] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em></em> '] ]],
['j', ['j', ['../_home_djay_src_minimal_test_doc_ssp.html#func_test_2__home_djay_src_minimal_test_doc_ssp_j', 1, ' [argument] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em></em> '] ]],
['k', ['k', ['../_home_djay_src_minimal_test_doc_ssp.html#func_test_2__home_djay_src_minimal_test_doc_ssp_k', 1, ' [argument] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em></em> '] ]],
['func_test', ['func_test', ['../_home_djay_src_minimal_test_doc_ssp.html#func_test_2__home_djay_src_minimal_test_doc_ssp', 1, ' [function] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em> test 3</em> '] ]],
['i', ['i', ['../_home_djay_src_minimal_test_doc_ssp.html#func_test_3__home_djay_src_minimal_test_doc_ssp_i', 1, ' [argument] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em></em> '] ]],
['j', ['j', ['../_home_djay_src_minimal_test_doc_ssp.html#func_test_3__home_djay_src_minimal_test_doc_ssp_j', 1, ' [argument] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em></em> '] ]],
['k', ['k', ['../_home_djay_src_minimal_test_doc_ssp.html#func_test_3__home_djay_src_minimal_test_doc_ssp_k', 1, ' [argument] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em></em> '] ]],
['func_test', ['func_test', ['../_home_djay_src_minimal_test_doc_ssp.html#func_test_3__home_djay_src_minimal_test_doc_ssp', 1, ' [function] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em></em> '] ]],
['f', ['f', ['../_home_djay_src_minimal_test_doc_ssp.html#func_array_0__home_djay_src_minimal_test_doc_ssp_f', 1, ' [argument] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em></em> '] ]],
['func_array', ['func_array', ['../_home_djay_src_minimal_test_doc_ssp.html#func_array_0__home_djay_src_minimal_test_doc_ssp', 1, ' [function] in <b>/home/djay/src/minimal/test/doc.ssp</b> <em></em> '] ]],
