absyn_8h/ – Gwion
Gwion
A strongly timed musical programming language
absyn_8h/
absyn.h File Reference
#include "type.h"
#include "map.h"
Data Structures
struct MyArg
struct Dot_Member
struct Array_Sub_
struct Array_Expression
struct Array
struct Var_Decl_
struct Var_Decl_List_
struct Type_Decl
struct Decl_Expression
struct Postfix_Expression
struct Cast_Expression
struct Complex
struct Polar
struct Vec_
struct Primary_Expression
struct Func_Call
struct Binary_Expression
struct If_Expression
struct Exp_Dur
struct Func_Ptr
struct Decl_List_
struct Union
struct Stmt
struct Unary_Expression
struct Arg_List_
struct Expression_
struct Stmt_Code_
struct Stmt_Return_
struct Stmt_Continue_
struct Stmt_Break_
struct Stmt_While_
struct Stmt_Until_
struct Stmt_For_
struct Stmt_Loop_
struct Stmt_If_
struct Stmt_Goto_Label_
struct Stmt_Switch_
struct Stmt_Case_
struct Stmt_Enum_
struct Stmt_List_
struct Class_Def_
struct Func_Def_
struct Section
struct Class_Ext_
struct Class_Body_
struct ID_List_
struct Type_List_
struct Ast_
Typedefs
typedef struct Expression_ * Expression
typedef struct Var_Decl_ * Var_Decl
typedef struct Var_Decl_List_ * Var_Decl_List
typedef struct Arg_List_ * Arg_List
typedef struct Vec_ * Vec
typedef struct Stmt_List_ * Stmt_List
typedef struct Stmt_Code_ * Stmt_Code
typedef struct Stmt_Return_ * Stmt_Return
typedef struct Stmt_Continue_ * Stmt_Continue
typedef struct Stmt_Break_ * Stmt_Break
typedef struct Stmt_While_ * Stmt_While
typedef struct Stmt_Until_ * Stmt_Until
typedef struct Stmt_For_ * Stmt_For
typedef struct Stmt_Loop_ * Stmt_Loop
typedef struct Stmt_If_ * Stmt_If
typedef struct Stmt_Switch_ * Stmt_Switch
typedef struct Stmt_Case_ * Stmt_Case
typedef struct Stmt_Goto_Label_ * Stmt_Goto_Label
typedef struct Stmt_Enum_ * Stmt_Enum
typedef struct Decl_List_ * Decl_List
typedef struct Class_Ext_ * Class_Ext
typedef struct Class_Body_ * Class_Body
Enumerations
enum ae_Keyword {
ae_key_this, ae_key_me, ae_key_func, ae_key_public,
ae_key_protected, ae_key_private, ae_key_static, ae_key_instance,
ae_key_abstract, ae_key_variadic
}
enum ae_Exp_Primary_Type {
ae_primary_var, ae_primary_num, ae_primary_float, ae_primary_str,
ae_primary_array, ae_primary_hack, ae_primary_complex, ae_primary_polar,
ae_primary_vec, ae_primary_char, ae_primary_nil
}
enum Expression_type {
Decl_Expression_type, Binary_Expression_type, Unary_Expression_type, Primary_Expression_type,
Cast_Expression_type, Postfix_Expression_type, Func_Call_type, Array_Expression_type,
If_Expression_type, Dot_Member_type, Dur_Expression_type
}
enum ae_Exp_Meta { ae_meta_var, ae_meta_value }
enum ae_Stmt_Type {
ae_stmt_exp, ae_stmt_while, ae_stmt_until, ae_stmt_for,
ae_stmt_loop, ae_stmt_if, ae_stmt_code, ae_stmt_switch,
ae_stmt_break, ae_stmt_continue, ae_stmt_return, ae_stmt_case,
ae_stmt_gotolabel, ae_stmt_enum, ae_stmt_funcptr, ae_stmt_union
}
enum ae_Section_Type { ae_section_stmt, ae_section_func, ae_section_class }
enum ae_func_type { ae_func_builtin, ae_func_user }
Functions
Array_Sub new_array_sub (Expression exp, int pos)
Array_Sub prepend_array_sub (Array_Sub array, Expression exp, int pos)
void free_Array_Sub (Array_Sub a)
Expression new_Array (Expression base, Array_Sub indices, int pos)
Var_Decl new_Var_Decl (m_str name, Array_Sub array, int pos)
Var_Decl_List new_Var_Decl_List (Var_Decl decl, Var_Decl_List list, int pos)
Type_Decl * new_Type_Decl (ID_List name, int ref, int pos)
Type_Decl * new_Type_Decl_from_dot (Dot_Member *dot, int ref, int pos)
void free_Type_Decl (Type_Decl *a)
Expression new_Decl_Expression (Type_Decl *type, Var_Decl_List list, m_bool is_static, int pos)
Expression new_Binary_Expression (Expression lhs, Operator op, Expression rhs, int pos)
Type_Decl * add_type_decl_array (Type_Decl *a, Array_Sub array, int pos)
Complex * new_complex (Expression re, int pos)
Expression new_exp_from_complex (Complex *exp, int pos)
Expression new_exp_from_polar (Polar *exp, int pos)
Expression new_exp_from_char (c_str chr, int pos)
Vec new_Vec (Expression e, int pos)
Expression new_exp_from_vec (Vec a, int pos)
Expression new_Primary_Expression_from_int (long i, int pos)
Expression new_Primary_Expression_from_float (m_float num, int pos)
Expression new_Primary_Expression_from_ID (m_str s, int pos)
Expression new_Primary_Expression_from_string (m_str s, int pos)
Expression new_exp_from_array_lit (Array_Sub exp_list, int pos)
Polar * new_polar (Expression mod, int pos)
Expression new_Postfix_Expression (Expression exp, Operator op, int pos)
Expression prepend_Expression (Expression exp, Expression next, int pos)
Expression new_Hack_Expression (Expression exp, int pos)
Expression new_Func_Call (Expression base, Expression args, int pos)
Expression new_Primary_Expression_from_nil (int pos)
Expression new_Cast_Expression (Type_Decl *type, Expression exp, int pos)
Expression new_If_Expression (Expression cond, Expression if_exp, Expression else_exp, int pos)
Expression new_Exp_Dur (Expression base, Expression unit, int pos)
Expression new_exp_from_member_dot (Expression base, m_str xid, int pos)
Decl_List new_Decl_List (Decl_Expression *d, Decl_List l)
Union * new_Union (Decl_List l)
Expression new_exp_from_unary (Operator oper, Expression exp, int pos)
Expression new_exp_from_unary2 (Operator oper, Type_Decl *type, Array_Sub array, int pos)
Expression new_exp_from_unary3 (Operator oper, Stmt *code, int pos)
Arg_List new_Arg_List (Type_Decl *type_decl, Var_Decl var_decl, Arg_List arg_list, int pos)
void free_Arg_List (Arg_List a)
Stmt * new_Func_Ptr_Stmt (ae_Keyword key, m_str type, Type_Decl *decl, Arg_List args, int pos)
Stmt * new_Stmt_from_Expression (Expression exp, int pos)
Stmt * new_stmt_from_code (Stmt_List stmt_list, int pos)
Stmt * new_stmt_from_while (Expression cond, Stmt *body, m_bool is_do, int pos)
Stmt * new_stmt_from_return (Expression exp, int pos)
Stmt * new_stmt_from_break (int pos)
Stmt * new_stmt_from_continue (int pos)
Stmt * new_stmt_from_if (Expression cond, Stmt *if_body, Stmt *else_body, int pos)
Stmt * new_stmt_from_until (Expression cond, Stmt *body, m_bool is_do, int pos)
Stmt * new_stmt_from_for (Stmt *c1, Stmt *c2, Expression c3, Stmt *body, int pos)
Stmt * new_stmt_from_loop (Expression cond, Stmt *body, int pos)
Stmt * new_stmt_from_gotolabel (m_str xid, m_bool is_label, int pos)
Stmt * new_stmt_from_case (Expression exp, int pos)
Stmt * new_stmt_from_enum (ID_List list, m_str type, int pos)
Stmt * new_stmt_from_switch (Expression val, Stmt *stmt, int pos)
Stmt * new_stmt_from_Union (Union *u, int pos)
Stmt_List new_Stmt_List (Stmt *stmt, Stmt_List next, int pos)
Func_Def new_Func_Def (ae_Keyword func_decl, ae_Keyword static_decl, Type_Decl *type_decl, m_str name, Arg_List arg_list, Stmt *code, int pos)
void free_Func_Def (Func_Def def)
m_bool scan1_Func_Def (Env env, Func_Def f)
m_bool scan2_Func_Def (Env env, Func_Def f)
m_bool check_Func_Def (Env env, Func_Def f)
Section * new_section_Stmt_List (Stmt_List list, int pos)
Section * new_section_Func_Def (Func_Def func_def, int pos)
Type_List new_type_list (ID_List list, Type_List next, int pos)
void free_Type_List (Type_List a)
Class_Def new_class_def (ae_Keyword class_decl, ID_List name, Class_Ext ext, Class_Body body, int pos)
Class_Def new_iface_def (ae_Keyword class_decl, ID_List name, Class_Ext ext, Class_Body body, int pos)
Class_Body new_class_body (Section *section, int pos)
Class_Body prepend_class_body (Section *section, Class_Body body, int pos)
Class_Ext new_class_ext (ID_List extend_id, ID_List impl_list, int pos)
ID_List new_id_list (const m_str xid, int pos)
ID_List prepend_id_list (const m_str xid, ID_List list, int pos)
void free_ID_List (ID_List a)
Section * new_section_Class_Def (Class_Def class_def, int pos)
Ast new_Ast (Section *section, Ast next, int pos)
Ast parse (m_str)
void free_Ast ()
Variables
Map scan_map
Typedef Documentation
Arg_List
typedef struct Arg_List_* Arg_List
Definition at line 11 of file absyn.h.
Class_Body
typedef struct Class_Body_* Class_Body
Definition at line 477 of file absyn.h.
Class_Ext
typedef struct Class_Ext_* Class_Ext
Definition at line 476 of file absyn.h.
Decl_List
typedef struct Decl_List_* Decl_List
Definition at line 271 of file absyn.h.
Expression
typedef struct Expression_* Expression
Definition at line 8 of file absyn.h.
Stmt_Break
typedef struct Stmt_Break_* Stmt_Break
Definition at line 241 of file absyn.h.
Stmt_Case
typedef struct Stmt_Case_* Stmt_Case
Definition at line 248 of file absyn.h.
Stmt_Code
typedef struct Stmt_Code_* Stmt_Code
Definition at line 238 of file absyn.h.
Stmt_Continue
typedef struct Stmt_Continue_* Stmt_Continue
Definition at line 240 of file absyn.h.
Stmt_Enum
typedef struct Stmt_Enum_* Stmt_Enum
Definition at line 250 of file absyn.h.
Stmt_For
typedef struct Stmt_For_* Stmt_For
Definition at line 244 of file absyn.h.
Stmt_Goto_Label
typedef struct Stmt_Goto_Label_* Stmt_Goto_Label
Definition at line 249 of file absyn.h.
Stmt_If
typedef struct Stmt_If_* Stmt_If
Definition at line 246 of file absyn.h.
Stmt_List
typedef struct Stmt_List_* Stmt_List
Definition at line 237 of file absyn.h.
Stmt_Loop
typedef struct Stmt_Loop_* Stmt_Loop
Definition at line 245 of file absyn.h.
Stmt_Return
typedef struct Stmt_Return_* Stmt_Return
Definition at line 239 of file absyn.h.
Stmt_Switch
typedef struct Stmt_Switch_* Stmt_Switch
Definition at line 247 of file absyn.h.
Stmt_Until
typedef struct Stmt_Until_* Stmt_Until
Definition at line 243 of file absyn.h.
Stmt_While
typedef struct Stmt_While_* Stmt_While
Definition at line 242 of file absyn.h.
Var_Decl
typedef struct Var_Decl_* Var_Decl
Definition at line 9 of file absyn.h.
Var_Decl_List
typedef struct Var_Decl_List_* Var_Decl_List
Definition at line 10 of file absyn.h.
Vec
typedef struct Vec_* Vec
Definition at line 145 of file absyn.h.
Enumeration Type Documentation
ae_Exp_Meta
enum ae_Exp_Meta
Enumerator
ae_meta_var
ae_meta_value
Definition at line 235 of file absyn.h.
 { ae_meta_var, ae_meta_value } ae_Exp_Meta;
ae_Exp_Primary_Type
enum ae_Exp_Primary_Type
Enumerator
ae_primary_var
ae_primary_num
ae_primary_float
ae_primary_str
ae_primary_array
ae_primary_hack
ae_primary_complex
ae_primary_polar
ae_primary_vec
ae_primary_char
ae_primary_nil
Definition at line 154 of file absyn.h.
              { ae_primary_var, ae_primary_num, ae_primary_float,
                ae_primary_str, ae_primary_array,
                ae_primary_hack, ae_primary_complex, ae_primary_polar, ae_primary_vec,
                ae_primary_char, ae_primary_nil
              } ae_Exp_Primary_Type;
ae_func_type
enum ae_func_type
Enumerator
ae_func_builtin
ae_func_user
Definition at line 495 of file absyn.h.
 { ae_func_builtin, ae_func_user} ae_func_type;
ae_Keyword
enum ae_Keyword
Enumerator
ae_key_this
ae_key_me
ae_key_func
ae_key_public
ae_key_protected
ae_key_private
ae_key_static
ae_key_instance
ae_key_abstract
ae_key_variadic
Definition at line 15 of file absyn.h.
              {
   ae_key_this, ae_key_me, ae_key_func, ae_key_public, ae_key_protected,
   ae_key_private, ae_key_static, ae_key_instance, ae_key_abstract, ae_key_variadic
 } ae_Keyword;
ae_Section_Type
enum ae_Section_Type
Enumerator
ae_section_stmt
ae_section_func
ae_section_class
Definition at line 492 of file absyn.h.
              { ae_section_stmt, ae_section_func, ae_section_class
              } ae_Section_Type;
ae_Stmt_Type
enum ae_Stmt_Type
Enumerator
ae_stmt_exp
ae_stmt_while
ae_stmt_until
ae_stmt_for
ae_stmt_loop
ae_stmt_if
ae_stmt_code
ae_stmt_switch
ae_stmt_break
ae_stmt_continue
ae_stmt_return
ae_stmt_case
ae_stmt_gotolabel
ae_stmt_enum
ae_stmt_funcptr
ae_stmt_union
Definition at line 251 of file absyn.h.
              { ae_stmt_exp, ae_stmt_while, ae_stmt_until, ae_stmt_for, ae_stmt_loop,
                ae_stmt_if, ae_stmt_code, ae_stmt_switch, ae_stmt_break,
                ae_stmt_continue, ae_stmt_return, ae_stmt_case, ae_stmt_gotolabel,
                ae_stmt_enum, ae_stmt_funcptr, ae_stmt_union
              } ae_Stmt_Type;
Expression_type
enum Expression_type
Enumerator
Decl_Expression_type
Binary_Expression_type
Unary_Expression_type
Primary_Expression_type
Cast_Expression_type
Postfix_Expression_type
Func_Call_type
Array_Expression_type
If_Expression_type
Dot_Member_type
Dur_Expression_type
Definition at line 230 of file absyn.h.
              { Decl_Expression_type, Binary_Expression_type, Unary_Expression_type, Primary_Expression_type,
                Cast_Expression_type, Postfix_Expression_type, Func_Call_type, Array_Expression_type,
                If_Expression_type, Dot_Member_type, Dur_Expression_type
              } Expression_type;
Function Documentation
add_type_decl_array()
Type_Decl* add_type_decl_array (Type_Decl * a, Array_Sub array, int pos)
Definition at line 134 of file absyn.c.
References Type_Decl::array.
Referenced by make_dll_as_fun(), and yyparse().
 {
   a->array = array;
   return a;
 }
check_Func_Def()
m_bool check_Func_Def (Env env, Func_Def f)
Definition at line 2248 of file type.c.
References ae_func_builtin, ae_func_user, ae_key_abstract, ae_key_static, Func_Def_::arg_list, check_Stmt_Code(), Value_::checked, Env_::class_def, Func_::code, Func_Def_::code, compat_func(), Env_::context, Env_::curr, Stmt::d, Func_::def, Type_::def, Func_Def_::dl_func_ptr, err_msg(), find_value(), Env_::func, Func_Def_::func, Value_::func_num_overloads, Value_::func_ref, Class_Def_::iface, insert_symbol(), Func_::is_member, Func_Def_::is_variadic, isa(), Value_::m_type, Func_::name, NameSpace_::name, Value_::name, Type_::name, Func_Def_::name, namespace_add_value(), namespace_lookup_func(), namespace_lookup_value(), namespace_pop_value(), namespace_push_value(), VM_Code_::need_this, new_Value(), Func_::next, Arg_List_::next, Value_::obj, NameSpace_::obj_v_table, Value_::owner_class, Type_::parent, Arg_List_::pos, Func_Def_::pos, rem_ref(), Func_Def_::ret_type, S_name(), Func_Def_::s_type, VM_Code_::stack_depth, Func_Def_::stack_depth, Func_Def_::static_decl, Stmt::stmt_code, t_vararg, TYPE_, Func_Def_::types, Func_::up, Var_Decl_::value, Func_::value_ref, Arg_List_::var_decl, vector_append(), vector_set(), vector_size(), Func_::vt_index, and Var_Decl_::xid.
Referenced by check_Class_Def(), check_Context(), and find_template_match().
 {
 #ifdef DEBUG_TYPE
   debug_msg("check", "func def '%s'", f->func->name);
 #endif
   Value value = NULL;
   Func func = NULL;
   Type parent = NULL;
   Value override = NULL;
   Value  v = NULL;
   Value vararg = NULL;
   Func  parent_func = NULL;
   Arg_List arg_list = NULL;
   m_bool parent_match = 0;
   m_str func_name = S_name(f->name);
   //  m_str func_name = strdup(S_name(f->name)); // strdup might be unnnecessary. 27/11/16
   m_uint count = 1;
   m_bool has_code = 0;
   if(f->types) // templating, check at call time
     return 1;
   if(env->func) {
     err_msg(TYPE_, f->pos, "nested function definitions are not (yet) allowed");
     return -1;
   }
   func = f->func;
   value = func->value_ref;
   // look up the value in the parent class
   if(env->class_def)
     override = find_value(env->class_def->parent, f->name);
   else if(value->func_num_overloads) { // check if func has ame args
     m_uint i, j;
     if(!f->types)
       for(i = 0; i <= value->func_num_overloads; i++) {
         char name[1024];
         sprintf(name, "%s@%li@%s", S_name(f->name), i, env->curr->name);
         Func f1 = namespace_lookup_func(env->curr, insert_symbol(name), -1);
         for(j = 1; j <= value->func_num_overloads; j++) {
           if(i != j) {
             sprintf(name, "%s@%li@%s", S_name(f->name), j, env->curr->name);
             Func f2 = namespace_lookup_func(env->curr, insert_symbol(name), -1);
             if(compat_func(f1->def, f2->def, f2->def->pos) > 0) {
               err_msg(TYPE_, f2->def->pos, "global function '%s' already defined for those arguments", S_name(f->name));
               return -1;
             }
           }
         }
       }
   }
   if(env->class_def &&  override) {
     if(isa(override->m_type, &t_function) < 0) {
       err_msg(TYPE_, f->pos, "function name '%s' conflicts with previously defined value...",
               S_name(f->name));
       err_msg(TYPE_, f->pos, "from super class '%s'...", override->owner_class->name);
       goto error;
     }
   }
   if(override) {
     // make reference to parent
     // TODO: ref count
     func->up = override;
   }
   if(!env->class_def && f->static_decl == ae_key_abstract) {
     err_msg(TYPE_, f->pos, "non-class function cannot be declared as 'pure'...");
     err_msg(TYPE_, f->pos, "...at function '%s'", S_name(f->name) );
     goto error;
   }
   if(f->s_type == ae_func_user) has_code = (f->code != NULL);
   else has_code = (f->dl_func_ptr != NULL); // imported
   if(env->class_def && env->class_def->def && env->class_def->def->iface && has_code) {
     err_msg(TYPE_, f->pos, "interface function signatures cannot contain code..." );
     err_msg(TYPE_, f->pos, "...at function '%s'", S_name(f->name));
     goto error;
   }
   if(f->static_decl == ae_key_abstract && has_code) {
     err_msg(TYPE_, f->pos, "'pure' function signatures cannot contain code..." );
     err_msg(TYPE_, f->pos, "...at function '%s'", S_name(f->name));
     goto error;
   }
   if(f->static_decl != ae_key_abstract && !has_code) {
     err_msg(TYPE_, f->pos, "function declaration must contain code..." );
     err_msg(TYPE_, f->pos, "(unless in interface, or is declared 'pure')" );
     err_msg(TYPE_, f->pos, "...at function '%s'", S_name(f->name));
     goto error;
   }
   // TODO if overload, check arguments do not match
   // if overriding super class function, then check signatures
   if(env->class_def) {
     // get parent
     parent = env->class_def->parent;
     while( parent && !parent_match ) {
       if((v = find_value(env->class_def->parent, f->name))) {
         // see if the target is a function
         if(!isa( v->m_type, &t_function)) {
           err_msg(TYPE_, f->pos, "function name '%s' conflicts with previously defined value...",
                   S_name(f->name));
           err_msg(TYPE_, f->pos, "from super class '%s'...", v->owner_class->name );
           goto error;
         }
         // parent func
         parent_func = v->func_ref;
         // go through all overloading
         while(parent_func && !parent_match) {
           // match the prototypes
           if(compat_func(f, parent_func->def, f->pos) < 0) {
             // next
             parent_func = parent_func->next;
             // move on
             continue;
           }
           // see if parent function is static
           if( parent_func->def->static_decl == ae_key_static ) {
             err_msg(TYPE_, f->pos,
                     "function '%s.%s' resembles '%s.%s' but cannot override...",
                     env->class_def->name, S_name(f->name),
                     v->owner_class->name, S_name(f->name) );
             err_msg(TYPE_, f->pos,
                     "...(reason: '%s.%s' is declared as 'static')",
                     v->owner_class->name, S_name(f->name) );
             goto error;
           }
           // see if function is static
           if(f->static_decl == ae_key_static) {
             err_msg(TYPE_, f->pos,
                     "function '%s.%s' resembles '%s.%s' but cannot override...",
                     env->class_def->name, S_name(f->name),
                     v->owner_class->name, S_name(f->name));
             err_msg(TYPE_, f->pos,
                     "...(reason: '%s.%s' is declared as 'static')",
                     env->class_def->name, S_name(f->name));
             goto error;
           }
           // see if function is pure
           if(f->static_decl == ae_key_abstract) {
             err_msg(TYPE_, f->pos,
                     "function '%s.%s' resembles '%s.%s' but cannot override...",
                     env->class_def->name, S_name(f->name),
                     v->owner_class->name, S_name(f->name));
             err_msg(TYPE_, f->pos,
                     "...(reason: '%s.%s' is declared as 'pure')",
                     env->class_def->name, S_name(f->name));
             goto error;
           }
           // make sure returns are equal
           if(isa(f->ret_type, parent_func->def->ret_type) < 0) {
             err_msg(TYPE_, f->pos, "function signatures differ in return type..." );
             err_msg(TYPE_, f->pos,
                     "function '%s.%s' matches '%s.%s' but cannot override...",
                     env->class_def->name, S_name(f->name),
                     v->owner_class->name, S_name(f->name));
             goto error;
           }
           parent_match = 1;
           func->vt_index = parent_func->vt_index;
           vector_set(env->curr->obj_v_table, func->vt_index, (vtype)func);
           func_name = parent_func->name;
           func->name = func_name;
           value->name = func_name;
         }
       }
       // move to next parent
       parent = parent->parent;
     }
   }
   if(func->is_member && !parent_match) {
     func->vt_index = vector_size(env->curr->obj_v_table);
     vector_append(env->curr->obj_v_table, (vtype)func);
   }
   env->func = func;
   namespace_push_value(env->curr);
   arg_list = f->arg_list;
   while(arg_list) {
     v = arg_list->var_decl->value;
     if(namespace_lookup_value( env->curr, arg_list->var_decl->xid, 0)) {
       err_msg(TYPE_, arg_list->pos, "argument %i '%s' is already defined in this scope",
               count, S_name(arg_list->var_decl->xid) );
       err_msg(TYPE_, arg_list->pos, "in function '%s':", S_name(f->name));
       goto error;
     }
     v->checked  = 1;
     namespace_add_value(env->curr, arg_list->var_decl->xid, v );
     count++;
     arg_list = arg_list->next;
   }
   if(f->is_variadic) {
     vararg = new_Value(env->context, &t_vararg, "vararg");
     vararg->checked = 1;
     namespace_add_value(env->curr, insert_symbol("vararg"), vararg);
   }
   if(f->code && check_Stmt_Code(env, f->code->d.stmt_code, 0) < 0) {
     err_msg(TYPE_, f->pos, "...in function '%s'", S_name(f->name));
     goto error;
   }
   if(f->is_variadic)
     rem_ref(vararg->obj, vararg);
   if(f->s_type == ae_func_builtin) { // is this useful ?
     func->code->stack_depth = f->stack_depth;
     func->code->need_this = 1;
   }
 //  else
 //    func->code->need_this = 0;
   namespace_pop_value(env->curr);
   env->func = NULL;
   return 1;
 error:
   namespace_pop_value(env->curr);
   env->func = NULL;
   return -1;
 }
free_Arg_List()
void free_Arg_List (Arg_List a)
Definition at line 832 of file absyn.c.
References Type_::array_type, free(), free_Arg_List(), free_Type_Decl(), free_Var_Decl(), Value_::m_type, Arg_List_::next, Type_::obj, Arg_List_::type_decl, Var_Decl_::value, and Arg_List_::var_decl.
Referenced by free_Arg_List(), free_Func_Def(), free_Section(), and free_Stmt_Func_Ptr().
 {
   if(a->next)
     free_Arg_List(a->next);
   free_Type_Decl(a->type_decl);
   if(a->var_decl->value) {
     if(a->var_decl->value->m_type->array_type) {
       free(a->var_decl->value->m_type->obj);
       free(a->var_decl->value->m_type);
     }
   }
   free_Var_Decl(a->var_decl);
   free(a);
 }
free_Array_Sub()
void free_Array_Sub (Array_Sub a)
Definition at line 29 of file absyn.c.
References Array_Sub_::exp_list, free(), and free_Expression().
Referenced by check_Unary(), free_Array_Expression(), free_Primary_Expression(), and free_Var_Decl().
 {
   free_Expression(a->exp_list);
   free(a);
 }
free_Ast()
void free_Ast ()
free_Func_Def()
void free_Func_Def (Func_Def def)
Definition at line 649 of file absyn.c.
References Func_Def_::arg_list, Type_::array_type, free(), free_Arg_List(), free_ID_List(), free_Type_Decl(), Func_Def_::is_template, Type_::obj, Func_Def_::ret_type, Func_Def_::type_decl, and Func_Def_::types.
Referenced by find_template_match(), free_Func(), and free_Section().
 {
   if(!a->is_template) {
     if(a->types)
       free_ID_List(a->types);
     if(a->ret_type && a->ret_type->array_type) {
       free(a->ret_type->obj);
       free(a->ret_type);
     }
     if(a->arg_list)
       free_Arg_List(a->arg_list);
 //  if(a->type_decl)
     free_Type_Decl(a->type_decl);
     free(a);
   } else
       free(a);
 }
free_ID_List()
void free_ID_List (ID_List a)
Definition at line 1378 of file absyn.c.
References free(), and ID_List_::next.
Referenced by free_Class_Def(), free_Func_Def(), free_Section(), free_Stmt_Enum(), free_Type_Decl(), free_Type_List(), make_dll_arg_list(), and str2list().
 {
 #ifdef DEBUG_AST
   debug_msg("emit", "free_ID_LIST");
 #endif
   ID_List tmp, curr = a;
   while(curr) {
     tmp = curr;
     curr = curr->next;
     free(tmp);
   }
 }
free_Type_Decl()
void free_Type_Decl (Type_Decl * a)
Definition at line 163 of file absyn.c.
References Type_Decl::array, free(), free_ID_List(), and Type_Decl::xid.
Referenced by free_Arg_List(), free_Cast_Expression(), free_Decl_Expression(), free_Func_Def(), free_Section(), free_Stmt_Func_Ptr(), and free_Unary_Expression().
 {
   if(a->array) {
     free(a->array);
   }
   free_ID_List(a->xid);
   free(a);
 }
free_Type_List()
void free_Type_List (Type_List a)
Definition at line 1400 of file absyn.c.
References free(), free_ID_List(), free_Type_List(), Type_List_::list, and Type_List_::next.
Referenced by check_Func_Call(), free_Func_Call(), and free_Type_List().
 {
   if(a->next)
     free_Type_List(a->next);
   free_ID_List(a->list);
   free(a);
 }
new_Arg_List()
Arg_List new_Arg_List (Type_Decl * type_decl, Var_Decl var_decl, Arg_List arg_list, int pos)
Definition at line 821 of file absyn.c.
References Arg_List_::doc, Arg_List_::next, Arg_List_::pos, Arg_List_::type_decl, and Arg_List_::var_decl.
Referenced by make_dll_arg_list(), and yyparse().
 {
   Arg_List a = calloc(1, sizeof(struct Arg_List_));
   a->type_decl = type_decl;
   a->var_decl = var_decl;
   a->next = arg_list;
   a->doc = NULL;
   a->pos = pos;
   return a;
 }
new_Array()
Expression new_Array (Expression base, Array_Sub indices, int pos)
Definition at line 140 of file absyn.c.
References ae_meta_var, Array_Expression_type, Array::base, Expression_::cast_to, Expression_::d, Expression_::exp_array, Expression_::exp_type, Array::indices, Expression_::meta, Expression_::next, Array::pos, Expression_::pos, and Array::self.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Array_Expression_type;
   a->meta = ae_meta_var;
   a->d.exp_array = calloc(1, sizeof(Array));
   a->d.exp_array->base = base;
   a->d.exp_array->indices = indices;
   a->pos = pos;
   a->d.exp_array->pos = pos;
   a->d.exp_array->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_array_sub()
Array_Sub new_array_sub (Expression exp, int pos)
Definition at line 97 of file absyn.c.
References Array_Sub_::depth, Array_Sub_::err_num, Array_Sub_::exp_list, and Array_Sub_::pos.
Referenced by import_var(), make_dll_arg_list(), make_dll_as_fun(), and yyparse().
 {
   Array_Sub a = calloc(1, sizeof(struct Array_Sub_));
   a->exp_list = exp;
   a->depth = 1;
   a->err_num = 0;
   a->pos = pos;
   return a;
 }
new_Ast()
Ast new_Ast (Section * section, Ast next, int pos)
Definition at line 1420 of file absyn.c.
References Ast_::doc, malloc(), Ast_::next, Ast_::pos, and Ast_::section.
Referenced by yyparse().
 {
 #ifdef DEBUG_AST
   debug_msg("emit", "new Ast");
 #endif
   Ast ast = malloc(sizeof(struct Ast_));
   ast->section = section;
   ast->next = next;
   ast->pos = pos;
   ast->doc = NULL;
   return ast;
 }
new_Binary_Expression()
Expression new_Binary_Expression (Expression lhs, Operator op, Expression rhs, int pos)
Definition at line 197 of file absyn.c.
References ae_meta_value, Binary_Expression_type, Expression_::cast_to, Expression_::d, Expression_::exp_binary, Expression_::exp_type, Binary_Expression::lhs, Expression_::meta, Expression_::next, Binary_Expression::op, Binary_Expression::pos, Expression_::pos, Binary_Expression::rhs, and Binary_Expression::self.
Referenced by yyparse().
 {
   Expression a = calloc(1,  sizeof( struct Expression_ ) );
   a->exp_type = Binary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_binary = calloc(1, sizeof(Binary_Expression));
   a->d.exp_binary->lhs = lhs;
   a->d.exp_binary->op = op;
   a->d.exp_binary->rhs = rhs;
   a->pos = pos;
   a->d.exp_binary->pos = pos;
   a->d.exp_binary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Cast_Expression()
Expression new_Cast_Expression (Type_Decl * type, Expression exp, int pos)
Definition at line 221 of file absyn.c.
References ae_meta_value, Cast_Expression_type, Expression_::cast_to, Expression_::d, Cast_Expression::exp, Expression_::exp_cast, Expression_::exp_type, Expression_::meta, Expression_::next, Cast_Expression::pos, Expression_::pos, Cast_Expression::self, and Cast_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1,  sizeof( struct Expression_ ) );
   a->exp_type = Cast_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_cast = calloc(1, sizeof(Cast_Expression));
   a->d.exp_cast->type = type;
   a->pos = pos;
   a->d.exp_cast->pos = pos;
   a->d.exp_cast->exp = exp;
   a->d.exp_cast->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_class_body()
Class_Body new_class_body (Section * section, int pos)
Definition at line 1334 of file absyn.c.
References Class_Body_::next, Class_Body_::pos, and Class_Body_::section.
Referenced by prepend_class_body(), and yyparse().
 {
   Class_Body a = calloc(1, sizeof(struct Class_Body_));
   a->section = section;
   a->pos = pos;
   a->next = NULL;
   return a;
 }
new_class_def()
Class_Def new_class_def (ae_Keyword class_decl, ID_List name, Class_Ext ext, Class_Body body, int pos)
Definition at line 1311 of file absyn.c.
References Class_Def_::body, Class_Def_::decl, Class_Def_::doc, Class_Def_::ext, Class_Def_::home, Class_Def_::name, Class_Def_::pos, and Class_Def_::type.
Referenced by new_iface_def(), and yyparse().
 {
   Class_Def a = calloc(1, sizeof(struct Class_Def_));
   a->decl = class_decl;
   a->name = name;
   a->ext  = ext;
   a->home = NULL;
   a->body = body;
   a->pos  = pos;
   a->doc  = NULL;
   a->type = NULL;
   return a;
 }
new_class_ext()
Class_Ext new_class_ext (ID_List extend_id, ID_List impl_list, int pos)
Definition at line 1351 of file absyn.c.
References Class_Ext_::extend_id, Class_Ext_::impl_list, and Class_Ext_::pos.
Referenced by yyparse().
 {
   Class_Ext a = calloc(1, sizeof(struct Class_Ext_));
   a->extend_id = extend_id;
   a->impl_list = impl_list;
   a->pos = pos;
   return a;
 }
new_complex()
Complex* new_complex (Expression re, int pos)
Definition at line 388 of file absyn.c.
References Complex::im, Expression_::next, Complex::pos, and Complex::re.
Referenced by yyparse().
 {
   Complex* a = calloc(1, sizeof(Complex));
   a->re = re;
   if(re)
     a->im = re->next;
   a->pos = pos;
   return a;
 }
new_Decl_Expression()
Expression new_Decl_Expression (Type_Decl * type, Var_Decl_List list, m_bool is_static, int pos)
Definition at line 172 of file absyn.c.
References Expression_::cast_to, Expression_::d, Decl_Expression_type, Expression_::exp_decl, Expression_::exp_type, Decl_Expression::is_static, Decl_Expression::list, Expression_::next, Decl_Expression::num_decl, Decl_Expression::pos, Expression_::pos, Decl_Expression::self, and Decl_Expression::type.
Referenced by import_var(), and yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Decl_Expression_type;
   a->d.exp_decl  = calloc(1, sizeof(Decl_Expression));
   a->d.exp_decl->type = type;
   a->d.exp_decl->num_decl = 0;
   a->d.exp_decl->list = list;
   a->d.exp_decl->is_static = is_static;
   a->pos  = pos;
   a->d.exp_decl->pos  = pos;
   a->d.exp_decl->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Decl_List()
Decl_List new_Decl_List (Decl_Expression * d, Decl_List l)
Definition at line 1123 of file absyn.c.
References Decl_List_::next, and Decl_List_::self.
Referenced by yyparse().
 {
   Decl_List a = calloc(1, sizeof(struct Decl_List_));
   a->self = d;
   a->next = l;
   return a;
 }
new_Exp_Dur()
Expression new_Exp_Dur (Expression base, Expression unit, int pos)
Definition at line 266 of file absyn.c.
References ae_meta_value, Exp_Dur::base, Expression_::cast_to, Expression_::d, Dur_Expression_type, Expression_::exp_dur, Expression_::exp_type, Expression_::meta, Expression_::next, Exp_Dur::pos, Expression_::pos, Exp_Dur::self, and Exp_Dur::unit.
Referenced by yyparse().
 {
   Expression a = calloc(1,  sizeof( struct Expression_ ) );
   a->exp_type = Dur_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_dur = calloc(1, sizeof(Exp_Dur));
   a->d.exp_dur->base = base;
   a->d.exp_dur->unit = unit;
   a->pos = pos;
   a->d.exp_dur->pos = pos;
   a->d.exp_dur->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_array_lit()
Expression new_exp_from_array_lit (Array_Sub exp_list, int pos)
Definition at line 421 of file absyn.c.
References ae_meta_value, ae_primary_array, Primary_Expression::array, Expression_::cast_to, Primary_Expression::d, Expression_::d, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_array;
   a->d.exp_primary->d.array = exp_list;
   a->pos = pos;
   a->d.exp_primary->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_char()
Expression new_exp_from_char (c_str chr, int pos)
Definition at line 405 of file absyn.c.
References ae_meta_value, ae_primary_char, Expression_::cast_to, Primary_Expression::chr, Primary_Expression::d, Expression_::d, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_char;
   a->d.exp_primary->d.chr = chr;
   a->pos = pos;
   a->d.exp_primary->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_complex()
Expression new_exp_from_complex (Complex * exp, int pos)
Definition at line 452 of file absyn.c.
References ae_meta_value, ae_primary_complex, Expression_::cast_to, Primary_Expression::cmp, Primary_Expression::d, Expression_::d, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Complex::self, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_complex;
   a->d.exp_primary->d.cmp = exp;
   a->d.exp_primary->pos = pos;
   a->pos = pos;
   a->d.exp_primary->d.cmp->self = a;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_member_dot()
Expression new_exp_from_member_dot (Expression base, m_str xid, int pos)
Definition at line 729 of file absyn.c.
References ae_meta_var, Dot_Member::base, Expression_::cast_to, Expression_::d, Dot_Member_type, Expression_::exp_dot, Expression_::exp_type, insert_symbol(), Expression_::meta, Expression_::next, Dot_Member::pos, Expression_::pos, Dot_Member::self, and Dot_Member::xid.
Referenced by emit_symbol(), and yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Dot_Member_type;
   a->meta = ae_meta_var;
   a->d.exp_dot = calloc(1, sizeof(Dot_Member));
   a->d.exp_dot->base = base;
   a->d.exp_dot->xid = insert_symbol( xid );
   a->pos = pos;
   a->d.exp_dot->pos = pos;
   a->d.exp_dot->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_polar()
Expression new_exp_from_polar (Polar * exp, int pos)
Definition at line 469 of file absyn.c.
References ae_meta_value, ae_primary_polar, Expression_::cast_to, Primary_Expression::d, Expression_::d, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::polar, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Polar::self, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_polar;
   a->d.exp_primary->d.polar = exp;
   a->d.exp_primary->pos = pos;
   a->pos = pos;
   a->d.exp_primary->d.polar->self = a;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_unary()
Expression new_exp_from_unary (Operator oper, Expression exp, int pos)
Definition at line 535 of file absyn.c.
References Expression_::cast_to, Unary_Expression::code, Expression_::d, Unary_Expression::exp, Expression_::exp_type, Expression_::exp_unary, Expression_::meta, Expression_::next, Unary_Expression::op, Unary_Expression::pos, Expression_::pos, Unary_Expression::self, and Unary_Expression_type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Unary_Expression_type;
   a->meta = exp->meta;
   a->d.exp_unary = calloc(1, sizeof(Unary_Expression));
   a->d.exp_unary->op = oper;
   a->d.exp_unary->exp = exp;
   a->d.exp_unary->code = NULL;
   a->pos = pos;
   a->d.exp_unary->pos = pos;
   a->d.exp_unary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_unary2()
Expression new_exp_from_unary2 (Operator oper, Type_Decl * type, Array_Sub array, int pos)
Definition at line 552 of file absyn.c.
References ae_meta_value, Unary_Expression::array, Expression_::cast_to, Unary_Expression::code, Expression_::d, Unary_Expression::exp, Expression_::exp_type, Expression_::exp_unary, Expression_::meta, Expression_::next, Unary_Expression::op, Unary_Expression::pos, Expression_::pos, Unary_Expression::self, Unary_Expression::type, and Unary_Expression_type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Unary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_unary = calloc(1, sizeof(Unary_Expression));
   a->d.exp_unary->exp = NULL;
   a->d.exp_unary->op = oper;
   a->d.exp_unary->type = type;
   a->d.exp_unary->array = array;
   a->d.exp_unary->code = NULL;
   a->pos = pos;
   a->d.exp_unary->pos = pos;
   a->d.exp_unary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_unary3()
Expression new_exp_from_unary3 (Operator oper, Stmt * code, int pos)
Definition at line 582 of file absyn.c.
References ae_meta_value, Unary_Expression::array, Expression_::cast_to, Unary_Expression::code, Expression_::d, Unary_Expression::exp, Expression_::exp_type, Expression_::exp_unary, Expression_::meta, new_id_list(), new_Type_Decl(), Expression_::next, Unary_Expression::op, Unary_Expression::pos, Expression_::pos, Unary_Expression::self, Unary_Expression::type, and Unary_Expression_type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Unary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_unary = calloc(1, sizeof(Unary_Expression));
   a->d.exp_unary->exp = NULL;
   a->d.exp_unary->op = oper;
   ID_List id = new_id_list("void", pos);
   a->d.exp_unary->type = new_Type_Decl(id, 0, pos);
   a->d.exp_unary->array = NULL;
   a->d.exp_unary->code = code;
   a->pos = pos;
   a->d.exp_unary->pos = pos;
   a->d.exp_unary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_vec()
Expression new_exp_from_vec (Vec a, int pos)
Definition at line 520 of file absyn.c.
References ae_meta_value, ae_primary_vec, Primary_Expression::d, Expression_::d, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Vec_::self, Primary_Expression::self, Primary_Expression::type, and Primary_Expression::vec.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_vec;
   a->d.exp_primary->d.vec = exp;
   a->d.exp_primary->pos = pos;
   a->pos = pos;
   a->d.exp_primary->d.vec->self = a;
   a->d.exp_primary->self = a;
   return a;
 }
new_Func_Call()
Expression new_Func_Call (Expression base, Expression args, int pos)
Definition at line 699 of file absyn.c.
References ae_meta_value, Func_Call::args, Expression_::cast_to, Expression_::d, Expression_::exp_func, Expression_::exp_type, Func_Call::func, Func_Call_type, Func_Call::m_func, Expression_::meta, Expression_::next, Func_Call::pos, Expression_::pos, Func_Call::self, and Func_Call::types.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Func_Call_type;
   a->meta = ae_meta_value;
   a->d.exp_func = calloc(1, sizeof(Func_Call));
   a->d.exp_func->func = base;
   a->d.exp_func->args = args;
   a->d.exp_func->types = NULL;
   a->pos = pos;
   a->d.exp_func->m_func = NULL;
   a->d.exp_func->pos = pos;
   a->d.exp_func->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Func_Def()
Func_Def new_Func_Def (ae_Keyword func_decl, ae_Keyword static_decl, Type_Decl * type_decl, m_str name, Arg_List arg_list, Stmt * code, int pos)
Definition at line 628 of file absyn.c.
References ae_func_spec_none, ae_func_user, ae_key_func, ae_key_variadic, Func_Def_::arg_list, Func_Def_::code, Func_Def_::func, Func_Def_::func_decl, insert_symbol(), Func_Def_::is_variadic, Func_Def_::name, Func_Def_::pos, Func_Def_::s_type, Func_Def_::spec, Func_Def_::stack_depth, Func_Def_::static_decl, and Func_Def_::type_decl.
Referenced by emit_Unary(), find_template_match(), make_dll_as_fun(), scan2_Func_Ptr(), and yyparse().
 {
   Func_Def a = calloc(1, sizeof(struct Func_Def_));
   a->func_decl = func_decl;
   a->static_decl = static_decl;
   a->type_decl = type_decl;
   a->name = insert_symbol(name);
   a->arg_list = arg_list;
   a->s_type = ae_func_user;
   a->code = code;
   a->func = NULL;
   a->stack_depth = 0;
   a->pos = pos;
   a->spec = ae_func_spec_none;
   if(a->func_decl == ae_key_variadic) {
     a->func_decl = ae_key_func;
     a->is_variadic = 1;
   }
   return a;
 }
new_Func_Ptr_Stmt()
Stmt* new_Func_Ptr_Stmt (ae_Keyword key, m_str type, Type_Decl * decl, Arg_List args, int pos)
Definition at line 667 of file absyn.c.
References ae_stmt_funcptr, Func_Ptr::args, Stmt::d, Func_Ptr::func, insert_symbol(), Func_Ptr::key, Func_Ptr::pos, Stmt::pos, Stmt::stmt_funcptr, Func_Ptr::type, Stmt::type, Func_Ptr::value, and Func_Ptr::xid.
Referenced by yyparse().
 {
   Stmt* a                = calloc(1, sizeof(Stmt));
   a->type                = ae_stmt_funcptr;
   a->d.stmt_funcptr        = calloc(1, sizeof(Func_Ptr));
   a->d.stmt_funcptr->key   = key;
   a->d.stmt_funcptr->type  = decl;
   a->d.stmt_funcptr->xid   = insert_symbol(xid);
   a->d.stmt_funcptr->args  = args;
   a->d.stmt_funcptr->func  = NULL;
   a->d.stmt_funcptr->value = NULL;
 //  a->stmt_funcptr->ref   = NULL;
   a->d.stmt_funcptr->pos   = pos;
   a->pos             = pos;
   return a;
 }
new_Hack_Expression()
Expression new_Hack_Expression (Expression exp, int pos)
Definition at line 372 of file absyn.c.
References ae_meta_value, ae_primary_hack, Expression_::cast_to, Primary_Expression::d, Expression_::d, Primary_Expression::exp, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_hack;
   a->d.exp_primary->d.exp = exp;
   a->d.exp_primary->pos = pos;
   a->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_id_list()
ID_List new_id_list (const m_str xid, int pos)
Definition at line 1360 of file absyn.c.
References insert_symbol(), ID_List_::next, ID_List_::pos, and ID_List_::xid.
Referenced by emit_Unary(), new_exp_from_unary3(), prepend_id_list(), and yyparse().
 {
   ID_List a = calloc(1,  sizeof( struct ID_List_ ) );
   a->xid = insert_symbol( xid );
   a->next = NULL;
   a->pos = pos;
   return a;
 }
new_If_Expression()
Expression new_If_Expression (Expression cond, Expression if_exp, Expression else_exp, int pos)
Definition at line 602 of file absyn.c.
References ae_meta_value, ae_meta_var, Expression_::cast_to, If_Expression::cond, Expression_::d, If_Expression::else_exp, Expression_::exp_if, Expression_::exp_type, If_Expression::if_exp, If_Expression_type, Expression_::meta, Expression_::next, If_Expression::pos, Expression_::pos, and If_Expression::self.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = If_Expression_type;
   a->meta = ( ( if_exp->meta == ae_meta_var &&
                 else_exp->meta == ae_meta_var ) ? ae_meta_var : ae_meta_value );
   a->d.exp_if = calloc(1, sizeof(If_Expression));
   a->d.exp_if->cond = cond;
   a->d.exp_if->if_exp = if_exp;
   a->d.exp_if->else_exp = else_exp;
   a->pos = pos;
   a->d.exp_if->pos = pos;
   a->d.exp_if->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_iface_def()
Class_Def new_iface_def (ae_Keyword class_decl, ID_List name, Class_Ext ext, Class_Body body, int pos)
Definition at line 1326 of file absyn.c.
References Class_Def_::iface, and new_class_def().
 {
   Class_Def a = new_class_def( class_decl, name, ext, body, pos );
   a->iface = 1;
   return a;
 }
new_polar()
Polar* new_polar (Expression mod, int pos)
Definition at line 486 of file absyn.c.
References Polar::mod, Expression_::next, Polar::phase, and Polar::pos.
Referenced by yyparse().
 {
   Polar* a = calloc(1, sizeof(Polar));
   a->mod = mod;
   if(mod)
     a->phase = mod->next;
   a->pos = pos;
   return a;
 }
new_Postfix_Expression()
Expression new_Postfix_Expression (Expression exp, Operator op, int pos)
Definition at line 244 of file absyn.c.
References ae_meta_var, Expression_::cast_to, Expression_::d, Postfix_Expression::exp, Expression_::exp_postfix, Expression_::exp_type, Expression_::meta, Expression_::next, Postfix_Expression::op, Postfix_Expression::pos, Expression_::pos, Postfix_Expression_type, and Postfix_Expression::self.
Referenced by yyparse().
 {
   Expression a = calloc(1,  sizeof( struct Expression_ ) );
   a->exp_type = Postfix_Expression_type;
   a->meta = ae_meta_var;
   a->d.exp_postfix = calloc(1, sizeof(Postfix_Expression));
   a->d.exp_postfix->exp = exp;
   a->d.exp_postfix->op = op;
   a->pos = pos;
   a->d.exp_postfix->pos = pos;
   a->d.exp_postfix->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Primary_Expression_from_float()
Expression new_Primary_Expression_from_float (m_float num, int pos)
Definition at line 306 of file absyn.c.
References ae_meta_value, ae_primary_float, Expression_::cast_to, Primary_Expression::d, Expression_::d, Expression_::emit_var, Expression_::exp_primary, Expression_::exp_type, Primary_Expression::fnum, Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1,  sizeof( struct Expression_ ) );
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->emit_var = 0; // ???
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_float;
   a->d.exp_primary->d.fnum = num;
   a->pos = pos;
   a->d.exp_primary->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Primary_Expression_from_ID()
Expression new_Primary_Expression_from_ID (m_str s, int pos)
Definition at line 355 of file absyn.c.
References ae_meta_var, ae_primary_var, Expression_::cast_to, Primary_Expression::d, Expression_::d, Expression_::emit_var, Expression_::exp_primary, Expression_::exp_type, insert_symbol(), Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, Primary_Expression::type, and Primary_Expression::var.
Referenced by emit_symbol(), and yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_var;
   a->emit_var = 0;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_var;
   a->d.exp_primary->d.var = insert_symbol(s);
   a->pos = pos;
   a->d.exp_primary->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Primary_Expression_from_int()
Expression new_Primary_Expression_from_int (long i, int pos)
Definition at line 289 of file absyn.c.
References ae_meta_value, ae_primary_num, Expression_::cast_to, Primary_Expression::d, Expression_::d, Expression_::emit_var, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::num, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->emit_var = 0;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_num;
   a->d.exp_primary->d.num = i;
   a->pos = pos;
   a->d.exp_primary->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Primary_Expression_from_nil()
Expression new_Primary_Expression_from_nil (int pos)
Definition at line 340 of file absyn.c.
References ae_meta_value, ae_primary_nil, Expression_::cast_to, Expression_::d, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression  a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_nil;
   a->d.exp_primary->pos = pos;
   a->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Primary_Expression_from_string()
Expression new_Primary_Expression_from_string (m_str s, int pos)
Definition at line 323 of file absyn.c.
References ae_meta_value, ae_primary_str, Expression_::cast_to, Primary_Expression::d, Expression_::d, Expression_::emit_var, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, Primary_Expression::str, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1,  sizeof( struct Expression_ ) );
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->emit_var = 0; // ???
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_str;
   a->d.exp_primary->d.str = s;
   a->pos = pos;
   a->d.exp_primary->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_section_Class_Def()
Section* new_section_Class_Def (Class_Def class_def, int pos)
Definition at line 1408 of file absyn.c.
References ae_section_class, Section::class_def, Section::d, Section::pos, and Section::type.
Referenced by yyparse().
 {
 #ifdef DEBUG_AST
   debug_msg("emit", "class def");
 #endif
   Section* a = calloc(1, sizeof(Section));
   a->type = ae_section_class;
   a->d.class_def = class_def;
   a->pos = pos;
   return a;
 }
new_section_Func_Def()
Section* new_section_Func_Def (Func_Def func_def, int pos)
Definition at line 1240 of file absyn.c.
References ae_section_func, Section::d, Section::func_def, Section::pos, and Section::type.
Referenced by yyparse().
 {
   Section* a = calloc(1, sizeof(Section));
   a->type = ae_section_func;
   a->d.func_def = func_def;
   a->pos = pos;
   return a;
 }
new_section_Stmt_List()
Section* new_section_Stmt_List (Stmt_List list, int pos)
Definition at line 1231 of file absyn.c.
References ae_section_stmt, Section::d, Section::pos, Section::stmt_list, and Section::type.
Referenced by yyparse().
 {
   Section* a = calloc(1, sizeof(Section));
   a->type = ae_section_stmt;
   a->d.stmt_list = list;
   a->pos = pos;
   return a;
 }
new_stmt_from_break()
Stmt* new_stmt_from_break (int pos)
Definition at line 893 of file absyn.c.
References ae_stmt_break, Stmt::d, Stmt::pos, Stmt_Break_::pos, Stmt_Break_::self, Stmt::stmt_break, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_break;
   a->d.stmt_break = calloc(1, sizeof(struct Stmt_Break_));
   a->pos = pos;
   a->d.stmt_break->pos = pos;
   a->d.stmt_break->self = a;
   return a;
 }
new_stmt_from_case()
Stmt* new_stmt_from_case (Expression exp, int pos)
Definition at line 1064 of file absyn.c.
References ae_stmt_case, Stmt::d, Stmt::pos, Stmt_Case_::pos, Stmt_Case_::self, Stmt::stmt_case, Stmt::type, and Stmt_Case_::val.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_case;
   a->d.stmt_case = calloc(1, sizeof(struct Stmt_Case_));
   a->d.stmt_case->val = val;
   a->pos = pos;
   a->d.stmt_case->pos = pos;
   a->d.stmt_case->self = a;
   return a;
 }
new_stmt_from_code()
Stmt* new_stmt_from_code (Stmt_List stmt_list, int pos)
Definition at line 857 of file absyn.c.
References ae_stmt_code, Stmt::d, Stmt::pos, Stmt_Code_::pos, Stmt_Code_::self, Stmt::stmt_code, Stmt_Code_::stmt_list, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_code;
   a->d.stmt_code = calloc(1, sizeof(struct Stmt_Code_));
   a->d.stmt_code->stmt_list = stmt_list;
   a->pos = pos;
   a->d.stmt_code->pos = pos;
   a->d.stmt_code->self = a;
   return a;
 }
new_stmt_from_continue()
Stmt* new_stmt_from_continue (int pos)
Definition at line 904 of file absyn.c.
References ae_stmt_continue, Stmt::d, Stmt::pos, Stmt_Continue_::pos, Stmt_Continue_::self, Stmt::stmt_continue, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_continue;
   a->d.stmt_continue = calloc(1, sizeof(struct Stmt_Continue_));
   a->pos = pos;
   a->d.stmt_continue->pos = pos;
   a->d.stmt_continue->self = a;
   return a;
 }
new_stmt_from_enum()
Stmt* new_stmt_from_enum (ID_List list, m_str type, int pos)
Definition at line 1082 of file absyn.c.
References ae_stmt_enum, Stmt::d, insert_symbol(), Stmt_Enum_::list, new_Vector(), Stmt::pos, Stmt_Enum_::pos, Stmt_Enum_::self, Stmt::stmt_enum, Stmt::type, Stmt_Enum_::values, and Stmt_Enum_::xid.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_enum;
   a->d.stmt_enum = calloc(1, sizeof(struct Stmt_Enum_));
   a->d.stmt_enum->xid = xid ? insert_symbol(xid) : NULL;
   a->d.stmt_enum->list = list;
   a->d.stmt_enum->values = new_Vector();
   a->pos = pos;
   a->d.stmt_enum->pos = pos;
   a->d.stmt_enum->self = a;
   return a;
 }
new_Stmt_from_Expression()
Stmt* new_Stmt_from_Expression (Expression exp, int pos)
Definition at line 848 of file absyn.c.
References ae_stmt_exp, Stmt::d, Stmt::pos, Stmt::stmt_exp, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* stmt = calloc(1, sizeof(Stmt));
   stmt->type = ae_stmt_exp;
   stmt->d.stmt_exp = exp;
   stmt->pos = pos;
   return stmt;
 }
new_stmt_from_for()
Stmt* new_stmt_from_for (Stmt * c1, Stmt * c2, Expression c3, Stmt * body, int pos)
Definition at line 957 of file absyn.c.
References ae_stmt_for, Stmt_For_::body, Stmt_For_::c1, Stmt_For_::c2, Stmt_For_::c3, Stmt::d, Stmt::pos, Stmt_For_::pos, Stmt_For_::self, Stmt::stmt_for, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_for;
   a->d.stmt_for = calloc(1, sizeof(struct Stmt_For_));
   a->d.stmt_for->c1 = c1;
   a->d.stmt_for->c2 = c2;
   a->d.stmt_for->c3 = c3;
   a->d.stmt_for->body = body;
   a->pos = pos;
   a->d.stmt_for->pos = pos;
   a->d.stmt_for->self = a;
   return a;
 }
new_stmt_from_gotolabel()
Stmt* new_stmt_from_gotolabel (m_str xid, m_bool is_label, int pos)
Definition at line 981 of file absyn.c.
References ae_stmt_gotolabel, Stmt::d, insert_symbol(), Stmt_Goto_Label_::is_label, Stmt_Goto_Label_::name, Stmt::pos, Stmt_Goto_Label_::pos, Stmt_Goto_Label_::self, Stmt::stmt_gotolabel, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_gotolabel;
   a->d.stmt_gotolabel = calloc(1, sizeof(struct Stmt_Goto_Label_));
   a->d.stmt_gotolabel->name = insert_symbol( xid );
   a->d.stmt_gotolabel->is_label = is_label;
   a->pos = pos;
   a->d.stmt_gotolabel->pos = pos;
   a->d.stmt_gotolabel->self = a;
   return a;
 }
new_stmt_from_if()
Stmt* new_stmt_from_if (Expression cond, Stmt * if_body, Stmt * else_body, int pos)
Definition at line 1022 of file absyn.c.
References ae_stmt_if, Stmt_If_::cond, Stmt::d, Stmt_If_::else_body, Stmt_If_::if_body, Stmt::pos, Stmt_If_::pos, Stmt_If_::self, Stmt::stmt_if, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_if;
   a->d.stmt_if = calloc(1, sizeof(struct Stmt_If_));
   a->d.stmt_if->cond = cond;
   a->d.stmt_if->if_body = if_body;
   a->d.stmt_if->else_body = else_body;
   a->pos = pos;
   a->d.stmt_if->pos = pos;
   a->d.stmt_if->self = a;
   return a;
 }
new_stmt_from_loop()
Stmt* new_stmt_from_loop (Expression cond, Stmt * body, int pos)
Definition at line 1002 of file absyn.c.
References ae_stmt_loop, Stmt_Loop_::body, Stmt_Loop_::cond, Stmt::d, Stmt::pos, Stmt_Loop_::pos, Stmt_Loop_::self, Stmt::stmt_loop, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_loop;
   a->d.stmt_loop = calloc(1, sizeof(struct Stmt_Loop_));
   a->d.stmt_loop->cond = cond;
   a->d.stmt_loop->body = body;
   a->pos = pos;
   a->d.stmt_loop->pos = pos;
   a->d.stmt_loop->self = a;
   return a;
 }
new_stmt_from_return()
Stmt* new_stmt_from_return (Expression exp, int pos)
Definition at line 875 of file absyn.c.
References ae_stmt_return, Stmt::d, Stmt::pos, Stmt_Return_::pos, Stmt_Return_::self, Stmt::stmt_return, Stmt::type, and Stmt_Return_::val.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_return;
   a->d.stmt_return = calloc(1, sizeof(struct Stmt_Return_));
   a->d.stmt_return->val = exp;
   a->pos = pos;
   a->d.stmt_return->pos = pos;
   a->d.stmt_return->self = a;
   return a;
 }
new_stmt_from_switch()
Stmt* new_stmt_from_switch (Expression val, Stmt * stmt, int pos)
Definition at line 1044 of file absyn.c.
References ae_stmt_switch, Stmt::d, Stmt::pos, Stmt_Switch_::pos, Stmt_Switch_::self, Stmt_Switch_::stmt, Stmt::stmt_switch, Stmt::type, and Stmt_Switch_::val.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_switch;
   a->d.stmt_switch = calloc(1, sizeof(struct Stmt_Switch_));
   a->d.stmt_switch->val = val;
   a->d.stmt_switch->stmt = stmt;
   a->pos = pos;
   a->d.stmt_switch->pos = pos;
   a->d.stmt_switch->self = a;
   return a;
 }
new_stmt_from_Union()
Stmt* new_stmt_from_Union (Union * u, int pos)
Definition at line 1113 of file absyn.c.
References ae_stmt_union, Stmt::d, Stmt::pos, Stmt::stmt_union, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_union;
   a->d.stmt_union = u;
   a->pos = pos;
   return a;
 }
new_stmt_from_until()
Stmt* new_stmt_from_until (Expression cond, Stmt * body, m_bool is_do, int pos)
Definition at line 936 of file absyn.c.
References ae_stmt_until, Stmt_Until_::body, Stmt_Until_::cond, Stmt::d, Stmt_Until_::is_do, Stmt::pos, Stmt_Until_::pos, Stmt_Until_::self, Stmt::stmt_until, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_until;
   a->d.stmt_until = calloc(1, sizeof(struct Stmt_Until_));
   a->d.stmt_until->is_do = 0;
   a->d.stmt_until->cond = cond;
   a->d.stmt_until->body = body;
   a->pos = pos;
   a->d.stmt_until->pos = pos;
   a->d.stmt_until->self = a;
   return a;
 }
new_stmt_from_while()
Stmt* new_stmt_from_while (Expression cond, Stmt * body, m_bool is_do, int pos)
Definition at line 915 of file absyn.c.
References ae_stmt_while, Stmt_While_::body, Stmt_While_::cond, Stmt::d, Stmt_While_::is_do, Stmt::pos, Stmt_While_::pos, Stmt_While_::self, Stmt::stmt_while, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_while;
   a->d.stmt_while = calloc(1, sizeof(struct Stmt_While_));
   a->d.stmt_while->is_do = is_do;
   a->d.stmt_while->cond = cond;
   a->d.stmt_while->body = body;
   a->pos = pos;
   a->d.stmt_while->pos = pos;
   a->d.stmt_while->self = a;
   return a;
 }
new_Stmt_List()
Stmt_List new_Stmt_List (Stmt * stmt, Stmt_List next, int pos)
Definition at line 1212 of file absyn.c.
References Stmt_List_::next, and Stmt_List_::stmt.
Referenced by yyparse().
 {
   Stmt_List list = calloc(1, sizeof(struct Stmt_List_));
   list->stmt = stmt;
   list->next = next;
   return list;
 }
new_Type_Decl()
Type_Decl* new_Type_Decl (ID_List name, int ref, int pos)
Definition at line 74 of file absyn.c.
References Type_Decl::array, Type_Decl::doc, Type_Decl::dot, Type_Decl::pos, Type_Decl::ref, and Type_Decl::xid.
Referenced by emit_Unary(), import_var(), make_dll_arg_list(), make_dll_as_fun(), new_exp_from_unary3(), and yyparse().
 {
   Type_Decl* a = calloc(1, sizeof(Type_Decl));
   a->xid = xid;
   a->ref = ref;
   a->pos = pos;
   a->array = NULL;
   a->dot = NULL;
   a->doc = NULL;
   return a;
 }
new_Type_Decl_from_dot()
Type_Decl* new_Type_Decl_from_dot (Dot_Member * dot, int ref, int pos)
Definition at line 86 of file absyn.c.
References Type_Decl::array, Type_Decl::dot, Type_Decl::pos, Type_Decl::ref, and Type_Decl::xid.
 {
   Type_Decl* a = calloc(1, sizeof(Type_Decl));
   a->xid = NULL;
   a->ref = ref;
   a->pos = pos;
   a->array = NULL;
   a->dot = dot;
   return a;
 }
new_type_list()
Type_List new_type_list (ID_List list, Type_List next, int pos)
Definition at line 1391 of file absyn.c.
References Type_List_::list, Type_List_::next, and Type_List_::pos.
Referenced by mk_type_list(), and yyparse().
 {
   Type_List a = calloc(1,  sizeof(struct Type_List_));
   a->list = list;
   a->next = next;
   a->pos = pos;
   return a;
 }
new_Union()
Union* new_Union (Decl_List l)
Definition at line 1147 of file absyn.c.
References Union::l, malloc(), new_Vector(), Union::s, and Union::v.
Referenced by yyparse().
 {
   Union* a = malloc(sizeof(Union));
   a->l = l;
   a->v = new_Vector();
   a->s = 0;
 //  a->o = 0;
   return a;
 }
new_Var_Decl()
Var_Decl new_Var_Decl (m_str name, Array_Sub array, int pos)
Definition at line 20 of file absyn.c.
References Var_Decl_::array, insert_symbol(), Var_Decl_::pos, and Var_Decl_::xid.
Referenced by import_var(), make_dll_arg_list(), and yyparse().
 {
   Var_Decl a = calloc(1, sizeof(struct Var_Decl_));
   a->xid = insert_symbol(name);
   a->array = array;
   a->pos = pos;
   return a;
 }
new_Var_Decl_List()
Var_Decl_List new_Var_Decl_List (Var_Decl decl, Var_Decl_List list, int pos)
Definition at line 53 of file absyn.c.
References Var_Decl_List_::doc, Var_Decl_List_::next, Var_Decl_List_::pos, and Var_Decl_List_::self.
Referenced by import_var(), and yyparse().
 {
   Var_Decl_List a = calloc(1, sizeof(struct Var_Decl_List_));
   a->self = decl;
   a->next = list;
   a->pos = pos;
   a->doc = NULL;
   return a;
 }
new_Vec()
Vec new_Vec (Expression e, int pos)
Definition at line 502 of file absyn.c.
References Vec_::args, Expression_::next, Vec_::numdims, and Vec_::pos.
Referenced by yyparse().
 {
   Vec a = calloc(1, sizeof(struct Vec_));
   a->args = e;
   while(e) {
     a->numdims++;
     e = e->next;
   }
   a->pos = pos;
   return a;
 }
parse()
Ast parse (m_str)
Definition at line 2976 of file lexer.c.
References Ast_::doc, err_msg(), free_Ast(), free_Vector(), malloc(), map_set(), minimal_get_extra(), minimal_lex_destroy(), minimal_lex_init(), minimal_parse(), minimal_set_extra(), minimal_set_in(), new_Vector(), PARSE_, MyArg::scanner, strcat(), vector_front(), and vector_remove().
Referenced by compile(), and SFUN().
 {
   Ast    ast  = NULL;
   FILE*  file = NULL;
   MyArg arg;
   minimal_lex_init(&arg.scanner);
   minimal_set_extra(&arg, arg.scanner);
 //  minimal_lex_init_extra(&arg, arg.scanner);
   map_set(scan_map, (vtype)arg.scanner, (vtype)&arg);
   map_set(scan_map, (vtype)minimal_get_extra(arg.scanner), (vtype)&arg);
   arg.line = 1; arg.pos  = 0; arg.doc = new_Vector();
   char c[1025];
   memset(c, 0, 1025);
   strncat(c, filename, 1024);
   if(!(file = fopen(c, "r")))
   {
     err_msg(PARSE_, 0, "error while opening file '%s'.", filename);
     return NULL;
   }
 //  arg.fd = fileno(file);
   arg.file = file;
   arg.filename = filename;
   minimal_set_in(file, arg.scanner);
   if(minimal_parse(&arg))
   {
     free_Ast(ast);
     free_Vector(arg.doc);
     minimal_lex_destroy(arg.scanner);
     return NULL;
   }
   filename = c;
   ast = arg.ast;
   if(vector_front(arg.doc))
   {
     ast->doc = malloc(sizeof(char));
     memset(ast->doc, 0, 1);
   }
   while(vector_front(arg.doc))
   {
     strcat(ast->doc, (m_str)vector_front(arg.doc));
     vector_remove(arg.doc, 0);
   }
   free_Vector(arg.doc);
   fclose(file);
   minimal_lex_destroy(arg.scanner);
   return ast;
 }
prepend_array_sub()
Array_Sub prepend_array_sub (Array_Sub array, Expression exp, int pos)
Definition at line 107 of file absyn.c.
References Array_Sub_::depth, Array_Sub_::err_num, Array_Sub_::err_pos, Array_Sub_::exp_list, free_Expression(), Expression_::next, and Expression_::pos.
Referenced by make_dll_arg_list(), make_dll_as_fun(), and yyparse().
 {
   if(a->err_num)
     goto error;
   if(exp && exp->next) {
     a->err_num = 1;
     a->err_pos = exp->pos;
     goto error;
   }
   if((exp && !a->exp_list) || (!exp && a->exp_list)) {
     a->err_num = 2;
     a->err_pos = pos;
     goto error;
   }
   if(exp) {
     exp->next = a->exp_list;
     a->exp_list = exp;
   }
   a->depth++;
   return a;
 error:
   free_Expression(exp);
   return a;
 }
prepend_class_body()
Class_Body prepend_class_body (Section * section, Class_Body body, int pos)
Definition at line 1343 of file absyn.c.
References new_class_body(), Class_Body_::next, and Class_Body_::pos.
Referenced by yyparse().
 {
   Class_Body a = new_class_body(section, pos);
   a->next = body;
   a->pos = pos;
   return a;
 }
prepend_Expression()
Expression prepend_Expression (Expression exp, Expression next, int pos)
Definition at line 752 of file absyn.c.
References Expression_::next.
Referenced by yyparse().
 {
   exp->next = next;
   return exp;
 }
prepend_id_list()
ID_List prepend_id_list (const m_str xid, ID_List list, int pos)
Definition at line 1369 of file absyn.c.
References new_id_list(), ID_List_::next, and ID_List_::pos.
Referenced by mk_type_list(), str2list(), and yyparse().
 {
   ID_List a = new_id_list(xid, pos);
   a->next = list;
   a->pos = pos;
   return a;
 }
scan1_Func_Def()
m_bool scan1_Func_Def (Env env, Func_Def f)
Definition at line 565 of file scan1.c.
References ae_func_spec_dtor, ae_func_spec_op, ae_key_abstract, Func_Def_::arg_list, Type_Decl::array, CHECK_BB, Env_::class_def, Func_Def_::code, Env_::curr, Stmt::d, Type_::def, Array_Sub_::depth, err_msg(), Array_Sub_::exp_list, find_type(), free(), Class_Def_::iface, Func_Def_::name, name2op(), new_array_type(), Arg_List_::next, Array_Sub_::pos, Arg_List_::pos, Func_Def_::pos, Type_Decl::ref, Func_Def_::ret_type, S_name(), SCAN1_, scan1_Stmt_Code(), Func_Def_::spec, Func_Def_::static_decl, Stmt::stmt_code, t_array, Arg_List_::type, Arg_List_::type_decl, Func_Def_::type_decl, type_path(), Func_Def_::types, verify_array(), Type_Decl::xid, and ID_List_::xid.
Referenced by scan1_Ast(), and scan1_Class_Def().
 {
 #ifdef DEBUG_SCAN1
   debug_msg("scan1", "func def");
 #endif
   if(f->spec == ae_func_spec_dtor && !env->class_def) {
     err_msg(SCAN1_, f->pos, "dtor must be in class def!!");
     goto error;
   }
   if(f->types)  // templating. nothing to be done here
     return 1;
   if(env->class_def && env->class_def->def && env->class_def->def->iface)
     f->static_decl = ae_key_abstract;
   Arg_List arg_list = NULL;
   m_uint count = 0;
   f->ret_type = find_type(env, f->type_decl->xid);
   if(!f->ret_type) {
     err_msg(SCAN1_, f->pos, "scan1: unknown return type '%s' of func '%s'",
             S_name(f->type_decl->xid->xid), S_name(f->name));
 //free(f);
 //    free_Func_Def(f);
     return -1;
 //    goto error;
   }
   // check if array
   if(f->type_decl->array) {
     CHECK_BB(verify_array(f->type_decl->array))
     Type t = NULL;
     Type t2 = f->ret_type;
     // should be partial and empty []
     if(f->type_decl->array->exp_list) {
       err_msg(SCAN1_, f->type_decl->array->pos, "in function '%s':", S_name(f->name) );
       err_msg(SCAN1_, f->type_decl->array->pos, "return array type must be defined with empty []'s" );
       goto error;
     }
     // create the new array type
     t = new_array_type(env, &t_array, f->type_decl->array->depth, t2, env->curr);
     // TODO: verify
     f->type_decl->ref = 1;
     f->ret_type = t;
     /*    SAFE_REF_ASSIGN( f->ret_type, t );*/
   }
   arg_list = f->arg_list;
   count = 1;
   while(arg_list) {
     arg_list->type = find_type(env, arg_list->type_decl->xid);
 // check this
     if(!arg_list->type)
       /*if(!arg_list->type && !(arg_list->type = namespace_lookup_type(env->curr, f->type_decl->xid->xid, 1)))*/
       /*if(!arg_list->type || !(arg_list->type = namespace_lookup_type(env->curr, f->type_decl->xid->xid, 1)))*/
     {
       m_str path = type_path(arg_list->type_decl->xid);
       err_msg(SCAN1_, arg_list->pos, "'%s' unknown type in argument %i of func %s", path, count, S_name(f->name));
       free(path);
       goto error;
     }
     count++;
     arg_list = arg_list->next;
   }
   // if operator,
   if(f->spec == ae_func_spec_op) {
     // check argument number
     if(count > 3 || count == 1) {
       err_msg(SCAN1_, f->pos, "operators can only have one or two arguments\n");
       goto error;
     }
     // and name
     if(name2op(S_name(f->name)) < 0) {
       err_msg(SCAN1_, f->pos, "%s is not a valid operator name\n", S_name(f->name));
       goto error;
     }
   }
   if(f->code && scan1_Stmt_Code(env, f->code->d.stmt_code, 0) < 0) {
     err_msg(SCAN1_, f->pos, "...in function '%s'\n", S_name(f->name));
     goto error;
   }
   return 1;
 error:
 //  free_Func_Def(f);
   return -1;
 }
scan2_Func_Def()
m_bool scan2_Func_Def (Env env, Func_Def f)
Definition at line 687 of file scan2.c.
References add_binary_op(), add_ref(), ae_func_builtin, ae_func_spec_dtor, ae_func_spec_op, ae_key_static, Func_Def_::arg_list, Var_Decl_::array, CHECK_BB, Value_::checked, Env_::class_def, Func_::code, Func_Def_::code, Env_::context, context_add_func(), Env_::curr, Stmt::d, Func_::def, Array_Sub_::depth, Func_Def_::dl_func_ptr, Func_::doc, Type_Decl::doc, e_type_obj, err_msg(), Array_Sub_::exp_list, find_type(), free(), free_Value(), NameSpace_::func, Env_::func, Type_::func, Func_Def_::func, Value_::func_num_overloads, Value_::func_ref, insert_symbol(), Value_::is_const, Value_::is_context_global, Func_::is_dtor, Func_::is_member, Value_::is_member, Func_Def_::is_template, Func_Def_::is_variadic, isa(), isprim(), isres(), Value_::m_type, Func_::name, NameSpace_::name, Value_::name, Type_::name, Func_Def_::name, name2op(), namespace_add_func(), namespace_add_value(), namespace_lookup_value(), namespace_pop_value(), namespace_push_value(), VM_Code_::native_func, VM_Code_::need_this, new_array_type(), new_Func(), new_Value(), new_VM_Code(), new_VM_Object(), Func_::next, Arg_List_::next, Func_::obj, Value_::obj, Type_::obj, Value_::offset, Value_::owner, Value_::owner_class, Type_::parent, Type_Decl::pos, Arg_List_::pos, Func_Def_::pos, Type_Decl::ref, rem_ref(), Func_Def_::ret_type, S_name(), Func_Def_::s_type, SCAN2_, scan2_Stmt_Code(), scope_rem(), Type_::size, Func_Def_::spec, Func_Def_::stack_depth, Func_Def_::static_decl, Stmt::stmt_code, t_array, t_function, te_function, Arg_List_::type, Arg_List_::type_decl, Func_Def_::type_decl, Func_Def_::types, Var_Decl_::value, Func_::value_ref, Arg_List_::var_decl, verify_array(), Type_::xid, Var_Decl_::xid, and Type_Decl::xid.
Referenced by scan2_Ast(), and scan2_Class_Def().
 {
   Type     type     = NULL;
   Value    value    = NULL;
   Func     func     = NULL;
   Value    overload = NULL;
   Arg_List arg_list = NULL;
   Value    v;
   m_str func_name = S_name(f->name);
   m_str orig_name = func_name;
   m_uint count = 0;
   if(env->func) {
     err_msg(SCAN2_, f->pos, "nested function definitions are not (yet) allowed");
     goto error;
   }
   if(f->types) {
     func = new_Func(func_name, f);
     overload = namespace_lookup_value(env->curr,  f->name, 0);
     if(overload)
       func->next = overload->func_ref->next;
     func->is_member = (env->class_def && (f->static_decl != ae_key_static));
     value = new_Value(env->context, &t_function, func_name);
     value->is_const = 1;
     value->owner = env->curr;
     value->owner_class = env->class_def;
     value->is_member = func->is_member;
     value->is_context_global = (env->class_def == NULL);
     value->func_ref = func;
     add_ref(value->func_ref->obj);
     func->value_ref = value;
     add_ref(value->obj);
     f->func = func;
     value->checked = 1;
     if(overload)
       overload->func_num_overloads++;
     else
       namespace_add_value(env->curr, insert_symbol(orig_name), value);
     char name[256];
     sprintf(name, "%s<template>@%li@%s", S_name(f->name),
             overload ? overload->func_num_overloads : 0, env->curr->name);
     namespace_add_value(env->curr, insert_symbol(name), value);
     return 1;
   }
   // overload
   overload = namespace_lookup_value(env->curr,  f->name, 0);
   if(overload) {
     if(isa(overload->m_type, &t_function) < 0) {
       err_msg(SCAN2_, f->pos, "function name '%s' is already used by another value", S_name(f->name));
       goto error;
     } else {
       if(!overload->func_ref) {
         err_msg(SCAN2_, f->pos, "internal error: missing function '%s'", overload->name );
         return -1;
       }
     }
   }
   char tmp[256];
   memset(tmp, 0, 256);
   m_uint len = strlen(func_name) + strlen("0") + strlen(env->curr->name) + 3;
   if(overload) {
     len = strlen(func_name) + ((overload->func_num_overloads + 1) % 10) + strlen(env->curr->name) + 3;
     snprintf(tmp, len + 1, "%s@%li@%s", func_name, ++overload->func_num_overloads, env->curr->name);
   } else
     snprintf(tmp, len + 1, "%s@0@%s", func_name, env->curr->name);
   func_name = strdup(tmp);
   func = new_Func(func_name, f);
 //  func = new_Func(func_name, tmp);
   func->is_member = (env->class_def && (f->static_decl != ae_key_static));
   if(f->s_type == ae_func_builtin) { // actual builtin func import
     func->code = new_VM_Code(NULL, func->def->stack_depth, 1, S_name(f->name), "builtin func code");
     func->code->need_this = func->is_member;
     func->code->native_func = (m_uint)func->def->dl_func_ptr;
   }
   type = calloc(1, sizeof(struct Type_));
   type->xid = te_function;
   type->name = strdup(tmp);
   type->parent = &t_function;
   type->size = SZ_INT;
   type->func = func;
   type->obj = new_VM_Object(e_type_obj);
   value = new_Value(env->context, type, func_name);
   value->is_const = 1;
   value->owner = env->curr;
   value->owner_class = env->class_def;
   value->is_member = func->is_member;
   value->is_context_global = (env->class_def == NULL);
   value->func_ref = func;
   add_ref(value->func_ref->obj);
   func->value_ref = value;
   f->func = func;
   add_ref(f->func->obj);
   if(overload) {
     func->next = overload->func_ref->next;
     overload->func_ref->next = func;
   }
   if(!f->ret_type) // template return value
     f->ret_type = find_type(env, f->type_decl->xid);
   if(isprim(f->ret_type) > 0 && f->type_decl->ref) { // TODO: string
     err_msg(SCAN2_,  f->type_decl->pos,
             "FUNC cannot declare references (@) of primitive type '%s'...\n", f->ret_type->name );
     err_msg(SCAN2_, f->type_decl->pos,
             "...(primitive types: 'int', 'float', 'time', 'dur')" );
     goto error;
   }
   arg_list = f->arg_list;
   count = 1;
   f->stack_depth = func->is_member ? SZ_INT : 0;
   namespace_push_value(env->curr);
   while(arg_list) {
     if(!arg_list->type) // template
       arg_list->type = find_type(env, arg_list->type_decl->xid);
     if(!arg_list->type->size) {
       err_msg(SCAN2_, arg_list->pos, "cannot declare variables of size '0' (i.e. 'void')...");
       namespace_pop_value(env->curr);
       goto error;
     }
     // check if reserved
     if(isres(env, arg_list->var_decl->xid, arg_list->pos) > 0) {
       err_msg(SCAN2_,  arg_list->pos, "in function '%s'", S_name(f->name) );
       namespace_pop_value(env->curr);
       goto error;
     }
     // primitive
     if( (isprim( arg_list->type ) > 0)
         && arg_list->type_decl->ref ) { // TODO: string
       err_msg(SCAN2_, arg_list->type_decl->pos,
               "cannot declare references (@) of primitive type '%s'...",
               arg_list->type->name);
       err_msg(SCAN2_, arg_list->type_decl->pos,
               "...(primitive types: 'int', 'float', 'time', 'dur')" );
       namespace_pop_value(env->curr);
       goto error;
     }
     if(arg_list->var_decl->array) {
       CHECK_BB(verify_array(arg_list->var_decl->array))
       Type t = arg_list->type;
       Type t2 = t;
       if(arg_list->var_decl->array->exp_list) { // should be partial and empty []
         err_msg(SCAN2_, arg_list->pos, "in function '%s':", S_name(f->name) );
         err_msg(SCAN2_, arg_list->pos, "argument %i '%s' must be defined with empty []'s",
                 count, S_name(arg_list->var_decl->xid) );
         namespace_pop_value(env->curr);
         goto error;
       }
       // create the new array type
       t = new_array_type(env, &t_array, arg_list->var_decl->array->depth, t2, env->curr);
       // set ref
       arg_list->type_decl->ref = 1;
       arg_list->type = t;
       /*      SAFE_REF_ASSIGN( arg_list->type, t );*/
     }
     // make new value
     v = calloc(1, sizeof(struct Value_));
     v->m_type = arg_list->type;
     //v->doc = arg_list->doc;
     v->name = S_name(arg_list->var_decl->xid);
     // remember the owner
     v->owner = env->curr;
     // function args not owned
     // v->owner_class = NULL;
     //  v->is_member = 0;
     namespace_add_value(env->curr, arg_list->var_decl->xid, v);
     // stack
     v->offset = f->stack_depth;
     f->stack_depth += arg_list->type->size;
     // remember
     if(arg_list->var_decl->value)
       free_Value(arg_list->var_decl->value);
     arg_list->var_decl->value = v;
     // count
     count++;
     // next arg
     arg_list = arg_list->next;
   }
   namespace_pop_value(env->curr);
   if(f->is_variadic)
     f->stack_depth += SZ_INT;
   else if(f->spec == ae_func_spec_op) {
     m_bool ret;
     m_str str = strdup(S_name(f->name));
     str = strsep(&str, "@");
     ret = name2op(str);
     free(str);
     if(ret == -1) {
       err_msg(SCAN2_, f->pos, "Invalid operator.");
       return -1;
     } else
       ret = add_binary_op(env, ret, f->arg_list->var_decl->value->m_type, f->arg_list->next->var_decl->value->m_type, f->ret_type, NULL, 1, 0);
     if(!env->class_def)
       context_add_func(env->context, func, func->obj);
     return ret;
   }
   value->checked = 1;
   // while making doc
   if(!env->class_def)
     context_add_func(env->context, func, func->obj);
   if(!overload)
     namespace_add_value(env->curr, insert_symbol(orig_name), value);
   else {
     namespace_add_value(env->curr, insert_symbol(func->name), value);
     if(overload->func_ref->def->ret_type) // template func don't check ret_type case
       if(!f->is_template) // template func don't check ret_type case
         if(f->ret_type->xid != overload->func_ref->def->ret_type->xid) {
           err_msg(SCAN2_,  f->pos, "function signatures differ in return type... '%s' and '%s'",
                   f->ret_type->name, overload->func_ref->def->ret_type->name );
           if(env->class_def)
             err_msg(SCAN2_, f->pos,
                     "function '%s.%s' matches '%s.%s' but cannot overload...",
                     env->class_def->name, S_name(f->name),
                     value->owner_class->name, S_name(f->name) );
 //return -1;
 //          goto error;
         }
   }
   namespace_add_func( env->curr, insert_symbol(func->name), func ); // template. is it necessary ?
   env->func = func;
   namespace_push_value(env->curr);
   if(f->code && scan2_Stmt_Code(env, f->code->d.stmt_code, 0) < 0) {
     err_msg(SCAN2_, f->pos, "...in function '%s'", S_name(f->name) );
     goto error;
   }
   namespace_pop_value(env->curr);
   env->func = NULL;
   if(f->spec == ae_func_spec_dtor) {
     f->func->is_dtor = 1;
     add_ref(f->func->value_ref->obj);
   }
   if(f->type_decl->doc)
     func->doc = f->type_decl->doc;
   return 1;
 error:
   if(func) {
     env->func = NULL;
     scope_rem(env->curr->func, f->name);
     func->def = NULL;
     f->func = NULL;
     rem_ref(func->obj, func);
   }
   if(value) {
     free(value->m_type->name);
     free(value->name);
     rem_ref(value->m_type->obj, value->m_type);
     rem_ref(value->obj, value);
   }
   return -1;
 }
Variable Documentation
scan_map
Map scan_map
Referenced by append_doc(), get_doc(), get_pos(), if(), main(), and newline().