Gwion dev-docs: eval/absyn.c File Reference
absyn.c File Reference
#include <stdlib.h>
#include "absyn.h"
#include "func.h"
Functions
void free_Expression (Expression exp)
void free_Arg_List (Arg_List a)
void free_Stmt (Stmt *a)
void free_Stmt_List (Stmt_List a)
void free_Stmt_Code (Stmt_Code a)
void free_Stmt_Return (Stmt_Return a)
static void free_Section ()
void free_Type_List (Type_List a)
int get_pos (void *data)
Var_Decl new_Var_Decl (m_str name, Array_Sub array, int pos)
void free_Array_Sub (Array_Sub a)
void free_Var_Decl (Var_Decl a)
Var_Decl_List new_Var_Decl_List (Var_Decl decl, Var_Decl_List list, int pos)
void free_Var_Decl_List (Var_Decl_List a)
Type_Decl * new_Type_Decl (ID_List xid, int ref, int pos)
Type_Decl * new_Type_Decl_from_dot (Dot_Member *dot, int ref, int pos)
Array_Sub new_array_sub (Expression exp, int pos)
Array_Sub prepend_array_sub (Array_Sub a, Expression exp, int pos)
Type_Decl * add_type_decl_array (Type_Decl *a, Array_Sub array, int pos)
Expression new_Array (Expression base, Array_Sub indices, int pos)
void free_Array_Expression (Array *a)
void free_Type_Decl (Type_Decl *a)
Expression new_Decl_Expression (Type_Decl *type, Var_Decl_List list, m_bool is_static, int pos)
void free_Decl_Expression (Decl_Expression *a)
Expression new_Binary_Expression (Expression lhs, Operator op, Expression rhs, int pos)
void free_Binary_Expression (Binary_Expression *binary)
Expression new_Cast_Expression (Type_Decl *type, Expression exp, int pos)
void free_Cast_Expression (Cast_Expression *a)
Expression new_Postfix_Expression (Expression exp, Operator op, int pos)
void free_Postfix_Expression (Postfix_Expression *postfix)
Expression new_Exp_Dur (Expression base, Expression unit, int pos)
void free_Dur_Expression (Exp_Dur *a)
Expression new_Primary_Expression_from_int (long i, int pos)
Expression new_Primary_Expression_from_float (m_float num, int pos)
Expression new_Primary_Expression_from_string (m_str s, int pos)
Expression new_Primary_Expression_from_nil (int pos)
Expression new_Primary_Expression_from_ID (m_str s, int pos)
Expression new_Hack_Expression (Expression exp, int pos)
Complex * new_complex (Expression re, int pos)
void free_complex (Complex *a)
Expression new_exp_from_char (c_str chr, int pos)
Expression new_exp_from_array_lit (Array_Sub exp_list, int pos)
Expression new_exp_from_complex (Complex *exp, int pos)
Expression new_exp_from_polar (Polar *exp, int pos)
Polar * new_polar (Expression mod, int pos)
void free_polar (Polar *a)
Vec new_Vec (Expression e, int pos)
void free_Vec (Vec a)
Expression new_exp_from_vec (Vec exp, int pos)
Expression new_exp_from_unary (Operator oper, Expression exp, int pos)
Expression new_exp_from_unary2 (Operator oper, Type_Decl *type, Array_Sub array, int pos)
void free_Unary_Expression (Unary_Expression *a)
Expression new_exp_from_unary3 (Operator oper, Stmt *code, int pos)
Expression new_If_Expression (Expression cond, Expression if_exp, Expression else_exp, int pos)
void free_If_Expression (If_Expression *a)
Func_Def new_Func_Def (ae_Keyword func_decl, ae_Keyword static_decl, Type_Decl *type_decl, m_str name, Arg_List arg_list, Stmt *code, int pos)
void free_Func_Def (Func_Def a)
Stmt * new_Func_Ptr_Stmt (ae_Keyword key, m_str xid, Type_Decl *decl, Arg_List args, int pos)
void free_Stmt_Func_Ptr (Func_Ptr *a)
Expression new_Func_Call (Expression base, Expression args, int pos)
void free_Func_Call (Func_Call *a)
Expression new_exp_from_member_dot (Expression base, m_str xid, int pos)
void free_Dot_Member_Expression (Dot_Member *dot)
Expression prepend_Expression (Expression exp, Expression next, int pos)
void free_Primary_Expression (Primary_Expression *a)
Arg_List new_Arg_List (Type_Decl *type_decl, Var_Decl var_decl, Arg_List arg_list, int pos)
Stmt * new_Stmt_from_Expression (Expression exp, int pos)
Stmt * new_stmt_from_code (Stmt_List stmt_list, int pos)
Stmt * new_stmt_from_return (Expression exp, int pos)
Stmt * new_stmt_from_break (int pos)
Stmt * new_stmt_from_continue (int pos)
Stmt * new_stmt_from_while (Expression cond, Stmt *body, m_bool is_do, int pos)
void free_Stmt_While (Stmt_While a)
Stmt * new_stmt_from_until (Expression cond, Stmt *body, m_bool is_do, int pos)
void free_Stmt_Until (Stmt_Until a)
Stmt * new_stmt_from_for (Stmt *c1, Stmt *c2, Expression c3, Stmt *body, int pos)
void free_Stmt_For (Stmt_For a)
Stmt * new_stmt_from_gotolabel (m_str xid, m_bool is_label, int pos)
void free_Stmt_GotoLabel (Stmt_Goto_Label a)
Stmt * new_stmt_from_loop (Expression cond, Stmt *body, int pos)
void free_Stmt_Loop (Stmt_Loop a)
Stmt * new_stmt_from_if (Expression cond, Stmt *if_body, Stmt *else_body, int pos)
void free_Stmt_If (Stmt_If a)
Stmt * new_stmt_from_switch (Expression val, Stmt *stmt, int pos)
void free_Stmt_Switch (Stmt_Switch a)
Stmt * new_stmt_from_case (Expression val, int pos)
void free_Stmt_Case (Stmt_Case a)
Stmt * new_stmt_from_enum (ID_List list, m_str xid, int pos)
void free_Stmt_Enum (Stmt_Enum a)
Stmt * new_stmt_from_Union (Union *u, int pos)
Decl_List new_Decl_List (Decl_Expression *d, Decl_List l)
void free_Decl_List (Decl_List a)
void free_Stmt_Union (Union *a)
Union * new_Union (Decl_List l)
Stmt_List new_Stmt_List (Stmt *stmt, Stmt_List next, int pos)
Section * new_section_Stmt_List (Stmt_List list, int pos)
Section * new_section_Func_Def (Func_Def func_def, int pos)
void free_Class_Def (Class_Def a)
void free_Section (Section *section)
Class_Def new_class_def (ae_Keyword class_decl, ID_List name, Class_Ext ext, Class_Body body, int pos)
Class_Def new_iface_def (ae_Keyword class_decl, ID_List name, Class_Ext ext, Class_Body body, int pos)
Class_Body new_class_body (Section *section, int pos)
Class_Body prepend_class_body (Section *section, Class_Body body, int pos)
Class_Ext new_class_ext (ID_List extend_id, ID_List impl_list, int pos)
ID_List new_id_list (const m_str xid, int pos)
ID_List prepend_id_list (const m_str xid, ID_List list, int pos)
void free_ID_List (ID_List a)
Type_List new_type_list (ID_List list, Type_List next, int pos)
Section * new_section_Class_Def (Class_Def class_def, int pos)
Ast new_Ast (Section *section, Ast next, int pos)
void free_Ast (Ast prog)
Function Documentation
add_type_decl_array()
Type_Decl* add_type_decl_array (Type_Decl * a, Array_Sub array, int pos)
Definition at line 134 of file absyn.c.
References Type_Decl::array.
Referenced by make_dll_as_fun(), and yyparse().
 {
   a->array = array;
   return a;
 }
free_Arg_List()
void free_Arg_List (Arg_List a)
Definition at line 832 of file absyn.c.
References Type_::array_type, free(), free_Arg_List(), free_Type_Decl(), free_Var_Decl(), Value_::m_type, Arg_List_::next, Type_::obj, Arg_List_::type_decl, Var_Decl_::value, and Arg_List_::var_decl.
Referenced by free_Arg_List(), free_Func_Def(), free_Section(), free_Stmt_Func_Ptr(), and make_dll_arg_list().
 {
   if(a->next)
     free_Arg_List(a->next);
   free_Type_Decl(a->type_decl);
   if(a->var_decl->value) {
     if(a->var_decl->value->m_type->array_type) {
       free(a->var_decl->value->m_type->obj);
       free(a->var_decl->value->m_type);
     }
   }
   free_Var_Decl(a->var_decl);
   free(a);
 }
free_Array_Expression()
void free_Array_Expression (Array * a)
Definition at line 156 of file absyn.c.
References Array::base, free(), free_Array_Sub(), free_Expression(), and Array::indices.
Referenced by free_Expression().
 {
   free_Array_Sub(a->indices);
   free_Expression(a->base);
   free(a);
 }
free_Array_Sub()
void free_Array_Sub (Array_Sub a)
Definition at line 29 of file absyn.c.
References Array_Sub_::exp_list, free(), and free_Expression().
Referenced by check_Unary(), free_Array_Expression(), free_Primary_Expression(), and free_Var_Decl().
 {
   free_Expression(a->exp_list);
   free(a);
 }
free_Ast()
void free_Ast (Ast prog)
Definition at line 1433 of file absyn.c.
References free(), free_Section(), Ast_::next, and Ast_::section.
Referenced by compile(), emit_Ast(), parse(), SFUN(), and type_engine_check_prog().
 {
 #ifdef DEBUG_AST
   debug_msg("ast", "free AST");
 #endif
   Ast tmp, ast = prog;
   while(ast) {
     tmp = ast;
     ast = ast->next;
     free_Section(tmp->section);
     free(tmp);
   }
 }
free_Binary_Expression()
void free_Binary_Expression (Binary_Expression * binary)
Definition at line 214 of file absyn.c.
References free(), free_Expression(), Binary_Expression::lhs, and Binary_Expression::rhs.
Referenced by free_Expression().
 {
   free_Expression(binary->lhs);
   free_Expression(binary->rhs);
   free(binary);
 }
free_Cast_Expression()
void free_Cast_Expression (Cast_Expression * a)
Definition at line 237 of file absyn.c.
References Cast_Expression::exp, free(), free_Expression(), free_Type_Decl(), and Cast_Expression::type.
Referenced by free_Expression().
 {
   free_Type_Decl(a->type);
   free_Expression(a->exp);
   free(a);
 }
free_Class_Def()
void free_Class_Def (Class_Def a)
Definition at line 1249 of file absyn.c.
References Class_Def_::body, Class_Def_::ext, Class_Ext_::extend_id, free(), free_ID_List(), free_Section(), Class_Ext_::impl_list, Class_Def_::name, Class_Body_::next, and Class_Body_::section.
Referenced by free_Section().
 {
   if(a->ext) {
     free_ID_List(a->ext->extend_id);
     if(a->ext->impl_list)
       free_ID_List(a->ext->impl_list);
     free(a->ext);
   }
   Class_Body tmp, b = a->body;
   while(b) {
     tmp = b;
     if(b->section)
       free_Section(b->section);
     b = b->next;
     free(tmp);
   }
   free_ID_List(a->name);
   free(a);
 }
free_complex()
void free_complex (Complex * a)
Definition at line 398 of file absyn.c.
References free(), free_Expression(), and Complex::re.
Referenced by free_Primary_Expression().
 {
   free_Expression(a->re);
   free(a);
 }
free_Decl_Expression()
void free_Decl_Expression (Decl_Expression * a)
Definition at line 189 of file absyn.c.
References free(), free_Type_Decl(), free_Var_Decl_List(), Decl_Expression::list, and Decl_Expression::type.
Referenced by free_Decl_List(), and free_Expression().
 {
   free_Type_Decl(a->type);
   free_Var_Decl_List(a->list);
   free(a);
 }
free_Decl_List()
void free_Decl_List (Decl_List a)
Definition at line 1131 of file absyn.c.
References free(), free_Decl_Expression(), Decl_List_::next, and Decl_List_::self.
Referenced by free_Stmt_Union().
 {
   if(a->next)
     free_Decl_List(a->next);
   if(a->self)
     free_Decl_Expression(a->self);
   free(a);
 }
free_Dot_Member_Expression()
void free_Dot_Member_Expression (Dot_Member * dot)
Definition at line 745 of file absyn.c.
References Dot_Member::base, free(), and free_Expression().
Referenced by free_Expression().
 {
   if(dot->base)
     free_Expression(dot->base);
   free(dot);
 }
free_Dur_Expression()
void free_Dur_Expression (Exp_Dur * a)
Definition at line 282 of file absyn.c.
References Exp_Dur::base, free(), free_Expression(), and Exp_Dur::unit.
Referenced by free_Expression().
 {
   free_Expression(a->base);
   free_Expression(a->unit);
   free(a);
 }
free_Expression()
void free_Expression (Expression exp)
Definition at line 773 of file absyn.c.
References Array_Expression_type, Binary_Expression_type, Cast_Expression_type, Expression_::d, Decl_Expression_type, Dot_Member_type, Dur_Expression_type, Expression_::exp_array, Expression_::exp_binary, Expression_::exp_cast, Expression_::exp_decl, Expression_::exp_dot, Expression_::exp_dur, Expression_::exp_func, Expression_::exp_if, Expression_::exp_postfix, Expression_::exp_primary, Expression_::exp_type, Expression_::exp_unary, free(), free_Array_Expression(), free_Binary_Expression(), free_Cast_Expression(), free_Decl_Expression(), free_Dot_Member_Expression(), free_Dur_Expression(), free_Func_Call(), free_If_Expression(), free_Postfix_Expression(), free_Primary_Expression(), free_Unary_Expression(), Func_Call_type, If_Expression_type, Expression_::next, Postfix_Expression_type, Primary_Expression_type, and Unary_Expression_type.
Referenced by emit_symbol(), free_Array_Expression(), free_Array_Sub(), free_Binary_Expression(), free_Cast_Expression(), free_complex(), free_Dot_Member_Expression(), free_Dur_Expression(), free_Func_Call(), free_If_Expression(), free_polar(), free_Postfix_Expression(), free_Primary_Expression(), free_Stmt(), free_Stmt_Case(), free_Stmt_For(), free_Stmt_If(), free_Stmt_Loop(), free_Stmt_Return(), free_Stmt_Switch(), free_Stmt_Until(), free_Stmt_While(), free_Unary_Expression(), free_Vec(), import_var(), and prepend_array_sub().
 {
   Expression tmp, curr = exp;
   while(curr) {
     switch(curr->exp_type) {
     case Decl_Expression_type:
       free_Decl_Expression(curr->d.exp_decl);
       break;
     case Binary_Expression_type:
       free_Binary_Expression(curr->d.exp_binary);
       break;
     case Unary_Expression_type:
       free_Unary_Expression(curr->d.exp_unary);
       break;
     case Primary_Expression_type:
       free_Primary_Expression(curr->d.exp_primary);
       break;
     case Cast_Expression_type:
       free_Cast_Expression(curr->d.exp_cast);
       break;
     case Postfix_Expression_type:
       free_Postfix_Expression(curr->d.exp_postfix);
       break;
     case Func_Call_type:
       free_Func_Call(curr->d.exp_func);
       break;
     case Array_Expression_type:
       free_Array_Expression(curr->d.exp_array);
       break;
     case If_Expression_type:
       free_If_Expression(curr->d.exp_if);
       break;
     case Dot_Member_type:
       free_Dot_Member_Expression(curr->d.exp_dot);
       break;
     case Dur_Expression_type:
       free_Dur_Expression(curr->d.exp_dur);
       break;
     default:
       printf("free Expression: unhandled exp type %i\n", curr->exp_type);
       break;
     }
     tmp = curr;
     curr = curr->next;
     free(tmp);
   }
 }
free_Func_Call()
void free_Func_Call (Func_Call * a)
Definition at line 717 of file absyn.c.
References Func_Call::args, free(), free_Expression(), free_Type_List(), Func_Call::func, and Func_Call::types.
Referenced by free_Expression().
 {
   if(a->types)
     free_Type_List(a->types);
 //  if(a->base)
 //    free_Type_List(a->base);
   free_Expression(a->func);
   if(a->args)
     free_Expression(a->args);
   free(a);
 }
free_Func_Def()
void free_Func_Def (Func_Def a)
Definition at line 649 of file absyn.c.
References Func_Def_::arg_list, Type_::array_type, free(), free_Arg_List(), free_ID_List(), free_Type_Decl(), Func_Def_::is_template, Type_::obj, Func_Def_::ret_type, Func_Def_::type_decl, and Func_Def_::types.
Referenced by find_template_match(), free_Func(), and free_Section().
 {
   if(!a->is_template) {
     if(a->types)
       free_ID_List(a->types);
     if(a->ret_type && a->ret_type->array_type) {
       free(a->ret_type->obj);
       free(a->ret_type);
     }
     if(a->arg_list)
       free_Arg_List(a->arg_list);
 //  if(a->type_decl)
     free_Type_Decl(a->type_decl);
     free(a);
   } else
       free(a);
 }
free_ID_List()
void free_ID_List (ID_List a)
Definition at line 1378 of file absyn.c.
References free(), and ID_List_::next.
Referenced by free_Class_Def(), free_Func_Def(), free_Section(), free_Stmt_Enum(), free_Type_Decl(), free_Type_List(), make_dll_arg_list(), and str2list().
 {
 #ifdef DEBUG_AST
   debug_msg("emit", "free_ID_LIST");
 #endif
   ID_List tmp, curr = a;
   while(curr) {
     tmp = curr;
     curr = curr->next;
     free(tmp);
   }
 }
free_If_Expression()
void free_If_Expression (If_Expression * a)
Definition at line 620 of file absyn.c.
References If_Expression::cond, If_Expression::else_exp, free(), free_Expression(), and If_Expression::if_exp.
Referenced by free_Expression().
 {
   free_Expression(a->cond);
   free_Expression(a->if_exp);
   free_Expression(a->else_exp);
   free(a);
 }
free_polar()
void free_polar (Polar * a)
Definition at line 496 of file absyn.c.
References free(), free_Expression(), and Polar::mod.
Referenced by free_Primary_Expression().
 {
   free_Expression(a->mod);
   free(a);
 }
free_Postfix_Expression()
void free_Postfix_Expression (Postfix_Expression * postfix)
Definition at line 260 of file absyn.c.
References Postfix_Expression::exp, free(), and free_Expression().
Referenced by free_Expression().
 {
   free_Expression(postfix->exp);
   free(postfix);
 }
free_Primary_Expression()
void free_Primary_Expression (Primary_Expression * a)
Definition at line 758 of file absyn.c.
References ae_primary_array, ae_primary_complex, ae_primary_hack, ae_primary_polar, ae_primary_vec, Primary_Expression::array, Primary_Expression::cmp, Primary_Expression::d, Primary_Expression::exp, free(), free_Array_Sub(), free_complex(), free_Expression(), free_polar(), free_Vec(), Primary_Expression::polar, Primary_Expression::type, and Primary_Expression::vec.
Referenced by free_Expression().
 {
   if(a->type == ae_primary_hack)
     free_Expression(a->d.exp);
   else if (a->type == ae_primary_array)
     free_Array_Sub(a->d.array);
   else if (a->type == ae_primary_complex)
     free_complex(a->d.cmp);
   else if (a->type == ae_primary_polar)
     free_polar(a->d.polar);
   else if (a->type == ae_primary_vec)
     free_Vec(a->d.vec);
   free(a);
 }
free_Section() [1/2]
static void free_Section () static
Referenced by free_Ast(), and free_Class_Def().
free_Section() [2/2]
void free_Section (Section * section)
Definition at line 1269 of file absyn.c.
References ae_section_class, ae_section_func, ae_section_stmt, Func_Def_::arg_list, Section::class_def, Func_Def_::code, Section::d, free(), free_Arg_List(), free_Class_Def(), free_Func_Def(), free_ID_List(), free_Stmt(), free_Stmt_List(), free_Type_Decl(), Func_Def_::func, Section::func_def, Value_::func_ref, Type_::info, insert_symbol(), Value_::name, Func_::obj, Value_::obj, Value_::owner_class, rem_ref(), scope_rem(), Section::stmt_list, Section::type, Func_Def_::type_decl, Func_Def_::types, NameSpace_::value, and Func_::value_ref.
 {
   switch(section->type) {
   case ae_section_class:
     free_Class_Def(section->d.class_def);
     break;
   case ae_section_stmt:
     free_Stmt_List(section->d.stmt_list);
     break;
   case ae_section_func:
     if(!section->d.func_def)
       break;
     free_Stmt(section->d.func_def->code);
     if(section->d.func_def->types) {
       if(section->d.func_def->func && section->d.func_def->func->value_ref->owner_class) {
         scope_rem(section->d.func_def->func->value_ref->owner_class->info->value,
         insert_symbol(section->d.func_def->func->value_ref->name));
         section->d.func_def->func->value_ref->func_ref = NULL;
         free(section->d.func_def->func->obj);
         free(section->d.func_def->func);
         free_Func_Def(section->d.func_def);
         break;
       }
       if(section->d.func_def->arg_list)
         free_Arg_List(section->d.func_def->arg_list);
       free_ID_List(section->d.func_def->types);
       free_Type_Decl(section->d.func_def->type_decl);
       if(section->d.func_def->func) {
         rem_ref(section->d.func_def->func->value_ref->obj, section->d.func_def->func->value_ref);
         free(section->d.func_def->func->obj);
         free(section->d.func_def->func);
       }
       free(section->d.func_def);
     } else {
       if(!section->d.func_def->func)
         free_Func_Def(section->d.func_def);
     }
     break;
   }
   free(section);
 }
free_Stmt()
void free_Stmt (Stmt * a)
Definition at line 1157 of file absyn.c.
References ae_stmt_break, ae_stmt_case, ae_stmt_code, ae_stmt_continue, ae_stmt_enum, ae_stmt_exp, ae_stmt_for, ae_stmt_funcptr, ae_stmt_gotolabel, ae_stmt_if, ae_stmt_loop, ae_stmt_return, ae_stmt_switch, ae_stmt_union, ae_stmt_until, ae_stmt_while, Stmt::d, free(), free_Expression(), free_Stmt_Case(), free_Stmt_Code(), free_Stmt_Enum(), free_Stmt_For(), free_Stmt_Func_Ptr(), free_Stmt_GotoLabel(), free_Stmt_If(), free_Stmt_Loop(), free_Stmt_Return(), free_Stmt_Switch(), free_Stmt_Union(), free_Stmt_Until(), free_Stmt_While(), Stmt::stmt_break, Stmt::stmt_case, Stmt::stmt_code, Stmt::stmt_continue, Stmt::stmt_enum, Stmt::stmt_exp, Stmt::stmt_for, Stmt::stmt_funcptr, Stmt::stmt_gotolabel, Stmt::stmt_if, Stmt::stmt_loop, Stmt::stmt_return, Stmt::stmt_switch, Stmt::stmt_union, Stmt::stmt_until, Stmt::stmt_while, and Stmt::type.
Referenced by free_Section(), free_Stmt_For(), free_Stmt_If(), free_Stmt_List(), free_Stmt_Loop(), free_Stmt_Switch(), free_Stmt_Until(), free_Stmt_While(), and free_Unary_Expression().
 {
   switch(stmt->type) {
   case ae_stmt_exp:
     free_Expression(stmt->d.stmt_exp);
     break;
   case ae_stmt_while:
     free_Stmt_While(stmt->d.stmt_while);
     break;
   case ae_stmt_until:
     free_Stmt_Until(stmt->d.stmt_until);
     break;
   case ae_stmt_for:
     free_Stmt_For(stmt->d.stmt_for);
     break;
   case ae_stmt_loop:
     free_Stmt_Loop(stmt->d.stmt_loop);
     break;
   case ae_stmt_if:
     free_Stmt_If(stmt->d.stmt_if);
     break;
   case ae_stmt_code:
     free_Stmt_Code(stmt->d.stmt_code);
     break;
   case ae_stmt_switch:
     free_Stmt_Switch(stmt->d.stmt_switch);
     break;
   case ae_stmt_break:
     free(stmt->d.stmt_break);
     break;
   case ae_stmt_continue:
     free(stmt->d.stmt_continue);
     break;
   case ae_stmt_return:
     free_Stmt_Return(stmt->d.stmt_return);
     break;
   case ae_stmt_case:
     free_Stmt_Case(stmt->d.stmt_case);
     break;
   case ae_stmt_gotolabel:
     free_Stmt_GotoLabel(stmt->d.stmt_gotolabel);
     break;
   case ae_stmt_enum:
     free_Stmt_Enum(stmt->d.stmt_enum);
     break;
   case ae_stmt_funcptr:
     free_Stmt_Func_Ptr(stmt->d.stmt_funcptr);
     break;
   case ae_stmt_union:
     free_Stmt_Union(stmt->d.stmt_union);
     break;
   }
   free(stmt);
 }
free_Stmt_Case()
void free_Stmt_Case (Stmt_Case a)
Definition at line 1076 of file absyn.c.
References free(), free_Expression(), and Stmt_Case_::val.
Referenced by free_Stmt().
 {
   free_Expression(a->val);
   free(a);
 }
free_Stmt_Code()
void free_Stmt_Code (Stmt_Code a)
Definition at line 869 of file absyn.c.
References free(), free_Stmt_List(), and Stmt_Code_::stmt_list.
Referenced by free_Stmt().
 {
   free_Stmt_List(a->stmt_list);
   free(a);
 }
free_Stmt_Enum()
void free_Stmt_Enum (Stmt_Enum a)
Definition at line 1096 of file absyn.c.
References free(), free_ID_List(), free_Vector(), Stmt_Enum_::list, Value_::obj, Value_::owner_class, Stmt_Enum_::values, vector_at(), and vector_size().
Referenced by free_Stmt().
 {
   vtype i;
   if(a->list)
     free_ID_List(a->list);
   for(i = 0; i < vector_size(a->values); i++) {
     Value v = (Value)vector_at(a->values, i);
 if(!v->owner_class) {
     free(v->obj);
     free(v);
 }
 //else    rem_ref(v->obj, v);
   }
   free_Vector(a->values);
   free(a);
 }
free_Stmt_For()
void free_Stmt_For (Stmt_For a)
Definition at line 972 of file absyn.c.
References Stmt_For_::body, Stmt_For_::c1, Stmt_For_::c2, Stmt_For_::c3, free(), free_Expression(), and free_Stmt().
Referenced by free_Stmt().
 {
   free_Stmt(a->c1);
   free_Stmt(a->c2);
   free_Expression(a->c3);
   free_Stmt(a->body);
   free(a);
 }
free_Stmt_Func_Ptr()
void free_Stmt_Func_Ptr (Func_Ptr * a)
Definition at line 686 of file absyn.c.
References Func_Ptr::args, free(), free_Arg_List(), free_Type_Decl(), Func_Ptr::func, Value_::is_member, Value_::m_type, Value_::obj, Type_::obj, rem_ref(), Func_Ptr::type, and Func_Ptr::value.
Referenced by free_Stmt().
 {
   if(a->args)
     free_Arg_List(a->args);
   if(a->value && !a->value->is_member) {
     if(!a->func)
       free_Type_Decl(a->type);
     rem_ref(a->value->m_type->obj, a->value->m_type);
     rem_ref(a->value->obj, a->value);
   }
   free(a);
 }
free_Stmt_GotoLabel()
void free_Stmt_GotoLabel (Stmt_Goto_Label a)
Definition at line 994 of file absyn.c.
References free().
Referenced by free_Stmt().
 {
 //  if(a->is_label && a->data.v)
 //    free_Vector(a->data.v);
 //  else free(a->data.instr);
   free(a);
 }
free_Stmt_If()
void free_Stmt_If (Stmt_If a)
Definition at line 1036 of file absyn.c.
References Stmt_If_::cond, Stmt_If_::else_body, free(), free_Expression(), free_Stmt(), and Stmt_If_::if_body.
Referenced by free_Stmt().
 {
   free_Expression(a->cond);
   free_Stmt(a->if_body);
   if(a->else_body)
     free_Stmt(a->else_body);
   free(a);
 }
free_Stmt_List()
void free_Stmt_List (Stmt_List a)
Definition at line 1220 of file absyn.c.
References free(), free_Stmt(), Stmt_List_::next, and Stmt_List_::stmt.
Referenced by free_Section(), and free_Stmt_Code().
 {
   Stmt_List tmp;
   while(list) {
     tmp = list;
     list = list->next;
     free_Stmt(tmp->stmt);
     free(tmp);
   }
 }
free_Stmt_Loop()
void free_Stmt_Loop (Stmt_Loop a)
Definition at line 1015 of file absyn.c.
References Stmt_Loop_::body, Stmt_Loop_::cond, free(), free_Expression(), and free_Stmt().
Referenced by free_Stmt().
 {
   free_Expression(a->cond);
   free_Stmt(a->body);
   free(a);
 }
free_Stmt_Return()
void free_Stmt_Return (Stmt_Return a)
Definition at line 887 of file absyn.c.
References free(), free_Expression(), and Stmt_Return_::val.
Referenced by free_Stmt().
 {
   free_Expression(a->val);
   free(a);
 }
free_Stmt_Switch()
void free_Stmt_Switch (Stmt_Switch a)
Definition at line 1057 of file absyn.c.
References free(), free_Expression(), free_Stmt(), Stmt_Switch_::stmt, and Stmt_Switch_::val.
Referenced by free_Stmt().
 {
   free_Expression(a->val);
   free_Stmt(a->stmt);
   free(a);
 }
free_Stmt_Union()
void free_Stmt_Union (Union * a)
Definition at line 1140 of file absyn.c.
References free(), free_Decl_List(), free_Vector(), Union::l, and Union::v.
Referenced by free_Stmt().
 {
   free_Decl_List(a->l);
   free_Vector(a->v);
   free(a);
 }
free_Stmt_Until()
void free_Stmt_Until (Stmt_Until a)
Definition at line 950 of file absyn.c.
References Stmt_Until_::body, Stmt_Until_::cond, free(), free_Expression(), and free_Stmt().
Referenced by free_Stmt().
 {
   free_Expression(a->cond);
   free_Stmt(a->body);
   free(a);
 }
free_Stmt_While()
void free_Stmt_While (Stmt_While a)
Definition at line 929 of file absyn.c.
References Stmt_While_::body, Stmt_While_::cond, free(), free_Expression(), and free_Stmt().
Referenced by free_Stmt().
 {
   free_Expression(a->cond);
   free_Stmt(a->body);
   free(a);
 }
free_Type_Decl()
void free_Type_Decl (Type_Decl * a)
Definition at line 163 of file absyn.c.
References Type_Decl::array, free(), free_ID_List(), and Type_Decl::xid.
Referenced by free_Arg_List(), free_Cast_Expression(), free_Decl_Expression(), free_Func_Def(), free_Section(), free_Stmt_Func_Ptr(), free_Unary_Expression(), make_dll_arg_list(), and yydestruct().
 {
   if(a->array) {
     free(a->array);
   }
   free_ID_List(a->xid);
   free(a);
 }
free_Type_List()
void free_Type_List (Type_List a)
Definition at line 1400 of file absyn.c.
References free(), free_ID_List(), free_Type_List(), Type_List_::list, and Type_List_::next.
Referenced by check_Func_Call(), free_Func_Call(), and free_Type_List().
 {
   if(a->next)
     free_Type_List(a->next);
   free_ID_List(a->list);
   free(a);
 }
free_Unary_Expression()
void free_Unary_Expression (Unary_Expression * a)
Definition at line 571 of file absyn.c.
References Unary_Expression::code, Unary_Expression::exp, free(), free_Expression(), free_Stmt(), free_Type_Decl(), and Unary_Expression::type.
Referenced by free_Expression().
 {
   if(a->exp) // sporked func
     free_Expression(a->exp);
   if(a->type)
     free_Type_Decl(a->type);
   if(a->code)
     free_Stmt(a->code);
   free(a);
 }
free_Var_Decl()
void free_Var_Decl (Var_Decl a)
Definition at line 35 of file absyn.c.
References Var_Decl_::array, free(), free_Array_Sub(), free_Value(), Value_::obj, Value_::owner_class, rem_ref(), and Var_Decl_::value.
Referenced by free_Arg_List(), and free_Var_Decl_List().
 {
   if(a->value) {
     if(!a->value->obj) // func argument. this migth change
       free_Value(a->value);
     else if(!a->value->owner_class) { // breaks for loop ?
       /*      if(a->value->m_type->array_type) {
               free(a->value->m_type->obj);
               free(a->value->m_type);
             }*/
       rem_ref(a->value->obj, a->value);
     }
   }
   if(a->array)
     free_Array_Sub(a->array);
   free(a);
 }
free_Var_Decl_List()
void free_Var_Decl_List (Var_Decl_List a)
Definition at line 63 of file absyn.c.
References free(), free_Var_Decl(), Var_Decl_List_::next, and Var_Decl_List_::self.
Referenced by free_Decl_Expression().
 {
   Var_Decl_List tmp, list = a;
   while(list) {
     free_Var_Decl(list->self);
     tmp = list;
     list = list->next;
     free(tmp);
   }
 }
free_Vec()
void free_Vec (Vec a)
Definition at line 514 of file absyn.c.
References Vec_::args, free(), and free_Expression().
Referenced by free_Primary_Expression().
 {
   free_Expression(a->args);
   free(a);
 }
get_pos()
int get_pos (void * data)
Definition at line 14 of file absyn.c.
References MyArg::line, map_get(), and scan_map.
 {
   MyArg* arg = (MyArg*)map_get(scan_map, (vtype)data);
   return arg->line;
 }
new_Arg_List()
Arg_List new_Arg_List (Type_Decl * type_decl, Var_Decl var_decl, Arg_List arg_list, int pos)
Definition at line 821 of file absyn.c.
References Arg_List_::doc, Arg_List_::next, Arg_List_::pos, Arg_List_::type_decl, and Arg_List_::var_decl.
Referenced by make_dll_arg_list(), and yyparse().
 {
   Arg_List a = calloc(1, sizeof(struct Arg_List_));
   a->type_decl = type_decl;
   a->var_decl = var_decl;
   a->next = arg_list;
   a->doc = NULL;
   a->pos = pos;
   return a;
 }
new_Array()
Expression new_Array (Expression base, Array_Sub indices, int pos)
Definition at line 140 of file absyn.c.
References ae_meta_var, Array_Expression_type, Array::base, Expression_::cast_to, Expression_::d, Expression_::exp_array, Expression_::exp_type, Array::indices, Expression_::meta, Expression_::next, Array::pos, Expression_::pos, and Array::self.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Array_Expression_type;
   a->meta = ae_meta_var;
   a->d.exp_array = calloc(1, sizeof(Array));
   a->d.exp_array->base = base;
   a->d.exp_array->indices = indices;
   a->pos = pos;
   a->d.exp_array->pos = pos;
   a->d.exp_array->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_array_sub()
Array_Sub new_array_sub (Expression exp, int pos)
Definition at line 97 of file absyn.c.
References Array_Sub_::depth, Array_Sub_::err_num, Array_Sub_::exp_list, and Array_Sub_::pos.
Referenced by import_var(), make_dll_arg_list(), make_dll_as_fun(), and yyparse().
 {
   Array_Sub a = calloc(1, sizeof(struct Array_Sub_));
   a->exp_list = exp;
   a->depth = 1;
   a->err_num = 0;
   a->pos = pos;
   return a;
 }
new_Ast()
Ast new_Ast (Section * section, Ast next, int pos)
Definition at line 1420 of file absyn.c.
References Ast_::doc, malloc(), Ast_::next, Ast_::pos, and Ast_::section.
Referenced by yyparse().
 {
 #ifdef DEBUG_AST
   debug_msg("emit", "new Ast");
 #endif
   Ast ast = malloc(sizeof(struct Ast_));
   ast->section = section;
   ast->next = next;
   ast->pos = pos;
   ast->doc = NULL;
   return ast;
 }
new_Binary_Expression()
Expression new_Binary_Expression (Expression lhs, Operator op, Expression rhs, int pos)
Definition at line 197 of file absyn.c.
References ae_meta_value, Binary_Expression_type, Expression_::cast_to, Expression_::d, Expression_::exp_binary, Expression_::exp_type, Binary_Expression::lhs, Expression_::meta, Expression_::next, Binary_Expression::op, Binary_Expression::pos, Expression_::pos, Binary_Expression::rhs, and Binary_Expression::self.
Referenced by yyparse().
 {
   Expression a = calloc(1,  sizeof( struct Expression_ ) );
   a->exp_type = Binary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_binary = calloc(1, sizeof(Binary_Expression));
   a->d.exp_binary->lhs = lhs;
   a->d.exp_binary->op = op;
   a->d.exp_binary->rhs = rhs;
   a->pos = pos;
   a->d.exp_binary->pos = pos;
   a->d.exp_binary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Cast_Expression()
Expression new_Cast_Expression (Type_Decl * type, Expression exp, int pos)
Definition at line 221 of file absyn.c.
References ae_meta_value, Cast_Expression_type, Expression_::cast_to, Expression_::d, Cast_Expression::exp, Expression_::exp_cast, Expression_::exp_type, Expression_::meta, Expression_::next, Cast_Expression::pos, Expression_::pos, Cast_Expression::self, and Cast_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1,  sizeof( struct Expression_ ) );
   a->exp_type = Cast_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_cast = calloc(1, sizeof(Cast_Expression));
   a->d.exp_cast->type = type;
   a->pos = pos;
   a->d.exp_cast->pos = pos;
   a->d.exp_cast->exp = exp;
   a->d.exp_cast->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_class_body()
Class_Body new_class_body (Section * section, int pos)
Definition at line 1334 of file absyn.c.
References Class_Body_::next, Class_Body_::pos, and Class_Body_::section.
Referenced by prepend_class_body(), and yyparse().
 {
   Class_Body a = calloc(1, sizeof(struct Class_Body_));
   a->section = section;
   a->pos = pos;
   a->next = NULL;
   return a;
 }
new_class_def()
Class_Def new_class_def (ae_Keyword class_decl, ID_List name, Class_Ext ext, Class_Body body, int pos)
Definition at line 1311 of file absyn.c.
References Class_Def_::body, Class_Def_::decl, Class_Def_::doc, Class_Def_::ext, Class_Def_::home, Class_Def_::name, Class_Def_::pos, and Class_Def_::type.
Referenced by new_iface_def(), and yyparse().
 {
   Class_Def a = calloc(1, sizeof(struct Class_Def_));
   a->decl = class_decl;
   a->name = name;
   a->ext  = ext;
   a->home = NULL;
   a->body = body;
   a->pos  = pos;
   a->doc  = NULL;
   a->type = NULL;
   return a;
 }
new_class_ext()
Class_Ext new_class_ext (ID_List extend_id, ID_List impl_list, int pos)
Definition at line 1351 of file absyn.c.
References Class_Ext_::extend_id, Class_Ext_::impl_list, and Class_Ext_::pos.
Referenced by yyparse().
 {
   Class_Ext a = calloc(1, sizeof(struct Class_Ext_));
   a->extend_id = extend_id;
   a->impl_list = impl_list;
   a->pos = pos;
   return a;
 }
new_complex()
Complex* new_complex (Expression re, int pos)
Definition at line 388 of file absyn.c.
References Complex::im, Expression_::next, Complex::pos, and Complex::re.
Referenced by yyparse().
 {
   Complex* a = calloc(1, sizeof(Complex));
   a->re = re;
   if(re)
     a->im = re->next;
   a->pos = pos;
   return a;
 }
new_Decl_Expression()
Expression new_Decl_Expression (Type_Decl * type, Var_Decl_List list, m_bool is_static, int pos)
Definition at line 172 of file absyn.c.
References Expression_::cast_to, Expression_::d, Decl_Expression_type, Expression_::exp_decl, Expression_::exp_type, Decl_Expression::is_static, Decl_Expression::list, Expression_::next, Decl_Expression::num_decl, Decl_Expression::pos, Expression_::pos, Decl_Expression::self, and Decl_Expression::type.
Referenced by import_var(), and yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Decl_Expression_type;
   a->d.exp_decl  = calloc(1, sizeof(Decl_Expression));
   a->d.exp_decl->type = type;
   a->d.exp_decl->num_decl = 0;
   a->d.exp_decl->list = list;
   a->d.exp_decl->is_static = is_static;
   a->pos  = pos;
   a->d.exp_decl->pos  = pos;
   a->d.exp_decl->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Decl_List()
Decl_List new_Decl_List (Decl_Expression * d, Decl_List l)
Definition at line 1123 of file absyn.c.
References Decl_List_::next, and Decl_List_::self.
Referenced by yyparse().
 {
   Decl_List a = calloc(1, sizeof(struct Decl_List_));
   a->self = d;
   a->next = l;
   return a;
 }
new_Exp_Dur()
Expression new_Exp_Dur (Expression base, Expression unit, int pos)
Definition at line 266 of file absyn.c.
References ae_meta_value, Exp_Dur::base, Expression_::cast_to, Expression_::d, Dur_Expression_type, Expression_::exp_dur, Expression_::exp_type, Expression_::meta, Expression_::next, Exp_Dur::pos, Expression_::pos, Exp_Dur::self, and Exp_Dur::unit.
Referenced by yyparse().
 {
   Expression a = calloc(1,  sizeof( struct Expression_ ) );
   a->exp_type = Dur_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_dur = calloc(1, sizeof(Exp_Dur));
   a->d.exp_dur->base = base;
   a->d.exp_dur->unit = unit;
   a->pos = pos;
   a->d.exp_dur->pos = pos;
   a->d.exp_dur->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_array_lit()
Expression new_exp_from_array_lit (Array_Sub exp_list, int pos)
Definition at line 421 of file absyn.c.
References ae_meta_value, ae_primary_array, Primary_Expression::array, Expression_::cast_to, Primary_Expression::d, Expression_::d, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_array;
   a->d.exp_primary->d.array = exp_list;
   a->pos = pos;
   a->d.exp_primary->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_char()
Expression new_exp_from_char (c_str chr, int pos)
Definition at line 405 of file absyn.c.
References ae_meta_value, ae_primary_char, Expression_::cast_to, Primary_Expression::chr, Primary_Expression::d, Expression_::d, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_char;
   a->d.exp_primary->d.chr = chr;
   a->pos = pos;
   a->d.exp_primary->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_complex()
Expression new_exp_from_complex (Complex * exp, int pos)
Definition at line 452 of file absyn.c.
References ae_meta_value, ae_primary_complex, Expression_::cast_to, Primary_Expression::cmp, Primary_Expression::d, Expression_::d, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Complex::self, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_complex;
   a->d.exp_primary->d.cmp = exp;
   a->d.exp_primary->pos = pos;
   a->pos = pos;
   a->d.exp_primary->d.cmp->self = a;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_member_dot()
Expression new_exp_from_member_dot (Expression base, m_str xid, int pos)
Definition at line 729 of file absyn.c.
References ae_meta_var, Dot_Member::base, Expression_::cast_to, Expression_::d, Dot_Member_type, Expression_::exp_dot, Expression_::exp_type, insert_symbol(), Expression_::meta, Expression_::next, Dot_Member::pos, Expression_::pos, Dot_Member::self, and Dot_Member::xid.
Referenced by emit_symbol(), and yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Dot_Member_type;
   a->meta = ae_meta_var;
   a->d.exp_dot = calloc(1, sizeof(Dot_Member));
   a->d.exp_dot->base = base;
   a->d.exp_dot->xid = insert_symbol( xid );
   a->pos = pos;
   a->d.exp_dot->pos = pos;
   a->d.exp_dot->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_polar()
Expression new_exp_from_polar (Polar * exp, int pos)
Definition at line 469 of file absyn.c.
References ae_meta_value, ae_primary_polar, Expression_::cast_to, Primary_Expression::d, Expression_::d, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::polar, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Polar::self, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_polar;
   a->d.exp_primary->d.polar = exp;
   a->d.exp_primary->pos = pos;
   a->pos = pos;
   a->d.exp_primary->d.polar->self = a;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_unary()
Expression new_exp_from_unary (Operator oper, Expression exp, int pos)
Definition at line 535 of file absyn.c.
References Expression_::cast_to, Unary_Expression::code, Expression_::d, Unary_Expression::exp, Expression_::exp_type, Expression_::exp_unary, Expression_::meta, Expression_::next, Unary_Expression::op, Unary_Expression::pos, Expression_::pos, Unary_Expression::self, and Unary_Expression_type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Unary_Expression_type;
   a->meta = exp->meta;
   a->d.exp_unary = calloc(1, sizeof(Unary_Expression));
   a->d.exp_unary->op = oper;
   a->d.exp_unary->exp = exp;
   a->d.exp_unary->code = NULL;
   a->pos = pos;
   a->d.exp_unary->pos = pos;
   a->d.exp_unary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_unary2()
Expression new_exp_from_unary2 (Operator oper, Type_Decl * type, Array_Sub array, int pos)
Definition at line 552 of file absyn.c.
References ae_meta_value, Unary_Expression::array, Expression_::cast_to, Unary_Expression::code, Expression_::d, Unary_Expression::exp, Expression_::exp_type, Expression_::exp_unary, Expression_::meta, Expression_::next, Unary_Expression::op, Unary_Expression::pos, Expression_::pos, Unary_Expression::self, Unary_Expression::type, and Unary_Expression_type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Unary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_unary = calloc(1, sizeof(Unary_Expression));
   a->d.exp_unary->exp = NULL;
   a->d.exp_unary->op = oper;
   a->d.exp_unary->type = type;
   a->d.exp_unary->array = array;
   a->d.exp_unary->code = NULL;
   a->pos = pos;
   a->d.exp_unary->pos = pos;
   a->d.exp_unary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_unary3()
Expression new_exp_from_unary3 (Operator oper, Stmt * code, int pos)
Definition at line 582 of file absyn.c.
References ae_meta_value, Unary_Expression::array, Expression_::cast_to, Unary_Expression::code, Expression_::d, Unary_Expression::exp, Expression_::exp_type, Expression_::exp_unary, Expression_::meta, new_id_list(), new_Type_Decl(), Expression_::next, Unary_Expression::op, Unary_Expression::pos, Expression_::pos, Unary_Expression::self, Unary_Expression::type, and Unary_Expression_type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Unary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_unary = calloc(1, sizeof(Unary_Expression));
   a->d.exp_unary->exp = NULL;
   a->d.exp_unary->op = oper;
   ID_List id = new_id_list("void", pos);
   a->d.exp_unary->type = new_Type_Decl(id, 0, pos);
   a->d.exp_unary->array = NULL;
   a->d.exp_unary->code = code;
   a->pos = pos;
   a->d.exp_unary->pos = pos;
   a->d.exp_unary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_exp_from_vec()
Expression new_exp_from_vec (Vec exp, int pos)
Definition at line 520 of file absyn.c.
References ae_meta_value, ae_primary_vec, Primary_Expression::d, Expression_::d, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Vec_::self, Primary_Expression::self, Primary_Expression::type, and Primary_Expression::vec.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_vec;
   a->d.exp_primary->d.vec = exp;
   a->d.exp_primary->pos = pos;
   a->pos = pos;
   a->d.exp_primary->d.vec->self = a;
   a->d.exp_primary->self = a;
   return a;
 }
new_Func_Call()
Expression new_Func_Call (Expression base, Expression args, int pos)
Definition at line 699 of file absyn.c.
References ae_meta_value, Func_Call::args, Expression_::cast_to, Expression_::d, Expression_::exp_func, Expression_::exp_type, Func_Call::func, Func_Call_type, Func_Call::m_func, Expression_::meta, Expression_::next, Func_Call::pos, Expression_::pos, Func_Call::self, and Func_Call::types.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Func_Call_type;
   a->meta = ae_meta_value;
   a->d.exp_func = calloc(1, sizeof(Func_Call));
   a->d.exp_func->func = base;
   a->d.exp_func->args = args;
   a->d.exp_func->types = NULL;
   a->pos = pos;
   a->d.exp_func->m_func = NULL;
   a->d.exp_func->pos = pos;
   a->d.exp_func->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Func_Def()
Func_Def new_Func_Def (ae_Keyword func_decl, ae_Keyword static_decl, Type_Decl * type_decl, m_str name, Arg_List arg_list, Stmt * code, int pos)
Definition at line 628 of file absyn.c.
References ae_func_spec_none, ae_func_user, ae_key_func, ae_key_variadic, Func_Def_::arg_list, Func_Def_::code, Func_Def_::func, Func_Def_::func_decl, insert_symbol(), Func_Def_::is_variadic, Func_Def_::name, Func_Def_::pos, Func_Def_::s_type, Func_Def_::spec, Func_Def_::stack_depth, Func_Def_::static_decl, and Func_Def_::type_decl.
Referenced by emit_Unary(), find_template_match(), make_dll_as_fun(), scan2_Func_Ptr(), and yyparse().
 {
   Func_Def a = calloc(1, sizeof(struct Func_Def_));
   a->func_decl = func_decl;
   a->static_decl = static_decl;
   a->type_decl = type_decl;
   a->name = insert_symbol(name);
   a->arg_list = arg_list;
   a->s_type = ae_func_user;
   a->code = code;
   a->func = NULL;
   a->stack_depth = 0;
   a->pos = pos;
   a->spec = ae_func_spec_none;
   if(a->func_decl == ae_key_variadic) {
     a->func_decl = ae_key_func;
     a->is_variadic = 1;
   }
   return a;
 }
new_Func_Ptr_Stmt()
Stmt* new_Func_Ptr_Stmt (ae_Keyword key, m_str xid, Type_Decl * decl, Arg_List args, int pos)
Definition at line 667 of file absyn.c.
References ae_stmt_funcptr, Func_Ptr::args, Stmt::d, Func_Ptr::func, insert_symbol(), Func_Ptr::key, Func_Ptr::pos, Stmt::pos, Stmt::stmt_funcptr, Func_Ptr::type, Stmt::type, Func_Ptr::value, and Func_Ptr::xid.
Referenced by yyparse().
 {
   Stmt* a                = calloc(1, sizeof(Stmt));
   a->type                = ae_stmt_funcptr;
   a->d.stmt_funcptr        = calloc(1, sizeof(Func_Ptr));
   a->d.stmt_funcptr->key   = key;
   a->d.stmt_funcptr->type  = decl;
   a->d.stmt_funcptr->xid   = insert_symbol(xid);
   a->d.stmt_funcptr->args  = args;
   a->d.stmt_funcptr->func  = NULL;
   a->d.stmt_funcptr->value = NULL;
 //  a->stmt_funcptr->ref   = NULL;
   a->d.stmt_funcptr->pos   = pos;
   a->pos             = pos;
   return a;
 }
new_Hack_Expression()
Expression new_Hack_Expression (Expression exp, int pos)
Definition at line 372 of file absyn.c.
References ae_meta_value, ae_primary_hack, Expression_::cast_to, Primary_Expression::d, Expression_::d, Primary_Expression::exp, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_hack;
   a->d.exp_primary->d.exp = exp;
   a->d.exp_primary->pos = pos;
   a->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_id_list()
ID_List new_id_list (const m_str xid, int pos)
Definition at line 1360 of file absyn.c.
References insert_symbol(), ID_List_::next, ID_List_::pos, and ID_List_::xid.
Referenced by emit_Unary(), new_exp_from_unary3(), prepend_id_list(), and yyparse().
 {
   ID_List a = calloc(1,  sizeof( struct ID_List_ ) );
   a->xid = insert_symbol( xid );
   a->next = NULL;
   a->pos = pos;
   return a;
 }
new_If_Expression()
Expression new_If_Expression (Expression cond, Expression if_exp, Expression else_exp, int pos)
Definition at line 602 of file absyn.c.
References ae_meta_value, ae_meta_var, Expression_::cast_to, If_Expression::cond, Expression_::d, If_Expression::else_exp, Expression_::exp_if, Expression_::exp_type, If_Expression::if_exp, If_Expression_type, Expression_::meta, Expression_::next, If_Expression::pos, Expression_::pos, and If_Expression::self.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = If_Expression_type;
   a->meta = ( ( if_exp->meta == ae_meta_var &&
                 else_exp->meta == ae_meta_var ) ? ae_meta_var : ae_meta_value );
   a->d.exp_if = calloc(1, sizeof(If_Expression));
   a->d.exp_if->cond = cond;
   a->d.exp_if->if_exp = if_exp;
   a->d.exp_if->else_exp = else_exp;
   a->pos = pos;
   a->d.exp_if->pos = pos;
   a->d.exp_if->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_iface_def()
Class_Def new_iface_def (ae_Keyword class_decl, ID_List name, Class_Ext ext, Class_Body body, int pos)
Definition at line 1326 of file absyn.c.
References Class_Def_::iface, and new_class_def().
 {
   Class_Def a = new_class_def( class_decl, name, ext, body, pos );
   a->iface = 1;
   return a;
 }
new_polar()
Polar* new_polar (Expression mod, int pos)
Definition at line 486 of file absyn.c.
References Polar::mod, Expression_::next, Polar::phase, and Polar::pos.
Referenced by yyparse().
 {
   Polar* a = calloc(1, sizeof(Polar));
   a->mod = mod;
   if(mod)
     a->phase = mod->next;
   a->pos = pos;
   return a;
 }
new_Postfix_Expression()
Expression new_Postfix_Expression (Expression exp, Operator op, int pos)
Definition at line 244 of file absyn.c.
References ae_meta_var, Expression_::cast_to, Expression_::d, Postfix_Expression::exp, Expression_::exp_postfix, Expression_::exp_type, Expression_::meta, Expression_::next, Postfix_Expression::op, Postfix_Expression::pos, Expression_::pos, Postfix_Expression_type, and Postfix_Expression::self.
Referenced by yyparse().
 {
   Expression a = calloc(1,  sizeof( struct Expression_ ) );
   a->exp_type = Postfix_Expression_type;
   a->meta = ae_meta_var;
   a->d.exp_postfix = calloc(1, sizeof(Postfix_Expression));
   a->d.exp_postfix->exp = exp;
   a->d.exp_postfix->op = op;
   a->pos = pos;
   a->d.exp_postfix->pos = pos;
   a->d.exp_postfix->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Primary_Expression_from_float()
Expression new_Primary_Expression_from_float (m_float num, int pos)
Definition at line 306 of file absyn.c.
References ae_meta_value, ae_primary_float, Expression_::cast_to, Primary_Expression::d, Expression_::d, Expression_::emit_var, Expression_::exp_primary, Expression_::exp_type, Primary_Expression::fnum, Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1,  sizeof( struct Expression_ ) );
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->emit_var = 0; // ???
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_float;
   a->d.exp_primary->d.fnum = num;
   a->pos = pos;
   a->d.exp_primary->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Primary_Expression_from_ID()
Expression new_Primary_Expression_from_ID (m_str s, int pos)
Definition at line 355 of file absyn.c.
References ae_meta_var, ae_primary_var, Expression_::cast_to, Primary_Expression::d, Expression_::d, Expression_::emit_var, Expression_::exp_primary, Expression_::exp_type, insert_symbol(), Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, Primary_Expression::type, and Primary_Expression::var.
Referenced by emit_symbol(), and yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_var;
   a->emit_var = 0;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_var;
   a->d.exp_primary->d.var = insert_symbol(s);
   a->pos = pos;
   a->d.exp_primary->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Primary_Expression_from_int()
Expression new_Primary_Expression_from_int (long i, int pos)
Definition at line 289 of file absyn.c.
References ae_meta_value, ae_primary_num, Expression_::cast_to, Primary_Expression::d, Expression_::d, Expression_::emit_var, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::num, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->emit_var = 0;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_num;
   a->d.exp_primary->d.num = i;
   a->pos = pos;
   a->d.exp_primary->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Primary_Expression_from_nil()
Expression new_Primary_Expression_from_nil (int pos)
Definition at line 340 of file absyn.c.
References ae_meta_value, ae_primary_nil, Expression_::cast_to, Expression_::d, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression  a = calloc(1, sizeof(struct Expression_));
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_nil;
   a->d.exp_primary->pos = pos;
   a->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_Primary_Expression_from_string()
Expression new_Primary_Expression_from_string (m_str s, int pos)
Definition at line 323 of file absyn.c.
References ae_meta_value, ae_primary_str, Expression_::cast_to, Primary_Expression::d, Expression_::d, Expression_::emit_var, Expression_::exp_primary, Expression_::exp_type, Expression_::meta, Expression_::next, Primary_Expression::pos, Expression_::pos, Primary_Expression_type, Primary_Expression::self, Primary_Expression::str, and Primary_Expression::type.
Referenced by yyparse().
 {
   Expression a = calloc(1,  sizeof( struct Expression_ ) );
   a->exp_type = Primary_Expression_type;
   a->meta = ae_meta_value;
   a->emit_var = 0; // ???
   a->d.exp_primary = calloc(1, sizeof(Primary_Expression));
   a->d.exp_primary->type = ae_primary_str;
   a->d.exp_primary->d.str = s;
   a->pos = pos;
   a->d.exp_primary->pos = pos;
   a->d.exp_primary->self = a;
   a->next = NULL;
   a->cast_to = NULL;
   return a;
 }
new_section_Class_Def()
Section* new_section_Class_Def (Class_Def class_def, int pos)
Definition at line 1408 of file absyn.c.
References ae_section_class, Section::class_def, Section::d, Section::pos, and Section::type.
Referenced by yyparse().
 {
 #ifdef DEBUG_AST
   debug_msg("emit", "class def");
 #endif
   Section* a = calloc(1, sizeof(Section));
   a->type = ae_section_class;
   a->d.class_def = class_def;
   a->pos = pos;
   return a;
 }
new_section_Func_Def()
Section* new_section_Func_Def (Func_Def func_def, int pos)
Definition at line 1240 of file absyn.c.
References ae_section_func, Section::d, Section::func_def, Section::pos, and Section::type.
Referenced by yyparse().
 {
   Section* a = calloc(1, sizeof(Section));
   a->type = ae_section_func;
   a->d.func_def = func_def;
   a->pos = pos;
   return a;
 }
new_section_Stmt_List()
Section* new_section_Stmt_List (Stmt_List list, int pos)
Definition at line 1231 of file absyn.c.
References ae_section_stmt, Section::d, Section::pos, Section::stmt_list, and Section::type.
Referenced by yyparse().
 {
   Section* a = calloc(1, sizeof(Section));
   a->type = ae_section_stmt;
   a->d.stmt_list = list;
   a->pos = pos;
   return a;
 }
new_stmt_from_break()
Stmt* new_stmt_from_break (int pos)
Definition at line 893 of file absyn.c.
References ae_stmt_break, Stmt::d, Stmt::pos, Stmt_Break_::pos, Stmt_Break_::self, Stmt::stmt_break, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_break;
   a->d.stmt_break = calloc(1, sizeof(struct Stmt_Break_));
   a->pos = pos;
   a->d.stmt_break->pos = pos;
   a->d.stmt_break->self = a;
   return a;
 }
new_stmt_from_case()
Stmt* new_stmt_from_case (Expression val, int pos)
Definition at line 1064 of file absyn.c.
References ae_stmt_case, Stmt::d, Stmt::pos, Stmt_Case_::pos, Stmt_Case_::self, Stmt::stmt_case, Stmt::type, and Stmt_Case_::val.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_case;
   a->d.stmt_case = calloc(1, sizeof(struct Stmt_Case_));
   a->d.stmt_case->val = val;
   a->pos = pos;
   a->d.stmt_case->pos = pos;
   a->d.stmt_case->self = a;
   return a;
 }
new_stmt_from_code()
Stmt* new_stmt_from_code (Stmt_List stmt_list, int pos)
Definition at line 857 of file absyn.c.
References ae_stmt_code, Stmt::d, Stmt::pos, Stmt_Code_::pos, Stmt_Code_::self, Stmt::stmt_code, Stmt_Code_::stmt_list, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_code;
   a->d.stmt_code = calloc(1, sizeof(struct Stmt_Code_));
   a->d.stmt_code->stmt_list = stmt_list;
   a->pos = pos;
   a->d.stmt_code->pos = pos;
   a->d.stmt_code->self = a;
   return a;
 }
new_stmt_from_continue()
Stmt* new_stmt_from_continue (int pos)
Definition at line 904 of file absyn.c.
References ae_stmt_continue, Stmt::d, Stmt::pos, Stmt_Continue_::pos, Stmt_Continue_::self, Stmt::stmt_continue, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_continue;
   a->d.stmt_continue = calloc(1, sizeof(struct Stmt_Continue_));
   a->pos = pos;
   a->d.stmt_continue->pos = pos;
   a->d.stmt_continue->self = a;
   return a;
 }
new_stmt_from_enum()
Stmt* new_stmt_from_enum (ID_List list, m_str xid, int pos)
Definition at line 1082 of file absyn.c.
References ae_stmt_enum, Stmt::d, insert_symbol(), Stmt_Enum_::list, new_Vector(), Stmt::pos, Stmt_Enum_::pos, Stmt_Enum_::self, Stmt::stmt_enum, Stmt::type, Stmt_Enum_::values, and Stmt_Enum_::xid.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_enum;
   a->d.stmt_enum = calloc(1, sizeof(struct Stmt_Enum_));
   a->d.stmt_enum->xid = xid ? insert_symbol(xid) : NULL;
   a->d.stmt_enum->list = list;
   a->d.stmt_enum->values = new_Vector();
   a->pos = pos;
   a->d.stmt_enum->pos = pos;
   a->d.stmt_enum->self = a;
   return a;
 }
new_Stmt_from_Expression()
Stmt* new_Stmt_from_Expression (Expression exp, int pos)
Definition at line 848 of file absyn.c.
References ae_stmt_exp, Stmt::d, Stmt::pos, Stmt::stmt_exp, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* stmt = calloc(1, sizeof(Stmt));
   stmt->type = ae_stmt_exp;
   stmt->d.stmt_exp = exp;
   stmt->pos = pos;
   return stmt;
 }
new_stmt_from_for()
Stmt* new_stmt_from_for (Stmt * c1, Stmt * c2, Expression c3, Stmt * body, int pos)
Definition at line 957 of file absyn.c.
References ae_stmt_for, Stmt_For_::body, Stmt_For_::c1, Stmt_For_::c2, Stmt_For_::c3, Stmt::d, Stmt::pos, Stmt_For_::pos, Stmt_For_::self, Stmt::stmt_for, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_for;
   a->d.stmt_for = calloc(1, sizeof(struct Stmt_For_));
   a->d.stmt_for->c1 = c1;
   a->d.stmt_for->c2 = c2;
   a->d.stmt_for->c3 = c3;
   a->d.stmt_for->body = body;
   a->pos = pos;
   a->d.stmt_for->pos = pos;
   a->d.stmt_for->self = a;
   return a;
 }
new_stmt_from_gotolabel()
Stmt* new_stmt_from_gotolabel (m_str xid, m_bool is_label, int pos)
Definition at line 981 of file absyn.c.
References ae_stmt_gotolabel, Stmt::d, insert_symbol(), Stmt_Goto_Label_::is_label, Stmt_Goto_Label_::name, Stmt::pos, Stmt_Goto_Label_::pos, Stmt_Goto_Label_::self, Stmt::stmt_gotolabel, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_gotolabel;
   a->d.stmt_gotolabel = calloc(1, sizeof(struct Stmt_Goto_Label_));
   a->d.stmt_gotolabel->name = insert_symbol( xid );
   a->d.stmt_gotolabel->is_label = is_label;
   a->pos = pos;
   a->d.stmt_gotolabel->pos = pos;
   a->d.stmt_gotolabel->self = a;
   return a;
 }
new_stmt_from_if()
Stmt* new_stmt_from_if (Expression cond, Stmt * if_body, Stmt * else_body, int pos)
Definition at line 1022 of file absyn.c.
References ae_stmt_if, Stmt_If_::cond, Stmt::d, Stmt_If_::else_body, Stmt_If_::if_body, Stmt::pos, Stmt_If_::pos, Stmt_If_::self, Stmt::stmt_if, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_if;
   a->d.stmt_if = calloc(1, sizeof(struct Stmt_If_));
   a->d.stmt_if->cond = cond;
   a->d.stmt_if->if_body = if_body;
   a->d.stmt_if->else_body = else_body;
   a->pos = pos;
   a->d.stmt_if->pos = pos;
   a->d.stmt_if->self = a;
   return a;
 }
new_stmt_from_loop()
Stmt* new_stmt_from_loop (Expression cond, Stmt * body, int pos)
Definition at line 1002 of file absyn.c.
References ae_stmt_loop, Stmt_Loop_::body, Stmt_Loop_::cond, Stmt::d, Stmt::pos, Stmt_Loop_::pos, Stmt_Loop_::self, Stmt::stmt_loop, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_loop;
   a->d.stmt_loop = calloc(1, sizeof(struct Stmt_Loop_));
   a->d.stmt_loop->cond = cond;
   a->d.stmt_loop->body = body;
   a->pos = pos;
   a->d.stmt_loop->pos = pos;
   a->d.stmt_loop->self = a;
   return a;
 }
new_stmt_from_return()
Stmt* new_stmt_from_return (Expression exp, int pos)
Definition at line 875 of file absyn.c.
References ae_stmt_return, Stmt::d, Stmt::pos, Stmt_Return_::pos, Stmt_Return_::self, Stmt::stmt_return, Stmt::type, and Stmt_Return_::val.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_return;
   a->d.stmt_return = calloc(1, sizeof(struct Stmt_Return_));
   a->d.stmt_return->val = exp;
   a->pos = pos;
   a->d.stmt_return->pos = pos;
   a->d.stmt_return->self = a;
   return a;
 }
new_stmt_from_switch()
Stmt* new_stmt_from_switch (Expression val, Stmt * stmt, int pos)
Definition at line 1044 of file absyn.c.
References ae_stmt_switch, Stmt::d, Stmt::pos, Stmt_Switch_::pos, Stmt_Switch_::self, Stmt_Switch_::stmt, Stmt::stmt_switch, Stmt::type, and Stmt_Switch_::val.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_switch;
   a->d.stmt_switch = calloc(1, sizeof(struct Stmt_Switch_));
   a->d.stmt_switch->val = val;
   a->d.stmt_switch->stmt = stmt;
   a->pos = pos;
   a->d.stmt_switch->pos = pos;
   a->d.stmt_switch->self = a;
   return a;
 }
new_stmt_from_Union()
Stmt* new_stmt_from_Union (Union * u, int pos)
Definition at line 1113 of file absyn.c.
References ae_stmt_union, Stmt::d, Stmt::pos, Stmt::stmt_union, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_union;
   a->d.stmt_union = u;
   a->pos = pos;
   return a;
 }
new_stmt_from_until()
Stmt* new_stmt_from_until (Expression cond, Stmt * body, m_bool is_do, int pos)
Definition at line 936 of file absyn.c.
References ae_stmt_until, Stmt_Until_::body, Stmt_Until_::cond, Stmt::d, Stmt_Until_::is_do, Stmt::pos, Stmt_Until_::pos, Stmt_Until_::self, Stmt::stmt_until, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_until;
   a->d.stmt_until = calloc(1, sizeof(struct Stmt_Until_));
   a->d.stmt_until->is_do = 0;
   a->d.stmt_until->cond = cond;
   a->d.stmt_until->body = body;
   a->pos = pos;
   a->d.stmt_until->pos = pos;
   a->d.stmt_until->self = a;
   return a;
 }
new_stmt_from_while()
Stmt* new_stmt_from_while (Expression cond, Stmt * body, m_bool is_do, int pos)
Definition at line 915 of file absyn.c.
References ae_stmt_while, Stmt_While_::body, Stmt_While_::cond, Stmt::d, Stmt_While_::is_do, Stmt::pos, Stmt_While_::pos, Stmt_While_::self, Stmt::stmt_while, and Stmt::type.
Referenced by yyparse().
 {
   Stmt* a = calloc(1, sizeof(Stmt));
   a->type = ae_stmt_while;
   a->d.stmt_while = calloc(1, sizeof(struct Stmt_While_));
   a->d.stmt_while->is_do = is_do;
   a->d.stmt_while->cond = cond;
   a->d.stmt_while->body = body;
   a->pos = pos;
   a->d.stmt_while->pos = pos;
   a->d.stmt_while->self = a;
   return a;
 }
new_Stmt_List()
Stmt_List new_Stmt_List (Stmt * stmt, Stmt_List next, int pos)
Definition at line 1212 of file absyn.c.
References Stmt_List_::next, and Stmt_List_::stmt.
Referenced by yyparse().
 {
   Stmt_List list = calloc(1, sizeof(struct Stmt_List_));
   list->stmt = stmt;
   list->next = next;
   return list;
 }
new_Type_Decl()
Type_Decl* new_Type_Decl (ID_List xid, int ref, int pos)
Definition at line 74 of file absyn.c.
References Type_Decl::array, Type_Decl::doc, Type_Decl::dot, Type_Decl::pos, Type_Decl::ref, and Type_Decl::xid.
Referenced by emit_Unary(), import_var(), make_dll_arg_list(), make_dll_as_fun(), new_exp_from_unary3(), and yyparse().
 {
   Type_Decl* a = calloc(1, sizeof(Type_Decl));
   a->xid = xid;
   a->ref = ref;
   a->pos = pos;
   a->array = NULL;
   a->dot = NULL;
   a->doc = NULL;
   return a;
 }
new_Type_Decl_from_dot()
Type_Decl* new_Type_Decl_from_dot (Dot_Member * dot, int ref, int pos)
Definition at line 86 of file absyn.c.
References Type_Decl::array, Type_Decl::dot, Type_Decl::pos, Type_Decl::ref, and Type_Decl::xid.
 {
   Type_Decl* a = calloc(1, sizeof(Type_Decl));
   a->xid = NULL;
   a->ref = ref;
   a->pos = pos;
   a->array = NULL;
   a->dot = dot;
   return a;
 }
new_type_list()
Type_List new_type_list (ID_List list, Type_List next, int pos)
Definition at line 1391 of file absyn.c.
References Type_List_::list, Type_List_::next, and Type_List_::pos.
Referenced by mk_type_list(), and yyparse().
 {
   Type_List a = calloc(1,  sizeof(struct Type_List_));
   a->list = list;
   a->next = next;
   a->pos = pos;
   return a;
 }
new_Union()
Union* new_Union (Decl_List l)
Definition at line 1147 of file absyn.c.
References Union::l, malloc(), new_Vector(), Union::s, and Union::v.
Referenced by yyparse().
 {
   Union* a = malloc(sizeof(Union));
   a->l = l;
   a->v = new_Vector();
   a->s = 0;
 //  a->o = 0;
   return a;
 }
new_Var_Decl()
Var_Decl new_Var_Decl (m_str name, Array_Sub array, int pos)
Definition at line 20 of file absyn.c.
References Var_Decl_::array, insert_symbol(), Var_Decl_::pos, and Var_Decl_::xid.
Referenced by import_var(), make_dll_arg_list(), and yyparse().
 {
   Var_Decl a = calloc(1, sizeof(struct Var_Decl_));
   a->xid = insert_symbol(name);
   a->array = array;
   a->pos = pos;
   return a;
 }
new_Var_Decl_List()
Var_Decl_List new_Var_Decl_List (Var_Decl decl, Var_Decl_List list, int pos)
Definition at line 53 of file absyn.c.
References Var_Decl_List_::doc, Var_Decl_List_::next, Var_Decl_List_::pos, and Var_Decl_List_::self.
Referenced by import_var(), and yyparse().
 {
   Var_Decl_List a = calloc(1, sizeof(struct Var_Decl_List_));
   a->self = decl;
   a->next = list;
   a->pos = pos;
   a->doc = NULL;
   return a;
 }
new_Vec()
Vec new_Vec (Expression e, int pos)
Definition at line 502 of file absyn.c.
References Vec_::args, Expression_::next, Vec_::numdims, and Vec_::pos.
Referenced by yyparse().
 {
   Vec a = calloc(1, sizeof(struct Vec_));
   a->args = e;
   while(e) {
     a->numdims++;
     e = e->next;
   }
   a->pos = pos;
   return a;
 }
prepend_array_sub()
Array_Sub prepend_array_sub (Array_Sub a, Expression exp, int pos)
Definition at line 107 of file absyn.c.
References Array_Sub_::depth, Array_Sub_::err_num, Array_Sub_::err_pos, Array_Sub_::exp_list, free_Expression(), Expression_::next, and Expression_::pos.
Referenced by make_dll_arg_list(), make_dll_as_fun(), and yyparse().
 {
   if(a->err_num)
     goto error;
   if(exp && exp->next) {
     a->err_num = 1;
     a->err_pos = exp->pos;
     goto error;
   }
   if((exp && !a->exp_list) || (!exp && a->exp_list)) {
     a->err_num = 2;
     a->err_pos = pos;
     goto error;
   }
   if(exp) {
     exp->next = a->exp_list;
     a->exp_list = exp;
   }
   a->depth++;
   return a;
 error:
   free_Expression(exp);
   return a;
 }
prepend_class_body()
Class_Body prepend_class_body (Section * section, Class_Body body, int pos)
Definition at line 1343 of file absyn.c.
References new_class_body(), Class_Body_::next, and Class_Body_::pos.
Referenced by yyparse().
 {
   Class_Body a = new_class_body(section, pos);
   a->next = body;
   a->pos = pos;
   return a;
 }
prepend_Expression()
Expression prepend_Expression (Expression exp, Expression next, int pos)
Definition at line 752 of file absyn.c.
References Expression_::next.
Referenced by yyparse().
 {
   exp->next = next;
   return exp;
 }
prepend_id_list()
ID_List prepend_id_list (const m_str xid, ID_List list, int pos)
Definition at line 1369 of file absyn.c.
References new_id_list(), ID_List_::next, and ID_List_::pos.
Referenced by mk_type_list(), str2list(), and yyparse().
 {
   ID_List a = new_id_list(xid, pos);
   a->next = list;
   a->pos = pos;
   return a;
 }