Gwion dev-docs: drvr/alsa.c File Reference
--- layout: default title: alsa_8c/ image: feature: abstract-1.jpg ---
alsa.c File Reference
#include <alsa/asoundlib.h>
#include <alsa/mixer.h>
#include "err_msg.h"
#include "vm.h"
#include "bbq.h"
#include "oo.h"
#include "type.h"
#include "dl.h"
#include "ugen.h"
#include "driver.h"
#include "alsa.h"
Macros
#define ALSA_FORMAT SND_PCM_FORMAT_FLOAT
Functions
static int sp_alsa_init (DriverInfo *di, snd_pcm_t **h, const char *device, int stream, int mode)
static m_bool alsa_ini (VM *vm, DriverInfo *di)
static void alsa_run (VM *vm, DriverInfo *di)
static void alsa_del (VM *vm)
Driver * alsa_driver (VM *vm)
Variables
static snd_pcm_t * out = NULL
static snd_pcm_t * in = NULL
static SPFLOAT ** in_buf = NULL
static SPFLOAT ** out_buf = NULL
static void ** _in_buf = NULL
static void ** _out_buf = NULL
void * in_bufi
void * out_bufi
Macro Definition Documentation
ALSA_FORMAT
#define ALSA_FORMAT SND_PCM_FORMAT_FLOAT
Definition at line 16 of file alsa.c.
Referenced by sp_alsa_init().
Function Documentation
alsa_del()
static void alsa_del (VM * vm) static
Definition at line 157 of file alsa.c.
References _in_buf, _out_buf, VM::bbq, free(), in, in_buf, in_bufi, out, out_buf, out_bufi, BBQ_::sp, and SP_ALSA_ACCESS.
Referenced by alsa_driver().
 {
   m_uint chan;
   snd_pcm_close(in);
 //  snd_pcm_hw_free(in);
   snd_pcm_close(out);
 //  snd_pcm_hw_free(out);
   snd_config_update_free_global();
 //snd_dlclose(out);
 //snd_dlclose(in);
   if(SP_ALSA_ACCESS == SND_PCM_ACCESS_RW_NONINTERLEAVED) {
     if(in_buf && out_buf) {
       for(chan = 0; chan < vm->bbq->sp->nchan; chan++) {
         free(in_buf[chan]);
         free(out_buf[chan]);
       }
       free(in_buf);
       free(out_buf);
     }
     if(_in_buf)
       free(_in_buf);
     if(_out_buf)
       free(_out_buf);
   } else { /* interleaved */
     if(in_bufi)
       free(in_bufi);
     if(out_bufi)
       free(out_bufi);
   }
 }
alsa_driver()
Driver* alsa_driver (VM * vm)
Definition at line 188 of file alsa.c.
References alsa_del(), alsa_ini(), alsa_run(), driver_wrapper::del, driver_wrapper::ini, malloc(), no_wakeup(), driver_wrapper::run, and VM::wakeup.
Referenced by no_wakeup(), select_driver(), and select_format().
 {
   Driver* d = malloc(sizeof(Driver));
   d->ini = alsa_ini;
   d->run = alsa_run;
   d->del = alsa_del;
   vm->wakeup = no_wakeup;
   return d;
 }
alsa_ini()
static m_bool alsa_ini (VM * vm, DriverInfo * di) static
Definition at line 73 of file alsa.c.
References ALSA_, containing_driver_info::card, containing_driver_info::chan, err_msg(), containing_driver_info::in, in, containing_driver_info::out, out, and sp_alsa_init().
Referenced by alsa_driver().
 {
   out = NULL;
   if(sp_alsa_init(di, &out, di->card, SND_PCM_STREAM_PLAYBACK, 0) < 0) {
     err_msg(ALSA_, 0, "problem with playback");
     return -1;
   }
   di->out = di->chan;
   in = NULL;
   if(sp_alsa_init(di, &in,  di->card, SND_PCM_STREAM_CAPTURE, SND_PCM_ASYNC | SND_PCM_NONBLOCK) < 0) {
     err_msg(ALSA_, 0, "problem with capture");
     return -1;
   }
   di->in = di->chan;
   return 1;
 }
alsa_run()
static void alsa_run (VM * vm, DriverInfo * di) static
Definition at line 90 of file alsa.c.
References _in_buf, _out_buf, VM::bbq, containing_driver_info::bufnum, containing_driver_info::bufsize, BBQ_::in, in, in_buf, in_bufi, VM::is_running, out, out_buf, out_bufi, BBQ_::sp, SP_ALSA_ACCESS, and vm_run().
Referenced by alsa_driver().
 {
   m_uint i, chan;
   BBQ bbq = vm->bbq;
   sp_data* sp = vm->bbq->sp;
   snd_pcm_get_params(out, &di->bufsize, &di->bufnum);
   di->bufsize /= di->bufnum;
   if(SP_ALSA_ACCESS == SND_PCM_ACCESS_RW_NONINTERLEAVED) {
     in_buf  = calloc(sp->nchan, sizeof(SPFLOAT*));
     out_buf = calloc(sp->nchan, sizeof(SPFLOAT*));
     _out_buf   = calloc(sp->nchan, sizeof(void*));
     _in_buf    = calloc(sp->nchan, sizeof(void*));
     for(chan = 0; chan < sp->nchan; chan++) {
       out_buf[chan]  = calloc(di->bufsize, sizeof(SPFLOAT));
       _out_buf[chan] = out_buf[chan];
       in_buf[chan]   = calloc(di->bufsize, sizeof(SPFLOAT));
       _in_buf[chan]  = in_buf[chan];
     }
     snd_pcm_hwsync(out);
     snd_pcm_hwsync(in);
     snd_pcm_start(out);
     snd_pcm_start(in);
     while(vm->is_running) {
       snd_pcm_readn(in, _in_buf, di->bufsize);
       for(i = 0; i < di->bufsize; i++) {
         for(chan = 0; chan < sp->nchan; chan++)
           bbq->in[chan] = ((m_float**)(_in_buf))[chan][i];
         vm_run(vm);
         for(chan = 0; chan < sp->nchan; chan++)
           out_buf[chan][i] = sp->out[chan];
         sp->pos++;
       }
       snd_pcm_writen(out, _out_buf, di->bufsize);
     }
   } else { // interleaved
     in_bufi  = calloc(sp->nchan * di->bufsize, sizeof(SPFLOAT));
     out_bufi = calloc(sp->nchan * di->bufsize, sizeof(SPFLOAT));
     snd_pcm_hwsync(out);
     snd_pcm_hwsync(in);
     snd_pcm_start(out);
     snd_pcm_start(in);
     while(vm->is_running) {
       int j = 0;
       int k = 0;
       sp->nchan = 2;
       snd_pcm_readi(in, in_bufi, di->bufsize);
       for(i = 0; i < di->bufsize; i++) {
         for(chan = 0; chan < sp->nchan; chan++) {
           bbq->in[chan] = ((m_float*)(in_bufi))[j];
           j++;
         }
         vm_run(vm);
         for(chan = 0; chan < sp->nchan; chan++) {
           ((m_float*)out_bufi)[k] = sp->out[chan];
           k++;
         }
         sp->pos++;
       }
       snd_pcm_writei(out, out_bufi, di->bufsize);
     }
   }
 }
sp_alsa_init()
static int sp_alsa_init (DriverInfo * di, snd_pcm_t ** h, const char * device, int stream, int mode) static
Definition at line 26 of file alsa.c.
References ALSA_FORMAT, containing_driver_info::bufnum, containing_driver_info::bufsize, containing_driver_info::chan, SP_ALSA_ACCESS, and containing_driver_info::sr.
Referenced by alsa_ini().
 {
   snd_pcm_t* handle = NULL;
   snd_pcm_hw_params_t* params;
   unsigned int num = di->bufnum;
   int dir = 0;
   if(snd_pcm_open(&handle, device, stream, mode) > 0 || !handle)
     return -1;
   snd_pcm_hw_params_alloca(&params);
   if(snd_pcm_hw_params_any(handle, params) > 0) {
     snd_pcm_close(handle);
     return -1;
   }
   if(!snd_pcm_hw_params_test_access(handle, params, SP_ALSA_ACCESS))
     snd_pcm_hw_params_set_access(handle, params, SP_ALSA_ACCESS);
   if(!snd_pcm_hw_params_test_format(handle, params, ALSA_FORMAT))
     snd_pcm_hw_params_set_format(handle, params, ALSA_FORMAT);
   if(!snd_pcm_hw_params_test_rate(handle, params, di->sr, dir))
     snd_pcm_hw_params_set_rate_near(handle, params, &di->sr, &dir);
   if(!snd_pcm_hw_params_test_channels(handle, params, di->chan))
     snd_pcm_hw_params_set_channels(handle, params, di->chan);
   else return -1;;
   if(snd_pcm_hw_params_set_period_size_near(handle, params, &di->bufsize, &dir))
     return -1;
   if(snd_pcm_hw_params_set_periods_near(handle, params, &num, &dir))
     return -1;
   di->bufnum = num;
   if(snd_pcm_hw_params(handle, params))
     return -1;
   snd_pcm_hw_params_get_rate_max(params, &di->sr, &dir);
   snd_pcm_hw_params_set_rate_near(handle, params, &di->sr, &dir);
   *h = handle;
   return 1;
 }
Variable Documentation
_in_buf
void** _in_buf = NULL static
Definition at line 21 of file alsa.c.
Referenced by alsa_del(), and alsa_run().
_out_buf
void ** _out_buf = NULL static
Definition at line 21 of file alsa.c.
Referenced by alsa_del(), and alsa_run().
in
snd_pcm_t * in = NULL static
Definition at line 19 of file alsa.c.
Referenced by alsa_del(), alsa_ini(), alsa_run(), callback(), gwion_cb(), and zerox_tick().
in_buf
SPFLOAT** in_buf = NULL static
Definition at line 20 of file alsa.c.
Referenced by alsa_del(), and alsa_run().
in_bufi
void* in_bufi
Definition at line 23 of file alsa.c.
Referenced by alsa_del(), and alsa_run().
out
snd_pcm_t* out = NULL static
Definition at line 19 of file alsa.c.
Referenced by alsa_del(), alsa_ini(), alsa_run(), callback(), channel_compute(), and gwion_cb().
out_buf
SPFLOAT ** out_buf = NULL static
Definition at line 20 of file alsa.c.
Referenced by alsa_del(), and alsa_run().
out_bufi
void* out_bufi
Definition at line 24 of file alsa.c.
Referenced by alsa_del(), and alsa_run().