Gwion dev-docs: lang/array.c File Reference
--- layout: homepage title: array_8c/ image: feature: abstract-1.jpg ---
array.c File Reference
#include "defs.h"
#include "vm.h"
#include "type.h"
#include "err_msg.h"
#include "instr.h"
#include "lang.h"
#include "import.h"
#include "object.h"
Functions
DTOR (array_dtor)
M_Object new_M_Array (m_uint size, m_uint length, m_uint depth)
m_uint m_vector_size (M_Vector *v)
m_uint i_vector_at (M_Vector *v, m_uint i)
m_float f_vector_at (M_Vector *v, m_uint i)
m_complex c_vector_at (M_Vector *v, m_uint i)
VEC3_T v3_vector_at (M_Vector *v, m_uint i)
VEC4_T v4_vector_at (M_Vector *v, m_uint i)
void i_vector_append (M_Vector *v, m_uint i)
void f_vector_append (M_Vector *v, m_float f)
void c_vector_append (M_Vector *v, m_complex c)
void v3_vector_append (M_Vector *v, VEC3_T c)
void v4_vector_append (M_Vector *v, VEC4_T c)
void i_vector_set (M_Vector *v, m_uint i, m_uint data)
void f_vector_set (M_Vector *v, m_uint i, m_float data)
m_uint * i_vector_addr (M_Vector *v, m_uint i)
m_float * f_vector_addr (M_Vector *v, m_uint i)
m_complex * c_vector_addr (M_Vector *v, m_uint i)
VEC3_T * v3_vector_addr (M_Vector *v, m_uint i)
VEC4_T * v4_vector_addr (M_Vector *v, m_uint i)
MFUN (vm_vector_size)
INSTR (Array_Append)
m_bool import_array (Env env)
Variables
struct Type_ t_array = { "@Array", SZ_INT, &t_object, te_array }
m_int o_array_vector
Function Documentation
c_vector_addr()
m_complex* c_vector_addr (M_Vector * v, m_uint i)
Definition at line 151 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return &*(m_complex*)(v->ptr + i * v->size);
 }
c_vector_append()
void c_vector_append (M_Vector * v, m_complex c)
Definition at line 89 of file array.c.
References M_Vector::len, M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   v->len++;
   v->ptr = realloc(v->ptr, v->len * v->size);
   *(m_complex*)(v->ptr + (v->len - 1)*v->size) = c;
 }
c_vector_at()
m_complex c_vector_at (M_Vector * v, m_uint i)
Definition at line 60 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return *(m_complex*)(v->ptr + i * v->size);
 }
DTOR()
DTOR (array_dtor)
Definition at line 14 of file array.c.
References err_msg(), free(), INSTR_, isa(), release(), and t_object.
 {
   if(o->type_ref->array_type) // maybe unnecessary. preferably check array depth
     if(o->d.array->depth > 1 || isa(o->type_ref->array_type, &t_object) > 0) {
       m_uint i;
       for(i = 0; i < o->d.array->len; i += SZ_INT)
         release(*(M_Object*)(o->d.array->ptr + i), shred);
   }
   free(o->d.array->ptr);
 // should not compare to t_array. see new_M_Array(Type t, ...
   if(o->type_ref != &t_array) {
     if(!--o->type_ref->obj->ref_count) {
       free(o->type_ref->obj);
       free(o->type_ref);
     }
   } else err_msg(INSTR_, 0, "array type not valid. please fix and implement a better new M_Array");
 }
f_vector_addr()
m_float* f_vector_addr (M_Vector * v, m_uint i)
Definition at line 146 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return &*(m_float*)(v->ptr + i * v->size);
 }
f_vector_append()
void f_vector_append (M_Vector * v, m_float f)
Definition at line 82 of file array.c.
References M_Vector::len, M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   v->len++;
   v->ptr = realloc(v->ptr, v->len * v->size);
   *(m_float*)(v->ptr + (v->len - 1)*v->size) = f;
 }
f_vector_at()
m_float f_vector_at (M_Vector * v, m_uint i)
Definition at line 55 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return *(m_float*)(v->ptr + i * v->size);
 }
f_vector_set()
void f_vector_set (M_Vector * v, m_uint i, m_float data)
Definition at line 116 of file array.c.
References M_Vector::len, M_Vector::ptr, and M_Vector::size.
Referenced by MFUN().
 {
   v->ptr = realloc(v->ptr, v->len * v->size);
   *(m_float*)(v->ptr + i * v->size) = data;
 }
i_vector_addr()
m_uint* i_vector_addr (M_Vector * v, m_uint i)
Definition at line 141 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by do_alloc_array(), and INSTR().
 {
   return &*(m_uint*)(v->ptr + i * v->size);
 }
i_vector_append()
void i_vector_append (M_Vector * v, m_uint i)
Definition at line 75 of file array.c.
References M_Vector::len, M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   v->len++;
   v->ptr = realloc(v->ptr, v->len * v->size);
   *(m_uint*)(v->ptr + (v->len - 1)*v->size) = i;
 }
i_vector_at()
m_uint i_vector_at (M_Vector * v, m_uint i)
Definition at line 50 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return *(m_uint*)(v->ptr + i * v->size);
 }
i_vector_set()
void i_vector_set (M_Vector * v, m_uint i, m_uint data)
Definition at line 110 of file array.c.
References M_Vector::len, M_Vector::ptr, and M_Vector::size.
Referenced by do_alloc_array(), INSTR(), and SFUN().
 {
   v->ptr = realloc(v->ptr, v->len * v->size);
   *(m_uint*)(v->ptr + i * v->size) = data;
 }
import_array()
m_bool import_array (Env env)
Definition at line 201 of file array.c.
References add_global_type(), CHECK_BB, CHECK_OB, Env_::class_def, Type_::doc, Env_::global_nspc, import_class_begin(), import_class_end(), import_mfun(), and new_DL_Func().
Referenced by type_engine_init().
 {
   DL_Func* fun;
   CHECK_BB(add_global_type(env, &t_array))
   CHECK_OB(import_class_begin(env, &t_array, env->global_nspc, NULL, array_dtor))
   fun = new_DL_Func("int", "size", (m_uint)vm_vector_size);
   CHECK_OB(import_mfun(env, fun))
   env->class_def->doc = "vector structure";
   CHECK_BB(import_class_end(env))
   return 1;
 }
INSTR()
INSTR (Array_Append)
Definition at line 171 of file array.c.
References M_Object_::array, c_vector_append(), M_Object_::d, f_vector_append(), i_vector_append(), Kindof_Complex, Kindof_Float, Kindof_Int, Kindof_Vec3, Kindof_Vec4, POP_REG, PUSH_REG, release(), v3_vector_append(), and v4_vector_append().
 {
   POP_REG(shred, SZ_INT);
   M_Object o = NULL;
   if(instr->m_val == Kindof_Int) {
     POP_REG(shred, SZ_INT);
     o = *(M_Object*)(shred->reg);
     i_vector_append(o->d.array, *(m_uint*)(shred->reg + SZ_INT));
   } else if(instr->m_val == Kindof_Float) {
     POP_REG(shred, SZ_FLOAT);
     o = *(M_Object*)(shred->reg);
     f_vector_append(o->d.array, *(m_float*)(shred->reg + SZ_INT));
   } else if(instr->m_val == Kindof_Complex) {
     POP_REG(shred, SZ_COMPLEX);
     o = *(M_Object*)(shred->reg);
     c_vector_append(o->d.array, *(m_complex*)(shred->reg + SZ_INT));
   } else if(instr->m_val == Kindof_Vec3) {
     POP_REG(shred, SZ_VEC3);
     o = *(M_Object*)(shred->reg);
     v3_vector_append(o->d.array, *(VEC3_T*)(shred->reg + SZ_INT));
   } else if(instr->m_val == Kindof_Vec4) {
     POP_REG(shred, SZ_VEC4);
     o = *(M_Object*)(shred->reg);
     v4_vector_append(o->d.array, *(VEC4_T*)(shred->reg + SZ_INT));
   }
   release(o, shred);
   *(M_Object*)(shred->reg) = o;
   PUSH_REG(shred, SZ_INT);
 }
m_vector_size()
m_uint m_vector_size (M_Vector * v)
Definition at line 44 of file array.c.
References M_Vector::len, and M_Vector::size.
Referenced by INSTR(), and MFUN().
 {
   return v->len / v->size;
   /*  return v->len;*/
 }
MFUN()
MFUN (vm_vector_size)
Definition at line 166 of file array.c.
References m_vector_size(), and RETURN.
 {
   RETURN->d.v_uint = o ? m_vector_size(o->d.array) : - 1;
 }
new_M_Array()
M_Object new_M_Array (m_uint size, m_uint length, m_uint depth)
Definition at line 32 of file array.c.
References M_Object_::array, M_Object_::d, M_Vector::depth, initialize_object(), M_Vector::len, malloc(), new_M_Object(), M_Vector::ptr, M_Vector::size, and Type_::size.
Referenced by do_alloc_array(), INSTR(), MFUN(), and SFUN().
 {
   M_Object a = new_M_Object();
   initialize_object(a, &t_array);
   a->d.array        = malloc(sizeof(M_Vector));
   a->d.array->ptr   = calloc(length, size);
   a->d.array->size  = size;
   a->d.array->len   = length * size;
   a->d.array->depth = depth;
   return a;
 }
v3_vector_addr()
VEC3_T* v3_vector_addr (M_Vector * v, m_uint i)
Definition at line 156 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return &*(VEC3_T*)(v->ptr + i * v->size);
 }
v3_vector_append()
void v3_vector_append (M_Vector * v, VEC3_T c)
Definition at line 96 of file array.c.
References M_Vector::len, M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   v->len++;
   v->ptr = realloc(v->ptr, v->len * v->size);
   *(VEC3_T*)(v->ptr + (v->len - 1)*v->size) = c;
 }
v3_vector_at()
VEC3_T v3_vector_at (M_Vector * v, m_uint i)
Definition at line 65 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return *(VEC3_T*)(v->ptr + i * v->size);
 }
v4_vector_addr()
VEC4_T* v4_vector_addr (M_Vector * v, m_uint i)
Definition at line 161 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return &*(VEC4_T*)(v->ptr + i * v->size);
 }
v4_vector_append()
void v4_vector_append (M_Vector * v, VEC4_T c)
Definition at line 103 of file array.c.
References M_Vector::len, M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   v->len++;
   v->ptr = realloc(v->ptr, v->len * v->size);
   *(VEC4_T*)(v->ptr + (v->len - 1)*v->size) = c;
 }
v4_vector_at()
VEC4_T v4_vector_at (M_Vector * v, m_uint i)
Definition at line 70 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return *(VEC4_T*)(v->ptr + i * v->size);
 }
Variable Documentation
o_array_vector
m_int o_array_vector
Definition at line 12 of file array.c.
t_array
struct Type_ t_array = { "@Array", SZ_INT, &t_object, te_array }
Definition at line 11 of file array.c.
Referenced by check_array_lit(), check_Unary(), scan1_Func_Def(), scan2_Decl_Expression(), scan2_Func_Def(), scan2_Func_Ptr(), and SFUN().