Gwion dev-docs: include/array.h File Reference
--- layout: default title: array_8h/ image: feature: abstract-1.jpg ---
array.h File Reference
#include <complex.h>
#include "map.h"
Data Structures
struct VM_Array_Info
struct M_Vector
struct VM_Array_
Typedefs
typedef struct VM_Vector_ * VM_Vector
Functions
m_uint m_vector_size (M_Vector *v)
m_uint i_vector_at (M_Vector *v, m_uint i)
m_float f_vector_at (M_Vector *v, m_uint i)
complex float c_vector_at (M_Vector *v, m_uint i)
VEC3_T v3_vector_at (M_Vector *v, m_uint i)
VEC4_T v4_vector_at (M_Vector *v, m_uint i)
m_uint * i_vector_addr (M_Vector *v, m_uint i)
m_float * f_vector_addr (M_Vector *v, m_uint i)
complex float * c_vector_addr (M_Vector *v, m_uint i)
VEC3_T * v3_vector_addr (M_Vector *v, m_uint i)
VEC4_T * v4_vector_addr (M_Vector *v, m_uint i)
void i_vector_set (M_Vector *v, m_uint i, m_uint data)
void f_vector_set (M_Vector *v, m_uint i, m_float data)
M_Object new_M_Array (m_uint size, m_uint length, m_uint depth)
Typedef Documentation
VM_Vector
typedef struct VM_Vector_* VM_Vector
Definition at line 6 of file array.h.
Function Documentation
c_vector_addr()
complex float* c_vector_addr (M_Vector * v, m_uint i)
Definition at line 151 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return &*(m_complex*)(v->ptr + i * v->size);
 }
c_vector_at()
complex float c_vector_at (M_Vector * v, m_uint i)
Definition at line 60 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return *(m_complex*)(v->ptr + i * v->size);
 }
f_vector_addr()
m_float* f_vector_addr (M_Vector * v, m_uint i)
Definition at line 146 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return &*(m_float*)(v->ptr + i * v->size);
 }
f_vector_at()
m_float f_vector_at (M_Vector * v, m_uint i)
Definition at line 55 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return *(m_float*)(v->ptr + i * v->size);
 }
f_vector_set()
void f_vector_set (M_Vector * v, m_uint i, m_float data)
Definition at line 116 of file array.c.
References M_Vector::len, M_Vector::ptr, and M_Vector::size.
Referenced by MFUN().
 {
   v->ptr = realloc(v->ptr, v->len * v->size);
   *(m_float*)(v->ptr + i * v->size) = data;
 }
i_vector_addr()
m_uint* i_vector_addr (M_Vector * v, m_uint i)
Definition at line 141 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by do_alloc_array(), and INSTR().
 {
   return &*(m_uint*)(v->ptr + i * v->size);
 }
i_vector_at()
m_uint i_vector_at (M_Vector * v, m_uint i)
Definition at line 50 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return *(m_uint*)(v->ptr + i * v->size);
 }
i_vector_set()
void i_vector_set (M_Vector * v, m_uint i, m_uint data)
Definition at line 110 of file array.c.
References M_Vector::len, M_Vector::ptr, and M_Vector::size.
Referenced by do_alloc_array(), INSTR(), and SFUN().
 {
   v->ptr = realloc(v->ptr, v->len * v->size);
   *(m_uint*)(v->ptr + i * v->size) = data;
 }
m_vector_size()
m_uint m_vector_size (M_Vector * v)
Definition at line 44 of file array.c.
References M_Vector::len, and M_Vector::size.
Referenced by INSTR(), and MFUN().
 {
   return v->len / v->size;
   /*  return v->len;*/
 }
new_M_Array()
M_Object new_M_Array (m_uint size, m_uint length, m_uint depth)
Definition at line 32 of file array.c.
References M_Object_::array, M_Object_::d, M_Vector::depth, initialize_object(), M_Vector::len, malloc(), new_M_Object(), M_Vector::ptr, M_Vector::size, and Type_::size.
Referenced by do_alloc_array(), INSTR(), MFUN(), and SFUN().
 {
   M_Object a = new_M_Object();
   initialize_object(a, &t_array);
   a->d.array        = malloc(sizeof(M_Vector));
   a->d.array->ptr   = calloc(length, size);
   a->d.array->size  = size;
   a->d.array->len   = length * size;
   a->d.array->depth = depth;
   return a;
 }
v3_vector_addr()
VEC3_T* v3_vector_addr (M_Vector * v, m_uint i)
Definition at line 156 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return &*(VEC3_T*)(v->ptr + i * v->size);
 }
v3_vector_at()
VEC3_T v3_vector_at (M_Vector * v, m_uint i)
Definition at line 65 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return *(VEC3_T*)(v->ptr + i * v->size);
 }
v4_vector_addr()
VEC4_T* v4_vector_addr (M_Vector * v, m_uint i)
Definition at line 161 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return &*(VEC4_T*)(v->ptr + i * v->size);
 }
v4_vector_at()
VEC4_T v4_vector_at (M_Vector * v, m_uint i)
Definition at line 70 of file array.c.
References M_Vector::ptr, and M_Vector::size.
Referenced by INSTR().
 {
   return *(VEC4_T*)(v->ptr + i * v->size);
 }