Gwion dev-docs: include/compile.h File Reference
--- layout: default title: compile_8h/ image: feature: abstract-1.jpg ---
compile.h File Reference
Functions
m_bool compile (VM *vm, const m_str filename)
void set_nspc_vm (VM *vm)
Function Documentation
compile()
m_bool compile (VM * vm, const m_str filename)
Definition at line 6 of file compile.c.
References add_instr(), VM_Shred_::args, CHECK_BB, clean, Emitter_::code, COMPILE_, VM::emit, emit_Ast(), emit_to_code(), VM::env, EOC(), err_msg(), Code::filename, free(), free_Ast(), insert_symbol(), VM_Shred_::me, Code::name, new_Shred(), new_Vector(), new_VM_Shred(), parse(), S_name(), type_engine_check_prog(), vector_append(), and vm_add_shred().
Referenced by main(), server_thread(), and SFUN().
 {
   m_bool ret = 1;
   VM_Shred shred;
   VM_Code  code;
   Ast      ast;
   Vector args = NULL;
   m_str _name, name, d = strdup(filename);
   _name = strsep(&d, ":");
   if(d)
     args = new_Vector();
   while(d)
     vector_append(args, (vtype)S_name(insert_symbol(strsep(&d, ":"))));
   free(d);
   name = realpath(_name, NULL);
   free(_name);
   if(!name) {
     err_msg(COMPILE_, 0, "error while opening file '%s'", filename);
     return -1;
   }
 #ifdef DEBUG_COMPILE
   debug_msg("parser", "get full path ok %s", name);
 #endif
 //    CHECK_OB((ast = parse(name)))
   if(!(ast = parse(name))) {
     ret = -1;
     goto clean;
   }
 #ifdef DEBUG_COMPILE
   debug_msg("lexer", "Ast of '%s' ok", name);
 #endif
   CHECK_BB(type_engine_check_prog(vm->env, ast, name))
 #ifdef DEBUG_COMPILE
   debug_msg("lexer", "type check  of '%s' ok", name);
 #endif
   CHECK_BB(emit_Ast(vm->emit, ast, name))
 #ifdef DEBUG_COMPILE
   debug_msg("lexer", "emit   of '%s' ok", name);
 #endif
   add_instr(vm->emit, EOC);
   vm->emit->code->name = strdup(name);
   vm->emit->code->filename = strdup(name);
   code = emit_to_code(vm->emit);
   free_Ast(ast);
   shred = new_VM_Shred(code);
   shred->args = args;
   shred->me = new_Shred(vm, shred);
   vm_add_shred(vm, shred);
 clean:
   free(name);
   return ret;
 }
set_nspc_vm()
void set_nspc_vm (VM * vm)
Definition at line 11 of file namespace.c.
Referenced by main().
 {
   vm = _vm;
 }