context_8c/ – Gwion
Gwion
A strongly timed musical programming language
context_8c/
context.c File Reference
#include <stdlib.h>
#include <string.h>
#include "defs.h"
#include "context.h"
#include "func.h"
Functions
void context_add_type (Context context, Type type, VM_Object obj)
void context_add_value (Context context, Value value, VM_Object obj)
void context_add_class (Context context, Value value, VM_Object obj)
void context_add_func (Context context, Func func, VM_Object obj)
Context new_Context (Ast prog, m_str filename)
void free_Context (Context a)
int load_context (Context context, Env env)
int unload_context (Context context, Env env)
Function Documentation
context_add_class()
void context_add_class (Context context, Value value, VM_Object obj)
Definition at line 19 of file context.c.
References Context_::new_class, VM_Object_::ref, and vector_append().
Referenced by scan0_Class_Def().
 {
   obj->ref = context->new_class;
   vector_append(context->new_class, (vtype)value);
 }
context_add_func()
void context_add_func (Context context, Func func, VM_Object obj)
Definition at line 25 of file context.c.
References Context_::new_funcs, VM_Object_::ref, and vector_append().
Referenced by scan2_Func_Def().
 {
   obj->ref = context->new_funcs;
   vector_append(context->new_funcs, (vtype)func);
 }
context_add_type()
void context_add_type (Context context, Type type, VM_Object obj)
Definition at line 7 of file context.c.
References Context_::new_types, VM_Object_::ref, and vector_append().
Referenced by add_global_type(), and scan0_Class_Def().
 {
   obj->ref = context->new_types;
   vector_append(context->new_types, (vtype)type);
 }
context_add_value()
void context_add_value (Context context, Value value, VM_Object obj)
Definition at line 13 of file context.c.
References Context_::new_values, VM_Object_::ref, and vector_append().
Referenced by add_global_value(), add_global_value_double(), and scan2_Decl_Expression().
 {
   obj->ref = context->new_values;
   vector_append(context->new_values, (vtype)value);
 }
free_Context()
void free_Context (Context a)
Definition at line 48 of file context.c.
References ae_func_spec_op, Func_::def, free(), free_Vector(), Func_Def_::is_template, Value_::m_type, Value_::name, Type_::name, Context_::new_class, Context_::new_funcs, Context_::new_types, Context_::new_values, Context_::nspc, Func_::obj, NameSpace_::obj, Value_::obj, Type_::obj, rem_ref(), Func_Def_::spec, Func_::value_ref, vector_at(), and vector_size().
Referenced by rem_ref().
 {
   vtype i;
   for(i = 0; i < vector_size(a->new_funcs); i++) {
     Func f = (Func)vector_at(a->new_funcs, i);
     if(f->def->spec == ae_func_spec_op) {
       free(f->value_ref->name);
       free(f->value_ref->m_type->name);
       free(f->value_ref->m_type->obj);
       free(f->value_ref->m_type);
       rem_ref(f->value_ref->obj, f->value_ref);
       rem_ref(f->obj, f);
       continue;
     } else if(!f->def->is_template) {
       free(f->value_ref->m_type->name);
       rem_ref(f->value_ref->m_type->obj, f->value_ref->m_type);
       free(f->value_ref->name);
       rem_ref(f->value_ref->obj, f->value_ref);
     }
   }
   free_Vector(a->new_funcs);
   for(i = 0; i < vector_size(a->new_class); i++) {
     Value v = (Value)vector_at(a->new_class, i);
     rem_ref(v->m_type->obj, v->m_type);
     rem_ref(v->obj, v);
   }
   free_Vector(a->new_class);
   free_Vector(a->new_values);
   free_Vector(a->new_types);
   rem_ref(a->nspc->obj, a->nspc);
   free(a);
 }
load_context()
int load_context (Context context, Env env)
Definition at line 83 of file context.c.
References add_ref(), Env_::context, Env_::contexts, Env_::curr, namespace_push_value(), Context_::nspc, Env_::nspc_stack, Context_::obj, NameSpace_::parent, and vector_append().
Referenced by type_engine_check_prog().
 {
   vector_append(env->contexts, (vtype)env->context);
   env->context = context;
   add_ref(env->context->obj);
   namespace_push_value(context->nspc);
   vector_append(env->nspc_stack, (vtype)env->curr);
   context->nspc->parent = env->curr;
   env->curr = context->nspc;
   return 1;
 }
new_Context()
Context new_Context (Ast prog, m_str filename)
Definition at line 31 of file context.c.
References e_context_obj, Context_::filename, NameSpace_::filename, malloc(), NameSpace_::name, Context_::new_class, Context_::new_funcs, new_NameSpace(), Context_::new_types, Context_::new_values, new_Vector(), new_VM_Object(), Context_::nspc, Context_::obj, Context_::public_class_def, and Context_::tree.
Referenced by new_Env(), and type_engine_check_prog().
 {
   Context context = malloc(sizeof(struct Context_));
   context->nspc = new_NameSpace();
   context->nspc->filename = filename;
   context->tree = prog;
   context->filename = filename;
   context->nspc->name = filename;
   context->obj = new_VM_Object(e_context_obj);
   context->new_funcs = new_Vector();
   context->new_values = new_Vector();
   context->new_types = new_Vector();
   context->new_class = new_Vector();
   context->public_class_def = NULL;
   return context;
 }
unload_context()
int unload_context (Context context, Env env)
Definition at line 95 of file context.c.
References Env_::context, Env_::contexts, Env_::curr, namespace_pop_value(), Context_::nspc, Env_::nspc_stack, vector_back(), and vector_pop().
Referenced by type_engine_check_prog().
 {
   namespace_pop_value(env->context->nspc);
   env->curr = (NameSpace)vector_back(env->nspc_stack);
   vector_pop(env->nspc_stack);
 //  rem_ref(env->context->obj, env->context);
   env->context = (Context)vector_back(env->contexts);
   vector_pop(env->contexts);
   return 1;
 }