Gwion dev-docs: include/dl.h File Reference
dl.h File Reference
#include <stdlib.h>
#include <complex.h>
#include "defs.h"
#include "vm.h"
Data Structures
struct DL_Return
struct DL_Value
struct DL_Func
Macros
#define CK_DLL_CALL
Typedefs
typedef struct DL_Return DL_Return
typedef void(CK_DLL_CALL * f_ctor) (M_Object o, VM_Shred sh)
typedef void(CK_DLL_CALL * f_dtor) (M_Object o, VM_Shred sh)
typedef void(CK_DLL_CALL * f_mfun) (M_Object o, DL_Return *RETURN, VM_Shred sh)
typedef void(CK_DLL_CALL * f_sfun) (DL_Return *RETURN, VM_Shred sh)
typedef m_bool(CK_DLL_CALL * f_init) (Env env)
Functions
void dl_return_push (const DL_Return retval, VM_Shred shred, int kind)
void free_DL_Value (DL_Value *a)
DL_Func * new_DL_Func (const m_str t, const m_str n, m_uint addr)
void free_DL_Func (DL_Func *a)
DL_Value * dl_func_add_arg (DL_Func *a, const m_str t, const m_str n)
Macro Definition Documentation
CK_DLL_CALL
#define CK_DLL_CALL
Definition at line 10 of file dl.h.
Typedef Documentation
DL_Return
typedef struct DL_Return DL_Return
f_ctor
typedef void(CK_DLL_CALL * f_ctor) (M_Object o, VM_Shred sh)
Definition at line 26 of file dl.h.
f_dtor
typedef void(CK_DLL_CALL * f_dtor) (M_Object o, VM_Shred sh)
Definition at line 27 of file dl.h.
f_init
typedef m_bool(CK_DLL_CALL * f_init) (Env env)
Definition at line 30 of file dl.h.
f_mfun
typedef void(CK_DLL_CALL * f_mfun) (M_Object o, DL_Return *RETURN, VM_Shred sh)
Definition at line 28 of file dl.h.
f_sfun
typedef void(CK_DLL_CALL * f_sfun) (DL_Return *RETURN, VM_Shred sh)
Definition at line 29 of file dl.h.
Function Documentation
dl_func_add_arg()
DL_Value* dl_func_add_arg (DL_Func * a, const m_str t, const m_str n)
Definition at line 59 of file dl.c.
References DL_Func::args, new_DL_Value(), and vector_append().
Referenced by import_ana(), import_fc(), import_fft(), import_fileio(), import_gain(), import_impulse(), import_lib(), import_machine(), import_rolloff(), import_shred(), import_sinosc(), import_step(), import_string(), import_ugen(), import_vec3(), and import_vec4().
 {
   DL_Value* v = new_DL_Value( t, n, 0, NULL );
   vector_append(a->args, (vtype)v);
   return v;
 }
dl_return_push()
void dl_return_push (const DL_Return retval, VM_Shred shred, int kind)
Definition at line 4 of file dl.c.
References DL_Return::d, Kindof_Complex, Kindof_Float, Kindof_Int, Kindof_Vec3, Kindof_Vec4, PUSH_REG, VM_Shred_::reg, DL_Return::v_complex, DL_Return::v_float, DL_Return::v_uint, DL_Return::v_vec3, and DL_Return::v_vec4.
Referenced by INSTR().
 {
   if(kind == Kindof_Int) {
     *(m_uint*)shred->reg = retval.d.v_uint;
     PUSH_REG(shred, SZ_INT);
   } else if(kind == Kindof_Float) {
     *(m_float*)shred->reg = retval.d.v_float;
     PUSH_REG(shred, SZ_FLOAT);
   } else if(kind == Kindof_Complex) {
     *(m_complex*)shred->reg = retval.d.v_complex;
     PUSH_REG(shred, SZ_COMPLEX);
   } else if(kind == Kindof_Vec3) {
     *(VEC3_T*)shred->reg = retval.d.v_vec3;
     PUSH_REG(shred, SZ_VEC3);
   } else if(kind == Kindof_Vec4) {
     *(VEC4_T*)shred->reg = retval.d.v_vec4;
     PUSH_REG(shred, SZ_VEC4);
   }
   return;
 }
free_DL_Func()
void free_DL_Func (DL_Func * a)
Definition at line 35 of file dl.c.
References DL_Func::args, free(), and free_Vector().
Referenced by make_dll_as_fun().
 {
   free_Vector(a->args);
   free(a);
 }
free_DL_Value()
void free_DL_Value (DL_Value * a)
Definition at line 52 of file dl.c.
References free().
Referenced by make_dll_arg_list().
 {
   /*  if(addr)*/
   /*    free(addr);*/
   free(a);
 }
new_DL_Func()
DL_Func* new_DL_Func (const m_str t, const m_str n, m_uint addr)
Definition at line 25 of file dl.c.
References DL_Func::addr, DL_Func::args, DL_Func::d, malloc(), DL_Func::name, new_Vector(), and DL_Func::type.
Referenced by import_ana(), import_array(), import_event(), import_fc(), import_fft(), import_fileio(), import_gain(), import_impulse(), import_lib(), import_machine(), import_rolloff(), import_shred(), import_sinosc(), import_step(), import_string(), import_ugen(), import_vec3(), and import_vec4().
 {
   DL_Func* a = malloc(sizeof(DL_Func));
   a->name = n;
   a->type = t;
   a->d.addr = addr;
   a->args = new_Vector();
   return a;
 }