doc_8h/ – Gwion
Gwion
A strongly timed musical programming language
doc_8h/
doc.h File Reference
Functions
void mkdoc_context (Env env, m_str str)
void mkadt_context (Env env, m_str str)
void operator_doc (Vector v, FILE *file)
Function Documentation
mkadt_context()
void mkadt_context (Env env, m_str str)
Definition at line 495 of file doc.c.
References Textadept::ctx, free_Textadept(), mkadt_func(), mkadt_type(), mkadt_value(), Context_::new_funcs, new_Textadept(), Context_::new_types, Context_::new_values, vector_at(), and vector_size().
Referenced by SFUN().
 {
   int i;
   Textadept* doc = new_Textadept(env, str);
   if(!doc)
     return;
   for(i = 0; i < vector_size(doc->ctx->new_types); i++)
     mkadt_type(doc, (Type)vector_at(doc->ctx->new_types, i));
   for(i = 0; i < vector_size(doc->ctx->new_values); i++)
     mkadt_value(doc, ((Value)vector_at(doc->ctx->new_values, i)));
   for(i = 0; i < vector_size(doc->ctx->new_funcs); i++)
     mkadt_func(doc, ((Func)vector_at(doc->ctx->new_funcs, i)));
   free_Textadept(doc);
 }
mkdoc_context()
void mkdoc_context (Env env, m_str str)
Definition at line 510 of file doc.c.
References Doc::ctx, Ast_::doc, Context_::filename, free_Doc(), Doc::html, mkdoc_func(), mkdoc_type(), mkdoc_value(), NameSpace_::name, new_Doc(), Context_::new_funcs, Context_::new_types, Context_::new_values, Context_::nspc, Context_::tree, vector_at(), and vector_size().
Referenced by SFUN().
 {
   int i;
   Doc* doc = new_Doc(env, str);
   if(!doc)
     return;
   fprintf(doc->html, "<meta http-equiv=\"Content-Type\" content=\"text/xhtml;charset=UTF-8\"/>\
 <title>Gwion: %s</title>\
 <html><body>\
 <section class=\"page-header\">\
 <h1 class=\"project-name\">Gwion</h1>\
 <h2 class=\"project-tagline\">A strongly timed musical programming language</h2>\
 </section>\
 <script src=\"dynsections.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\
 <script src=\"jquery.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\
 <script src=\"searchdata.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\
 <link rel=\"stylesheet\" href=\"gwion.css\">\
 <link rel=\"stylesheet\" href=\"normalize.css\">\
 <link href=\"search/search.css\" rel=\"stylesheet\" type=\"text/css\"/>\
 <script src=\"search/list.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\
 <script src=\"search/search.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\
 <script type=\"text/javascript\">$(document).ready(function() { searchBox.OnSelectItem(0); });</script>\
 <script type=\"text/javascript\">var searchBox = new SearchBox(\"searchBox\", \"search\",false,'Search');</script>\
 <div id=\"MSearchBox\" class=\"MSearchBoxInactive\">\
   <span class=\"left\">\
     <img id=\"MSearchSelect\" src=\"search/mag_sel.png\"\
       onmouseover=\"return searchBox.OnSearchSelectShow()\"\
       onmouseout=\"return searchBox.OnSearchSelectHide()\"\
       alt=\"\"/>\
     <input type=\"text\" id=\"MSearchField\" value=\"Search\" accesskey=\"S\"\
       onfocus=\"searchBox.OnSearchFieldFocus(true)\"\
       onblur=\"searchBox.OnSearchFieldFocus(false)\"\
       onkeyup=\"searchBox.OnSearchFieldChange(event)\"/>\
   </span>\
   <span class=\"right\">\
     <a id=\"MSearchClose\" href=\"javascript:searchBox.CloseResultsWindow()\"><img id=\"MSearchCloseImg\" border=\"0\" sr$\
   </span>\
 </div>\
 <div id=\"doc-content\">\
 <!-- window showing the filter options -->\
 <div id=\"MSearchSelectWindow\"\
      onmouseover=\"return searchBox.OnSearchSelectShow()\"\
      onmouseout=\"return searchBox.OnSearchSelectHide()\"\
      onkeydown=\"return searchBox.OnSearchSelectKey(event)\">\
 <a class=\"SelectItem\" href=\"javascript:void(0)\" onclick=\"searchBox.OnSelectItem(0)\"><span class=\"SelectionMark\">&#160;</span>All</a>\
 <a class=\"SelectItem\" href=\"javascript:void(0)\" onclick=\"searchBox.OnSelectItem(1)\"><span class=\"SelectionMark\">&#160;</span>Core</a>\
 <a class=\"SelectItem\" href=\"javascript:void(0)\" onclick=\"searchBox.OnSelectItem(2)\"><span class=\"SelectionMark\">&#160;</span>Plugins</a>\
 <a class=\"SelectItem\" href=\"javascript:void(0)\" onclick=\"searchBox.OnSelectItem(2)\"><span class=\"SelectionMark\">&#160;</span>User</a>\
 <a class=\"SelectItem\" href=\"javascript:void(0)\" onclick=\"searchBox.OnSelectItem(2)\"><span class=\"SelectionMark\">&#160;</span>Public</a>\
 <a class=\"SelectItem\" href=\"javascript:void(0)\" onclick=\"searchBox.OnSelectItem(2)\"><span class=\"SelectionMark\">&#160;</span>Private</a>\
 </div>\
 <!-- iframe showing the search results (closed by default) -->\
 <div id=\"MSearchResultsWindow\">\
 <iframe src=\"javascript:void(0)\" frameborder=\"0\"\
         name=\"MSearchResults\" id=\"MSearchResults\">\
 </iframe></div></div>\
 <section class=\"main-content\">\
 <h1 class=\"title\">%s</h1><h2>Description</h2><em>%s</em>\n",
           doc->ctx->filename, doc->ctx->nspc->name, doc->ctx->tree->doc ? doc->ctx->tree->doc : "");
   fprintf(doc->html, "<h1>Global Types</h1>\n");
   for(i = 0; i < vector_size(doc->ctx->new_types); i++)
     mkdoc_type(doc, (Type)vector_at(doc->ctx->new_types, i));
   fprintf(doc->html, "</blockquote>\n");
   fprintf(doc->html, "<h2>Global Variables</h2><blockquote>\n");
   for(i = 0; i < vector_size(doc->ctx->new_values); i++)
     mkdoc_value(doc, ((Value)vector_at(doc->ctx->new_values, i)));
   fprintf(doc->html, "</blockquote>\n");
   fprintf(doc->html, "<h2>Global Functions</h2><blockquote>\n");
   for(i = 0; i < vector_size(doc->ctx->new_funcs); i++)
     mkdoc_func(doc, ((Func)vector_at(doc->ctx->new_funcs, i)));
   fprintf(doc->html, "</blockquote>\n");
   fprintf(doc->html, "</section>\n");
   fprintf(doc->html, "<footer class=\"site-footer\"><span class=\"site-footer-owner\"><a href=\"fennecdjay.github.io\">Gwion</a> is maintained by <a href=\"https://fennecdjay.github.io/Gwion/\">Jérémie Astor</a>.</span>\
   <span class=\"site-footer-credits\">This page was generated by <a href=\"https://pages.github.com\">GitHub Pages</a>, with a theme based on <a href=\"https://github.com/pietromenna/jekyll-cayman-theme\">Cayman theme</a> by <a\
 href=\"http://github.com/jasonlong\">Jason Long</a>.</span>\
 </footer></body></html>");
   free_Doc(doc);
 }
operator_doc()
void operator_doc (Vector v, FILE * file)
Definition at line 336 of file operator.c.
References M_Operator::doc, M_Operator::lhs, Type_::name, op2str(), M_Operator::ret, M_Operator::rhs, vector_at(), and vector_size().
 {
 #ifdef DEBUG_OPERATOR
   debug_msg(" op", "making doc");
 #endif
   m_uint i;
   fprintf(file, "@itemize @bullet\n");
   for(i = 0; i < vector_size(v); i++) {
     M_Operator* mo = (M_Operator*)vector_at(v, i);
     fprintf(file, "@item (%s) '%s' %s '%s'\n", mo->ret->name, mo->lhs->name, op2str(i), mo->rhs->name);
     if(mo->doc)
       fprintf(file, "'%s'\n", mo->doc);
   }
   fprintf(file, "@end itemize\n");
 }