env_8h/ – Gwion
Gwion
A strongly timed musical programming language
env_8h/
env.h File Reference
#include "defs.h"
#include "vm.h"
Data Structures
struct Env_
Functions
Env new_Env ()
void env_reset (Env env)
void free_Env ()
Function Documentation
env_reset()
void env_reset (Env env)
Definition at line 30 of file env.c.
References Env_::class_def, Env_::class_scope, Env_::class_stack, Env_::curr, free_Vector(), Env_::func, Env_::global_nspc, new_Vector(), Env_::nspc_stack, and vector_append().
Referenced by new_Env(), and type_engine_check_prog().
 {
   // TODO: release stack items?
   free_Vector(env->nspc_stack);
   env->nspc_stack = new_Vector();
   vector_append(env->nspc_stack, (vtype)env->global_nspc);
 //  if(env->user_nspc)
 //    vector_append(env->nspc_stack, (vtype)env->user_nspc);
   free_Vector(env->class_stack);
   env->class_stack = new_Vector();
   vector_append(env->class_stack, (vtype)NULL);
   // should be at top level
 //  if(env->user_nspc)
 //    env->curr = env->user_nspc;
 //  else
   env->curr = env->global_nspc;
   env->class_def = NULL;
   env->func = NULL;
   env->class_scope = 0;
 }
free_Env()
void free_Env ()
new_Env()
Env new_Env ()
Definition at line 6 of file env.c.
References add_ref(), Env_::breaks, Env_::class_scope, Env_::class_stack, Env_::context, Env_::contexts, Env_::conts, Env_::curr, e_env_obj, env_reset(), NameSpace_::filename, Env_::global_context, Env_::global_nspc, Env_::known_ctx, NameSpace_::name, new_Context(), new_Map(), new_NameSpace(), new_Vector(), new_VM_Object(), Env_::nspc_stack, Context_::obj, NameSpace_::obj, and Env_::obj.
Referenced by type_engine_init().
 {
   Env env = calloc(1, sizeof(struct Env_));
   env->global_context = new_Context(NULL, "global_context");
   add_ref(env->global_context->obj);
   env->context = env->global_context;
   env->contexts = new_Vector();
   env->class_stack = new_Vector();
   env->nspc_stack = new_Vector();
   env->class_scope = 0;
   env->obj = new_VM_Object(e_env_obj);
   env->global_nspc = new_NameSpace();
   env->global_nspc->name = "global_nspc";
   env->global_nspc->filename = "global_nspc";
   env->curr = env->global_nspc;
   add_ref(env->global_nspc->obj);
   env->breaks = new_Vector();
   env->conts = new_Vector();
 //  env->user_nspc = NULL;
   env->known_ctx = new_Map();
   env_reset(env);
   return env;
 }