Gwion dev-docs: include/err_msg.h File Reference
--- layout: homepage title: err__msg_8h/ image: feature: abstract-1.jpg ---
err_msg.h File Reference
#include <stdarg.h>
Enumerations
enum a_header {
PARSE_, SCAN0_, SCAN1_, SCAN2_,
TYPE_, EMIT_, UTIL_, COMPILE_,
INSTR_, UDP, ALSA_, VM_,
OPERATOR_
}
Functions
void err_msg (a_header header, long int pos, const char *fmt,...)
Enumeration Type Documentation
a_header
enum a_header
Enumerator
PARSE_
SCAN0_
SCAN1_
SCAN2_
TYPE_
EMIT_
UTIL_
COMPILE_
INSTR_
UDP
ALSA_
VM_
OPERATOR_
Definition at line 2 of file err_msg.h.
              { PARSE_, SCAN0_, SCAN1_, SCAN2_, TYPE_, EMIT_, UTIL_, COMPILE_, INSTR_, UDP, ALSA_,
                VM_, OPERATOR_
              } a_header;
Function Documentation
err_msg()
void err_msg (a_header header, long int pos, const char * fmt, ...)
Definition at line 9 of file err_msg.c.
References err_headers.
Referenced by add_binary_op(), alsa_ini(), check_Array(), check_array_lit(), check_array_subscripts(), check_Binary_Expression(), check_Break(), check_Case(), check_Cast_Expression(), check_Class_Def(), check_Continue(), check_Decl_Expression(), check_Dot_Member(), check_Dur(), check_exp_if(), check_Expression(), check_For(), check_Func_Call(), check_Func_Call1(), check_Func_Def(), check_Goto_Label(), check_If(), check_Loop(), check_op(), check_Postfix_Expression(), check_Primary_Expression(), check_Return(), check_Stmt(), check_Switch(), check_Unary(), check_Until(), check_Vec(), check_While(), compile(), DTOR(), emit_Array(), emit_array_lit(), emit_Case(), emit_Cast_Expression1(), emit_Class_Def(), emit_Do_Until(), emit_Do_While(), emit_Dot_Member(), emit_exp_if(), emit_Expression(), emit_For(), emit_Func_Args(), emit_Func_Call(), emit_Func_Call1(), emit_Func_Def(), emit_Goto_Label(), emit_If(), emit_implicit_cast(), emit_Loop(), emit_Postfix_Expression(), emit_Primary_Expression(), emit_spork(), emit_Stmt(), emit_Switch(), emit_symbol(), emit_Unary(), emit_Until(), emit_While(), find_type(), if(), import_class_begin(), import_class_end(), import_var(), initialize_object(), INSTR(), isres(), make_dll_arg_list(), make_dll_as_fun(), MFUN(), new_Doc(), new_Textadept(), NullException(), operator_set_type_func(), parse(), Recv(), scan0_Ast(), scan0_Class_Def(), scan1_Decl_Expression(), scan1_Enum(), scan1_Expression(), scan1_Func_Def(), scan1_Func_Ptr(), scan1_Postfix_Expression(), scan1_Stmt(), scan2_Decl_Expression(), scan2_Expression(), scan2_Func_Call(), scan2_Func_Def(), scan2_Func_Ptr(), scan2_Goto_Label(), scan2_Postfix_Expression(), scan2_Stmt(), scan2_Stmt_Enum(), Send(), server_init(), shredule(), sinosc_size(), sinosc_size_phase(), str2char(), str2list(), type_engine_init(), verify_array(), and vm_run().
 {
   char msg[256];
   va_list arg;
   va_start(arg, fmt);
 #ifdef COLOR
   fprintf(stderr, "\033[1m[\033[0m\033[31m%s\033[0m\033[1m]\033[0m", err_headers[header]);
 #else
   fprintf(stderr, "%s", err_headers[header]);
 #endif
   if(pos > 0)
 #ifdef COLOR
     fprintf(stderr, " \033[4mline \033[1m%li\033[0m\t", pos);
 #else
     fprintf(stderr, " line: %li\t", pos);
 #endif
   vsnprintf(msg, 256, fmt, arg);
   fprintf(stderr, "\t%s\n", msg);
   va_end(arg);
 }