Gwion dev-docs: core/frame.c File Reference
--- layout: homepage title: frame_8c/ image: feature: abstract-1.jpg ---
frame.c File Reference
#include <stdlib.h>
#include "map.h"
#include "frame.h"
Functions
Frame * new_Frame ()
void free_Frame (Frame *a)
Local * frame_alloc_local (Frame *frame, m_uint size, m_str name, m_bool is_ref, m_bool is_obj)
void frame_push_scope (Frame *frame)
void frame_pop_scope (Frame *frame, Vector v)
Function Documentation
frame_alloc_local()
Local* frame_alloc_local (Frame * frame, m_uint size, m_str name, m_bool is_ref, m_bool is_obj)
Definition at line 21 of file frame.c.
References Frame::curr_offset, Local::is_obj, Local::is_ref, Local::name, Local::offset, Local::size, Frame::stack, and vector_append().
Referenced by emit_array_lit(), emit_Class_Def(), emit_Decl_Expression(), emit_Enum(), emit_Func_Call1(), emit_Func_Def(), emit_Primary_Expression(), emit_Stmt(), and get_instr().
 {
   Local* local = calloc(1, sizeof(Local));
   local->size = size;
   local->offset = frame->curr_offset;
   local->is_ref = is_ref;
   local->is_obj = is_obj;
   frame->curr_offset += local->size;
   local->name = name;
   vector_append(frame->stack, (vtype)local);
   return local;
 }
frame_pop_scope()
void frame_pop_scope (Frame * frame, Vector v)
Definition at line 39 of file frame.c.
References Frame::curr_offset, Local::size, Frame::stack, vector_append(), vector_back(), vector_pop(), and vector_size().
Referenced by emit_pop_scope().
 {
   m_uint i;
   Local* local = (Local*)vector_back(frame->stack);
   while((i = vector_size(frame->stack) && vector_back(frame->stack))) {
     local = (Local*)vector_back(frame->stack);
     vector_pop(frame->stack);
     if(local) {
       frame->curr_offset -= local->size;
       vector_append(v, (vtype)local);
     }
   }
   vector_pop(frame->stack);
 }
frame_push_scope()
void frame_push_scope (Frame * frame)
Definition at line 34 of file frame.c.
References Frame::stack, and vector_append().
Referenced by emit_Ast(), emit_Do_Until(), emit_Do_While(), emit_For(), emit_Func_Def(), emit_If(), emit_Loop(), emit_Unary(), emit_Until(), and emit_While().
 {
   vector_append(frame->stack, (vtype)NULL);
 }
free_Frame()
void free_Frame (Frame * a)
Definition at line 12 of file frame.c.
References free(), free_Vector(), Frame::stack, vector_at(), and vector_size().
Referenced by free_Code().
 {
   vtype i;
   for(i = 0; i < vector_size(a->stack); i++)
     free((Local*)vector_at(a->stack, i));
   free_Vector(a->stack);
   free(a);
 }
new_Frame()
Frame* new_Frame ()
Definition at line 5 of file frame.c.
References new_Vector(), and Frame::stack.
Referenced by new_Code().
 {
   Frame* frame = calloc(1, sizeof(Frame));
   frame->stack = new_Vector();
   return frame;
 }