Gwion dev-docs: include/lang.h File Reference
lang.h File Reference
#include "object.h"
#include "array.h"
#include "emit.h"
Functions
m_bool import_int (Env env)
m_bool import_array (Env env)
m_bool import_float (Env env)
m_bool import_complex (Env env)
m_bool import_vec3 (Env env)
m_bool import_vec4 (Env env)
m_bool import_shred (Env env)
m_bool import_machine (Env env)
m_bool import_object (Env env)
m_bool import_string (Env env)
m_bool import_event (Env env)
m_bool import_fileio (Env env)
m_bool import_lib (Env env)
m_bool import_analys (Env env)
M_Object new_Shred (VM *vm, VM_Shred shred)
void array_ctor (M_Object o, VM_Shred shred)
INSTR (Array_Append)
void broadcast (M_Object o)
void release (M_Object obj, VM_Shred shred)
m_bool initialize_object (M_Object object, Type type)
Variables
m_int o_fileio_file
m_uint o_object_doc
m_int o_string_data
m_int o_event_shred
m_int o_shred_me
Function Documentation
array_ctor()
void array_ctor (M_Object o, VM_Shred shred)
broadcast()
void broadcast (M_Object o)
Definition at line 56 of file event.c.
References EV_SHREDS, get_now(), shredule(), VM::shreduler, vector_at(), vector_clear(), vector_size(), VM_Shred_::vm_ref, and VM_Shred_::wait.
Referenced by MFUN().
 {
   m_uint i;
   VM_Shred sh;
   for(i = 0; i < vector_size(EV_SHREDS(o)); i++) {
     sh = (VM_Shred)vector_at(EV_SHREDS(o), i);
     sh->wait = NULL;
     shredule(sh->vm_ref->shreduler, sh, get_now(sh->vm_ref->shreduler) + .5);
   }
   vector_clear(EV_SHREDS(o));
 }
import_analys()
m_bool import_analys (Env env)
Definition at line 756 of file analys.c.
References add_binary_op(), CHECK_BB, import_ana(), import_asc(), import_ass(), import_centroid(), import_fc(), import_fft(), import_freq(), import_kurtosis(), import_rms(), import_rolloff(), import_skewness(), import_spread(), op_chuck, and op_unchuck.
Referenced by type_engine_init().
 {
   CHECK_BB(import_fft(env))
   CHECK_BB(import_ana(env))
   CHECK_BB(import_centroid(env))
   CHECK_BB(import_spread(env))
   CHECK_BB(import_skewness(env))
   CHECK_BB(import_kurtosis(env))
   CHECK_BB(import_rms(env))
   CHECK_BB(import_rolloff(env))
   CHECK_BB(import_freq(env))
   CHECK_BB(import_asc(env))
   CHECK_BB(import_ass(env))
   CHECK_BB(import_fc(env))
   CHECK_BB(add_binary_op(env, op_chuck,   &t_ana, &t_fc, &t_fc, fc_connect,    1, 0))
   CHECK_BB(add_binary_op(env, op_unchuck, &t_ana, &t_fc, &t_fc, fc_disconnect, 1, 0))
   return 1;
 }
import_array()
m_bool import_array (Env env)
Definition at line 201 of file array.c.
References add_global_type(), CHECK_BB, CHECK_OB, Env_::class_def, Type_::doc, Env_::global_nspc, import_class_begin(), import_class_end(), import_mfun(), and new_DL_Func().
Referenced by type_engine_init().
 {
   DL_Func* fun;
   CHECK_BB(add_global_type(env, &t_array))
   CHECK_OB(import_class_begin(env, &t_array, env->global_nspc, NULL, array_dtor))
   fun = new_DL_Func("int", "size", (m_uint)vm_vector_size);
   CHECK_OB(import_mfun(env, fun))
   env->class_def->doc = "vector structure";
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_complex()
m_bool import_complex (Env env)
Definition at line 265 of file complex.c.
References add_binary_op(), add_global_type(), CHECK_BB, CHECK_OB, Type_::doc, Env_::global_nspc, import_class_begin(), import_class_end(), import_mvar(), o_complex_imag, o_complex_real, o_polar_mod, o_polar_phase, op_assign, op_chuck, op_divide, op_divide_chuck, op_minus, op_minus_chuck, op_plus, op_plus_chuck, op_times, op_times_chuck, and Type_::size.
Referenced by type_engine_init().
 {
   CHECK_BB(add_global_type(env, &t_complex))
   CHECK_OB(import_class_begin(env, &t_complex, env->global_nspc, NULL, NULL))
   o_complex_real = import_mvar(env, "float", "re",   0, 0, "real part");
   CHECK_BB(o_complex_real)
   o_complex_imag = import_mvar(env, "float", "im",   0, 0, "imaginary part");
   CHECK_BB(o_complex_imag)
   CHECK_BB(import_class_end(env))
   CHECK_BB(add_global_type(env, &t_polar))
   CHECK_OB(import_class_begin(env, &t_polar, env->global_nspc, NULL, NULL))
   o_polar_mod = import_mvar(env, "float", "mod",   0, 0, "real part");
   CHECK_BB(o_polar_mod)
   o_polar_phase = import_mvar(env, "float", "phase",   0, 0, "imaginary part");
   CHECK_BB(o_polar_phase)
   CHECK_BB(import_class_end(env))
 // arithmetic
   CHECK_BB(add_binary_op(env, op_assign,        &t_complex, &t_complex, &t_complex, assign,     0, 0))
   CHECK_BB(add_binary_op(env, op_plus,          &t_complex, &t_complex, &t_complex, plus,       0, 0))
   CHECK_BB(add_binary_op(env, op_minus,         &t_complex, &t_complex, &t_complex, minus,      0, 0))
   CHECK_BB(add_binary_op(env, op_times,         &t_complex, &t_complex, &t_complex, times,      0, 0))
   CHECK_BB(add_binary_op(env, op_divide,        &t_complex, &t_complex, &t_complex, divide,     0, 0))
   /*    CHECK_BB(add_binary_op(env, op_percent,       &t_complex, &t_complex, &t_complex, modulo,     0, 0)) */
 // reverse arithmetic
   CHECK_BB(add_binary_op(env, op_chuck,         &t_complex, &t_complex, &t_complex, r_assign,   0, 0))
   CHECK_BB(add_binary_op(env, op_plus_chuck,    &t_complex, &t_complex, &t_complex, r_plus,     0, 0))
   CHECK_BB(add_binary_op(env, op_minus_chuck,   &t_complex, &t_complex, &t_complex, r_minus,    0, 0))
   CHECK_BB(add_binary_op(env, op_times_chuck,   &t_complex, &t_complex, &t_complex, r_times,    0, 0))
   CHECK_BB(add_binary_op(env, op_divide_chuck,  &t_complex, &t_complex, &t_complex, r_divide,   0, 0))
   /*    CHECK_BB(add_binary_op(env, op_modulo_chuck,  &t_complex, &t_complex, &t_complex, r_modulo,   0, 0)) */
   CHECK_BB(add_binary_op(env, op_assign,        &t_polar, &t_polar, &t_polar, assign,           0, 0))
   CHECK_BB(add_binary_op(env, op_chuck,         &t_polar, &t_polar, &t_polar, r_assign,         0, 0))
   CHECK_BB(add_binary_op(env, op_plus,          &t_polar, &t_polar, &t_polar, polar_plus,       0, 0))
   CHECK_BB(add_binary_op(env, op_minus,         &t_polar, &t_polar, &t_polar, polar_minus,      0, 0))
   CHECK_BB(add_binary_op(env, op_times,         &t_polar, &t_polar, &t_polar, polar_times,      0, 0))
   CHECK_BB(add_binary_op(env, op_divide,        &t_polar, &t_polar, &t_polar, polar_divide,     0, 0))
   CHECK_BB(add_binary_op(env, op_plus_chuck,    &t_polar, &t_polar, &t_polar, polar_plus_r,     0, 0))
   CHECK_BB(add_binary_op(env, op_minus_chuck,   &t_polar, &t_polar, &t_polar, polar_minus_r,    0, 0))
   CHECK_BB(add_binary_op(env, op_times_chuck,   &t_polar, &t_polar, &t_polar, polar_times_r,    0, 0))
   CHECK_BB(add_binary_op(env, op_divide_chuck,  &t_polar, &t_polar, &t_polar, polar_divide_r,   0, 0))
   t_complex.doc   = "complex numbers";
   t_polar.doc     = "polar   numbers";
   t_complex.size = sizeof(m_float) *2;
   t_polar.size = sizeof(m_float) *2;
   return 1;
 }
import_event()
m_bool import_event (Env env)
Definition at line 76 of file event.c.
References add_binary_op(), add_global_type(), CHECK_BB, CHECK_OB, Env_::class_def, Type_::doc, event_ctor(), event_dtor(), Event_Wait(), Env_::global_nspc, import_class_begin(), import_class_end(), import_mfun(), import_mvar(), new_DL_Func(), o_event_shred, op_chuck, t_int, and t_now.
Referenced by type_engine_init().
 {
   DL_Func* fun;
   CHECK_BB(add_global_type(env, &t_event))
   CHECK_OB(import_class_begin(env, &t_event, env->global_nspc, event_ctor, event_dtor))
   env->class_def->doc = "Process event, with precise timing";
   o_event_shred = import_mvar(env, "int", "@shreds", 0, 0, "the place for blocked shreds");
   CHECK_BB(o_event_shred);
   fun = new_DL_Func("int", "signal", (m_uint)event_signal);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("int", "broadcast", (m_uint)event_broadcast);
   CHECK_OB(import_mfun(env, fun))
   CHECK_BB(add_binary_op(env, op_chuck,        &t_event, &t_now, &t_int, Event_Wait, 1, 0))
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_fileio()
m_bool import_fileio (Env env)
Definition at line 285 of file fileio.c.
References add_binary_op(), add_global_type(), add_global_value(), CHECK_BB, CHECK_OB, Env_::class_def, dl_func_add_arg(), Type_::doc, Env_::global_nspc, import_class_begin(), import_class_end(), import_mfun(), import_mvar(), import_sfun(), initialize_object(), IO_FILE, new_DL_Func(), new_M_Object(), o_fileio_ascii, o_fileio_dir, o_fileio_file, o_fileio_line, op_chuck, t_float, t_int, t_null, t_object, and t_string.
Referenced by type_engine_init().
 {
   DL_Func* fun;
   // hack
   CHECK_BB(add_global_type(env, &t_io))
   CHECK_OB(import_class_begin(env, &t_io, env->global_nspc, NULL, NULL))
   env->class_def->doc = "io operations";
   CHECK_BB(import_class_end(env))
   // !hack
   CHECK_BB(add_global_type(env, &t_fileio))
   CHECK_OB(import_class_begin(env, &t_fileio, env->global_nspc, fileio_ctor, fileio_dtor))
   env->class_def->doc = "read/write files";
   // import vars
   o_fileio_dir = import_mvar(env, "int",  "@dir",   0, 0, "place for the directory");
   CHECK_BB(o_fileio_dir)
   o_fileio_file = import_mvar(env, "int", "@file",  0, 0, "place for the file");
   CHECK_BB(o_fileio_file)
   o_fileio_ascii = import_mvar(env, "int", "ascii", 0, 0, "ascii or binary");
   CHECK_BB(o_fileio_ascii)
   o_fileio_line = import_mvar(env, "int", "@line",  0, 0, "place for the file");
   CHECK_BB(o_fileio_line)
   // import funcs
   fun = new_DL_Func("int", "nl", (m_uint)file_nl);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("int", "open", (m_uint)file_open);
   dl_func_add_arg(fun, "string", "filename");
   dl_func_add_arg(fun, "string", "mode");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("int", "close", (m_uint)file_close);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("int", "remove", (m_uint)file_remove);
   dl_func_add_arg(fun, "string", "filename");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("string[]", "list", (m_uint)file_list);
   dl_func_add_arg(fun, "string", "filename");
   CHECK_OB(import_sfun(env, fun))
   // import operators
   CHECK_BB(add_binary_op(env, op_chuck, &t_int,    &t_fileio, &t_fileio, int_to_file, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck, &t_float,  &t_fileio, &t_fileio, float_to_file, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck, &t_string, &t_fileio, &t_fileio, string_to_file, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck, &t_object, &t_fileio, &t_fileio, object_to_file, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck, &t_null,   &t_fileio, &t_fileio, object_to_file, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck, &t_fileio, &t_string, &t_string, file_to_string, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck, &t_fileio, &t_int,    &t_int,    file_to_int, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck, &t_fileio, &t_float,  &t_float,  file_to_float, 1, 0))
   CHECK_BB(import_class_end(env))
   CHECK_BB(add_global_type(env, &t_cout))
   CHECK_OB(import_class_begin(env, &t_cout, env->global_nspc, NULL, static_fileio_dtor))
   CHECK_BB(import_class_end(env))
   CHECK_BB(add_global_type(env, &t_cerr))
   CHECK_OB(import_class_begin(env, &t_cerr, env->global_nspc, NULL, static_fileio_dtor))
   CHECK_BB(import_class_end(env))
   CHECK_BB(add_global_type(env, &t_cin))
   CHECK_OB(import_class_begin(env, &t_cin, env->global_nspc, NULL, static_fileio_dtor))
   CHECK_BB(import_class_end(env))
   gw_cin = new_M_Object();
   initialize_object(gw_cin, &t_cin);
   gw_cout = new_M_Object();
   initialize_object(gw_cout, &t_cout);
   IO_FILE(gw_cout) = stdout;
   gw_cerr = new_M_Object();
   initialize_object(gw_cerr, &t_cerr);
   IO_FILE(gw_cerr) = stderr;
   add_global_value(env, "cin",  &t_fileio, 1, gw_cin);
   add_global_value(env, "cout", &t_fileio, 1, gw_cout);
   add_global_value(env, "cerr", &t_fileio, 1, gw_cerr);
   return 1;
 }
import_float()
m_bool import_float (Env env)
Definition at line 597 of file float.c.
References add_binary_op(), add_global_type(), add_global_value_double(), CHECK_BB, Type_::doc, negatef(), notf(), op_and, op_assign, op_chuck, op_divide, op_divide_chuck, op_eq, op_exclamation, op_ge, op_gt, op_le, op_lt, op_minus, op_minus_chuck, op_neq, op_or, op_plus, op_plus_chuck, op_times, op_times_chuck, t_int, Time_Advance(), and timesf().
Referenced by type_engine_init().
 {
   CHECK_BB(add_global_type(env, &t_float))
 // arithmetic
   CHECK_BB(add_binary_op(env, op_assign,        &t_float, &t_float, &t_float, assign,    0, 0))
   CHECK_BB(add_binary_op(env, op_plus,          &t_float, &t_float, &t_float, plus,      0, 0))
   CHECK_BB(add_binary_op(env, op_minus,         &t_float, &t_float, &t_float, minus,     0, 0))
   CHECK_BB(add_binary_op(env, op_times,         &t_float, &t_float, &t_float, timesf,    0, 0))
   CHECK_BB(add_binary_op(env, op_divide,        &t_float, &t_float, &t_float, divide,    0, 0))
   /*    CHECK_BB(add_binary_op(env, op_percent,       &t_float, &t_float, &t_float, modulo,     0, 0))*/
 // logical
   CHECK_BB(add_binary_op(env, op_and,           &t_float, &t_float, &t_int, and,         0, 0))
   CHECK_BB(add_binary_op(env, op_or,            &t_float, &t_float, &t_int, or,          0, 0))
   CHECK_BB(add_binary_op(env, op_eq,                      &t_float, &t_float, &t_int, eq,          0, 0))
   CHECK_BB(add_binary_op(env, op_neq,                 &t_float, &t_float, &t_int, neq,         0, 0))
   CHECK_BB(add_binary_op(env, op_gt,                    &t_float, &t_float, &t_int, gt,          0, 0))
   CHECK_BB(add_binary_op(env, op_ge,                    &t_float, &t_float, &t_int, ge,          0, 0))
   CHECK_BB(add_binary_op(env, op_lt,                    &t_float, &t_float, &t_int, lt,          0, 0))
   CHECK_BB(add_binary_op(env, op_le,                    &t_float, &t_float, &t_int, le,          0, 0))
 // unary
   CHECK_BB(add_binary_op(env, op_minus,         NULL,   &t_float, &t_float, negatef,     0, 0))
   CHECK_BB(add_binary_op(env, op_exclamation,   NULL,   &t_int,   &t_float, notf,        0, 0))
 // reverse arithmetic
   CHECK_BB(add_binary_op(env, op_chuck,         &t_float, &t_float, &t_float, r_assign,  0, 0))
   CHECK_BB(add_binary_op(env, op_plus_chuck,    &t_float, &t_float, &t_float, r_plus,    0, 0))
   CHECK_BB(add_binary_op(env, op_minus_chuck,   &t_float, &t_float, &t_float, r_minus,   0, 0))
   CHECK_BB(add_binary_op(env, op_times_chuck,   &t_float, &t_float, &t_float, r_times,   0, 0))
   CHECK_BB(add_binary_op(env, op_divide_chuck,  &t_float, &t_float, &t_float, r_divide,  0, 0))
 // int to float
   // arithmetic
   CHECK_BB(add_binary_op(env, op_assign,        &t_int, &t_float, &t_int,   if_assign,   0, 0))
   CHECK_BB(add_binary_op(env, op_plus,          &t_int, &t_float, &t_float, if_plus,     0, 0))
   CHECK_BB(add_binary_op(env, op_minus,         &t_int, &t_float, &t_float, if_minus,    0, 0))
   CHECK_BB(add_binary_op(env, op_times,         &t_int, &t_float, &t_float, if_timesf,   0, 0))
   CHECK_BB(add_binary_op(env, op_divide,        &t_int, &t_float, &t_float, if_divide,   0, 0))
   // logical
   CHECK_BB(add_binary_op(env, op_and,           &t_int, &t_float, &t_int, if_and,        0, 0))
   CHECK_BB(add_binary_op(env, op_or,            &t_int, &t_float, &t_int, if_or,         0, 0))
   CHECK_BB(add_binary_op(env, op_eq,                      &t_int, &t_float, &t_int, if_eq,         0, 0))
   CHECK_BB(add_binary_op(env, op_neq,                 &t_int, &t_float, &t_int, if_neq,        0, 0))
   CHECK_BB(add_binary_op(env, op_gt,                    &t_int, &t_float, &t_int, if_gt,         0, 0))
   CHECK_BB(add_binary_op(env, op_ge,                    &t_int, &t_float, &t_int, if_ge,         0, 0))
   CHECK_BB(add_binary_op(env, op_lt,                    &t_int, &t_float, &t_int, if_lt,         0, 0))
   CHECK_BB(add_binary_op(env, op_le,                    &t_int, &t_float, &t_int, if_le,         0, 0))
 // reverse arithmetic
   CHECK_BB(add_binary_op(env, op_chuck,         &t_int, &t_float, &t_float, ifr_assign,  0, 0))
   CHECK_BB(add_binary_op(env, op_plus_chuck,    &t_int, &t_float, &t_float, ifr_plus,    0, 0))
   CHECK_BB(add_binary_op(env, op_minus_chuck,   &t_int, &t_float, &t_float, ifr_minus,   0, 0))
   CHECK_BB(add_binary_op(env, op_times_chuck,   &t_int, &t_float, &t_float, ifr_times,   0, 0))
   CHECK_BB(add_binary_op(env, op_divide_chuck,  &t_int, &t_float, &t_float, ifr_divide,  0, 0))
 // float to int
   // arithmetic
   CHECK_BB(add_binary_op(env, op_assign,        &t_float,  &t_int,  &t_float, fi_assign, 0, 0))
   CHECK_BB(add_binary_op(env, op_plus,          &t_float,  &t_int,  &t_float, fi_plus,   0, 0))
   CHECK_BB(add_binary_op(env, op_minus,         &t_float,  &t_int,  &t_float, fi_minus,  0, 0))
   CHECK_BB(add_binary_op(env, op_times,         &t_float,  &t_int,  &t_float, fi_timesf, 0, 0))
   CHECK_BB(add_binary_op(env, op_divide,        &t_float,  &t_int,  &t_float, fi_divide, 0, 0))
   // logical
   CHECK_BB(add_binary_op(env, op_and,           &t_float, &t_int, &t_int, fi_and,        0, 0))
   CHECK_BB(add_binary_op(env, op_or,            &t_float, &t_int, &t_int, fi_or,         0, 0))
   CHECK_BB(add_binary_op(env, op_eq,                      &t_float, &t_int, &t_int, fi_eq,         0, 0))
   CHECK_BB(add_binary_op(env, op_neq,                 &t_float, &t_int, &t_int, fi_neq,        0, 0))
   CHECK_BB(add_binary_op(env, op_gt,                    &t_float, &t_int, &t_int, fi_gt,         0, 0))
   CHECK_BB(add_binary_op(env, op_ge,                    &t_float, &t_int, &t_int, fi_ge,         0, 0))
   CHECK_BB(add_binary_op(env, op_lt,                    &t_float, &t_int, &t_int, fi_lt,         0, 0))
   CHECK_BB(add_binary_op(env, op_le,                    &t_float, &t_int, &t_int, fi_le,         0, 0))
   // reverse arithmetic
   CHECK_BB(add_binary_op(env, op_chuck,        &t_float,  &t_int, &t_int, fi_r_assign, 0, 0))
   CHECK_BB(add_binary_op(env, op_plus_chuck,    &t_float, &t_int, &t_int, fi_r_plus,    0, 0))
   CHECK_BB(add_binary_op(env, op_minus_chuck,   &t_float, &t_int, &t_int, fi_r_minus,   0, 0))
   CHECK_BB(add_binary_op(env, op_times_chuck,   &t_float, &t_int, &t_int, fi_r_times,   0, 0))
   CHECK_BB(add_binary_op(env, op_divide_chuck,  &t_float, &t_int, &t_int, fi_r_divide,  0, 0))
   t_float.doc     = "floating point number";
   CHECK_BB(add_global_type(env, &t_dur))
   CHECK_BB(add_binary_op(env, op_chuck,        &t_dur,  &t_dur, &t_dur, r_assign, 0, 0))
   CHECK_BB(add_binary_op(env, op_plus,         &t_dur,  &t_dur, &t_dur, plus, 0, 0))
   CHECK_BB(add_binary_op(env, op_minus,         &t_dur,  &t_dur, &t_dur, minus, 0, 0))
   CHECK_BB(add_binary_op(env, op_times,         &t_dur,  &t_dur, &t_dur, timesf, 0, 0))
   CHECK_BB(add_binary_op(env, op_times,         &t_dur,  &t_float, &t_dur, timesf, 0, 0))
   CHECK_BB(add_binary_op(env, op_divide,        &t_dur,  &t_dur, &t_float, divide, 0, 0))
   CHECK_BB(add_binary_op(env, op_divide,        &t_dur,  &t_float, &t_dur, divide, 0, 0))
   /*    CHECK_BB(add_binary_op(env, op_chuck,        &t_time, &t_dur, &t_dur, assign, 0, 0))*/
   CHECK_BB(add_binary_op(env, op_gt,           &t_dur,  &t_dur, &t_int, gt,   0, 0))
   CHECK_BB(add_binary_op(env, op_ge,           &t_dur,  &t_dur, &t_int, ge,   0, 0))
   CHECK_BB(add_binary_op(env, op_lt,           &t_dur,  &t_dur, &t_int, lt,   0, 0))
   CHECK_BB(add_binary_op(env, op_le,           &t_dur,  &t_dur, &t_int, le,   0, 0))
   t_dur.doc       = "duration expression";
   CHECK_BB(add_global_type(env, &t_time))
   CHECK_BB(add_binary_op(env, op_chuck,        &t_time, &t_time, &t_time, r_assign, 0, 0))
   CHECK_BB(add_binary_op(env, op_chuck,        &t_dur,  &t_time, &t_time, r_assign, 0, 0))
   CHECK_BB(add_binary_op(env, op_chuck,        &t_dur,  &t_now,  &t_time, Time_Advance, 0, 0))
   CHECK_BB(add_binary_op(env, op_plus,         &t_time, &t_dur,  &t_time, plus,   0, 0))
   CHECK_BB(add_binary_op(env, op_plus,         &t_dur,  &t_time, &t_time, plus,   0, 0))
   CHECK_BB(add_binary_op(env, op_gt,           &t_time,  &t_time, &t_time, gt,   0, 0))
   CHECK_BB(add_binary_op(env, op_ge,           &t_time,  &t_time, &t_time, ge,   0, 0))
   CHECK_BB(add_binary_op(env, op_lt,           &t_time,  &t_time, &t_time, lt,   0, 0))
   CHECK_BB(add_binary_op(env, op_le,           &t_time,  &t_time, &t_time, le,   0, 0))
   add_global_value_double(env, "t_zero",       &t_time, 0.);
   t_time.doc      = "time expression";
   return 1;
 }
import_int()
m_bool import_int (Env env)
Definition at line 433 of file int.c.
References add_binary_op(), add_global_type(), CHECK_BB, dec(), Type_::doc, inc(), negate(), not(), op_and, op_assign, op_chuck, op_divide, op_divide_chuck, op_eq, op_exclamation, op_ge, op_gt, op_le, op_lt, op_minus, op_minus_chuck, op_minusminus, op_modulo_chuck, op_neq, op_or, op_percent, op_plus, op_plus_chuck, op_plusplus, op_rand, op_req, op_rge, op_rgt, op_rle, op_rlt, op_rneq, op_ror, op_rsand, op_rsl, op_rsor, op_rsr, op_rsxor, op_s_and, op_s_or, op_s_xor, op_shift_left, op_shift_right, op_times, and op_times_chuck.
Referenced by type_engine_init().
 {
   CHECK_BB(add_global_type(env, &t_int))
 // arithmetic
   CHECK_BB(add_binary_op(env, op_assign,        &t_int, &t_int, &t_int, assign,     1, 0))
   CHECK_BB(add_binary_op(env, op_plus,          &t_int, &t_int, &t_int, plus,       1, 0))
   CHECK_BB(add_binary_op(env, op_minus,         &t_int, &t_int, &t_int, minus,      1, 0))
   CHECK_BB(add_binary_op(env, op_times,         &t_int, &t_int, &t_int, times,      1, 0))
   CHECK_BB(add_binary_op(env, op_divide,        &t_int, &t_int, &t_int, divide,     1, 0))
   CHECK_BB(add_binary_op(env, op_percent,       &t_int, &t_int, &t_int, modulo,     1, 0))
 // logical
   CHECK_BB(add_binary_op(env, op_and,           &t_int, &t_int, &t_int, and,        1, 0))
   CHECK_BB(add_binary_op(env, op_or,            &t_int, &t_int, &t_int, or,         1, 0))
   CHECK_BB(add_binary_op(env, op_eq,                      &t_int, &t_int, &t_int, eq,         1, 0))
   CHECK_BB(add_binary_op(env, op_neq,                 &t_int, &t_int, &t_int, neq,        1, 0))
   CHECK_BB(add_binary_op(env, op_gt,                    &t_int, &t_int, &t_int, gt,         1, 0))
   CHECK_BB(add_binary_op(env, op_ge,                    &t_int, &t_int, &t_int, ge,         1, 0))
   CHECK_BB(add_binary_op(env, op_lt,                    &t_int, &t_int, &t_int, lt,         1, 0))
   CHECK_BB(add_binary_op(env, op_le,                    &t_int, &t_int, &t_int, le,         1, 0))
 // bitwise
   CHECK_BB(add_binary_op(env, op_shift_right,   &t_int, &t_int, &t_int, sr,         1, 0))
   CHECK_BB(add_binary_op(env, op_shift_left,    &t_int, &t_int, &t_int, sl,         1, 0))
   CHECK_BB(add_binary_op(env, op_s_and,         &t_int, &t_int, &t_int, sand,       1, 0))
   CHECK_BB(add_binary_op(env, op_s_or,          &t_int, &t_int, &t_int, sor,        1, 0))
   CHECK_BB(add_binary_op(env, op_s_xor,               &t_int, &t_int, &t_int, xor,        1, 0))
 // unary
   CHECK_BB(add_binary_op(env, op_minus,         NULL,   &t_int, &t_int, negate,     1, 0))
   CHECK_BB(add_binary_op(env, op_exclamation,   NULL,   &t_int, &t_int, not,        1, 0))
   CHECK_BB(add_binary_op(env, op_plusplus,      &t_int, NULL,   &t_int, inc,        1, 0))
   CHECK_BB(add_binary_op(env, op_plusplus,      NULL,   &t_int, &t_int, inc,        1, 0))
   CHECK_BB(add_binary_op(env, op_minusminus,    &t_int, NULL,   &t_int, dec,        1, 0))
   CHECK_BB(add_binary_op(env, op_minusminus,    NULL,   &t_int, &t_int, dec,        1, 0))
 // reverse arithmetic
   CHECK_BB(add_binary_op(env, op_chuck,         &t_int, &t_int, &t_int, r_assign,   1, 0))
   CHECK_BB(add_binary_op(env, op_plus_chuck,    &t_int, &t_int, &t_int, r_plus,     1, 0))
   CHECK_BB(add_binary_op(env, op_minus_chuck,   &t_int, &t_int, &t_int, r_minus,    1, 0))
   CHECK_BB(add_binary_op(env, op_times_chuck,   &t_int, &t_int, &t_int, r_times,    1, 0))
   CHECK_BB(add_binary_op(env, op_divide_chuck,  &t_int, &t_int, &t_int, r_divide,   1, 0))
   CHECK_BB(add_binary_op(env, op_modulo_chuck,  &t_int, &t_int, &t_int, r_modulo,   1, 0))
 // reverse logical
   CHECK_BB(add_binary_op(env, op_rand,          &t_int, &t_int, &t_int, r_and,      1, 0))
   CHECK_BB(add_binary_op(env, op_ror,           &t_int, &t_int, &t_int,  ror,       1, 0))
   CHECK_BB(add_binary_op(env, op_req,                 &t_int, &t_int, &t_int, req,        1, 0))
   CHECK_BB(add_binary_op(env, op_rneq,                &t_int, &t_int, &t_int, rneq,       1, 0))
   CHECK_BB(add_binary_op(env, op_rgt,                 &t_int, &t_int, &t_int, rgt,        1, 0))
   CHECK_BB(add_binary_op(env, op_rge,                 &t_int, &t_int, &t_int, rge,        1, 0))
   CHECK_BB(add_binary_op(env, op_rlt,                 &t_int, &t_int, &t_int, rlt,        1, 0))
   CHECK_BB(add_binary_op(env, op_rle,                 &t_int, &t_int, &t_int, rle,        1, 0))
 // TODO: reverse bitwise
   CHECK_BB(add_binary_op(env, op_rsl,           &t_int, &t_int, &t_int, rsl,        1, 0))
   CHECK_BB(add_binary_op(env, op_rsr,           &t_int, &t_int, &t_int, rsr,        1, 0))
   CHECK_BB(add_binary_op(env, op_rsand,         &t_int, &t_int, &t_int, rsand,      1, 0))
   CHECK_BB(add_binary_op(env, op_rsor,          &t_int, &t_int, &t_int, rsor,       1, 0))
   CHECK_BB(add_binary_op(env, op_rsxor,               &t_int, &t_int, &t_int, rsxor,      1, 0))
   t_int.doc       = "integral number";
   return 1;
 }
import_lib()
m_bool import_lib (Env env)
Definition at line 458 of file std.c.
References add_global_type(), CHECK_BB, CHECK_OB, Env_::class_def, dl_func_add_arg(), Type_::doc, Env_::global_nspc, import_class_begin(), import_class_end(), import_sfun(), and new_DL_Func().
Referenced by type_engine_init().
 {
   DL_Func* fun;
   CHECK_BB(add_global_type(env, &t_math))
   CHECK_OB(import_class_begin(env, &t_math, env->global_nspc, NULL, NULL))
   env->class_def->doc = "Standard library";
   fun = new_DL_Func("int", "abs",    (m_uint)std_abs);
   dl_func_add_arg(fun, "int", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "fabs", (m_uint)std_fabs);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("int", "rand",    (m_uint)std_rand);
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("int", "rand2",   (m_uint)std_rand2);
   dl_func_add_arg(fun, "int", "min");
   dl_func_add_arg(fun, "int", "max");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "randf",  (m_uint)std_randf);
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "rand2f", (m_uint)std_rand2f);
   dl_func_add_arg(fun, "float", "min");
   dl_func_add_arg(fun, "float", "max");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "srand",  (m_uint)std_srand);
   dl_func_add_arg(fun, "float", "seed");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("int", "sgn",      (m_uint)std_sgn);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "hypot", (m_uint)std_hypot);
   dl_func_add_arg(fun, "float", "min");
   dl_func_add_arg(fun, "float", "max");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "sin",      (m_uint)std_sin);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "cos",      (m_uint)std_cos);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "tan",      (m_uint)std_tan);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "asin",      (m_uint)std_asin);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "acos",      (m_uint)std_acos);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "atan",      (m_uint)std_atan);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "atan2",      (m_uint)std_atan2);
   dl_func_add_arg(fun, "float", "value");
   dl_func_add_arg(fun, "float", "value2");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "sinh",      (m_uint)std_sinh);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "cosh",      (m_uint)std_cosh);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "tanh",      (m_uint)std_tanh);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "asinh",      (m_uint)std_asinh);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "acosh",      (m_uint)std_acosh);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "atanh",      (m_uint)std_atanh);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "pow",      (m_uint)std_pow);
   dl_func_add_arg(fun, "float", "value");
   dl_func_add_arg(fun, "float", "value2");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "sqrt",      (m_uint)std_sqrt);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "exp",      (m_uint)std_exp);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "log",      (m_uint)std_log);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "log2",      (m_uint)std_log2);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "log10",      (m_uint)std_log10);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "floor",      (m_uint)std_floor);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "ceil",      (m_uint)std_ceil);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "round",      (m_uint)std_round);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "trunc",      (m_uint)std_trunc);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "fmod",      (m_uint)std_fmod);
   dl_func_add_arg(fun, "float", "value");
   dl_func_add_arg(fun, "float", "value2");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "remainder",      (m_uint)std_remainder);
   dl_func_add_arg(fun, "float", "value");
   dl_func_add_arg(fun, "float", "value2");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "min",      (m_uint)std_min);
   dl_func_add_arg(fun, "float", "value");
   dl_func_add_arg(fun, "float", "value2");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "max",      (m_uint)std_max);
   dl_func_add_arg(fun, "float", "value");
   dl_func_add_arg(fun, "float", "value2");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "isinf",      (m_uint)std_isinf);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "isnan",      (m_uint)std_isnan);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   CHECK_BB(import_class_end(env))
   CHECK_BB(add_global_type(env, &t_std))
   CHECK_OB(import_class_begin(env, &t_std, env->global_nspc, NULL, NULL))
   env->class_def->doc = "Standard library";
   fun = new_DL_Func("int", "clamp",     (m_uint)std_clamp);
   dl_func_add_arg(fun, "int", "value");
   dl_func_add_arg(fun, "int", "min");
   dl_func_add_arg(fun, "int", "max");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "clampf", (m_uint)std_clampf);
   dl_func_add_arg(fun, "float", "value");
   dl_func_add_arg(fun, "float", "min");
   dl_func_add_arg(fun, "float", "max");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "scale", (m_uint)std_scale);
   dl_func_add_arg(fun, "float", "value");
   dl_func_add_arg(fun, "float", "srcmin");
   dl_func_add_arg(fun, "float", "srcmax");
   dl_func_add_arg(fun, "float", "dstmin");
   dl_func_add_arg(fun, "float", "dstmax");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("int", "system",  (m_uint)std_system);
   dl_func_add_arg(fun, "string", "cmd");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("string", "getenv",  (m_uint)std_getenv);
   dl_func_add_arg(fun, "string", "key");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("int", "setenv",  (m_uint)std_setenv);
   dl_func_add_arg(fun, "string", "key");
   dl_func_add_arg(fun, "string", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("int", "atoi",  (m_uint)std_atoi);
   dl_func_add_arg(fun, "string", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "atof",  (m_uint)std_atof);
   dl_func_add_arg(fun, "string", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("string", "itoa",  (m_uint)std_itoa);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("string", "ftoa",  (m_uint)std_ftoa);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("int", "ftoi",  (m_uint)std_ftoi);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "mtof",  (m_uint)std_mtof);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "ftom",  (m_uint)std_ftom);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "powtodb",  (m_uint)std_powtodb);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "rmstodb",  (m_uint)std_rmstodb);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "dbtopow",  (m_uint)std_dbtopow);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "dbtorms",  (m_uint)std_dbtorms);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "dbtolin",  (m_uint)std_dbtolin);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   fun = new_DL_Func("float", "lintodb",  (m_uint)std_lintodb);
   dl_func_add_arg(fun, "float", "value");
   CHECK_OB(import_sfun(env, fun))
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_machine()
m_bool import_machine (Env env)
Definition at line 231 of file machine.c.
References add_global_type(), CHECK_BB, CHECK_OB, Env_::class_def, dl_func_add_arg(), Type_::doc, Env_::global_nspc, import_class_begin(), import_class_end(), import_sfun(), and new_DL_Func().
Referenced by type_engine_init().
 {
   DL_Func* fun;
   CHECK_BB(add_global_type(env, &t_machine))
   CHECK_OB(import_class_begin(env, &t_machine, env->global_nspc, NULL, NULL))
   env->class_def->doc = "access the virtual machine, including docs";
   fun = new_DL_Func("void",  "add",     (m_uint)machine_add);
   dl_func_add_arg(fun,       "string",  "filename");
   CHECK_OB(import_sfun(env,  fun))
   fun = new_DL_Func("int[]", "shreds", (m_uint)machine_shreds);
   CHECK_OB(import_sfun(env,  fun))
   fun = new_DL_Func("void",  "doc",     (m_uint)machine_doc);
   dl_func_add_arg(fun,       "string",  "context");
   CHECK_OB(import_sfun(env,  fun))
   fun = new_DL_Func("void",  "doc_update",     (m_uint)machine_doc_update);
   CHECK_OB(import_sfun(env,  fun))
   fun = new_DL_Func("void",  "adept",     (m_uint)machine_adept);
   dl_func_add_arg(fun,       "string",  "context");
   CHECK_OB(import_sfun(env,  fun))
 //  fun = new_DL_Func("string",  "check",     (m_uint)machine_check);
   fun = new_DL_Func("int",  "check",     (m_uint)machine_check);
   dl_func_add_arg(fun,       "string",  "prefix");
   dl_func_add_arg(fun,       "string",  "code");
   CHECK_OB(import_sfun(env,  fun))
   fun = new_DL_Func("void",  "compile",     (m_uint)machine_compile);
   dl_func_add_arg(fun,       "string",  "prefix");
   dl_func_add_arg(fun,       "string",  "filename");
   CHECK_OB(import_sfun(env,  fun))
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_object()
m_bool import_object (Env env)
Definition at line 243 of file object.c.
 {
   CHECK_BB(add_global_type(env, &t_object))
   CHECK_OB(import_class_begin(env, &t_object, env->global_nspc, NULL, object_dtor))
   env->class_def->doc = "the base class";
   CHECK_BB(add_binary_op(env, op_at_chuck, &t_null, &t_object, &t_object, Assign_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_at_chuck, &t_object, &t_object, &t_object, Assign_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_eq,  &t_object, &t_object, &t_int,  eq_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_neq, &t_object, &t_object, &t_int, neq_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_eq,  &t_null,   &t_object, &t_int,  eq_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_neq, &t_null,   &t_object, &t_int, neq_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_eq,  &t_object, &t_null, &t_int,  eq_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_neq, &t_object, &t_null, &t_int, neq_Object, 1, 0))
   add_global_value(env, "NULL", &t_object, 1, 0);
   CHECK_BB(import_class_end(env))
   CHECK_BB(add_global_type(env, &t_vararg))
   CHECK_BB(add_global_type(env, &t_varobj))
   CHECK_OB(import_class_begin(env, &t_vararg, env->global_nspc, NULL, NULL))
   import_mvar(env, "int", "start", 1, 0, "start vararg loop");
   import_mvar(env, "int", "end", 1, 0, "end vararg loop");
   import_mvar(env, "int", "i", 1, 0, "vararg int");
   import_mvar(env, "float", "f", 1, 0, "vararg float");
   import_mvar(env, "time", "t", 1, 0, "vararg time");
   import_mvar(env, "dur", "d", 1, 0, "vararg dur");
   import_mvar(env, "complex", "c", 1, 0, "vararg complex");
   import_mvar(env, "polar", "p", 1, 0, "vararg polar");
   import_mvar(env, "Vec3", "v3", 1, 0, "vararg Vec3");
   import_mvar(env, "Vec4", "v4", 1, 0, "vararg Vec4");
   import_mvar(env, "VarObject", "o", 1, 0, "vararg object");
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_shred()
m_bool import_shred (Env env)
Definition at line 104 of file shred.c.
References add_global_type(), CHECK_BB, CHECK_OB, Env_::class_def, dl_func_add_arg(), Func_::doc, Type_::doc, DL_Value::doc, Env_::global_nspc, import_class_begin(), import_class_end(), import_mfun(), import_mvar(), import_sfun(), new_DL_Func(), and o_shred_me.
Referenced by type_engine_init().
 {
   DL_Func* fun;
   DL_Value* arg;
   Func f;
   CHECK_BB(add_global_type(env, &t_shred))
   CHECK_OB(import_class_begin(env, &t_shred, env->global_nspc, NULL, shred_dtor))
   env->class_def->doc = "Shred is the type for processes, allowing to handle concurrency";
   o_shred_me = import_mvar(env, "int", "@me",   0, 0, "shred placeholder");
   CHECK_BB(o_shred_me)
   fun = new_DL_Func("void", "exit", (m_uint)vm_shred_exit);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "make the shred exit";
   fun = new_DL_Func("int", "running", (m_uint)vm_shred_is_running);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "return 1 if shred is done, 0 otherwise";
   fun = new_DL_Func("int", "done", (m_uint)vm_shred_is_done);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "return 1 if shred is done, 0 otherwise";
   fun = new_DL_Func("int", "id", (m_uint)vm_shred_id);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "return shred id";
   fun = new_DL_Func("Shred", "fromId", (m_uint)vm_shred_from_id);
   arg = dl_func_add_arg(fun, "int", "arg1");
   arg->doc = "id of the shred";
   CHECK_OB((f = import_sfun(env, fun)))
   f->doc = "get a shred from id";
   fun = new_DL_Func("int", "yield", (m_uint)shred_yield);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "let other shreds a chance to compute";
   fun = new_DL_Func("int", "args", (m_uint)shred_args);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "return shred arguments number";
   fun = new_DL_Func("string", "arg", (m_uint)shred_arg);
   dl_func_add_arg(fun, "int", "n");
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "return shred nth argument";
   fun = new_DL_Func("string", "path", (m_uint)shred_path);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "return shred basename";
   fun = new_DL_Func("string", "dir", (m_uint)shred_dir);
   CHECK_OB((f = import_mfun(env, fun)))
   f->doc = "return shred dirname";
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_string()
m_bool import_string (Env env)
Definition at line 857 of file string.c.
References add_binary_op(), add_global_type(), CHECK_BB, CHECK_OB, Env_::class_def, dl_func_add_arg(), Type_::doc, Env_::global_nspc, import_class_begin(), import_class_end(), import_mfun(), import_mvar(), new_DL_Func(), o_string_data, op_chuck, op_plus, op_plus_chuck, string_ctor(), t_complex, t_float, t_int, t_null, t_object, t_polar, t_vec3, and t_vec4.
Referenced by type_engine_init().
 {
   CHECK_BB(add_global_type(env, &t_string));
   CHECK_OB(import_class_begin(env, &t_string, env->global_nspc, string_ctor, NULL))
   env->class_def->doc = "chain of characters";
   o_string_data = import_mvar(env, "int", "@data",   1, 0, "place to hold the string");
   CHECK_BB(o_string_data)
   DL_Func* fun = new_DL_Func("int", "size", (m_uint)string_len);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("string", "upper", (m_uint)string_upper);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("string", "lower", (m_uint)string_lower);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("string", "ltrim", (m_uint)string_ltrim);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("string", "rtrim", (m_uint)string_rtrim);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("string", "trim", (m_uint)string_trim);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("int", "charAt", (m_uint)string_charAt);
   dl_func_add_arg(fun, "int", "pos");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("int", "charAt", (m_uint)string_setCharAt);
   dl_func_add_arg(fun, "int", "pos");
   dl_func_add_arg(fun, "int", "char");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("string", "substring", (m_uint)string_substring);
   dl_func_add_arg(fun, "int", "start");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("string", "substring", (m_uint)string_substringN);
   dl_func_add_arg(fun, "int", "start");
   dl_func_add_arg(fun, "int", "end");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("string", "insert", (m_uint)string_insert);
   dl_func_add_arg(fun, "int", "pos");
   dl_func_add_arg(fun, "string", "string");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("string", "replace", (m_uint)string_replace);
   dl_func_add_arg(fun, "int", "pos");
   dl_func_add_arg(fun, "string", "string");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("string", "replace", (m_uint)string_replaceN);
   dl_func_add_arg(fun, "int", "pos");
   dl_func_add_arg(fun, "int", "n");
   dl_func_add_arg(fun, "string", "string");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("int", "find", (m_uint)string_find);
   dl_func_add_arg(fun, "int", "char");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("int", "find", (m_uint)string_findStart);
   dl_func_add_arg(fun, "int", "pos");
   dl_func_add_arg(fun, "int", "char");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("int", "find", (m_uint)string_findStr);
   dl_func_add_arg(fun, "string", "str");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("int", "find", (m_uint)string_findStrStart);
   dl_func_add_arg(fun, "int", "pos");
   dl_func_add_arg(fun, "string", "str");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("int", "rfind", (m_uint)string_rfind);
   dl_func_add_arg(fun, "int", "char");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("int", "rfind", (m_uint)string_rfindStart);
   dl_func_add_arg(fun, "int", "pos");
   dl_func_add_arg(fun, "int", "char");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("int", "rfind", (m_uint)string_rfindStr);
   dl_func_add_arg(fun, "string", "str");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("int", "rfind", (m_uint)string_rfindStrStart);
   dl_func_add_arg(fun, "int", "pos");
   dl_func_add_arg(fun, "string", "str");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void",   "erase", (m_uint)string_erase);
   dl_func_add_arg(fun, "int", "start");
   dl_func_add_arg(fun, "int", "length");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("int", "toInt", (m_uint)string_toInt);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("float", "toFloat", (m_uint)string_toFloat);
   CHECK_OB(import_mfun(env, fun))
   CHECK_BB(add_binary_op(env, op_chuck, &t_string,  &t_string, &t_string, String_Assign, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck, &t_int,     &t_string, &t_string, Int_String_Assign, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck, &t_float,   &t_string, &t_string, Float_String_Assign, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck, &t_complex, &t_string, &t_string, Complex_String_Assign, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck, &t_polar,   &t_string, &t_string, Polar_String_Assign, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck, &t_vec3,    &t_string, &t_string, Vec3_String_Assign, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck, &t_vec4,    &t_string, &t_string, Vec4_String_Assign, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck, &t_object,  &t_string, &t_string, Object_String_Assign, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck, &t_null,    &t_string, &t_string, Object_String_Assign, 1, 0))
   CHECK_BB(add_binary_op(env, op_plus, &t_string,  &t_string, &t_string, String_String, 1, 1))
   CHECK_BB(add_binary_op(env, op_plus, &t_int,     &t_string, &t_string, Int_String, 1, 1))
   CHECK_BB(add_binary_op(env, op_plus, &t_float,   &t_string, &t_string, Float_String, 1, 1))
   CHECK_BB(add_binary_op(env, op_plus, &t_complex, &t_string, &t_string, Complex_String, 1, 1))
   CHECK_BB(add_binary_op(env, op_plus, &t_polar,   &t_string, &t_string, Polar_String, 1, 1))
   CHECK_BB(add_binary_op(env, op_plus, &t_vec3,    &t_string, &t_string, Vec3_String, 1, 1))
   CHECK_BB(add_binary_op(env, op_plus, &t_vec4,    &t_string, &t_string, Vec4_String, 1, 1))
   CHECK_BB(add_binary_op(env, op_plus, &t_object,  &t_string, &t_string, Object_String, 1, 1))
   CHECK_BB(add_binary_op(env, op_plus, &t_null,  &t_string, &t_string, Object_String, 1, 1))
   CHECK_BB(add_binary_op(env, op_plus_chuck, &t_string,  &t_string, &t_string, String_Plus, 1, 0))
   CHECK_BB(add_binary_op(env, op_plus_chuck, &t_int,     &t_string, &t_string, Int_String_Plus, 1, 0))
   CHECK_BB(add_binary_op(env, op_plus_chuck, &t_float,   &t_string, &t_string, Float_String_Plus, 1, 0))
   CHECK_BB(add_binary_op(env, op_plus_chuck, &t_complex, &t_string, &t_string, Complex_String_Plus, 1, 0))
   CHECK_BB(add_binary_op(env, op_plus_chuck, &t_polar,   &t_string, &t_string, Polar_String_Plus, 1, 0))
   CHECK_BB(add_binary_op(env, op_plus_chuck, &t_vec3,    &t_string, &t_string, Vec3_String_Plus, 1, 0))
   CHECK_BB(add_binary_op(env, op_plus_chuck, &t_vec4,    &t_string, &t_string, Vec4_String_Plus, 1, 0))
   CHECK_BB(add_binary_op(env, op_plus_chuck, &t_object,  &t_string, &t_string, Object_String_Plus, 1, 0))
   CHECK_BB(add_binary_op(env, op_plus_chuck, &t_null,    &t_string, &t_string, Object_String_Plus, 1, 0))
   CHECK_BB(import_class_end(env))
   return 1;
 }
import_vec3()
m_bool import_vec3 (Env env)
Definition at line 299 of file vec.c.
References add_binary_op(), add_global_type(), CHECK_BB, CHECK_OB, dl_func_add_arg(), Env_::global_nspc, import_class_begin(), import_class_end(), import_mfun(), import_mvar(), new_DL_Func(), op_chuck, op_divide, op_minus, op_plus, op_times, Type_::size, and t_float.
Referenced by type_engine_init().
 {
   DL_Func* fun;
   CHECK_BB(add_global_type(env, &t_vec3))
   CHECK_OB(import_class_begin(env, &t_vec3, env->global_nspc, NULL, NULL))
   import_mvar(env, "float", "x",   0, 0, "real part");
   import_mvar(env, "float", "y",   0, 0, "real part");
   import_mvar(env, "float", "z",   0, 0, "real part");
   fun = new_DL_Func("void", "set", (m_uint)vec3_set);
   dl_func_add_arg(fun, "float", "x");
   dl_func_add_arg(fun, "float", "y");
   dl_func_add_arg(fun, "float", "z");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "setAll", (m_uint)vec3_setAll);
   dl_func_add_arg(fun, "float", "x");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("float", "magnitude", (m_uint)vec3_magnitude);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "normalize", (m_uint)vec3_normalize);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("float", "interp", (m_uint)vec3_interp);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("float", "interp", (m_uint)vec3_float);
   dl_func_add_arg(fun, "float", "delta");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("float", "interp", (m_uint)vec3_dur);
   dl_func_add_arg(fun, "dur", "delta");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "update", (m_uint)vec3_update);
   dl_func_add_arg(fun, "float", "goal");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "update", (m_uint)vec3_update_slew);
   dl_func_add_arg(fun, "float", "goal");
   dl_func_add_arg(fun, "float", "slew");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "supdate", (m_uint)vec3_update_set);
   dl_func_add_arg(fun, "float", "goalAndValue");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "supdate", (m_uint)vec3_update_set_slew);
   dl_func_add_arg(fun, "float", "goalAndValue");
   dl_func_add_arg(fun, "float", "slew");
   CHECK_OB(import_mfun(env, fun))
   CHECK_BB(add_binary_op(env, op_plus,   &t_vec3,   &t_vec3, &t_vec3,  vec3_add, 1, 0))
   CHECK_BB(add_binary_op(env, op_minus,  &t_vec3,   &t_vec3, &t_vec3,  vec3_minus, 1, 0))
   CHECK_BB(add_binary_op(env, op_times,  &t_vec3,   &t_vec3, &t_vec3,  vec3_xproduct, 1, 0))
   CHECK_BB(add_binary_op(env, op_times,  &t_vec3,   &t_float, &t_vec3, vec3_times_float, 1, 0))
   CHECK_BB(add_binary_op(env, op_divide, &t_vec3,   &t_float, &t_vec3, vec3_divide_float, 1, 0))
   CHECK_BB(add_binary_op(env, op_times,  &t_float,  &t_vec3, &t_vec3,  float_times_vec3, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck,  &t_vec3,   &t_vec3, &t_vec3,  vec3_r_assign, 1, 0))
   CHECK_BB(import_class_end(env))
   t_vec3.size = SZ_VEC3;
   return 1;
 }
import_vec4()
m_bool import_vec4 (Env env)
Definition at line 516 of file vec.c.
References add_binary_op(), add_global_type(), CHECK_BB, CHECK_OB, dl_func_add_arg(), Env_::global_nspc, import_class_begin(), import_class_end(), import_mfun(), import_mvar(), new_DL_Func(), op_chuck, op_divide, op_minus, op_plus, op_times, Type_::size, and t_float.
Referenced by type_engine_init().
 {
   DL_Func* fun;
   CHECK_BB(add_global_type(env, &t_vec4))
   CHECK_OB(import_class_begin(env, &t_vec4, env->global_nspc, NULL, NULL))
   import_mvar(env, "float", "x",   0, 0, "real part");
   import_mvar(env, "float", "y",   0, 0, "real part");
   import_mvar(env, "float", "z",   0, 0, "real part");
   import_mvar(env, "float", "w",   0, 0, "real part");
   fun = new_DL_Func("void", "set", (m_uint)vec4_set);
   dl_func_add_arg(fun, "float", "x");
   dl_func_add_arg(fun, "float", "y");
   dl_func_add_arg(fun, "float", "z");
   dl_func_add_arg(fun, "float", "w");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "setAll", (m_uint)vec4_setAll);
   dl_func_add_arg(fun, "float", "x");
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("float", "magnitude", (m_uint)vec4_magnitude);
   CHECK_OB(import_mfun(env, fun))
   fun = new_DL_Func("void", "normalize", (m_uint)vec4_normalize);
   CHECK_OB(import_mfun(env, fun))
   CHECK_BB(add_binary_op(env, op_plus,   &t_vec4,   &t_vec4,  &t_vec4,  vec4_add, 1, 0))
   CHECK_BB(add_binary_op(env, op_minus,  &t_vec4,   &t_vec4,  &t_vec4,  vec4_minus, 1, 0))
   CHECK_BB(add_binary_op(env, op_times,  &t_vec4,   &t_vec4,  &t_vec4,  vec4_xproduct, 1, 0))
   CHECK_BB(add_binary_op(env, op_times,  &t_vec4,   &t_float, &t_vec4,  vec4_times_float, 1, 0))
   CHECK_BB(add_binary_op(env, op_divide, &t_vec4,   &t_float, &t_vec4,  vec4_divide_float, 1, 0))
   CHECK_BB(add_binary_op(env, op_times,  &t_float,  &t_vec4,  &t_vec4,  float_times_vec4, 1, 0))
   CHECK_BB(add_binary_op(env, op_chuck,   &t_vec4,   &t_vec4,  &t_vec4,  vec4_r_assign, 1, 0))
   CHECK_BB(import_class_end(env))
   t_vec4.size = SZ_VEC4;
   return 1;
 }
initialize_object()
m_bool initialize_object (M_Object object, Type type)
Definition at line 44 of file object.c.
 {
   if (!type->info) {
     err_msg(TYPE_, 0, "internal error: no type->info for type '%s'", type->name);
     return -1;
   }
   object->vtable = type->info->obj_v_table;
   object->type_ref = type;
   object->size = type->obj_size;
   if (object->size) {
     object->d.data = calloc(object->size, sizeof(unsigned char));
     if (!object->d.data)
       goto out_of_memory;
     memset(object->d.data, 0, object->size);
   } else
     object->d.data = NULL;
   return 1;
 out_of_memory:
   err_msg(TYPE_, 0, "OutOfMemory: while instantiating object '%s'\n", type->name);
   return -1;
 }
INSTR()
INSTR (Array_Append)
Definition at line 171 of file array.c.
References M_Object_::array, c_vector_append(), M_Object_::d, f_vector_append(), i_vector_append(), Kindof_Complex, Kindof_Float, Kindof_Int, Kindof_Vec3, Kindof_Vec4, POP_REG, PUSH_REG, release(), v3_vector_append(), and v4_vector_append().
 {
   POP_REG(shred, SZ_INT);
   M_Object o = NULL;
   if(instr->m_val == Kindof_Int) {
     POP_REG(shred, SZ_INT);
     o = *(M_Object*)(shred->reg);
     i_vector_append(o->d.array, *(m_uint*)(shred->reg + SZ_INT));
   } else if(instr->m_val == Kindof_Float) {
     POP_REG(shred, SZ_FLOAT);
     o = *(M_Object*)(shred->reg);
     f_vector_append(o->d.array, *(m_float*)(shred->reg + SZ_INT));
   } else if(instr->m_val == Kindof_Complex) {
     POP_REG(shred, SZ_COMPLEX);
     o = *(M_Object*)(shred->reg);
     c_vector_append(o->d.array, *(m_complex*)(shred->reg + SZ_INT));
   } else if(instr->m_val == Kindof_Vec3) {
     POP_REG(shred, SZ_VEC3);
     o = *(M_Object*)(shred->reg);
     v3_vector_append(o->d.array, *(VEC3_T*)(shred->reg + SZ_INT));
   } else if(instr->m_val == Kindof_Vec4) {
     POP_REG(shred, SZ_VEC4);
     o = *(M_Object*)(shred->reg);
     v4_vector_append(o->d.array, *(VEC4_T*)(shred->reg + SZ_INT));
   }
   release(o, shred);
   *(M_Object*)(shred->reg) = o;
   PUSH_REG(shred, SZ_INT);
 }
new_Shred()
M_Object new_Shred (VM * vm, VM_Shred shred)
Definition at line 13 of file shred.c.
References initialize_object(), ME, new_M_Object(), and Type_::obj.
Referenced by compile(), INSTR(), and release().
 {
   M_Object obj = new_M_Object();
   initialize_object(obj, &t_shred);
   ME(obj) = shred;
   return obj;
 }
release()
void release (M_Object obj, VM_Shred shred)
Definition at line 67 of file object.c.
 {
   if (!obj)
     return;
   if (!--obj->ref) {
     Type t = obj->type_ref;
     while (t) {
 #ifdef DEBUG_INSTR
       debug_msg("instr", "dtor loop %p %s", obj, t->name);
 #endif
       m_uint i;
       Vector v = scope_get(t->info->value);
       for(i = 0; i < vector_size(v); i++) {
         Value value = (Value)vector_at(v, i);
         if(isprim(value->m_type) < 0)
           release(*(M_Object*)(obj->d.data + value->offset), shred);
       }
       free_Vector(v);
       if (t->has_destructor) {
         if (t->info->dtor->native_func)
           ((f_dtor)t->info->dtor->native_func)(obj, shred);
         else {
           VM_Code code = new_VM_Code(t->info->dtor->instr, SZ_INT, 1, "[dtor]", "[in code dtor exec]");
           VM_Shred sh = new_VM_Shred(code);
           sh->me = new_Shred(shred->vm_ref, sh);
           memcpy(sh->mem, shred->mem, SIZEOF_MEM);
           vector_pop(code->instr);
           Instr eoc = new_Instr();
           eoc->execute = EOC;
           vector_append(code->instr, (vtype)eoc);
           vm_add_shred(shred->vm_ref, sh);
         }
       }
       t = t->parent;
     }
   }
 }
Variable Documentation
o_event_shred
m_int o_event_shred
Definition at line 12 of file event.c.
Referenced by import_event().
o_fileio_file
m_int o_fileio_file
Definition at line 22 of file fileio.c.
Referenced by import_fileio().
o_object_doc
m_uint o_object_doc
o_shred_me
m_int o_shred_me
Definition at line 11 of file shred.c.
Referenced by import_shred().
o_string_data
m_int o_string_data
Definition at line 17 of file string.c.
Referenced by import_string().