lexer_8c/ – Gwion
Gwion
A strongly timed musical programming language
lexer_8c/
lexer.c File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include "absyn.h"
#include "parser.h"
#include <unistd.h>
#include "err_msg.h"
Data Structures
struct yy_buffer_state
struct yy_trans_info
struct yyguts_t
Macros
#define YY_INT_ALIGNED short int
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 3
#define FLEX_BETA
#define yy_create_buffer minimal__create_buffer
#define yy_delete_buffer minimal__delete_buffer
#define yy_scan_buffer minimal__scan_buffer
#define yy_scan_string minimal__scan_string
#define yy_scan_bytes minimal__scan_bytes
#define yy_init_buffer minimal__init_buffer
#define yy_flush_buffer minimal__flush_buffer
#define yy_load_buffer_state minimal__load_buffer_state
#define yy_switch_to_buffer minimal__switch_to_buffer
#define yypush_buffer_state minimal_push_buffer_state
#define yypop_buffer_state minimal_pop_buffer_state
#define yyensure_buffer_stack minimal_ensure_buffer_stack
#define yylex minimal_lex
#define yyrestart minimal_restart
#define yylex_init minimal_lex_init
#define yylex_init_extra minimal_lex_init_extra
#define yylex_destroy minimal_lex_destroy
#define yyget_debug minimal_get_debug
#define yyset_debug minimal_set_debug
#define yyget_extra minimal_get_extra
#define yyset_extra minimal_set_extra
#define yyget_in minimal_get_in
#define yyset_in minimal_set_in
#define yyget_out minimal_get_out
#define yyset_out minimal_set_out
#define yyget_leng minimal_get_leng
#define yyget_text minimal_get_text
#define yyget_lineno minimal_get_lineno
#define yyset_lineno minimal_set_lineno
#define yyget_column minimal_get_column
#define yyset_column minimal_set_column
#define yywrap minimal_wrap
#define yyget_lval minimal_get_lval
#define yyset_lval minimal_set_lval
#define yyalloc minimal_alloc
#define yyrealloc minimal_realloc
#define yyfree minimal_free
#define FLEXINT_H
#define INT8_MIN (-128)
#define INT16_MIN (-32767-1)
#define INT32_MIN (-2147483647-1)
#define INT8_MAX (127)
#define INT16_MAX (32767)
#define INT32_MAX (2147483647)
#define UINT8_MAX (255U)
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define yyconst const
#define yynoreturn
#define YY_NULL 0
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
#define YY_TYPEDEF_YY_SCANNER_T
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r
#define BEGIN yyg->yy_start = 1 + 2 *
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE minimal_restart(yyin ,yyscanner)
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE 16384
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_SIZE_T
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define YY_LESS_LINENO(n)
#define YY_LINENO_REWIND_TO(ptr)
#define yyless(n)
#define unput(c) yyunput(c, yyg->yytext_ptr , yyscanner)
#define YY_STRUCT_YY_BUFFER_STATE
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define YY_BUFFER_EOF_PENDING 2
#define YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
#define YY_FLUSH_BUFFER minimal__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
#define yy_new_buffer minimal__create_buffer
#define yy_set_interactive(is_interactive)
#define yy_set_bol(at_bol)
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define minimal_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
#define yytext_ptr yytext_r
#define YY_DO_BEFORE_ACTION
#define YY_NUM_RULES 126
#define YY_END_OF_BUFFER 127
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define YY_NO_INPUT 1
#define INITIAL 0
#define comment 1
#define cdoc 2
#define COMMENT 3
#define CDOC 4
#define YY_EXTRA_TYPE void *
#define yylval yyg->yylval_r
#define YY_READ_BUF_SIZE 8192
#define ECHO do { if (fwrite(yytext, (size_t) yyleng, 1, yyout)) {} } while (0)
#define YY_INPUT(buf, result, max_size)
#define yyterminate() return YY_NULL
#define YY_START_STACK_INCR 25
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg , yyscanner)
#define YY_DECL_IS_OURS 1
#define YY_DECL
#define YY_USER_ACTION
#define YY_BREAK /*LINTED*/break;
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_EXIT_FAILURE 2
#define yyless(n)
#define YYTABLES_NAME "yytables"
Typedefs
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef void * yyscan_t
typedef struct yy_buffer_state * YY_BUFFER_STATE
typedef size_t yy_size_t
typedef flex_uint8_t YY_CHAR
typedef int yy_state_type
Functions
void minimal_restart (FILE *input_file, yyscan_t yyscanner)
void minimal__switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
YY_BUFFER_STATE minimal__create_buffer (FILE *file, int size, yyscan_t yyscanner)
void minimal__delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
void minimal__flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
void minimal_push_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
void minimal_pop_buffer_state (yyscan_t yyscanner)
static void minimal_ensure_buffer_stack (yyscan_t yyscanner)
static void minimal__load_buffer_state (yyscan_t yyscanner)
static void minimal__init_buffer (YY_BUFFER_STATE b, FILE *file, yyscan_t yyscanner)
YY_BUFFER_STATE minimal__scan_buffer (char *base, yy_size_t size, yyscan_t yyscanner)
YY_BUFFER_STATE minimal__scan_string (const char *yy_str, yyscan_t yyscanner)
YY_BUFFER_STATE minimal__scan_bytes (const char *bytes, int len, yyscan_t yyscanner)
void * minimal_alloc (yy_size_t, yyscan_t yyscanner)
void * minimal_realloc (void *, yy_size_t, yyscan_t yyscanner)
void minimal_free (void *, yyscan_t yyscanner)
static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner)
static int yy_get_next_buffer (yyscan_t yyscanner)
static void yynoreturn yy_fatal_error (const char *msg, yyscan_t yyscanner)
static char * strip_lit (char *str)
static char * alloc_str (char *str)
static long htol (char *str)
static int newline (void *data)
char * minimal_get_text (yyscan_t yyscanner)
static int adjust (void *data)
static int yy_init_globals (yyscan_t yyscanner)
int minimal_lex_init (yyscan_t *scanner)
int minimal_lex_init_extra (YY_EXTRA_TYPE user_defined, yyscan_t *scanner)
int minimal_lex_destroy (yyscan_t yyscanner)
int minimal_get_debug (yyscan_t yyscanner)
void minimal_set_debug (int debug_flag, yyscan_t yyscanner)
YY_EXTRA_TYPE minimal_get_extra (yyscan_t yyscanner)
void minimal_set_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
FILE * minimal_get_in (yyscan_t yyscanner)
void minimal_set_in (FILE *_in_str, yyscan_t yyscanner)
FILE * minimal_get_out (yyscan_t yyscanner)
void minimal_set_out (FILE *_out_str, yyscan_t yyscanner)
int minimal_get_leng (yyscan_t yyscanner)
int minimal_get_lineno (yyscan_t yyscanner)
void minimal_set_lineno (int _line_number, yyscan_t yyscanner)
int minimal_get_column (yyscan_t yyscanner)
void minimal_set_column (int _column_no, yyscan_t yyscanner)
YYSTYPE * minimal_get_lval (yyscan_t yyscanner)
void minimal_set_lval (YYSTYPE *yylval_param, yyscan_t yyscanner)
int minimal_lex (YYSTYPE *yylval_param, yyscan_t yyscanner)
if (!yyg->yy_init)
Ast parse (m_str filename)
Variables
static const flex_int16_t yy_accept [311]
static const YY_CHAR yy_ec [256]
static const YY_CHAR yy_meta [68]
static const flex_int16_t yy_base [320]
static const flex_int16_t yy_def [320]
static const flex_int16_t yy_nxt [476]
static const flex_int16_t yy_chk [476]
YY_DECL
char * yy_cp
char * yy_bp
int yy_act
struct yyguts_t * yyg = (struct yyguts_t*)yyscanner
yylval = yylval_param
Macro Definition Documentation
BEGIN
#define BEGIN yyg->yy_start = 1 + 2 *
Definition at line 203 of file lexer.c.
Referenced by if().
cdoc
#define cdoc 2
Definition at line 802 of file lexer.c.
Referenced by if().
CDOC
#define CDOC 4
Definition at line 804 of file lexer.c.
Referenced by if().
comment
#define comment 1
Definition at line 801 of file lexer.c.
Referenced by if().
COMMENT
#define COMMENT 3
Definition at line 803 of file lexer.c.
Referenced by if().
ECHO
#define ECHO do { if (fwrite(yytext, (size_t) yyleng, 1, yyout)) {} } while (0)
Definition at line 949 of file lexer.c.
Referenced by if().
EOB_ACT_CONTINUE_SCAN
#define EOB_ACT_CONTINUE_SCAN 0
Definition at line 243 of file lexer.c.
Referenced by if().
EOB_ACT_END_OF_FILE
#define EOB_ACT_END_OF_FILE 1
Definition at line 244 of file lexer.c.
Referenced by if().
EOB_ACT_LAST_MATCH
#define EOB_ACT_LAST_MATCH 2
Definition at line 245 of file lexer.c.
Referenced by if().
FLEX_BETA
#define FLEX_BETA
Definition at line 14 of file lexer.c.
FLEX_SCANNER
#define FLEX_SCANNER
Definition at line 9 of file lexer.c.
FLEXINT_H
#define FLEXINT_H
Definition at line 104 of file lexer.c.
INITIAL
#define INITIAL 0
Definition at line 800 of file lexer.c.
Referenced by if().
INT16_MAX
#define INT16_MAX (32767)
Definition at line 146 of file lexer.c.
Referenced by read_sample_s16ne(), and write_sample_s16ne().
INT16_MIN
#define INT16_MIN (-32767-1)
Definition at line 137 of file lexer.c.
Referenced by read_sample_s16ne(), and write_sample_s16ne().
INT32_MAX
#define INT32_MAX (2147483647)
Definition at line 149 of file lexer.c.
Referenced by read_sample_s32ne(), and write_sample_s32ne().
INT32_MIN
#define INT32_MIN (-2147483647-1)
Definition at line 140 of file lexer.c.
Referenced by read_sample_s32ne(), and write_sample_s32ne().
INT8_MAX
#define INT8_MAX (127)
Definition at line 143 of file lexer.c.
INT8_MIN
#define INT8_MIN (-128)
Definition at line 134 of file lexer.c.
minimal_wrap
#define minimal_wrap (yyscanner) (/*CONSTCOND*/1)
Definition at line 388 of file lexer.c.
Referenced by if().
REJECT
#define REJECT reject_used_but_not_detected
Definition at line 693 of file lexer.c.
UINT16_MAX
#define UINT16_MAX (65535U)
Definition at line 155 of file lexer.c.
UINT32_MAX
#define UINT32_MAX (4294967295U)
Definition at line 158 of file lexer.c.
UINT8_MAX
#define UINT8_MAX (255U)
Definition at line 152 of file lexer.c.
unput
#define unput (c) yyunput(c, yyg->yytext_ptr , yyscanner)
Definition at line 263 of file lexer.c.
YY_AT_BOL
#define YY_AT_BOL () (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
Definition at line 384 of file lexer.c.
YY_BREAK
#define YY_BREAK /*LINTED*/break;
Definition at line 1030 of file lexer.c.
Referenced by if().
YY_BUF_SIZE
#define YY_BUF_SIZE 16384
Definition at line 225 of file lexer.c.
Referenced by if().
YY_BUFFER_EOF_PENDING
#define YY_BUFFER_EOF_PENDING 2
Definition at line 325 of file lexer.c.
Referenced by if().
YY_BUFFER_NEW
#define YY_BUFFER_NEW 0
Definition at line 313 of file lexer.c.
Referenced by if().
YY_BUFFER_NORMAL
#define YY_BUFFER_NORMAL 1
Definition at line 314 of file lexer.c.
Referenced by if().
yy_create_buffer
#define yy_create_buffer minimal__create_buffer
Definition at line 17 of file lexer.c.
YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER
Value:
(yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
Definition at line 336 of file lexer.c.
Referenced by if().
YY_CURRENT_BUFFER_LVALUE
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
Definition at line 342 of file lexer.c.
Referenced by if().
YY_DECL
#define YY_DECL
Value:
int minimal_lex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
Definition at line 1017 of file lexer.c.
YY_DECL_IS_OURS
#define YY_DECL_IS_OURS 1
Definition at line 1012 of file lexer.c.
yy_delete_buffer
#define yy_delete_buffer minimal__delete_buffer
Definition at line 19 of file lexer.c.
YY_DO_BEFORE_ACTION
#define YY_DO_BEFORE_ACTION
Value:
yyg->yytext_ptr = yy_bp; \
    yyleng = (int) (yy_cp - yy_bp); \
    yyg->yy_hold_char = *yy_cp; \
    *yy_cp = '\0'; \
    yyg->yy_c_buf_p = yy_cp;
Definition at line 404 of file lexer.c.
Referenced by if().
YY_END_OF_BUFFER
#define YY_END_OF_BUFFER 127
Definition at line 411 of file lexer.c.
Referenced by if().
YY_END_OF_BUFFER_CHAR
#define YY_END_OF_BUFFER_CHAR 0
Definition at line 214 of file lexer.c.
Referenced by if().
YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
Referenced by if().
YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
Definition at line 815 of file lexer.c.
Referenced by if().
YY_FATAL_ERROR
#define YY_FATAL_ERROR (msg) yy_fatal_error(msg , yyscanner)
Definition at line 1003 of file lexer.c.
Referenced by if().
yy_flex_debug
#define yy_flex_debug yyg->yy_flex_debug_r
Definition at line 197 of file lexer.c.
Referenced by if().
YY_FLEX_MAJOR_VERSION
#define YY_FLEX_MAJOR_VERSION 2
Definition at line 10 of file lexer.c.
YY_FLEX_MINOR_VERSION
#define YY_FLEX_MINOR_VERSION 6
Definition at line 11 of file lexer.c.
YY_FLEX_SUBMINOR_VERSION
#define YY_FLEX_SUBMINOR_VERSION 3
Definition at line 12 of file lexer.c.
yy_flush_buffer
#define yy_flush_buffer minimal__flush_buffer
Definition at line 29 of file lexer.c.
YY_FLUSH_BUFFER
#define YY_FLUSH_BUFFER minimal__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
Definition at line 355 of file lexer.c.
yy_init_buffer
#define yy_init_buffer minimal__init_buffer
Definition at line 27 of file lexer.c.
YY_INPUT
#define YY_INPUT (buf, result, max_size)
Value:
if (YY_CURRENT_BUFFER_LVALUE->yy_is_interactive) \
        { \
        int c = '*'; \
        int n; \
        for ( n = 0; n < max_size && \
                 (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
            buf[n] = (char) c; \
        if ( c == '\n' ) \
            buf[n++] = (char) c; \
        if ( c == EOF && ferror( yyin ) ) \
            YY_FATAL_ERROR( "input in flex scanner failed" ); \
        result = n; \
        } \
    else \
        { \
        errno=0; \
        while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
            { \
            if( errno != EINTR) \
                { \
                YY_FATAL_ERROR( "input in flex scanner failed" ); \
                break; \
                } \
            errno=0; \
            clearerr(yyin); \
            } \
        }\
\
Definition at line 956 of file lexer.c.
Referenced by if().
YY_INT_ALIGNED
#define YY_INT_ALIGNED short int
Definition at line 5 of file lexer.c.
YY_LESS_LINENO
#define YY_LESS_LINENO (n)
Definition at line 247 of file lexer.c.
YY_LINENO_REWIND_TO
#define YY_LINENO_REWIND_TO (ptr)
Definition at line 248 of file lexer.c.
yy_load_buffer_state
#define yy_load_buffer_state minimal__load_buffer_state
Definition at line 31 of file lexer.c.
YY_MORE_ADJ
#define YY_MORE_ADJ 0
Definition at line 695 of file lexer.c.
Referenced by if().
yy_new_buffer
#define yy_new_buffer minimal__create_buffer
Definition at line 365 of file lexer.c.
YY_NEW_FILE
#define YY_NEW_FILE minimal_restart(yyin ,yyscanner)
Definition at line 213 of file lexer.c.
Referenced by if().
YY_NO_INPUT
#define YY_NO_INPUT 1
Definition at line 796 of file lexer.c.
YY_NULL
#define YY_NULL 0
Definition at line 175 of file lexer.c.
YY_NUM_RULES
#define YY_NUM_RULES 126
Definition at line 410 of file lexer.c.
YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
Definition at line 940 of file lexer.c.
Referenced by if().
YY_RESTORE_YY_MORE_OFFSET
#define YY_RESTORE_YY_MORE_OFFSET
Definition at line 696 of file lexer.c.
Referenced by if().
YY_RULE_SETUP
#define YY_RULE_SETUP YY_USER_ACTION
Definition at line 1033 of file lexer.c.
Referenced by if().
YY_SC_TO_UI
#define YY_SC_TO_UI (c) ((YY_CHAR) (c))
Definition at line 180 of file lexer.c.
Referenced by if().
yy_scan_buffer
#define yy_scan_buffer minimal__scan_buffer
Definition at line 21 of file lexer.c.
yy_scan_bytes
#define yy_scan_bytes minimal__scan_bytes
Definition at line 25 of file lexer.c.
yy_scan_string
#define yy_scan_string minimal__scan_string
Definition at line 23 of file lexer.c.
yy_set_bol
#define yy_set_bol (at_bol)
Value:
{ \
    if ( ! YY_CURRENT_BUFFER ){\
        minimal_ensure_buffer_stack (yyscanner); \
        YY_CURRENT_BUFFER_LVALUE =    \
            minimal__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
    } \
    YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
    }
Definition at line 375 of file lexer.c.
yy_set_interactive
#define yy_set_interactive (is_interactive)
Value:
{ \
    if ( ! YY_CURRENT_BUFFER ){ \
        minimal_ensure_buffer_stack (yyscanner); \
        YY_CURRENT_BUFFER_LVALUE =    \
            minimal__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
    } \
    YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
    }
Definition at line 366 of file lexer.c.
YY_SKIP_YYWRAP
#define YY_SKIP_YYWRAP
Definition at line 389 of file lexer.c.
YY_START
#define YY_START ((yyg->yy_start - 1) / 2)
Definition at line 208 of file lexer.c.
Referenced by if().
YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
Definition at line 998 of file lexer.c.
YY_STATE_BUF_SIZE
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
Definition at line 231 of file lexer.c.
YY_STATE_EOF
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
Definition at line 211 of file lexer.c.
Referenced by if().
YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
Definition at line 266 of file lexer.c.
yy_switch_to_buffer
#define yy_switch_to_buffer minimal__switch_to_buffer
Definition at line 33 of file lexer.c.
YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
Definition at line 234 of file lexer.c.
YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
Definition at line 184 of file lexer.c.
YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
Definition at line 239 of file lexer.c.
YY_USER_ACTION
#define YY_USER_ACTION
Definition at line 1025 of file lexer.c.
yyalloc
#define yyalloc minimal_alloc
Definition at line 85 of file lexer.c.
yycolumn
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
Definition at line 196 of file lexer.c.
Referenced by if().
yyconst
#define yyconst const
Definition at line 166 of file lexer.c.
yyensure_buffer_stack
#define yyensure_buffer_stack minimal_ensure_buffer_stack
Definition at line 39 of file lexer.c.
yyextra
#define yyextra yyg->yyextra_r
Definition at line 192 of file lexer.c.
Referenced by if().
yyfree
#define yyfree minimal_free
Definition at line 89 of file lexer.c.
yyget_column
#define yyget_column minimal_get_column
Definition at line 75 of file lexer.c.
yyget_debug
#define yyget_debug minimal_get_debug
Definition at line 51 of file lexer.c.
yyget_extra
#define yyget_extra minimal_get_extra
Definition at line 55 of file lexer.c.
yyget_in
#define yyget_in minimal_get_in
Definition at line 59 of file lexer.c.
yyget_leng
#define yyget_leng minimal_get_leng
Definition at line 67 of file lexer.c.
yyget_lineno
#define yyget_lineno minimal_get_lineno
Definition at line 71 of file lexer.c.
yyget_lval
#define yyget_lval minimal_get_lval
Definition at line 81 of file lexer.c.
yyget_out
#define yyget_out minimal_get_out
Definition at line 63 of file lexer.c.
yyget_text
#define yyget_text minimal_get_text
Definition at line 69 of file lexer.c.
yyin
#define yyin yyg->yyin_r
Definition at line 190 of file lexer.c.
Referenced by if().
yyleng
#define yyleng yyg->yyleng_r
Definition at line 193 of file lexer.c.
Referenced by if().
yyless [1/2]
#define yyless (n)
Value:
do \
        { \
        /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
        *yy_cp = yyg->yy_hold_char; \
        YY_RESTORE_YY_MORE_OFFSET \
        yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
    while ( 0 )
Definition at line 251 of file lexer.c.
yyless [2/2]
#define yyless (n)
Value:
do \
        { \
        /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
        yytext[yyleng] = yyg->yy_hold_char; \
        yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
        yyg->yy_hold_char = *yyg->yy_c_buf_p; \
        *yyg->yy_c_buf_p = '\0'; \
        yyleng = yyless_macro_arg; \
        } \
    while ( 0 )
Definition at line 251 of file lexer.c.
yylex
#define yylex minimal_lex
Definition at line 41 of file lexer.c.
yylex_destroy
#define yylex_destroy minimal_lex_destroy
Definition at line 49 of file lexer.c.
yylex_init
#define yylex_init minimal_lex_init
Definition at line 45 of file lexer.c.
yylex_init_extra
#define yylex_init_extra minimal_lex_init_extra
Definition at line 47 of file lexer.c.
yylineno
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
Definition at line 195 of file lexer.c.
Referenced by if().
yylval
#define yylval yyg->yylval_r
Definition at line 858 of file lexer.c.
Referenced by if().
yymore
#define yymore () yymore_used_but_not_detected
Definition at line 694 of file lexer.c.
yynoreturn
#define yynoreturn
Definition at line 171 of file lexer.c.
Referenced by if().
yyout
#define yyout yyg->yyout_r
Definition at line 191 of file lexer.c.
Referenced by if().
yypop_buffer_state
#define yypop_buffer_state minimal_pop_buffer_state
Definition at line 37 of file lexer.c.
yypush_buffer_state
#define yypush_buffer_state minimal_push_buffer_state
Definition at line 35 of file lexer.c.
yyrealloc
#define yyrealloc minimal_realloc
Definition at line 87 of file lexer.c.
yyrestart
#define yyrestart minimal_restart
Definition at line 43 of file lexer.c.
yyset_column
#define yyset_column minimal_set_column
Definition at line 77 of file lexer.c.
yyset_debug
#define yyset_debug minimal_set_debug
Definition at line 53 of file lexer.c.
yyset_extra
#define yyset_extra minimal_set_extra
Definition at line 57 of file lexer.c.
yyset_in
#define yyset_in minimal_set_in
Definition at line 61 of file lexer.c.
yyset_lineno
#define yyset_lineno minimal_set_lineno
Definition at line 73 of file lexer.c.
yyset_lval
#define yyset_lval minimal_set_lval
Definition at line 83 of file lexer.c.
yyset_out
#define yyset_out minimal_set_out
Definition at line 65 of file lexer.c.
YYSTATE
#define YYSTATE YY_START
Definition at line 209 of file lexer.c.
YYTABLES_NAME
#define YYTABLES_NAME "yytables"
yyterminate
#define yyterminate () return YY_NULL
Definition at line 993 of file lexer.c.
Referenced by if().
yytext
#define yytext yyg->yytext_r
Definition at line 194 of file lexer.c.
Referenced by if().
yytext_ptr
#define yytext_ptr yytext_r
Definition at line 394 of file lexer.c.
yywrap
#define yywrap minimal_wrap
Definition at line 79 of file lexer.c.
Typedef Documentation
flex_int16_t
typedef short int flex_int16_t
Definition at line 126 of file lexer.c.
flex_int32_t
typedef int flex_int32_t
Definition at line 127 of file lexer.c.
flex_int8_t
typedef signed char flex_int8_t
Definition at line 125 of file lexer.c.
flex_uint16_t
typedef unsigned short int flex_uint16_t
Definition at line 129 of file lexer.c.
flex_uint32_t
typedef unsigned int flex_uint32_t
Definition at line 130 of file lexer.c.
flex_uint8_t
typedef unsigned char flex_uint8_t
Definition at line 128 of file lexer.c.
YY_BUFFER_STATE
typedef struct yy_buffer_state* YY_BUFFER_STATE
Definition at line 235 of file lexer.c.
YY_CHAR
typedef flex_uint8_t YY_CHAR
Definition at line 390 of file lexer.c.
yy_size_t
typedef size_t yy_size_t
Definition at line 240 of file lexer.c.
yy_state_type
typedef int yy_state_type
Definition at line 392 of file lexer.c.
yyscan_t
typedef void* yyscan_t
Definition at line 185 of file lexer.c.
Function Documentation
adjust()
static int adjust (void * data) static
Referenced by if(), and newline().
alloc_str()
static char* alloc_str (char * str) static
Definition at line 709 of file lexer.c.
References insert_symbol(), and S_name().
Referenced by if().
 {
 /*
   char* s = (char*)calloc(1,  strlen(str) + 1 );
   strcpy( s, str );
   return s;
 */
  S_Symbol sym = insert_symbol(str);
  return S_name(sym);
 }
htol()
static long htol (char * str) static
Definition at line 720 of file lexer.c.
Referenced by if().
 {
 char * c = str;
   unsigned long n = 0;
   c += 2;
   while( *c )
   {
     n <<= 4;
     switch( *c )
     {
       case '1': case '2': case '3': case '4': case '5':
       case '6': case '7': case '8': case '9': case '0':
       n += *c - '0';
       break;
       case 'a': case 'b': case 'c': case 'd': case 'e': case
       'f':
       n += *c - 'a' + 10;
       break;
       case 'A': case 'B': case
       'C': case 'D': case 'E':
       case 'F':
       n += *c - 'A'
       + 10;
       break;
     }
     c++;
   }
   return n;
 }
if()
if (!yyg-> yy_init)
Definition at line 1047 of file lexer.c.
References ABSTRACT, adjust(), alloc_str(), AND, ASSIGN, AST_DTOR, ATCHUCK, ATPAREN, ATSYM, BEGIN, BREAK, CASE, cdoc, CDOC, CHAR_LIT, CHUCK, CLASS, COLON, COLONCOLON, COMMA, comment, COMMENT, CONTINUE, DIVIDE, DIVIDECHUCK, DO, DOC, DOLLAR, DOT, ECHO, ELSE, ENUM, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, EQ, err_msg(), EXCLAMATION, EXTENDS, MyArg::file, MyArg::filename, FLOAT, FOR, free(), FUNC_PTR, FUNCTION, GE, GOTO, GT, GTB, htol(), ID, IF, IMPLEMENTS, INITIAL, INTERFACE, L_HACK, LBRACE, LBRACK, LE, MyArg::line, LOOP, LPAREN, LT, LTB, malloc(), map_get(), minimal__create_buffer(), minimal__delete_buffer(), minimal__flush_buffer(), minimal__init_buffer(), minimal__load_buffer_state(), minimal__scan_buffer(), minimal__scan_bytes(), minimal__scan_string(), minimal__switch_to_buffer(), minimal_alloc(), minimal_ensure_buffer_stack(), minimal_error(), minimal_free(), minimal_get_column(), minimal_get_debug(), minimal_get_extra(), minimal_get_in(), minimal_get_leng(), minimal_get_lineno(), minimal_get_lval(), minimal_get_out(), minimal_get_text(), minimal_lex_destroy(), minimal_lex_init(), minimal_lex_init_extra(), minimal_pop_buffer_state(), minimal_push_buffer_state(), minimal_realloc(), minimal_restart(), minimal_set_column(), minimal_set_debug(), minimal_set_extra(), minimal_set_in(), minimal_set_lineno(), minimal_set_lval(), minimal_set_out(), minimal_wrap, MINUS, MINUSCHUCK, MINUSMINUS, MODULOCHUCK, NEQ, NEW, newline(), NUM, OPERATOR, OR, PARSE_, PERCENT, PERCENTPAREN, PLUS, PLUSCHUCK, PLUSPLUS, MyArg::pos, PRIVATE, PROTECTED, PUBLIC, QUESTION, R_HACK, RAND, RBRACE, RBRACK, REQ, RETURN, RGE, RGT, RLE, RLT, RNEQ, ROR, RPAREN, RSAND, RSL, RSOR, RSR, RSXOR, S_AND, S_OR, S_XOR, scan_map, SEMICOLON, SHARPPAREN, SHIFT_LEFT, SHIFT_RIGHT, SIZEOF, SPORK, STATIC, strcat(), STRING_LIT, strip_lit(), SWITCH, TEMPLATE, TILDA, TIMES, TIMESCHUCK, TRIG, TYPEOF, UNCHUCK, UNION, UNTIL, UNTRIG, VARARG, WHILE, yy_accept, yy_buffer_state::yy_at_bol, yy_base, YY_BREAK, yy_buffer_state::yy_bs_column, yy_buffer_state::yy_bs_lineno, yy_buffer_state::yy_buf_pos, YY_BUF_SIZE, yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, YY_BUFFER_NEW, YY_BUFFER_NORMAL, yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, yy_buffer_state::yy_buffer_status, yyguts_t::yy_c_buf_p, yy_buffer_state::yy_ch_buf, yy_chk, yy_cp, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_def, yyguts_t::yy_did_buffer_switch_on_eof, YY_DO_BEFORE_ACTION, yy_ec, YY_END_OF_BUFFER, YY_END_OF_BUFFER_CHAR, YY_EXIT_FAILURE, YY_EXTRA_TYPE, yy_fatal_error(), YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_flex_debug, yy_get_next_buffer(), yy_get_previous_state(), yyguts_t::yy_hold_char, yyguts_t::yy_init, yy_init_globals(), YY_INPUT, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, yy_meta, YY_MORE_ADJ, yy_buffer_state::yy_n_chars, yyguts_t::yy_n_chars, YY_NEW_FILE, yy_nxt, YY_READ_BUF_SIZE, YY_RESTORE_YY_MORE_OFFSET, YY_RULE_SETUP, YY_SC_TO_UI, YY_START, yyguts_t::yy_start, yyguts_t::yy_start_stack, yyguts_t::yy_start_stack_depth, yyguts_t::yy_start_stack_ptr, YY_STATE_EOF, yy_try_NUL_trans(), yycolumn, yyextra, yyin, yyleng, yylineno, yylval, yynoreturn, yyout, yyterminate, and yytext.
         {
         yyg->yy_init = 1;
 #ifdef YY_USER_INIT
         YY_USER_INIT;
 #endif
         if ( ! yyg->yy_start )
             yyg->yy_start = 1;  /* first start state */
         if ( ! yyin )
             yyin = stdin;
         if ( ! yyout )
             yyout = stdout;
         if ( ! YY_CURRENT_BUFFER ) {
             minimal_ensure_buffer_stack (yyscanner);
             YY_CURRENT_BUFFER_LVALUE =
                 minimal__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
         }
         minimal__load_buffer_state(yyscanner );
         }
minimal__create_buffer()
YY_BUFFER_STATE minimal__create_buffer (FILE * file, int size, yyscan_t yyscanner)
Referenced by if().
minimal__delete_buffer()
void minimal__delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Referenced by if().
minimal__flush_buffer()
void minimal__flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Referenced by if().
minimal__init_buffer()
static void minimal__init_buffer (YY_BUFFER_STATE b, FILE * file, yyscan_t yyscanner) static
Referenced by if().
minimal__load_buffer_state()
static void minimal__load_buffer_state (yyscan_t yyscanner) static
Referenced by if().
minimal__scan_buffer()
YY_BUFFER_STATE minimal__scan_buffer (char * base, yy_size_t size, yyscan_t yyscanner)
Referenced by if().
minimal__scan_bytes()
YY_BUFFER_STATE minimal__scan_bytes (const char * bytes, int len, yyscan_t yyscanner)
Referenced by if().
minimal__scan_string()
YY_BUFFER_STATE minimal__scan_string (const char * yy_str, yyscan_t yyscanner)
Referenced by if().
minimal__switch_to_buffer()
void minimal__switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Referenced by if().
minimal_alloc()
void* minimal_alloc (yy_size_t , yyscan_t yyscanner)
Referenced by if().
minimal_ensure_buffer_stack()
static void minimal_ensure_buffer_stack (yyscan_t yyscanner) static
Referenced by if().
minimal_free()
void minimal_free (void * , yyscan_t yyscanner)
Referenced by if().
minimal_get_column()
int minimal_get_column (yyscan_t yyscanner)
Referenced by if().
minimal_get_debug()
int minimal_get_debug (yyscan_t yyscanner)
Referenced by if().
minimal_get_extra()
YY_EXTRA_TYPE minimal_get_extra (yyscan_t yyscanner)
Referenced by if(), and parse().
minimal_get_in()
FILE* minimal_get_in (yyscan_t yyscanner)
Referenced by if().
minimal_get_leng()
int minimal_get_leng (yyscan_t yyscanner)
Referenced by if().
minimal_get_lineno()
int minimal_get_lineno (yyscan_t yyscanner)
Referenced by if().
minimal_get_lval()
YYSTYPE* minimal_get_lval (yyscan_t yyscanner)
Referenced by if().
minimal_get_out()
FILE* minimal_get_out (yyscan_t yyscanner)
Referenced by if().
minimal_get_text()
char * minimal_get_text (yyscan_t yyscanner)
Referenced by if(), and newline().
minimal_lex()
int minimal_lex (YYSTYPE * yylval_param, yyscan_t yyscanner)
minimal_lex_destroy()
int minimal_lex_destroy (yyscan_t yyscanner)
Referenced by if(), and parse().
minimal_lex_init()
int minimal_lex_init (yyscan_t * scanner)
Referenced by if(), and parse().
minimal_lex_init_extra()
int minimal_lex_init_extra (YY_EXTRA_TYPE user_defined, yyscan_t * scanner)
Referenced by if().
minimal_pop_buffer_state()
void minimal_pop_buffer_state (yyscan_t yyscanner)
Referenced by if().
minimal_push_buffer_state()
void minimal_push_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Referenced by if().
minimal_realloc()
void* minimal_realloc (void * , yy_size_t , yyscan_t yyscanner)
Referenced by if().
minimal_restart()
void minimal_restart (FILE * input_file, yyscan_t yyscanner)
Referenced by if().
minimal_set_column()
void minimal_set_column (int _column_no, yyscan_t yyscanner)
Referenced by if().
minimal_set_debug()
void minimal_set_debug (int debug_flag, yyscan_t yyscanner)
Referenced by if().
minimal_set_extra()
void minimal_set_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Referenced by if(), and parse().
minimal_set_in()
void minimal_set_in (FILE * _in_str, yyscan_t yyscanner)
Referenced by if(), and parse().
minimal_set_lineno()
void minimal_set_lineno (int _line_number, yyscan_t yyscanner)
Referenced by if().
minimal_set_lval()
void minimal_set_lval (YYSTYPE * yylval_param, yyscan_t yyscanner)
Referenced by if().
minimal_set_out()
void minimal_set_out (FILE * _out_str, yyscan_t yyscanner)
Referenced by if().
newline()
static int newline (void * data) static
Definition at line 753 of file lexer.c.
References adjust(), MyArg::line, map_get(), minimal_get_text(), MyArg::pos, and scan_map.
Referenced by if().
 {
   MyArg* arg = (MyArg*)map_get(scan_map, (vtype)data);
   arg->line++;
   arg->pos = 1;
   return 1;
 }
parse()
Ast parse (m_str filename)
Definition at line 2976 of file lexer.c.
References Ast_::doc, err_msg(), free_Ast(), free_Vector(), malloc(), map_set(), minimal_get_extra(), minimal_lex_destroy(), minimal_lex_init(), minimal_parse(), minimal_set_extra(), minimal_set_in(), new_Vector(), PARSE_, MyArg::scanner, strcat(), vector_front(), and vector_remove().
Referenced by compile(), and SFUN().
 {
   Ast    ast  = NULL;
   FILE*  file = NULL;
   MyArg arg;
   minimal_lex_init(&arg.scanner);
   minimal_set_extra(&arg, arg.scanner);
 //  minimal_lex_init_extra(&arg, arg.scanner);
   map_set(scan_map, (vtype)arg.scanner, (vtype)&arg);
   map_set(scan_map, (vtype)minimal_get_extra(arg.scanner), (vtype)&arg);
   arg.line = 1; arg.pos  = 0; arg.doc = new_Vector();
   char c[1025];
   memset(c, 0, 1025);
   strncat(c, filename, 1024);
   if(!(file = fopen(c, "r")))
   {
     err_msg(PARSE_, 0, "error while opening file '%s'.", filename);
     return NULL;
   }
 //  arg.fd = fileno(file);
   arg.file = file;
   arg.filename = filename;
   minimal_set_in(file, arg.scanner);
   if(minimal_parse(&arg))
   {
     free_Ast(ast);
     free_Vector(arg.doc);
     minimal_lex_destroy(arg.scanner);
     return NULL;
   }
   filename = c;
   ast = arg.ast;
   if(vector_front(arg.doc))
   {
     ast->doc = malloc(sizeof(char));
     memset(ast->doc, 0, 1);
   }
   while(vector_front(arg.doc))
   {
     strcat(ast->doc, (m_str)vector_front(arg.doc));
     vector_remove(arg.doc, 0);
   }
   free_Vector(arg.doc);
   fclose(file);
   minimal_lex_destroy(arg.scanner);
   return ast;
 }
strip_lit()
static char* strip_lit (char * str) static
Definition at line 703 of file lexer.c.
Referenced by if().
 {
   str[strlen(str)-1] = '\0';
   return str+1;
 }
yy_fatal_error()
static void yynoreturn yy_fatal_error (const char * msg, yyscan_t yyscanner) static
Referenced by if().
yy_get_next_buffer()
static int yy_get_next_buffer (yyscan_t yyscanner) static
Referenced by if().
yy_get_previous_state()
static yy_state_type yy_get_previous_state (yyscan_t yyscanner) static
Referenced by if().
yy_init_globals()
static int yy_init_globals (yyscan_t yyscanner) static
Referenced by if().
yy_try_NUL_trans()
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner) static
Referenced by if().
Variable Documentation
yy_accept
const flex_int16_t yy_accept[311] static
Definition at line 419 of file lexer.c.
Referenced by if().
yy_act
int yy_act
Definition at line 1042 of file lexer.c.
yy_base
const flex_int16_t yy_base[320] static
Definition at line 500 of file lexer.c.
Referenced by if().
yy_bp
char * yy_bp
Definition at line 1041 of file lexer.c.
yy_chk
const flex_int16_t yy_chk[476] static
Definition at line 634 of file lexer.c.
Referenced by if().
yy_cp
char* yy_cp
Definition at line 1041 of file lexer.c.
Referenced by if().
YY_DECL
YY_DECL
Initial value:
{
    yy_state_type yy_current_state
The main scanner function which does all the work.
Definition at line 1039 of file lexer.c.
yy_def
const flex_int16_t yy_def[320] static
Definition at line 539 of file lexer.c.
Referenced by if().
yy_ec
const YY_CHAR yy_ec[256] static
Definition at line 457 of file lexer.c.
Referenced by if().
yy_meta
const YY_CHAR yy_meta[68] static
Initial value:
=
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    5,    5,    5,    5,    1,    1,    1,    1,    4,
        4,    4,    4,    4,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    1,    1
    }
Definition at line 489 of file lexer.c.
Referenced by if().
yy_nxt
const flex_int16_t yy_nxt[476] static
Definition at line 578 of file lexer.c.
Referenced by if().
yyg
struct yyguts_t* yyg = (struct yyguts_t*)yyscanner
Definition at line 1043 of file lexer.c.
yylval
yylval = yylval_param
Definition at line 1045 of file lexer.c.
Referenced by yyparse().