Gwion dev-docs: lang/machine.c File Reference
--- layout: default title: machine_8c/ image: feature: abstract-1.jpg ---
machine.c File Reference
#include <string.h>
#include <dirent.h>
#include <soundpipe.h>
#include "defs.h"
#include "absyn.h"
#include "import.h"
#include "shreduler.h"
#include "compile.h"
#include "lang.h"
#include "doc.h"
#include "bbq.h"
Macros
#define prepare()
#define clean()
Functions
static SFUN (machine_add)
static SFUN (machine_doc)
static int js_filter (const struct dirent *dir)
static SFUN (machine_doc_update)
static SFUN (machine_adept)
static m_str randstring (VM *vm, int length)
SFUN (machine_check)
static SFUN (machine_compile)
static SFUN (machine_shreds)
m_bool import_machine (Env env)
Variables
struct Type_ t_machine = { "Machine", 0, NULL, te_machine}
Macro Definition Documentation
clean
#define clean ()
Value:
if(ast) \
    free_Ast(ast);
Definition at line 31 of file machine.c.
Referenced by compile(), and main().
prepare
#define prepare ()
Value:
Ast ast = NULL; \
  M_Object obj = *(M_Object*)(shred->mem + SZ_INT);\
  char* str = STRING(obj);\
  release(obj, shred); \
    if(strcmp(str, "global_context"))\
    {\
      str = realpath(str, NULL);\
      if(!str) return;\
      ast = parse(str);\
      if(!ast) return;\
      if(type_engine_check_prog(shred->vm_ref->env, ast, str) < 0) return;\
    }
Definition at line 17 of file machine.c.
Referenced by SFUN().
Function Documentation
import_machine()
m_bool import_machine (Env env)
Definition at line 231 of file machine.c.
References add_global_type(), CHECK_BB, CHECK_OB, Env_::class_def, dl_func_add_arg(), Type_::doc, Env_::global_nspc, import_class_begin(), import_class_end(), import_sfun(), and new_DL_Func().
Referenced by type_engine_init().
 {
   DL_Func* fun;
   CHECK_BB(add_global_type(env, &t_machine))
   CHECK_OB(import_class_begin(env, &t_machine, env->global_nspc, NULL, NULL))
   env->class_def->doc = "access the virtual machine, including docs";
   fun = new_DL_Func("void",  "add",     (m_uint)machine_add);
   dl_func_add_arg(fun,       "string",  "filename");
   CHECK_OB(import_sfun(env,  fun))
   fun = new_DL_Func("int[]", "shreds", (m_uint)machine_shreds);
   CHECK_OB(import_sfun(env,  fun))
   fun = new_DL_Func("void",  "doc",     (m_uint)machine_doc);
   dl_func_add_arg(fun,       "string",  "context");
   CHECK_OB(import_sfun(env,  fun))
   fun = new_DL_Func("void",  "doc_update",     (m_uint)machine_doc_update);
   CHECK_OB(import_sfun(env,  fun))
   fun = new_DL_Func("void",  "adept",     (m_uint)machine_adept);
   dl_func_add_arg(fun,       "string",  "context");
   CHECK_OB(import_sfun(env,  fun))
 //  fun = new_DL_Func("string",  "check",     (m_uint)machine_check);
   fun = new_DL_Func("int",  "check",     (m_uint)machine_check);
   dl_func_add_arg(fun,       "string",  "prefix");
   dl_func_add_arg(fun,       "string",  "code");
   CHECK_OB(import_sfun(env,  fun))
   fun = new_DL_Func("void",  "compile",     (m_uint)machine_compile);
   dl_func_add_arg(fun,       "string",  "prefix");
   dl_func_add_arg(fun,       "string",  "filename");
   CHECK_OB(import_sfun(env,  fun))
   CHECK_BB(import_class_end(env))
   return 1;
 }
js_filter()
static int js_filter (const struct dirent * dir) static
Definition at line 77 of file machine.c.
Referenced by SFUN().
 {
   return strstr(dir->d_name, ".js") ? 1 : 0;
 }
randstring()
static m_str randstring (VM * vm, int length) static
Definition at line 128 of file machine.c.
References VM::bbq, malloc(), and BBQ_::sp.
Referenced by SFUN().
 {
   char *string = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_";
   size_t stringLen = 26 * 2 + 10 + 2;
   char *randomString;
   randomString = malloc(sizeof(char) * (length + 1));
   if (!randomString) {
     return (char*)0;
   }
   unsigned int key = 0;
   for (int n = 0; n < length; n++) {
     key = sp_rand(vm->bbq->sp) % stringLen;
     randomString[n] = string[key];
   }
   randomString[length] = '\0';
   return randomString;
 }
SFUN() [1/7]
static SFUN (machine_add) static
Definition at line 37 of file machine.c.
References compile(), Type_::obj, release(), RETURN, and STRING.
 {
   M_Object obj = *(M_Object*)(shred->mem + SZ_INT);
   if(!obj)
     return;
   m_str str = STRING(obj);
   release(obj, shred);
   if(!str)
     return;
   RETURN->d.v_uint = compile(shred->vm_ref, str);
 }
SFUN() [2/7]
static SFUN (machine_doc) static
Definition at line 49 of file machine.c.
References free(), free_Ast(), mkdoc_context(), Type_::obj, parse(), release(), STRING, and type_engine_check_prog().
 {
 //  prepare()
   Ast ast = NULL;
   M_Object obj = *(M_Object*)(shred->mem + SZ_INT);
   char* str = STRING(obj);
   m_bool global = strcmp(str, "global_context") ? 1 : 0;
   if(global) {
     str = realpath(str, NULL);
     if(!str)
       return;
     ast = parse(str);
     if(!ast)
       return;
     if(type_engine_check_prog(shred->vm_ref->env, ast, str) < 0)
       return;
   }
   mkdoc_context(shred->vm_ref->env, str);
   if(ast)
     free_Ast(ast);
   release(obj, shred);
   if(global)
     free(str);
 //  clean()
 }
SFUN() [3/7]
static SFUN (machine_doc_update) static
Definition at line 82 of file machine.c.
References free(), GWION_DOC_DIR, js_filter(), and strcat().
 {
   FILE* f, * all;
   char c[strlen(GWION_DOC_DIR) + 15];
   memset(c, 0, strlen(GWION_DOC_DIR) + 15);
   strncpy(c, GWION_DOC_DIR, strlen(GWION_DOC_DIR));
   strncat(c, "/search/all.js", 14);
   all = fopen(c, "w");
   if(!all)
     return;
   struct dirent **namelist;
   char* line = NULL;
   int n;
   ssize_t read;
   size_t len = 0;
   memset(c, 0, strlen(c));
   strncpy(c, GWION_DOC_DIR, strlen(GWION_DOC_DIR));
   strncat(c, "/dat/", 14);
   n = scandir(c, &namelist, js_filter, alphasort);
   fprintf(all, "var searchData = \n[\n");
   if (n > 0) {
     while (n--) {
       char name[strlen(c) + strlen(namelist[n]->d_name) + 1];
       memset(name, 0, strlen(c) + strlen(namelist[n]->d_name) + 1);
       strcat(name, c);
       strcat(name, namelist[n]->d_name);
       f = fopen(name, "r");
       printf("\t'%s', \n", name);
       while((read = getline(&line, &len, f)) != -1)
         fprintf(all, "%s\n", line);
       free(namelist[n]);
       fclose(f);
     }
   }
   free(namelist);
   free(line);
   fprintf(all, "];");
   fclose(all);
 }
SFUN() [4/7]
static SFUN (machine_adept) static
Definition at line 122 of file machine.c.
References mkadt_context(), and prepare.
 {
   prepare()
   mkadt_context(shred->vm_ref->env, str);
 }
SFUN() [5/7]
SFUN (machine_check)
Definition at line 152 of file machine.c.
References free(), free_Ast(), parse(), randstring(), release(), RETURN, STRING, and type_engine_check_prog().
 {
   char c[104];
   m_str prefix, filename;
   M_Object prefix_obj = *(M_Object*)(shred->mem + SZ_INT);
   M_Object code_obj = *(M_Object*)(shred->mem + SZ_INT * 2);
   if(!prefix_obj)
     prefix = ".";
   else {
     prefix = STRING(prefix_obj);
     release(prefix_obj, shred);
   }
   if(!code_obj) {
     RETURN->d.v_uint = 0;
     return;
   }
   filename = randstring(shred->vm_ref, 12);
   sprintf(c, "%s/%s", prefix, filename);
   FILE* file = fopen(c, "w");
   fprintf(file, "%s\n", STRING(code_obj));
   release(code_obj, shred);
   fclose(file);
   free(filename);
   Ast ast = parse(c);
   if(!ast) {
     RETURN->d.v_uint = 0;
     return;
   }
   m_str s = strdup(c);
   if(type_engine_check_prog(shred->vm_ref->env, ast, s) < 0) {
     RETURN->d.v_uint = 0;
     return;
   }
   free(s);
   free_Ast(ast); // it could be in 'type_engine_check_prog'
 //  RETURN->d.v_uint = (m_uint)new_String(c);
   RETURN->d.v_uint = 1;
 }
SFUN() [6/7]
static SFUN (machine_compile) static
Definition at line 191 of file machine.c.
References compile(), free(), randstring(), release(), RETURN, and STRING.
 {
   char c[104];
   m_str prefix, filename;
   M_Object prefix_obj = *(M_Object*)(shred->mem + SZ_INT);
   M_Object code_obj = *(M_Object*)(shred->mem + SZ_INT * 2);
   if(!prefix_obj)
     prefix = ".";
   else {
     prefix = STRING(prefix_obj);
     release(prefix_obj, shred);
   }
   if(!code_obj) {
     RETURN->d.v_uint = 0;
     return;
   }
   filename = randstring(shred->vm_ref, 12);
   sprintf(c, "%s/%s.gw", prefix, filename);
   FILE* file = fopen(c, "w");
   fprintf(file, "%s\n", STRING(code_obj));
   release(code_obj, shred);
   fclose(file);
   free(filename);
   compile(shred->vm_ref, c);
 }
SFUN() [7/7]
static SFUN (machine_shreds) static
Definition at line 218 of file machine.c.
References M_Object_::array, M_Object_::d, i_vector_set(), new_M_Array(), RETURN, VM::shred, vector_at(), vector_size(), vm, and VM_Shred_::xid.
 {
   int i;
   VM* vm = shred->vm_ref;
   VM_Shred sh;
   M_Object obj = new_M_Array(SZ_INT, vector_size(vm->shred), 1);
   for(i = 0; i < vector_size(vm->shred); i++) {
     sh = (VM_Shred)vector_at(vm->shred, i);
     i_vector_set(obj->d.array, i, sh->xid);
   }
   RETURN->d.v_object = obj;
 }
Variable Documentation
t_machine
struct Type_ t_machine = { "Machine", 0, NULL, te_machine}
Definition at line 35 of file machine.c.