object_8c/ – Gwion
Gwion
A strongly timed musical programming language
object_8c/
object.c File Reference
#include "defs.h"
#include "err_msg.h"
#include "import.h"
#include "instr.h"
#include "lang.h"
#include "type.h"
#include "vm.h"
#include "object.h"
Data Structures
struct Vararg
Functions
void NullException (VM_Shred shred)
M_Object new_M_Object ()
M_Object new_String (m_str str)
m_bool initialize_object (M_Object object, Type type)
void release (M_Object obj, VM_Shred shred)
void object_dtor (M_Object o, VM_Shred shred)
INSTR (Assign_Object)
static INSTR (eq_Object)
static INSTR (neq_Object)
INSTR (Vararg_start)
INSTR (Vararg_end)
INSTR (Vararg_int)
INSTR (Vararg_float)
INSTR (Vararg_complex)
INSTR (Vararg_object)
INSTR (Vararg_Vec3)
INSTR (Vararg_Vec4)
m_bool import_object (Env env)
Variables
struct Type_ t_null = { "@null", SZ_INT, NULL, te_null}
struct Type_ t_object = { "Object", SZ_INT, NULL, te_object }
struct Type_ t_vararg = { "@Vararg", SZ_INT, &t_object, te_vararg}
struct Type_ t_varobj = { "VarObject", SZ_INT, &t_object, te_vararg}
Function Documentation
import_object()
m_bool import_object (Env env)
Definition at line 243 of file object.c.
References add_binary_op(), add_global_type(), add_global_value(), Assign_Object(), CHECK_BB, CHECK_OB, Env_::class_def, Type_::doc, Env_::global_nspc, import_class_begin(), import_class_end(), import_mvar(), object_dtor(), op_at_chuck, op_eq, op_neq, and t_int.
Referenced by type_engine_init().
 {
   CHECK_BB(add_global_type(env, &t_object))
   CHECK_OB(import_class_begin(env, &t_object, env->global_nspc, NULL, object_dtor))
   env->class_def->doc = "the base class";
   CHECK_BB(add_binary_op(env, op_at_chuck, &t_null, &t_object, &t_object, Assign_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_at_chuck, &t_object, &t_object, &t_object, Assign_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_eq,  &t_object, &t_object, &t_int,  eq_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_neq, &t_object, &t_object, &t_int, neq_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_eq,  &t_null,   &t_object, &t_int,  eq_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_neq, &t_null,   &t_object, &t_int, neq_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_eq,  &t_object, &t_null, &t_int,  eq_Object, 1, 0))
   CHECK_BB(add_binary_op(env, op_neq, &t_object, &t_null, &t_int, neq_Object, 1, 0))
   add_global_value(env, "NULL", &t_object, 1, 0);
   CHECK_BB(import_class_end(env))
   CHECK_BB(add_global_type(env, &t_vararg))
   CHECK_BB(add_global_type(env, &t_varobj))
   CHECK_OB(import_class_begin(env, &t_vararg, env->global_nspc, NULL, NULL))
   import_mvar(env, "int", "start", 1, 0, "start vararg loop");
   import_mvar(env, "int", "end", 1, 0, "end vararg loop");
   import_mvar(env, "int", "i", 1, 0, "vararg int");
   import_mvar(env, "float", "f", 1, 0, "vararg float");
   import_mvar(env, "time", "t", 1, 0, "vararg time");
   import_mvar(env, "dur", "d", 1, 0, "vararg dur");
   import_mvar(env, "complex", "c", 1, 0, "vararg complex");
   import_mvar(env, "polar", "p", 1, 0, "vararg polar");
   import_mvar(env, "Vec3", "v3", 1, 0, "vararg Vec3");
   import_mvar(env, "Vec4", "v4", 1, 0, "vararg Vec4");
   import_mvar(env, "VarObject", "o", 1, 0, "vararg object");
   CHECK_BB(import_class_end(env))
   return 1;
 }
initialize_object()
m_bool initialize_object (M_Object object, Type type)
Definition at line 44 of file object.c.
References M_Object_::d, M_Object_::data, err_msg(), Type_::info, Type_::name, Type_::obj_size, NameSpace_::obj_v_table, Type_::size, M_Object_::size, and TYPE_.
Referenced by import_fileio(), instantiate_object(), new_M_Array(), new_M_UGen(), new_Shred(), and new_String().
 {
   if (!type->info) {
     err_msg(TYPE_, 0, "internal error: no type->info for type '%s'", type->name);
     return -1;
   }
   object->vtable = type->info->obj_v_table;
   object->type_ref = type;
   object->size = type->obj_size;
   if (object->size) {
     object->d.data = calloc(object->size, sizeof(unsigned char));
     if (!object->d.data)
       goto out_of_memory;
     memset(object->d.data, 0, object->size);
   } else
     object->d.data = NULL;
   return 1;
 out_of_memory:
   err_msg(TYPE_, 0, "OutOfMemory: while instantiating object '%s'\n", type->name);
   return -1;
 }
INSTR() [1/11]
INSTR (Assign_Object)
Definition at line 111 of file object.c.
References POP_REG, PUSH_REG, and release().
 {
 #ifdef DEBUG_INSTR
   debug_msg("instr", "assign object %p %p", instr->m_val, *(m_uint*)(shred->reg - SZ_INT * 2), **(m_uint**)(shred->reg - SZ_INT));
 #endif
   POP_REG(shred, SZ_INT * 2);
   M_Object done = **(M_Object**)(shred->reg + SZ_INT);
   if(done)
     release(done, shred);
   (**(m_uint**)(shred->reg + SZ_INT) = *(m_uint*)shred->reg);
   PUSH_REG(shred, SZ_INT);
 }
INSTR() [2/11]
static INSTR (eq_Object) static
Definition at line 124 of file object.c.
References POP_REG, and PUSH_REG.
 {
 #ifdef DEBUG_INSTR
   debug_msg("instr", "eq Object");
 #endif
   POP_REG(shred, SZ_INT * 2);
   m_uint* lhs = *(m_uint**)shred->reg;
   m_uint* rhs = *(m_uint**)(shred->reg + SZ_INT);
   *(m_uint*)shred->reg = (lhs == rhs);
   PUSH_REG(shred, SZ_INT);
 }
INSTR() [3/11]
static INSTR (neq_Object) static
Definition at line 136 of file object.c.
References Vararg::d, Vararg::i, Vararg::k, Vararg::o, POP_REG, PUSH_REG, and Vararg::s.
 {
 #ifdef DEBUG_INSTR
   debug_msg("instr", "neq Object");
 #endif
   POP_REG(shred, SZ_INT * 2);
   m_uint* lhs = *(m_uint**)shred->reg;
   m_uint* rhs = *(m_uint**)(shred->reg + SZ_INT);
   *(m_uint*)shred->reg = (lhs != rhs);
   PUSH_REG(shred, SZ_INT);
 }
INSTR() [4/11]
INSTR (Vararg_start)
Definition at line 154 of file object.c.
References Vararg::d, and PUSH_REG.
 {
 #ifdef DEBUG_INSTR
   debug_msg("instr", "vararg start %i", instr->m_val);
 #endif
   struct Vararg* arg = *(struct Vararg**)(shred->mem + instr->m_val);
   if (!arg->d)
     shred->next_pc = instr->m_val2 + 1;
   PUSH_REG(shred, SZ_INT);
   *(m_uint*)(shred->reg - SZ_INT) = 0;
 }
INSTR() [5/11]
INSTR (Vararg_end)
Definition at line 166 of file object.c.
References Vararg::d, free(), Vararg::i, Vararg::k, Kindof_Complex, Kindof_Float, Kindof_Int, Kindof_Ptr, Kindof_Vec3, Kindof_Vec4, Kindof_Void, Vararg::o, PUSH_REG, and Vararg::s.
 {
   struct Vararg* arg = *(struct Vararg**)(shred->mem + instr->m_val);
   switch (arg->k[arg->i]) {
   case Kindof_Int:
     arg->o += SZ_INT;
     break;
   case Kindof_Float:
     arg->o += SZ_FLOAT;
     break;
   case Kindof_Complex:
     arg->o += SZ_COMPLEX;
     break;
   case Kindof_Vec3:
     arg->o += SZ_VEC3;
     break;
   case Kindof_Vec4:
     arg->o += SZ_VEC4;
     break;
   // can you reach this ?
   case Kindof_Void:
   case Kindof_Ptr:
     break;
   }
   PUSH_REG(shred, SZ_INT);
   arg->i++;
   if (arg->i == arg->s) {
     free(arg->d);
     free(arg->k);
     free(arg);
   } else {
     *(m_uint*)(shred->reg - SZ_INT) = 0;
     shred->next_pc = instr->m_val2;
   }
 }
INSTR() [6/11]
INSTR (Vararg_int)
Definition at line 202 of file object.c.
References Vararg::d, Vararg::o, and PUSH_REG.
 {
   struct Vararg* arg = *(struct Vararg**)(shred->mem + instr->m_val);
   *(m_uint*)shred->reg = *(m_uint*)(arg->d + arg->o);
   PUSH_REG(shred, SZ_INT);
 }
INSTR() [7/11]
INSTR (Vararg_float)
Definition at line 208 of file object.c.
References Vararg::d, Vararg::o, and PUSH_REG.
 {
   struct Vararg* arg = *(struct Vararg**)(shred->mem + instr->m_val);
   *(m_float*)shred->reg = *(m_float*)(arg->d + arg->o);
   PUSH_REG(shred, SZ_FLOAT);
 }
INSTR() [8/11]
INSTR (Vararg_complex)
Definition at line 215 of file object.c.
References Vararg::d, Vararg::o, and PUSH_REG.
 {
   struct Vararg* arg = *(struct Vararg**)(shred->mem + instr->m_val);
   *(m_complex*)shred->reg = *(m_complex*)(arg->d + arg->o);
   PUSH_REG(shred, SZ_COMPLEX);
 }
INSTR() [9/11]
INSTR (Vararg_object)
Definition at line 222 of file object.c.
References Vararg::d, Vararg::o, and PUSH_REG.
 {
   struct Vararg* arg = *(struct Vararg**)(shred->mem + instr->m_val);
   *(M_Object*)shred->reg = *(M_Object*)(arg->d + arg->o);
   PUSH_REG(shred, SZ_INT);
 }
INSTR() [10/11]
INSTR (Vararg_Vec3)
Definition at line 229 of file object.c.
References Vararg::d, Vararg::o, and PUSH_REG.
 {
   struct Vararg* arg = *(struct Vararg**)(shred->mem + instr->m_val);
   *(VEC3_T*)shred->reg = *(VEC3_T*)(arg->d + arg->o);
   PUSH_REG(shred, SZ_VEC3);
 }
INSTR() [11/11]
INSTR (Vararg_Vec4)
Definition at line 236 of file object.c.
References Vararg::d, Vararg::o, and PUSH_REG.
 {
   struct Vararg* arg = *(struct Vararg**)(shred->mem + instr->m_val);
   *(VEC4_T*)shred->reg = *(VEC4_T*)(arg->d + arg->o);
   PUSH_REG(shred, SZ_VEC4);
 }
new_M_Object()
M_Object new_M_Object ()
Definition at line 24 of file object.c.
References M_Object_::d, M_Object_::data, M_Object_::ref, M_Object_::size, M_Object_::type_ref, M_Object_::ugen, and M_Object_::vtable.
Referenced by import_fileio(), instantiate_object(), new_M_Array(), new_M_UGen(), new_Shred(), and new_String().
 {
   M_Object a = calloc(1, sizeof(struct M_Object_));
   a->vtable = NULL;
   a->type_ref = NULL;
   a->size = 0;
   a->d.data = NULL;
   a->ugen = NULL;
   a->ref = 1;
   return a;
 }
new_String()
M_Object new_String (m_str str)
Definition at line 36 of file object.c.
References initialize_object(), insert_symbol(), new_M_Object(), S_name(), STRING, and t_string.
Referenced by INSTR(), MFUN(), and SFUN().
 {
   M_Object o = new_M_Object();
   initialize_object(o, &t_string);
   STRING(o) = S_name(insert_symbol(str));
   return o;
 }
NullException()
void NullException (VM_Shred shred)
Definition at line 16 of file object.c.
References err_msg(), INSTR_, VM_Shred_::is_done, VM_Shred_::is_running, VM_Shred_::name, VM_Shred_::pc, and VM_Shred_::xid.
 {
   err_msg(INSTR_, 0, "NullPointerException: shred[id=%lu:%s], PC=[%lu]\n",
           shred->xid, shred->name, shred->pc);
   shred->is_running = 0;
   shred->is_done = 1;
 }
object_dtor()
void object_dtor (M_Object o, VM_Shred shred)
Definition at line 105 of file object.c.
References M_Object_::d, M_Object_::data, and free().
Referenced by import_object().
 {
   free(o->d.data);
   free(o);
 }
release()
void release (M_Object obj, VM_Shred shred)
Definition at line 67 of file object.c.
References M_Object_::d, M_Object_::data, NameSpace_::dtor, EOC(), Instr_::execute, free_Vector(), Type_::has_destructor, Type_::info, VM_Code_::instr, isprim(), Value_::m_type, VM_Shred_::me, VM_Shred_::mem, Type_::name, VM_Code_::native_func, new_Instr(), new_Shred(), new_VM_Code(), new_VM_Shred(), Type_::obj, Value_::offset, Type_::parent, M_Object_::ref, release(), scope_get(), SIZEOF_MEM, M_Object_::type_ref, NameSpace_::value, vector_append(), vector_at(), vector_pop(), vector_size(), vm_add_shred(), and VM_Shred_::vm_ref.
Referenced by do_alloc_array(), DTOR(), free_NameSpace(), free_VM_Shred(), INSTR(), MFUN(), release(), SFUN(), and ugen_dtor().
 {
   if (!obj)
     return;
   if (!--obj->ref) {
     Type t = obj->type_ref;
     while (t) {
 #ifdef DEBUG_INSTR
       debug_msg("instr", "dtor loop %p %s", obj, t->name);
 #endif
       m_uint i;
       Vector v = scope_get(t->info->value);
       for(i = 0; i < vector_size(v); i++) {
         Value value = (Value)vector_at(v, i);
         if(isprim(value->m_type) < 0)
           release(*(M_Object*)(obj->d.data + value->offset), shred);
       }
       free_Vector(v);
       if (t->has_destructor) {
         if (t->info->dtor->native_func)
           ((f_dtor)t->info->dtor->native_func)(obj, shred);
         else {
           VM_Code code = new_VM_Code(t->info->dtor->instr, SZ_INT, 1, "[dtor]", "[in code dtor exec]");
           VM_Shred sh = new_VM_Shred(code);
           sh->me = new_Shred(shred->vm_ref, sh);
           memcpy(sh->mem, shred->mem, SIZEOF_MEM);
           vector_pop(code->instr);
           Instr eoc = new_Instr();
           eoc->execute = EOC;
           vector_append(code->instr, (vtype)eoc);
           vm_add_shred(shred->vm_ref, sh);
         }
       }
       t = t->parent;
     }
   }
 }
Variable Documentation
t_null
struct Type_ t_null = { "@null", SZ_INT, NULL, te_null}
Definition at line 11 of file object.c.
Referenced by check_Cast_Expression(), check_op(), check_Primary_Expression(), check_Return(), emit_Binary_Expression(), emit_Cast_Expression1(), find_func_match_actual(), import_fileio(), and import_string().
t_object
struct Type_ t_object = { "Object", SZ_INT, NULL, te_object }
Definition at line 12 of file object.c.
Referenced by check_Binary_Expression(), check_Cast_Expression(), check_Class_Def(), check_If(), check_op(), check_Unary(), DTOR(), emit_Binary_Expression(), emit_Cast_Expression1(), emit_Decl_Expression(), emit_Func_Call1(), emit_If(), emit_instantiate_object(), emit_Unary(), find_func_match_actual(), free_NameSpace(), import_fileio(), import_string(), INSTR(), isprim(), kindof(), and scan0_Class_Def().
t_vararg
struct Type_ t_vararg = { "@Vararg", SZ_INT, &t_object, te_vararg}
Definition at line 13 of file object.c.
Referenced by check_Func_Def(), emit_Dot_Member(), and emit_symbol().
t_varobj
struct Type_ t_varobj = { "VarObject", SZ_INT, &t_object, te_vararg}
Definition at line 14 of file object.c.
Referenced by check_op().