Gwion dev-docs: include/oo.h File Reference
oo.h File Reference
#include "defs.h"
#include "array.h"
Data Structures
struct VM_Object_
struct M_Object_
Enumerations
enum e_obj {
e_dll_obj, e_emit_obj, e_namespace_obj, e_env_obj,
e_context_obj, e_ugen_obj, e_type_obj, e_value_obj,
e_func_obj, e_array_obj
}
Functions
VM_Object new_VM_Object (e_obj type)
void add_ref (VM_Object a)
void rem_ref (VM_Object a, void *ptr)
M_Object new_M_UGen ()
M_Object new_M_Object ()
Enumeration Type Documentation
e_obj
enum e_obj
Enumerator
e_dll_obj
e_emit_obj
e_namespace_obj
e_env_obj
e_context_obj
e_ugen_obj
e_type_obj
e_value_obj
e_func_obj
e_array_obj
Definition at line 7 of file oo.h.
              {
   e_dll_obj, e_emit_obj, e_namespace_obj, e_env_obj, e_context_obj,
   e_ugen_obj, e_type_obj, e_value_obj, e_func_obj, e_array_obj
 } e_obj;
Function Documentation
add_ref()
void add_ref (VM_Object a)
Definition at line 22 of file oo.c.
References VM_Object_::ref_count.
Referenced by check_Func_Ptr(), emit_Func_Def(), import_class_begin(), load_context(), new_Env(), scan0_Class_Def(), scan0_Func_Ptr(), scan1_Decl_Expression(), scan1_Enum(), scan1_Stmt(), scan2_Decl_Expression(), scan2_Func_Def(), scan2_Func_Ptr(), and type_engine_check_prog().
 {
   a->ref_count++;
 }
new_M_Object()
M_Object new_M_Object ()
Definition at line 24 of file object.c.
References M_Object_::d, M_Object_::data, M_Object_::ref, M_Object_::size, M_Object_::type_ref, M_Object_::ugen, and M_Object_::vtable.
Referenced by import_fileio(), instantiate_object(), new_M_Array(), new_M_UGen(), new_Shred(), and new_String().
 {
   M_Object a = calloc(1, sizeof(struct M_Object_));
   a->vtable = NULL;
   a->type_ref = NULL;
   a->size = 0;
   a->d.data = NULL;
   a->ugen = NULL;
   a->ref = 1;
   return a;
 }
new_M_UGen()
M_Object new_M_UGen ()
Definition at line 158 of file ugen.c.
References initialize_object(), new_M_Object(), new_UGen(), and M_Object_::ugen.
Referenced by assign_ugen(), and type_engine_init().
 {
   M_Object o = new_M_Object();
   initialize_object(o, &t_ugen);
   o->ugen = new_UGen();
   return o;
 }
new_VM_Object()
VM_Object new_VM_Object (e_obj type)
Definition at line 12 of file oo.c.
References VM_Object_::lock, malloc(), VM_Object_::ref, VM_Object_::ref_count, and VM_Object_::type.
Referenced by add_global_type(), new_Context(), new_Emitter(), new_Env(), new_Func(), new_NameSpace(), new_Type(), new_Value(), scan2_Func_Def(), and type_copy().
 {
   VM_Object a = malloc(sizeof(struct VM_Object_));
   a->type = type;
   a->ref_count = 0;
   a->lock = 0;
   a->ref = NULL;
   return a;
 }
rem_ref()
void rem_ref (VM_Object a, void * ptr)
Definition at line 27 of file oo.c.
References e_context_obj, e_dll_obj, e_emit_obj, e_env_obj, e_func_obj, e_namespace_obj, e_type_obj, e_value_obj, free(), free_Context(), free_Emitter(), free_Env(), free_Func(), free_NameSpace(), free_Type(), free_Value(), VM_Object_::lock, our_locks_in_effects, VM_Object_::ref_count, and VM_Object_::type.
Referenced by check_Func_Def(), free_Context(), free_Emitter(), free_Env(), free_NameSpace(), free_Section(), free_Stmt_Func_Ptr(), free_Type(), free_Var_Decl(), free_VM(), INSTR(), scan2_Func_Def(), and type_engine_check_prog().
 {
   if((!--a->ref_count && !a->lock) || !our_locks_in_effects) {
     switch(a->type) {
     case e_dll_obj:
       goto error;
     case e_emit_obj:
       free_Emitter(ptr);
       break;
     case e_namespace_obj:
       free_NameSpace(ptr);
       break;
     case e_env_obj:
       free_Env(ptr);
       break;
     case e_type_obj:
       free_Type(ptr);
       break;
     case e_value_obj:
       free_Value(ptr);
       break;
     case e_context_obj:
       free_Context(ptr);
       break;
     case e_func_obj:
       free_Func(ptr);
       break;
     default:
       goto error;
     }
     free(a);
   }
   return;
 error:
   printf("error in rem_ref: unhandled object type: %i\n", a->type);
 }