oo_8c/ – Gwion
Gwion
A strongly timed musical programming language
oo_8c/
oo.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include "map.h"
#include "context.h"
#include "func.h"
#include "oo.h"
#include "emit.h"
Functions
VM_Object new_VM_Object (e_obj type)
void add_ref (VM_Object a)
void rem_ref (VM_Object a, void *ptr)
Variables
static m_bool our_locks_in_effects = 0
Function Documentation
add_ref()
void add_ref (VM_Object a)
Definition at line 22 of file oo.c.
References VM_Object_::ref_count.
Referenced by check_Func_Ptr(), emit_Func_Def(), import_class_begin(), load_context(), new_Env(), scan0_Class_Def(), scan0_Func_Ptr(), scan1_Decl_Expression(), scan1_Enum(), scan1_Stmt(), scan2_Decl_Expression(), scan2_Func_Def(), scan2_Func_Ptr(), and type_engine_check_prog().
 {
   a->ref_count++;
 }
new_VM_Object()
VM_Object new_VM_Object (e_obj type)
Definition at line 12 of file oo.c.
References VM_Object_::lock, malloc(), VM_Object_::ref, VM_Object_::ref_count, and VM_Object_::type.
Referenced by add_global_type(), new_Context(), new_Emitter(), new_Env(), new_Func(), new_NameSpace(), new_Type(), new_Value(), scan2_Func_Def(), and type_copy().
 {
   VM_Object a = malloc(sizeof(struct VM_Object_));
   a->type = type;
   a->ref_count = 0;
   a->lock = 0;
   a->ref = NULL;
   return a;
 }
rem_ref()
void rem_ref (VM_Object a, void * ptr)
Definition at line 27 of file oo.c.
References e_context_obj, e_dll_obj, e_emit_obj, e_env_obj, e_func_obj, e_namespace_obj, e_type_obj, e_value_obj, free(), free_Context(), free_Emitter(), free_Env(), free_Func(), free_NameSpace(), free_Type(), free_Value(), VM_Object_::lock, our_locks_in_effects, VM_Object_::ref_count, and VM_Object_::type.
Referenced by check_Func_Def(), free_Context(), free_Emitter(), free_Env(), free_NameSpace(), free_Section(), free_Stmt_Func_Ptr(), free_Type(), free_Var_Decl(), free_VM(), INSTR(), scan2_Func_Def(), and type_engine_check_prog().
 {
   if((!--a->ref_count && !a->lock) || !our_locks_in_effects) {
     switch(a->type) {
     case e_dll_obj:
       goto error;
     case e_emit_obj:
       free_Emitter(ptr);
       break;
     case e_namespace_obj:
       free_NameSpace(ptr);
       break;
     case e_env_obj:
       free_Env(ptr);
       break;
     case e_type_obj:
       free_Type(ptr);
       break;
     case e_value_obj:
       free_Value(ptr);
       break;
     case e_context_obj:
       free_Context(ptr);
       break;
     case e_func_obj:
       free_Func(ptr);
       break;
     default:
       goto error;
     }
     free(a);
   }
   return;
 error:
   printf("error in rem_ref: unhandled object type: %i\n", a->type);
 }
Variable Documentation
our_locks_in_effects
m_bool our_locks_in_effects = 0 static
Definition at line 10 of file oo.c.
Referenced by rem_ref().