Gwion dev-docs: include/operator.h File Reference
--- layout: homepage title: operator_8h/ image: feature: abstract-1.jpg ---
operator.h File Reference
#include "vm.h"
Typedefs
typedef void(* f_instr) (VM *vm, VM_Shred shred, Instr instr)
Functions
m_str op2str (Operator op)
m_bool add_binary_op (Env env, Operator op, Type lhs, Type rhs, Type ret, f_instr f, m_bool global, m_bool is_new)
Type get_return_type (Env env, Operator op, Type rhs, Type lhs)
m_int name2op (m_str)
m_bool operator_set_func (Env env, Func f, Type lhs, Type rhs)
Map new_Operator_Map ()
void free_Operator_Map ()
Typedef Documentation
f_instr
typedef void(* f_instr) (VM *vm, VM_Shred shred, Instr instr)
Definition at line 3 of file operator.h.
Function Documentation
add_binary_op()
m_bool add_binary_op (Env env, Operator op, Type lhs, Type rhs, Type ret, f_instr f, m_bool global, m_bool is_new)
Definition at line 168 of file operator.c.
References Env_::curr, M_Operator::doc, err_msg(), M_Operator::func, Env_::global_nspc, M_Operator::instr, M_Operator::is_new, M_Operator::lhs, malloc(), map_get(), NameSpace_::name, Type_::name, op2str(), NameSpace_::operator, operator_find(), NameSpace_::parent, M_Operator::ret, M_Operator::rhs, TYPE_, M_Operator::type_func, and vector_append().
Referenced by import_analys(), import_complex(), import_event(), import_fileio(), import_float(), import_int(), import_object(), import_string(), import_ugen(), import_vec3(), import_vec4(), and scan2_Func_Def().
 {
 // is_new unused for now
 #ifdef DEBUG_OPERATOR
   debug_msg(" op  ", "import operator '%s' for type '%s' and '%s', in  '%s'",
             op2str(op), lhs ? lhs->name : NULL, rhs ? rhs->name : NULL, env->curr->name);
 #endif
   NameSpace nspc = env->curr;
   Vector v;
   M_Operator* mo;
   last  = NULL;
   if(global && nspc->parent)
     /*      nspc = nspc->parent;*/
     nspc = env->global_nspc;
   v = (Vector)map_get(nspc->operator, (vtype)op);
   if(!v) {
     err_msg(TYPE_, 0, "failed to import operator '%s', for type '%s' and '%s'. reason: no such operator",
             op2str(op), lhs ? lhs->name : NULL, rhs ? rhs->name : NULL);
     return -1;
   }
   if((mo = operator_find(v, lhs, rhs))) {
     err_msg(TYPE_, 0, "operator '%s', for type '%s' and '%s' already imported",
             op2str(op), lhs ? lhs->name : NULL, rhs ? rhs->name : NULL);
     return -1;
   }
   mo = malloc(sizeof(M_Operator));
   mo->lhs       = lhs;
   mo->rhs       = rhs;
   mo->ret       = ret;
   mo->instr     = f;
   mo->func      = NULL;
   mo->type_func = NULL;
   mo->doc       = NULL;
   mo->is_new = is_new;
   vector_append(v, (vtype)mo);
   last = mo;
   return 1;
 }
free_Operator_Map()
void free_Operator_Map ()
get_return_type()
Type get_return_type (Env env, Operator op, Type rhs, Type lhs)
Definition at line 211 of file operator.c.
References get_return_type(), Env_::global_nspc, map_get(), Type_::name, op2str(), NameSpace_::operator, operator_find(), NameSpace_::parent, Type_::parent, and M_Operator::ret.
Referenced by check_op(), and get_return_type().
 {
 #ifdef DEBUG_OPERATOR
   debug_msg(" op", "get return type for operator '%s', for type '%s' and '%s'",
             op2str(op), lhs ? lhs->name : NULL, rhs ? rhs->name : NULL);
 #endif
   Type t, l = lhs, r = lhs;
 /*  NameSpace nspc = env->curr; */
   NameSpace nspc = env->global_nspc;
   M_Operator* mo;
   while(nspc) {
     Vector v = (Vector)map_get(nspc->operator, (vtype)op);
     if((mo = operator_find(v, lhs, rhs)))
       return mo->ret;
     l = l ? l->parent : NULL;
     while(l) {
       if((t = get_return_type(env, op, l, rhs)))
         return t;
       r = rhs;
       while(r) {
         if((t = get_return_type(env, op, l, r)))
           return t;
         r = r->parent;
       }
       l = l->parent;
     }
     nspc = nspc->parent;
   }
   nspc = env->global_nspc;
   while(nspc) {
     Vector v = (Vector)map_get(nspc->operator, (vtype)op);
     if((mo = operator_find(v, lhs, rhs)))
       return mo->ret;
     r = rhs->parent;
     while(r) {
       if((t = get_return_type(env, op, lhs, r)))
         return t;
       l = lhs;
       while(l) {
         if((t = get_return_type(env, op, l, r)))
           return t;
         l = l->parent;
       }
       r = r->parent;
     }
     nspc = nspc->parent;
   }
   return NULL;
 }
name2op()
m_int name2op (m_str)
Definition at line 108 of file operator.c.
References op_name, op_str, and operators.
Referenced by operator_set_func(), scan1_Func_Def(), and scan2_Func_Def().
 {
   m_uint i = 0;
 //  for(i = 0; i < (sizeof(operators) / sizeof(Operator)) - 1; i++)
   while(op_name[i] && op_str[i]) {
     if(!strcmp(op_name[i], name)) {
       return operators[i];
     }
     if(!op_name[i + 1]) {
       return -1;
     }
     i++;
   }
   return -1;
 }
new_Operator_Map()
Map new_Operator_Map ()
Definition at line 129 of file operator.c.
References map_set(), new_Map(), new_Vector(), and operators.
Referenced by new_NameSpace().
 {
   m_uint i;
   Map map = new_Map();
   for(i = 0; i < (sizeof(operators) / sizeof(Operator)); i++)
     map_set(map, (vtype)operators[i], (vtype)new_Vector());
   return map;
 }
op2str()
m_str op2str (Operator op)
Definition at line 124 of file operator.c.
References op_str.
Referenced by add_binary_op(), check_Binary_Expression(), check_op(), check_Postfix_Expression(), check_Unary(), emit_Postfix_Expression(), emit_Unary(), get_instr(), get_return_type(), operator_doc(), scan1_Postfix_Expression(), and scan2_Postfix_Expression().
 {
   return op_str[op];
 }
operator_set_func()
m_bool operator_set_func (Env env, Func f, Type lhs, Type rhs)
Definition at line 278 of file operator.c.
References Env_::curr, Func_::def, M_Operator::func, map_get(), Func_Def_::name, name2op(), NameSpace_::operator, operator_find(), NameSpace_::parent, and S_name().
Referenced by emit_Func_Def().
 {
 #ifdef DEBUG_OPERATOR
   debug_msg(" op", 0, "set func'");
 #endif
   NameSpace nspc = env->curr;
   while(nspc) {
     M_Operator* mo;
     Vector v = (Vector)map_get(nspc->operator, (vtype)name2op(S_name(f->def->name)));
     if((mo = operator_find(v, lhs, rhs))) {
       mo->func = f;
       return 1;
     }
     nspc = nspc->parent;
   }
   return -1;
 }