parser_8c/ – Gwion
Gwion
A strongly timed musical programming language
parser_8c/
parser.c File Reference
#include "absyn.h"
#include <stddef.h>
Data Structures
union YYSTYPE
union yyalloc
Macros
#define YYBISON 1
#define YYBISON_VERSION "3.0.4"
#define YYSKELETON_NAME "yacc.c"
#define YYPURE 2
#define YYPUSH 0
#define YYPULL 1
#define yyparse minimal_parse
#define yylex minimal_lex
#define yyerror minimal_error
#define yydebug minimal_debug
#define yynerrs minimal_nerrs
#define YYERROR_VERBOSE
#define scanner arg->scanner
#define YY_NULLPTR 0
#define YYERROR_VERBOSE 1
#define YY_MINIMAL_EVAL_PARSER_H_INCLUDED
#define YYDEBUG 0
#define YYTOKENTYPE
#define SEMICOLON 258
#define CHUCK 259
#define COMMA 260
#define ASSIGN 261
#define DIVIDE 262
#define TIMES 263
#define PERCENT 264
#define L_HACK 265
#define R_HACK 266
#define LPAREN 267
#define RPAREN 268
#define LBRACK 269
#define RBRACK 270
#define LBRACE 271
#define RBRACE 272
#define PLUSCHUCK 273
#define MINUSCHUCK 274
#define TIMESCHUCK 275
#define DIVIDECHUCK 276
#define MODULOCHUCK 277
#define ATCHUCK 278
#define UNCHUCK 279
#define TRIG 280
#define UNTRIG 281
#define PERCENTPAREN 282
#define SHARPPAREN 283
#define PROTECTED 284
#define ABSTRACT 285
#define ATSYM 286
#define FUNCTION 287
#define DOLLAR 288
#define TILDA 289
#define QUESTION 290
#define COLON 291
#define EXCLAMATION 292
#define IF 293
#define ELSE 294
#define WHILE 295
#define DO 296
#define UNTIL 297
#define LOOP 298
#define FOR 299
#define GOTO 300
#define SWITCH 301
#define CASE 302
#define ENUM 303
#define RETURN 304
#define BREAK 305
#define CONTINUE 306
#define PLUSPLUS 307
#define MINUSMINUS 308
#define NEW 309
#define SPORK 310
#define SIZEOF 311
#define TYPEOF 312
#define CLASS 313
#define INTERFACE 314
#define STATIC 315
#define PRIVATE 316
#define PUBLIC 317
#define EXTENDS 318
#define IMPLEMENTS 319
#define DOT 320
#define COLONCOLON 321
#define AND 322
#define EQ 323
#define GE 324
#define GT 325
#define LE 326
#define LT 327
#define MINUS 328
#define PLUS 329
#define NEQ 330
#define SHIFT_LEFT 331
#define SHIFT_RIGHT 332
#define S_AND 333
#define S_OR 334
#define S_XOR 335
#define OR 336
#define AST_DTOR 337
#define OPERATOR 338
#define FUNC_PTR 339
#define RSL 340
#define RSR 341
#define RSAND 342
#define RSOR 343
#define RSXOR 344
#define RAND 345
#define ROR 346
#define REQ 347
#define RNEQ 348
#define RGT 349
#define RGE 350
#define RLT 351
#define RLE 352
#define RINC 353
#define RDEC 354
#define RUNINC 355
#define RUNDEC 356
#define TEMPLATE 357
#define NOELSE 358
#define ARROW_LEFT 359
#define ARROW_RIGHT 360
#define LTB 361
#define GTB 362
#define VARARG 363
#define UNION 364
#define ATPAREN 365
#define NUM 366
#define FLOAT 367
#define ID 368
#define STRING_LIT 369
#define CHAR_LIT 370
#define DOC 371
#define YYSTYPE_IS_TRIVIAL 1
#define YYSTYPE_IS_DECLARED 1
#define YYSIZE_T size_t
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
#define YY_(Msgid) Msgid
#define YY_ATTRIBUTE(Spec) /* empty */
#define YY_ATTRIBUTE_PURE YY_ATTRIBUTE ((__pure__))
#define YY_ATTRIBUTE_UNUSED YY_ATTRIBUTE ((__unused__))
#define _Noreturn YY_ATTRIBUTE ((__noreturn__))
#define YYUSE(E) ((void) (E))
#define YY_INITIAL_VALUE(Value) Value
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
#define YYSTACK_ALLOC YYMALLOC
#define YYSTACK_FREE YYFREE
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#define YYMALLOC malloc
#define YYFREE free
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
#define YYSTACK_BYTES(N)
#define YYCOPY_NEEDED 1
#define YYSTACK_RELOCATE(Stack_alloc, Stack)
#define YYCOPY(Dst, Src, Count)
#define YYFINAL 150
#define YYLAST 1616
#define YYNTOKENS 117
#define YYNNTS 65
#define YYNRULES 224
#define YYNSTATES 416
#define YYUNDEFTOK 2
#define YYMAXUTOK 371
#define YYTRANSLATE(YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
#define YYPACT_NINF -229
#define yypact_value_is_default(Yystate) (!!((Yystate) == (-229)))
#define YYTABLE_NINF -134
#define yytable_value_is_error(Yytable_value) 0
#define yyerrok (yyerrstatus = 0)
#define yyclearin (yychar = YYEMPTY)
#define YYEMPTY (-2)
#define YYEOF 0
#define YYACCEPT goto yyacceptlab
#define YYABORT goto yyabortlab
#define YYERROR goto yyerrorlab
#define YYRECOVERING() (!!yyerrstatus)
#define YYBACKUP(Token, Value)
#define YYTERROR 1
#define YYERRCODE 256
#define YYDPRINTF(Args)
#define YY_SYMBOL_PRINT(Title, Type, Value, Location)
#define YY_STACK_PRINT(Bottom, Top)
#define YY_REDUCE_PRINT(Rule)
#define YYINITDEPTH 200
#define YYMAXDEPTH 10000
#define YYCASE_(N, S)
#define YYPOPSTACK(N) (yyvsp -= (N), yyssp -= (N))
#define YYSYNTAX_ERROR
Typedefs
typedef union YYSTYPE YYSTYPE
typedef unsigned char yytype_uint8
typedef signed char yytype_int8
typedef unsigned short int yytype_uint16
typedef short int yytype_int16
Enumerations
enum yytokentype {
SEMICOLON = 258, CHUCK = 259, COMMA = 260, ASSIGN = 261,
DIVIDE = 262, TIMES = 263, PERCENT = 264, L_HACK = 265,
R_HACK = 266, LPAREN = 267, RPAREN = 268, LBRACK = 269,
RBRACK = 270, LBRACE = 271, RBRACE = 272, PLUSCHUCK = 273,
MINUSCHUCK = 274, TIMESCHUCK = 275, DIVIDECHUCK = 276, MODULOCHUCK = 277,
ATCHUCK = 278, UNCHUCK = 279, TRIG = 280, UNTRIG = 281,
PERCENTPAREN = 282, SHARPPAREN = 283, PROTECTED = 284, ABSTRACT = 285,
ATSYM = 286, FUNCTION = 287, DOLLAR = 288, TILDA = 289,
QUESTION = 290, COLON = 291, EXCLAMATION = 292, IF = 293,
ELSE = 294, WHILE = 295, DO = 296, UNTIL = 297,
LOOP = 298, FOR = 299, GOTO = 300, SWITCH = 301,
CASE = 302, ENUM = 303, RETURN = 304, BREAK = 305,
CONTINUE = 306, PLUSPLUS = 307, MINUSMINUS = 308, NEW = 309,
SPORK = 310, SIZEOF = 311, TYPEOF = 312, CLASS = 313,
INTERFACE = 314, STATIC = 315, PRIVATE = 316, PUBLIC = 317,
EXTENDS = 318, IMPLEMENTS = 319, DOT = 320, COLONCOLON = 321,
AND = 322, EQ = 323, GE = 324, GT = 325,
LE = 326, LT = 327, MINUS = 328, PLUS = 329,
NEQ = 330, SHIFT_LEFT = 331, SHIFT_RIGHT = 332, S_AND = 333,
S_OR = 334, S_XOR = 335, OR = 336, AST_DTOR = 337,
OPERATOR = 338, FUNC_PTR = 339, RSL = 340, RSR = 341,
RSAND = 342, RSOR = 343, RSXOR = 344, RAND = 345,
ROR = 346, REQ = 347, RNEQ = 348, RGT = 349,
RGE = 350, RLT = 351, RLE = 352, RINC = 353,
RDEC = 354, RUNINC = 355, RUNDEC = 356, TEMPLATE = 357,
NOELSE = 358, ARROW_LEFT = 359, ARROW_RIGHT = 360, LTB = 361,
GTB = 362, VARARG = 363, UNION = 364, ATPAREN = 365,
NUM = 366, FLOAT = 367, ID = 368, STRING_LIT = 369,
CHAR_LIT = 370, DOC = 371, SEMICOLON = 258, CHUCK = 259,
COMMA = 260, ASSIGN = 261, DIVIDE = 262, TIMES = 263,
PERCENT = 264, L_HACK = 265, R_HACK = 266, LPAREN = 267,
RPAREN = 268, LBRACK = 269, RBRACK = 270, LBRACE = 271,
RBRACE = 272, PLUSCHUCK = 273, MINUSCHUCK = 274, TIMESCHUCK = 275,
DIVIDECHUCK = 276, MODULOCHUCK = 277, ATCHUCK = 278, UNCHUCK = 279,
TRIG = 280, UNTRIG = 281, PERCENTPAREN = 282, SHARPPAREN = 283,
PROTECTED = 284, ABSTRACT = 285, ATSYM = 286, FUNCTION = 287,
DOLLAR = 288, TILDA = 289, QUESTION = 290, COLON = 291,
EXCLAMATION = 292, IF = 293, ELSE = 294, WHILE = 295,
DO = 296, UNTIL = 297, LOOP = 298, FOR = 299,
GOTO = 300, SWITCH = 301, CASE = 302, ENUM = 303,
RETURN = 304, BREAK = 305, CONTINUE = 306, PLUSPLUS = 307,
MINUSMINUS = 308, NEW = 309, SPORK = 310, SIZEOF = 311,
TYPEOF = 312, CLASS = 313, INTERFACE = 314, STATIC = 315,
PRIVATE = 316, PUBLIC = 317, EXTENDS = 318, IMPLEMENTS = 319,
DOT = 320, COLONCOLON = 321, AND = 322, EQ = 323,
GE = 324, GT = 325, LE = 326, LT = 327,
MINUS = 328, PLUS = 329, NEQ = 330, SHIFT_LEFT = 331,
SHIFT_RIGHT = 332, S_AND = 333, S_OR = 334, S_XOR = 335,
OR = 336, AST_DTOR = 337, OPERATOR = 338, FUNC_PTR = 339,
RSL = 340, RSR = 341, RSAND = 342, RSOR = 343,
RSXOR = 344, RAND = 345, ROR = 346, REQ = 347,
RNEQ = 348, RGT = 349, RGE = 350, RLT = 351,
RLE = 352, RINC = 353, RDEC = 354, RUNINC = 355,
RUNDEC = 356, TEMPLATE = 357, NOELSE = 358, ARROW_LEFT = 359,
ARROW_RIGHT = 360, LTB = 361, GTB = 362, VARARG = 363,
UNION = 364, ATPAREN = 365, NUM = 366, FLOAT = 367,
ID = 368, STRING_LIT = 369, CHAR_LIT = 370, DOC = 371,
SEMICOLON = 258, CHUCK = 259, COMMA = 260, ASSIGN = 261,
DIVIDE = 262, TIMES = 263, PERCENT = 264, L_HACK = 265,
R_HACK = 266, LPAREN = 267, RPAREN = 268, LBRACK = 269,
RBRACK = 270, LBRACE = 271, RBRACE = 272, PLUSCHUCK = 273,
MINUSCHUCK = 274, TIMESCHUCK = 275, DIVIDECHUCK = 276, MODULOCHUCK = 277,
ATCHUCK = 278, UNCHUCK = 279, PERCENTPAREN = 280, POUNDPAREN = 281,
PROTECTED = 282, ABSTRACT = 283, ATSYM = 284, FUNCTION = 285,
DOLLAR = 286, TILDA = 287, QUESTION = 288, COLON = 289,
EXCLAMATION = 290, IF = 291, ELSE = 292, WHILE = 293,
DO = 294, UNTIL = 295, LOOP = 296, FOR = 297,
GOTO = 298, SWITCH = 299, CASE = 300, ENUM = 301,
RETURN = 302, BREAK = 303, CONTINUE = 304, PLUSPLUS = 305,
MINUSMINUS = 306, NEW = 307, SPORK = 308, SIZEOF = 309,
TYPEOF = 310, CLASS = 311, INTERFACE = 312, STATIC = 313,
PRIVATE = 314, PUBLIC = 315, EXTENDS = 316, IMPLEMENTS = 317,
DOT = 318, COLONCOLON = 319, AND = 320, EQ = 321,
GE = 322, GT = 323, LE = 324, LT = 325,
MINUS = 326, PLUS = 327, NEQ = 328, NOR = 329,
SHIFT_LEFT = 330, SHIFT_RIGHT = 331, S_AND = 332, S_OR = 333,
S_XOR = 334, OR = 335, NUM = 336, FLOAT = 337,
ID = 338, STRING_LIT = 339, CHAR_LIT = 340
}
Functions
char * strcat (char *dest, const char *src)
void minimal_error (void *data, const char *s)
int minimal_lex (void *, void *, void *)
static int get_pos (void *data)
static char * append_doc (void *data, m_str str)
static m_str get_doc (void *data)
int minimal_parse (MyArg *arg)
void * malloc (YYSIZE_T)
void free (void *)
static YYSIZE_T yystrlen (const char *yystr)
static char * yystpcpy (char *yydest, const char *yysrc)
static YYSIZE_T yytnamerr (char *yyres, const char *yystr)
static int yysyntax_error (YYSIZE_T *yymsg_alloc, char **yymsg, yytype_int16 *yyssp, int yytoken)
static void yydestruct (const char *yymsg, int yytype, YYSTYPE *yyvaluep, MyArg *arg)
int yyparse (MyArg *arg)
Variables
static const yytype_uint8 yytranslate []
static const char *const yytname []
static const yytype_int16 yypact []
static const yytype_uint8 yydefact []
static const yytype_int16 yypgoto []
static const yytype_int16 yydefgoto []
static const yytype_int16 yytable []
static const yytype_int16 yycheck []
static const yytype_uint8 yystos []
static const yytype_uint8 yyr1 []
static const yytype_uint8 yyr2 []
Macro Definition Documentation
_Noreturn
#define _Noreturn YY_ATTRIBUTE ((__noreturn__))
Definition at line 510 of file parser.c.
ABSTRACT
#define ABSTRACT 285
Definition at line 292 of file parser.c.
Referenced by if().
AND
#define AND 322
Definition at line 329 of file parser.c.
Referenced by if().
ARROW_LEFT
#define ARROW_LEFT 359
Definition at line 366 of file parser.c.
ARROW_RIGHT
#define ARROW_RIGHT 360
Definition at line 367 of file parser.c.
ASSIGN
#define ASSIGN 261
Definition at line 268 of file parser.c.
Referenced by if().
AST_DTOR
#define AST_DTOR 337
Definition at line 344 of file parser.c.
Referenced by if().
ATCHUCK
#define ATCHUCK 278
Definition at line 285 of file parser.c.
Referenced by if().
ATPAREN
#define ATPAREN 365
Definition at line 372 of file parser.c.
Referenced by if().
ATSYM
#define ATSYM 286
Definition at line 293 of file parser.c.
Referenced by if().
BREAK
#define BREAK 305
Definition at line 312 of file parser.c.
Referenced by if().
CASE
#define CASE 302
Definition at line 309 of file parser.c.
Referenced by if().
CHAR_LIT
#define CHAR_LIT 370
Definition at line 377 of file parser.c.
Referenced by if().
CHUCK
#define CHUCK 259
Definition at line 266 of file parser.c.
Referenced by if().
CLASS
#define CLASS 313
Definition at line 320 of file parser.c.
Referenced by if().
COLON
#define COLON 291
Definition at line 298 of file parser.c.
Referenced by if().
COLONCOLON
#define COLONCOLON 321
Definition at line 328 of file parser.c.
Referenced by if().
COMMA
#define COMMA 260
Definition at line 267 of file parser.c.
Referenced by if().
CONTINUE
#define CONTINUE 306
Definition at line 313 of file parser.c.
Referenced by if().
DIVIDE
#define DIVIDE 262
Definition at line 269 of file parser.c.
Referenced by if().
DIVIDECHUCK
#define DIVIDECHUCK 276
Definition at line 283 of file parser.c.
Referenced by if().
DO
#define DO 296
Definition at line 303 of file parser.c.
Referenced by if().
DOC
#define DOC 371
Definition at line 378 of file parser.c.
Referenced by if().
DOLLAR
#define DOLLAR 288
Definition at line 295 of file parser.c.
Referenced by if().
DOT
#define DOT 320
Definition at line 327 of file parser.c.
Referenced by if().
ELSE
#define ELSE 294
Definition at line 301 of file parser.c.
Referenced by if().
ENUM
#define ENUM 303
Definition at line 310 of file parser.c.
Referenced by if().
EQ
#define EQ 323
Definition at line 330 of file parser.c.
Referenced by if().
EXCLAMATION
#define EXCLAMATION 292
Definition at line 299 of file parser.c.
Referenced by if().
EXTENDS
#define EXTENDS 318
Definition at line 325 of file parser.c.
Referenced by if().
FLOAT
#define FLOAT 367
Definition at line 374 of file parser.c.
Referenced by if().
FOR
#define FOR 299
Definition at line 306 of file parser.c.
Referenced by if().
FUNC_PTR
#define FUNC_PTR 339
Definition at line 346 of file parser.c.
Referenced by if().
FUNCTION
#define FUNCTION 287
Definition at line 294 of file parser.c.
Referenced by if().
GE
#define GE 324
Definition at line 331 of file parser.c.
Referenced by if().
GOTO
#define GOTO 300
Definition at line 307 of file parser.c.
Referenced by if().
GT
#define GT 325
Definition at line 332 of file parser.c.
Referenced by if().
GTB
#define GTB 362
Definition at line 369 of file parser.c.
Referenced by if().
ID
#define ID 368
Definition at line 375 of file parser.c.
Referenced by if().
IF
#define IF 293
Definition at line 300 of file parser.c.
Referenced by if().
IMPLEMENTS
#define IMPLEMENTS 319
Definition at line 326 of file parser.c.
Referenced by if().
INTERFACE
#define INTERFACE 314
Definition at line 321 of file parser.c.
Referenced by if().
L_HACK
#define L_HACK 265
Definition at line 272 of file parser.c.
Referenced by if().
LBRACE
#define LBRACE 271
Definition at line 278 of file parser.c.
Referenced by if().
LBRACK
#define LBRACK 269
Definition at line 276 of file parser.c.
Referenced by if().
LE
#define LE 326
Definition at line 333 of file parser.c.
Referenced by if().
LOOP
#define LOOP 298
Definition at line 305 of file parser.c.
Referenced by if().
LPAREN
#define LPAREN 267
Definition at line 274 of file parser.c.
Referenced by if().
LT
#define LT 327
Definition at line 334 of file parser.c.
Referenced by if().
LTB
#define LTB 361
Definition at line 368 of file parser.c.
Referenced by if().
MINUS
#define MINUS 328
Definition at line 335 of file parser.c.
Referenced by if().
MINUSCHUCK
#define MINUSCHUCK 274
Definition at line 281 of file parser.c.
Referenced by if().
MINUSMINUS
#define MINUSMINUS 308
Definition at line 315 of file parser.c.
Referenced by if().
MODULOCHUCK
#define MODULOCHUCK 277
Definition at line 284 of file parser.c.
Referenced by if().
NEQ
#define NEQ 330
Definition at line 337 of file parser.c.
Referenced by if().
NEW
#define NEW 309
Definition at line 316 of file parser.c.
Referenced by if().
NOELSE
#define NOELSE 358
Definition at line 365 of file parser.c.
NUM
#define NUM 366
Definition at line 373 of file parser.c.
Referenced by if().
OPERATOR
#define OPERATOR 338
Definition at line 345 of file parser.c.
Referenced by if().
OR
#define OR 336
Definition at line 343 of file parser.c.
Referenced by if().
PERCENT
#define PERCENT 264
Definition at line 271 of file parser.c.
Referenced by if().
PERCENTPAREN
#define PERCENTPAREN 282
Definition at line 289 of file parser.c.
Referenced by if().
PLUS
#define PLUS 329
Definition at line 336 of file parser.c.
Referenced by if().
PLUSCHUCK
#define PLUSCHUCK 273
Definition at line 280 of file parser.c.
Referenced by if().
PLUSPLUS
#define PLUSPLUS 307
Definition at line 314 of file parser.c.
Referenced by if().
PRIVATE
#define PRIVATE 316
Definition at line 323 of file parser.c.
Referenced by if().
PROTECTED
#define PROTECTED 284
Definition at line 291 of file parser.c.
Referenced by if().
PUBLIC
#define PUBLIC 317
Definition at line 324 of file parser.c.
Referenced by if().
QUESTION
#define QUESTION 290
Definition at line 297 of file parser.c.
Referenced by if().
R_HACK
#define R_HACK 266
Definition at line 273 of file parser.c.
Referenced by if().
RAND
#define RAND 345
Definition at line 352 of file parser.c.
Referenced by if().
RBRACE
#define RBRACE 272
Definition at line 279 of file parser.c.
Referenced by if().
RBRACK
#define RBRACK 270
Definition at line 277 of file parser.c.
Referenced by if().
RDEC
#define RDEC 354
Definition at line 361 of file parser.c.
REQ
#define REQ 347
Definition at line 354 of file parser.c.
Referenced by if().
RETURN
#define RETURN 304
Definition at line 311 of file parser.c.
Referenced by if(), MFUN(), and SFUN().
RGE
#define RGE 350
Definition at line 357 of file parser.c.
Referenced by if().
RGT
#define RGT 349
Definition at line 356 of file parser.c.
Referenced by if().
RINC
#define RINC 353
Definition at line 360 of file parser.c.
RLE
#define RLE 352
Definition at line 359 of file parser.c.
Referenced by if().
RLT
#define RLT 351
Definition at line 358 of file parser.c.
Referenced by if().
RNEQ
#define RNEQ 348
Definition at line 355 of file parser.c.
Referenced by if().
ROR
#define ROR 346
Definition at line 353 of file parser.c.
Referenced by if().
RPAREN
#define RPAREN 268
Definition at line 275 of file parser.c.
Referenced by if().
RSAND
#define RSAND 342
Definition at line 349 of file parser.c.
Referenced by if().
RSL
#define RSL 340
Definition at line 347 of file parser.c.
Referenced by if().
RSOR
#define RSOR 343
Definition at line 350 of file parser.c.
Referenced by if().
RSR
#define RSR 341
Definition at line 348 of file parser.c.
Referenced by if().
RSXOR
#define RSXOR 344
Definition at line 351 of file parser.c.
Referenced by if().
RUNDEC
#define RUNDEC 356
Definition at line 363 of file parser.c.
RUNINC
#define RUNINC 355
Definition at line 362 of file parser.c.
S_AND
#define S_AND 333
Definition at line 340 of file parser.c.
Referenced by if().
S_OR
#define S_OR 334
Definition at line 341 of file parser.c.
Referenced by if().
S_XOR
#define S_XOR 335
Definition at line 342 of file parser.c.
Referenced by if().
scanner
#define scanner arg->scanner
Definition at line 75 of file parser.c.
Referenced by yyparse().
SEMICOLON
#define SEMICOLON 258
Definition at line 265 of file parser.c.
Referenced by if().
SHARPPAREN
#define SHARPPAREN 283
Definition at line 290 of file parser.c.
Referenced by if().
SHIFT_LEFT
#define SHIFT_LEFT 331
Definition at line 338 of file parser.c.
Referenced by if().
SHIFT_RIGHT
#define SHIFT_RIGHT 332
Definition at line 339 of file parser.c.
Referenced by if().
SIZEOF
#define SIZEOF 311
Definition at line 318 of file parser.c.
Referenced by if().
SPORK
#define SPORK 310
Definition at line 317 of file parser.c.
Referenced by if().
STATIC
#define STATIC 315
Definition at line 322 of file parser.c.
Referenced by if().
STRING_LIT
#define STRING_LIT 369
Definition at line 376 of file parser.c.
Referenced by if().
SWITCH
#define SWITCH 301
Definition at line 308 of file parser.c.
Referenced by if().
TEMPLATE
#define TEMPLATE 357
Definition at line 364 of file parser.c.
Referenced by if().
TILDA
#define TILDA 289
Definition at line 296 of file parser.c.
Referenced by if().
TIMES
#define TIMES 263
Definition at line 270 of file parser.c.
Referenced by if().
TIMESCHUCK
#define TIMESCHUCK 275
Definition at line 282 of file parser.c.
Referenced by if().
TRIG
#define TRIG 280
Definition at line 287 of file parser.c.
Referenced by if().
TYPEOF
#define TYPEOF 312
Definition at line 319 of file parser.c.
Referenced by if().
UNCHUCK
#define UNCHUCK 279
Definition at line 286 of file parser.c.
Referenced by if().
UNION
#define UNION 364
Definition at line 371 of file parser.c.
Referenced by if().
UNTIL
#define UNTIL 297
Definition at line 304 of file parser.c.
Referenced by if().
UNTRIG
#define UNTRIG 281
Definition at line 288 of file parser.c.
Referenced by if().
VARARG
#define VARARG 363
Definition at line 370 of file parser.c.
Referenced by if().
WHILE
#define WHILE 295
Definition at line 302 of file parser.c.
Referenced by if().
YY_
#define YY_ (Msgid) Msgid
Definition at line 483 of file parser.c.
Referenced by yyparse(), and yysyntax_error().
YY_ATTRIBUTE
#define YY_ATTRIBUTE (Spec) /* empty */
Definition at line 493 of file parser.c.
YY_ATTRIBUTE_PURE
#define YY_ATTRIBUTE_PURE YY_ATTRIBUTE ((__pure__))
Definition at line 498 of file parser.c.
YY_ATTRIBUTE_UNUSED
#define YY_ATTRIBUTE_UNUSED YY_ATTRIBUTE ((__unused__))
Definition at line 502 of file parser.c.
YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
Definition at line 533 of file parser.c.
Referenced by yydestruct(), and yyparse().
YY_IGNORE_MAYBE_UNINITIALIZED_END
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
Definition at line 534 of file parser.c.
Referenced by yydestruct(), and yyparse().
YY_INITIAL_VALUE
#define YY_INITIAL_VALUE (Value) Value
Definition at line 530 of file parser.c.
Referenced by yyparse().
YY_MINIMAL_EVAL_PARSER_H_INCLUDED
#define YY_MINIMAL_EVAL_PARSER_H_INCLUDED
Definition at line 134 of file parser.c.
YY_NULLPTR
#define YY_NULLPTR 0
Definition at line 119 of file parser.c.
Referenced by yysyntax_error().
YY_REDUCE_PRINT
#define YY_REDUCE_PRINT (Rule)
Definition at line 1558 of file parser.c.
Referenced by yyparse().
YY_STACK_PRINT
#define YY_STACK_PRINT (Bottom, Top)
Definition at line 1557 of file parser.c.
Referenced by yyparse().
YY_SYMBOL_PRINT
#define YY_SYMBOL_PRINT (Title, Type, Value, Location)
Definition at line 1556 of file parser.c.
Referenced by yydestruct(), and yyparse().
YYABORT
#define YYABORT goto yyabortlab
Definition at line 1402 of file parser.c.
Referenced by yyparse().
YYACCEPT
#define YYACCEPT goto yyacceptlab
Definition at line 1401 of file parser.c.
Referenced by yyparse().
YYBACKUP
#define YYBACKUP (Token, Value)
Value:
do                                                              \
  if (yychar == YYEMPTY)                                        \
    {                                                           \
      yychar = (Token);                                         \
      yylval = (Value);                                         \
      YYPOPSTACK (yylen);                                       \
      yystate = *yyssp;                                         \
      goto yybackup;                                            \
    }                                                           \
  else                                                          \
    {                                                           \
      yyerror (arg, YY_("syntax error: cannot back up")); \
      YYERROR;                                                  \
    }                                                           \
while (0)
Definition at line 1408 of file parser.c.
YYBISON
#define YYBISON 1
Definition at line 44 of file parser.c.
YYBISON_VERSION
#define YYBISON_VERSION "3.0.4"
Definition at line 47 of file parser.c.
YYCASE_
#define YYCASE_ (N, S)
Value:
case N:                               \
        yyformat = S;                       \
      break
Referenced by yysyntax_error().
yyclearin
#define yyclearin (yychar = YYEMPTY)
Definition at line 1397 of file parser.c.
YYCOPY
#define YYCOPY (Dst, Src, Count)
Value:
do                                        \
        {                                       \
          YYSIZE_T yyi;                         \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
Definition at line 657 of file parser.c.
YYCOPY_NEEDED
#define YYCOPY_NEEDED 1
Definition at line 629 of file parser.c.
yydebug
#define yydebug minimal_debug
Definition at line 66 of file parser.c.
YYDEBUG
#define YYDEBUG 0
Definition at line 137 of file parser.c.
YYDPRINTF
#define YYDPRINTF (Args)
Definition at line 1555 of file parser.c.
Referenced by yyparse().
YYEMPTY
#define YYEMPTY (-2)
Definition at line 1398 of file parser.c.
Referenced by yyparse(), and yysyntax_error().
YYEOF
#define YYEOF 0
Definition at line 1399 of file parser.c.
Referenced by yyparse().
YYERRCODE
#define YYERRCODE 256
Definition at line 1427 of file parser.c.
yyerrok
#define yyerrok (yyerrstatus = 0)
Definition at line 1396 of file parser.c.
yyerror
#define yyerror minimal_error
Definition at line 65 of file parser.c.
Referenced by yyparse().
YYERROR
#define YYERROR goto yyerrorlab
Definition at line 1403 of file parser.c.
YYERROR_VERBOSE [1/2]
#define YYERROR_VERBOSE
Definition at line 126 of file parser.c.
YYERROR_VERBOSE [2/2]
#define YYERROR_VERBOSE 1
Definition at line 126 of file parser.c.
YYFINAL
#define YYFINAL 150
Definition at line 670 of file parser.c.
Referenced by yyparse().
YYFREE
#define YYFREE free
Definition at line 600 of file parser.c.
YYINITDEPTH
#define YYINITDEPTH 200
Definition at line 1564 of file parser.c.
Referenced by yyparse().
YYLAST
#define YYLAST 1616
Definition at line 672 of file parser.c.
Referenced by yyparse(), and yysyntax_error().
yylex
#define yylex minimal_lex
Definition at line 64 of file parser.c.
Referenced by yyparse().
YYMALLOC
#define YYMALLOC malloc
Definition at line 594 of file parser.c.
YYMAXDEPTH
#define YYMAXDEPTH 10000
Definition at line 1575 of file parser.c.
Referenced by yyparse().
YYMAXUTOK
#define YYMAXUTOK 371
Definition at line 686 of file parser.c.
yynerrs
#define yynerrs minimal_nerrs
Definition at line 67 of file parser.c.
Referenced by yyparse().
YYNNTS
#define YYNNTS 65
Definition at line 677 of file parser.c.
YYNRULES
#define YYNRULES 224
Definition at line 679 of file parser.c.
YYNSTATES
#define YYNSTATES 416
Definition at line 681 of file parser.c.
YYNTOKENS
#define YYNTOKENS 117
Definition at line 675 of file parser.c.
Referenced by yyparse(), and yysyntax_error().
YYPACT_NINF
#define YYPACT_NINF -229
Definition at line 825 of file parser.c.
yypact_value_is_default
#define yypact_value_is_default (Yystate) (!!((Yystate) == (-229)))
Definition at line 827 of file parser.c.
Referenced by yyparse(), and yysyntax_error().
yyparse
#define yyparse minimal_parse
Definition at line 63 of file parser.c.
YYPOPSTACK
#define YYPOPSTACK (N) (yyvsp -= (N), yyssp -= (N))
Referenced by yyparse().
YYPULL
#define YYPULL 1
Definition at line 59 of file parser.c.
YYPURE
#define YYPURE 2
Definition at line 53 of file parser.c.
YYPUSH
#define YYPUSH 0
Definition at line 56 of file parser.c.
YYRECOVERING
#define YYRECOVERING () (!!yyerrstatus)
Definition at line 1406 of file parser.c.
YYSIZE_MAXIMUM
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
Definition at line 473 of file parser.c.
YYSIZE_T
#define YYSIZE_T size_t
Definition at line 467 of file parser.c.
Referenced by yyparse(), yystpcpy(), yystrlen(), yysyntax_error(), and yytnamerr().
YYSKELETON_NAME
#define YYSKELETON_NAME "yacc.c"
Definition at line 50 of file parser.c.
YYSTACK_ALLOC
#define YYSTACK_ALLOC YYMALLOC
Definition at line 580 of file parser.c.
Referenced by yyparse().
YYSTACK_ALLOC_MAXIMUM
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
Definition at line 583 of file parser.c.
Referenced by yysyntax_error().
YYSTACK_BYTES
#define YYSTACK_BYTES (N)
Value:
((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)
Definition at line 625 of file parser.c.
Referenced by yyparse().
YYSTACK_FREE
#define YYSTACK_FREE YYFREE
Definition at line 581 of file parser.c.
Referenced by yyparse().
YYSTACK_GAP_MAXIMUM
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
Definition at line 621 of file parser.c.
YYSTACK_RELOCATE
#define YYSTACK_RELOCATE (Stack_alloc, Stack)
Value:
do                                                                  \
      {                                                                 \
        YYSIZE_T yynewbytes;                                            \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / sizeof (*yyptr);                          \
      }                                                                 \
    while (0)
Definition at line 636 of file parser.c.
Referenced by yyparse().
YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
Definition at line 419 of file parser.c.
YYSTYPE_IS_TRIVIAL
#define YYSTYPE_IS_TRIVIAL 1
Definition at line 418 of file parser.c.
YYSYNTAX_ERROR
#define YYSYNTAX_ERROR
Value:
yysyntax_error (&yymsg_alloc, &yymsg, \
                                        yyssp, yytoken)
Referenced by yyparse().
YYTABLE_NINF
#define YYTABLE_NINF -134
Definition at line 830 of file parser.c.
yytable_value_is_error
#define yytable_value_is_error (Yytable_value) 0
Definition at line 832 of file parser.c.
Referenced by yyparse(), and yysyntax_error().
YYTERROR
#define YYTERROR 1
Definition at line 1426 of file parser.c.
Referenced by yyparse(), and yysyntax_error().
YYTOKENTYPE
#define YYTOKENTYPE
Definition at line 145 of file parser.c.
YYTRANSLATE
#define YYTRANSLATE (YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
Definition at line 688 of file parser.c.
Referenced by yyparse().
YYUNDEFTOK
#define YYUNDEFTOK 2
Definition at line 685 of file parser.c.
YYUSE
#define YYUSE (E) ((void) (E))
Definition at line 516 of file parser.c.
Referenced by yydestruct().
Typedef Documentation
YYSTYPE
typedef union YYSTYPE YYSTYPE
Definition at line 417 of file parser.c.
yytype_int16
typedef short int yytype_int16
Definition at line 457 of file parser.c.
yytype_int8
typedef signed char yytype_int8
Definition at line 445 of file parser.c.
yytype_uint16
typedef unsigned short int yytype_uint16
Definition at line 451 of file parser.c.
yytype_uint8
typedef unsigned char yytype_uint8
Definition at line 439 of file parser.c.
Enumeration Type Documentation
yytokentype
enum yytokentype
Enumerator
SEMICOLON
CHUCK
COMMA
ASSIGN
DIVIDE
TIMES
PERCENT
L_HACK
R_HACK
LPAREN
RPAREN
LBRACK
RBRACK
LBRACE
RBRACE
PLUSCHUCK
MINUSCHUCK
TIMESCHUCK
DIVIDECHUCK
MODULOCHUCK
ATCHUCK
UNCHUCK
TRIG
UNTRIG
PERCENTPAREN
SHARPPAREN
PROTECTED
ABSTRACT
ATSYM
FUNCTION
DOLLAR
TILDA
QUESTION
COLON
EXCLAMATION
IF
ELSE
WHILE
DO
UNTIL
LOOP
FOR
GOTO
SWITCH
CASE
ENUM
RETURN
BREAK
CONTINUE
PLUSPLUS
MINUSMINUS
NEW
SPORK
SIZEOF
TYPEOF
CLASS
INTERFACE
STATIC
PRIVATE
PUBLIC
EXTENDS
IMPLEMENTS
DOT
COLONCOLON
AND
EQ
GE
GT
LE
LT
MINUS
PLUS
NEQ
SHIFT_LEFT
SHIFT_RIGHT
S_AND
S_OR
S_XOR
OR
AST_DTOR
OPERATOR
FUNC_PTR
RSL
RSR
RSAND
RSOR
RSXOR
RAND
ROR
REQ
RNEQ
RGT
RGE
RLT
RLE
RINC
RDEC
RUNINC
RUNDEC
TEMPLATE
NOELSE
ARROW_LEFT
ARROW_RIGHT
LTB
GTB
VARARG
UNION
ATPAREN
NUM
FLOAT
ID
STRING_LIT
CHAR_LIT
DOC
SEMICOLON
CHUCK
COMMA
ASSIGN
DIVIDE
TIMES
PERCENT
L_HACK
R_HACK
LPAREN
RPAREN
LBRACK
RBRACK
LBRACE
RBRACE
PLUSCHUCK
MINUSCHUCK
TIMESCHUCK
DIVIDECHUCK
MODULOCHUCK
ATCHUCK
UNCHUCK
TRIG
UNTRIG
PERCENTPAREN
SHARPPAREN
PROTECTED
ABSTRACT
ATSYM
FUNCTION
DOLLAR
TILDA
QUESTION
COLON
EXCLAMATION
IF
ELSE
WHILE
DO
UNTIL
LOOP
FOR
GOTO
SWITCH
CASE
ENUM
RETURN
BREAK
CONTINUE
PLUSPLUS
MINUSMINUS
NEW
SPORK
SIZEOF
TYPEOF
CLASS
INTERFACE
STATIC
PRIVATE
PUBLIC
EXTENDS
IMPLEMENTS
DOT
COLONCOLON
AND
EQ
GE
GT
LE
LT
MINUS
PLUS
NEQ
SHIFT_LEFT
SHIFT_RIGHT
S_AND
S_OR
S_XOR
OR
AST_DTOR
OPERATOR
FUNC_PTR
RSL
RSR
RSAND
RSOR
RSXOR
RAND
ROR
REQ
RNEQ
RGT
RGE
RLT
RLE
RINC
RDEC
RUNINC
RUNDEC
TEMPLATE
NOELSE
ARROW_LEFT
ARROW_RIGHT
LTB
GTB
VARARG
UNION
ATPAREN
NUM
FLOAT
ID
STRING_LIT
CHAR_LIT
DOC
SEMICOLON
CHUCK
COMMA
ASSIGN
DIVIDE
TIMES
PERCENT
L_HACK
R_HACK
LPAREN
RPAREN
LBRACK
RBRACK
LBRACE
RBRACE
PLUSCHUCK
MINUSCHUCK
TIMESCHUCK
DIVIDECHUCK
MODULOCHUCK
ATCHUCK
UNCHUCK
PERCENTPAREN
POUNDPAREN
PROTECTED
ABSTRACT
ATSYM
FUNCTION
DOLLAR
TILDA
QUESTION
COLON
EXCLAMATION
IF
ELSE
WHILE
DO
UNTIL
LOOP
FOR
GOTO
SWITCH
CASE
ENUM
RETURN
BREAK
CONTINUE
PLUSPLUS
MINUSMINUS
NEW
SPORK
SIZEOF
TYPEOF
CLASS
INTERFACE
STATIC
PRIVATE
PUBLIC
EXTENDS
IMPLEMENTS
DOT
COLONCOLON
AND
EQ
GE
GT
LE
LT
MINUS
PLUS
NEQ
NOR
SHIFT_LEFT
SHIFT_RIGHT
S_AND
S_OR
S_XOR
OR
NUM
FLOAT
ID
STRING_LIT
CHAR_LIT
Definition at line 146 of file parser.c.
   {
     SEMICOLON = 258,
     CHUCK = 259,
     COMMA = 260,
     ASSIGN = 261,
     DIVIDE = 262,
     TIMES = 263,
     PERCENT = 264,
     L_HACK = 265,
     R_HACK = 266,
     LPAREN = 267,
     RPAREN = 268,
     LBRACK = 269,
     RBRACK = 270,
     LBRACE = 271,
     RBRACE = 272,
     PLUSCHUCK = 273,
     MINUSCHUCK = 274,
     TIMESCHUCK = 275,
     DIVIDECHUCK = 276,
     MODULOCHUCK = 277,
     ATCHUCK = 278,
     UNCHUCK = 279,
     TRIG = 280,
     UNTRIG = 281,
     PERCENTPAREN = 282,
     SHARPPAREN = 283,
     PROTECTED = 284,
     ABSTRACT = 285,
     ATSYM = 286,
     FUNCTION = 287,
     DOLLAR = 288,
     TILDA = 289,
     QUESTION = 290,
     COLON = 291,
     EXCLAMATION = 292,
     IF = 293,
     ELSE = 294,
     WHILE = 295,
     DO = 296,
     UNTIL = 297,
     LOOP = 298,
     FOR = 299,
     GOTO = 300,
     SWITCH = 301,
     CASE = 302,
     ENUM = 303,
     RETURN = 304,
     BREAK = 305,
     CONTINUE = 306,
     PLUSPLUS = 307,
     MINUSMINUS = 308,
     NEW = 309,
     SPORK = 310,
     SIZEOF = 311,
     TYPEOF = 312,
     CLASS = 313,
     INTERFACE = 314,
     STATIC = 315,
     PRIVATE = 316,
     PUBLIC = 317,
     EXTENDS = 318,
     IMPLEMENTS = 319,
     DOT = 320,
     COLONCOLON = 321,
     AND = 322,
     EQ = 323,
     GE = 324,
     GT = 325,
     LE = 326,
     LT = 327,
     MINUS = 328,
     PLUS = 329,
     NEQ = 330,
     SHIFT_LEFT = 331,
     SHIFT_RIGHT = 332,
     S_AND = 333,
     S_OR = 334,
     S_XOR = 335,
     OR = 336,
     AST_DTOR = 337,
     OPERATOR = 338,
     FUNC_PTR = 339,
     RSL = 340,
     RSR = 341,
     RSAND = 342,
     RSOR = 343,
     RSXOR = 344,
     RAND = 345,
     ROR = 346,
     REQ = 347,
     RNEQ = 348,
     RGT = 349,
     RGE = 350,
     RLT = 351,
     RLE = 352,
     RINC = 353,
     RDEC = 354,
     RUNINC = 355,
     RUNDEC = 356,
     TEMPLATE = 357,
     NOELSE = 358,
     ARROW_LEFT = 359,
     ARROW_RIGHT = 360,
     LTB = 361,
     GTB = 362,
     VARARG = 363,
     UNION = 364,
     ATPAREN = 365,
     NUM = 366,
     FLOAT = 367,
     ID = 368,
     STRING_LIT = 369,
     CHAR_LIT = 370,
     DOC = 371
   };
Function Documentation
append_doc()
static char* append_doc (void * data, m_str str) static
Definition at line 87 of file parser.c.
References MyArg::doc, map_get(), scan_map, and vector_append().
Referenced by yyparse().
 {
   MyArg* arg = (MyArg*)map_get(scan_map, (vtype)data);
   vector_append(arg->doc, (vtype)str);
   return str;
 }
free()
void free (void *)
Referenced by alsa_del(), ana_dtor(), check_Array(), check_Cast_Expression(), check_Class_Def(), check_Decl_Expression(), check_Func_Call1(), check_Unary(), compile(), DTOR(), emit_Ast(), emit_Class_Def(), emit_Func_Call1(), emit_Goto_Label(), emit_pop_scope(), fft_tick(), free_Arg_List(), free_Array_Expression(), free_Array_Sub(), free_Ast(), free_BBQ(), free_Binary_Expression(), free_Cast_Expression(), free_Class_Def(), free_Code(), free_complex(), free_Context(), free_Decl_Expression(), free_Decl_List(), free_DL_Func(), free_DL_Value(), free_Doc(), free_Dot_Member_Expression(), free_Driver(), free_Dur_Expression(), free_Emitter(), free_Env(), free_Expression(), free_Frame(), free_Func(), free_Func_Call(), free_Func_Def(), free_ID_List(), free_If_Expression(), free_Map(), free_NameSpace(), free_Operator_Map(), free_polar(), free_Postfix_Expression(), free_Primary_Expression(), free_Scope(), free_Section(), free_Shreduler(), free_Stmt(), free_Stmt_Case(), free_Stmt_Code(), free_Stmt_Enum(), free_Stmt_For(), free_Stmt_Func_Ptr(), free_Stmt_GotoLabel(), free_Stmt_If(), free_Stmt_List(), free_Stmt_Loop(), free_Stmt_Return(), free_Stmt_Switch(), free_Stmt_Union(), free_Stmt_Until(), free_Stmt_While(), free_Symbol(), free_Textadept(), free_Type(), free_Type_Decl(), free_Type_List(), free_UGen(), free_Unary_Expression(), free_Value(), free_Var_Decl(), free_Var_Decl_List(), free_Vec(), free_Vector(), free_VM(), free_VM_Code(), free_VM_Shred(), fullrect_dtor(), gain_dtor(), getfull(), halfrect_dtor(), if(), impulse_dtor(), INSTR(), jack_del(), jack_run(), map_remove(), MFUN(), mkadt_func(), mkadt_nspc(), mkdoc_func(), mkdoc_nspc(), mkdoc_type(), mkdoc_value(), new_BBQ(), new_Doc(), new_Textadept(), object_dtor(), rem_ref(), scan1_Func_Def(), scan1_Func_Ptr(), scan2_Func_Def(), server_thread(), SFUN(), shreduler_remove(), sndfile_del(), sp_buffer_destroy(), step_dtor(), str2list(), type_engine_check_prog(), type_engine_init(), vector_remove(), and zerox_dtor().
get_doc()
static m_str get_doc (void * data) static
Definition at line 94 of file parser.c.
References MyArg::doc, map_get(), scan_map, vector_front(), and vector_remove().
Referenced by yyparse().
 {
   m_str ret;
   MyArg* arg = (MyArg*)map_get(scan_map, (vtype)data);
   ret = (m_str)vector_front(arg->doc);
   vector_remove(arg->doc, 0);
   return ret;
 }
get_pos()
static int get_pos (void * data) static
Definition at line 81 of file parser.c.
References MyArg::line, map_get(), and scan_map.
Referenced by yyparse().
 {
   MyArg* arg = (MyArg*)map_get(scan_map, (vtype)data);
   return arg->line;
 }
malloc()
void* malloc (YYSIZE_T)
Referenced by add_binary_op(), alsa_driver(), ana_ctor(), check_Func_Call1(), dummy_driver(), fullrect_ctor(), gain_ctor(), halfrect_ctor(), if(), impulse_ctor(), INSTR(), jack_driver(), jack_ini(), new_Ast(), new_BBQ(), new_Context(), new_DL_Func(), new_DL_Value(), new_Doc(), new_M_Array(), new_Map(), new_Scope(), new_Shreduler(), new_Textadept(), new_Union(), new_Vector(), new_Vector_fixed(), new_VM(), new_VM_Code(), new_VM_Object(), pa_driver(), parse(), randstring(), raw_driver(), silent_driver(), sinosc_ctor(), sio_driver(), sndfile_driver(), sp_buffer_create(), step_ctor(), and zerox_ctor().
minimal_error()
void minimal_error (void * data, const char * s)
Referenced by if().
minimal_lex()
int minimal_lex (void * , void * , void *)
minimal_parse()
int minimal_parse (MyArg * arg)
Referenced by parse().
strcat()
char* strcat (char * dest, const char * src)
Referenced by check_Dot_Member(), check_op(), getfull(), if(), parse(), print_type(), SFUN(), and type_path().
yydestruct()
static void yydestruct (const char * yymsg, int yytype, YYSTYPE * yyvaluep, MyArg * arg) static
Definition at line 1806 of file parser.c.
References free_Type_Decl(), YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_SYMBOL_PRINT, and YYUSE.
Referenced by yyparse().
 {
   YYUSE (yyvaluep);
   YYUSE (arg);
   if (!yymsg)
     yymsg = "Deleting";
   YY_SYMBOL_PRINT (yymsg, yytype, yyvaluep, yylocationp);
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   switch (yytype)
     {
           case 132: /* type_decl2  */
 #line 178 "eval/gwion.y" /* yacc.c:1257  */
       { printf("!!!!\n"); free_Type_Decl(((*yyvaluep).type_decl)); }
 #line 1821 "eval/parser.c" /* yacc.c:1257  */
         break;
     case 155: /* type_decl  */
 #line 178 "eval/gwion.y" /* yacc.c:1257  */
       { printf("!!!!\n"); free_Type_Decl(((*yyvaluep).type_decl)); }
 #line 1827 "eval/parser.c" /* yacc.c:1257  */
         break;
       default:
         break;
     }
   YY_IGNORE_MAYBE_UNINITIALIZED_END
 }
yyparse()
int yyparse (MyArg * arg)
Definition at line 1844 of file parser.c.
References add_type_decl_array(), ae_func_spec_dtor, ae_func_spec_op, ae_key_abstract, ae_key_func, ae_key_instance, ae_key_private, ae_key_public, ae_key_static, ae_key_variadic, ae_op_arrow_left, ae_op_arrow_right, append_doc(), YYSTYPE::arg_list, YYSTYPE::array_sub, MyArg::ast, YYSTYPE::ast, YYSTYPE::c_val, YYSTYPE::class_body, YYSTYPE::class_def, YYSTYPE::class_ext, YYSTYPE::decl_list, Type_Decl::doc, YYSTYPE::exp, Expression_::exp_func, YYSTYPE::func_def, YYSTYPE::fval, get_doc(), get_pos(), YYSTYPE::id_list, YYSTYPE::ival, new_Arg_List(), new_Array(), new_array_sub(), new_Ast(), new_Binary_Expression(), new_Cast_Expression(), new_class_body(), new_class_def(), new_class_ext(), new_complex(), new_Decl_Expression(), new_Decl_List(), new_Exp_Dur(), new_exp_from_array_lit(), new_exp_from_char(), new_exp_from_complex(), new_exp_from_member_dot(), new_exp_from_polar(), new_exp_from_unary(), new_exp_from_unary2(), new_exp_from_unary3(), new_exp_from_vec(), new_Func_Call(), new_Func_Def(), new_Func_Ptr_Stmt(), new_Hack_Expression(), new_id_list(), new_If_Expression(), new_polar(), new_Postfix_Expression(), new_Primary_Expression_from_float(), new_Primary_Expression_from_ID(), new_Primary_Expression_from_int(), new_Primary_Expression_from_nil(), new_Primary_Expression_from_string(), new_section_Class_Def(), new_section_Func_Def(), new_section_Stmt_List(), new_stmt_from_break(), new_stmt_from_case(), new_stmt_from_code(), new_stmt_from_continue(), new_stmt_from_enum(), new_Stmt_from_Expression(), new_stmt_from_for(), new_stmt_from_gotolabel(), new_stmt_from_if(), new_stmt_from_loop(), new_stmt_from_return(), new_stmt_from_switch(), new_stmt_from_Union(), new_stmt_from_until(), new_stmt_from_while(), new_Stmt_List(), new_Type_Decl(), new_type_list(), new_Union(), new_Var_Decl(), new_Var_Decl_List(), new_Vec(), op_and, op_assign, op_at_chuck, op_chuck, op_divide, op_divide_chuck, op_eq, op_exclamation, op_ge, op_gt, op_le, op_lt, op_minus, op_minus_chuck, op_minusminus, op_modulo_chuck, op_neq, op_new, op_or, op_percent, op_plus, op_plus_chuck, op_plusplus, op_rand, op_rdec, op_req, op_rge, op_rgt, op_rinc, op_rle, op_rlt, op_rneq, op_ror, op_rsand, op_rsl, op_rsor, op_rsr, op_rsxor, op_rundec, op_runinc, op_s_and, op_s_or, op_s_xor, op_shift_left, op_shift_right, op_sizeof, op_spork, op_tilda, op_times, op_times_chuck, op_trig, op_typeof, op_unchuck, op_untrig, YYSTYPE::polar, prepend_array_sub(), prepend_class_body(), prepend_Expression(), prepend_id_list(), scanner, YYSTYPE::section, YYSTYPE::stmt, YYSTYPE::stmt_list, YYSTYPE::sval, YYSTYPE::type_decl, YYSTYPE::type_list, Func_Call::types, YYSTYPE::union_stmt, YYSTYPE::var_decl, YYSTYPE::var_decl_list, YYSTYPE::vec, YY_, YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_INITIAL_VALUE, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yycheck, yydefact, yydefgoto, yydestruct(), YYDPRINTF, YYEMPTY, YYEOF, yyerror, YYFINAL, YYINITDEPTH, YYLAST, yylex, yylval, YYMAXDEPTH, yynerrs, YYNTOKENS, yypact, yypact_value_is_default, yypgoto, YYPOPSTACK, yyr1, yyr2, YYSIZE_T, yyalloc::yyss_alloc, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, yystos, YYSYNTAX_ERROR, yytable, yytable_value_is_error, YYTERROR, YYTRANSLATE, and yyalloc::yyvs_alloc.
 {
 /* The lookahead symbol.  */
 int yychar;
 /* The semantic value of the lookahead symbol.  */
 /* Default value used for initialization, for pacifying older GCCs
    or non-GCC compilers.  */
 YY_INITIAL_VALUE (static YYSTYPE yyval_default;)
 YYSTYPE yylval YY_INITIAL_VALUE (= yyval_default);
     /* Number of syntax errors so far.  */
     int yynerrs;
     int yystate;
     /* Number of tokens to shift before error messages enabled.  */
     int yyerrstatus;
     /* The stacks and their tools:
        'yyss': related to states.
        'yyvs': related to semantic values.
        Refer to the stacks through separate pointers, to allow yyoverflow
        to reallocate them elsewhere.  */
     /* The state stack.  */
     yytype_int16 yyssa[YYINITDEPTH];
     yytype_int16 *yyss;
     yytype_int16 *yyssp;
     /* The semantic value stack.  */
     YYSTYPE yyvsa[YYINITDEPTH];
     YYSTYPE *yyvs;
     YYSTYPE *yyvsp;
     YYSIZE_T yystacksize;
   int yyn;
   int yyresult;
   /* Lookahead token as an internal (translated) token number.  */
   int yytoken = 0;
   /* The variables used to return semantic value and location from the
      action routines.  */
   YYSTYPE yyval;
 #if YYERROR_VERBOSE
   /* Buffer for error messages, and its allocated size.  */
   char yymsgbuf[128];
   char *yymsg = yymsgbuf;
   YYSIZE_T yymsg_alloc = sizeof yymsgbuf;
 #endif
 #define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))
   /* The number of symbols on the RHS of the reduced rule.
      Keep to zero when no symbol should be popped.  */
   int yylen = 0;
   yyssp = yyss = yyssa;
   yyvsp = yyvs = yyvsa;
   yystacksize = YYINITDEPTH;
   YYDPRINTF ((stderr, "Starting parse\n"));
   yystate = 0;
   yyerrstatus = 0;
   yynerrs = 0;
   yychar = YYEMPTY; /* Cause a token to be read.  */
   goto yysetstate;
 /*------------------------------------------------------------.
 | yynewstate -- Push a new state, which is found in yystate.  |
 `------------------------------------------------------------*/
  yynewstate:
   /* In all cases, when you get here, the value and location stacks
      have just been pushed.  So pushing a state here evens the stacks.  */
   yyssp++;
  yysetstate:
   *yyssp = yystate;
   if (yyss + yystacksize - 1 <= yyssp)
     {
       /* Get the current used size of the three stacks, in elements.  */
       YYSIZE_T yysize = yyssp - yyss + 1;
 #ifdef yyoverflow
       {
         /* Give user a chance to reallocate the stack.  Use copies of
            these so that the &'s don't force the real ones into
            memory.  */
         YYSTYPE *yyvs1 = yyvs;
         yytype_int16 *yyss1 = yyss;
         /* Each stack pointer address is followed by the size of the
            data in use in that stack, in bytes.  This used to be a
            conditional around just the two extra args, but that might
            be undefined if yyoverflow is a macro.  */
         yyoverflow (YY_("memory exhausted"),
                     &yyss1, yysize * sizeof (*yyssp),
                     &yyvs1, yysize * sizeof (*yyvsp),
                     &yystacksize);
         yyss = yyss1;
         yyvs = yyvs1;
       }
 #else /* no yyoverflow */
 # ifndef YYSTACK_RELOCATE
       goto yyexhaustedlab;
 # else
       /* Extend the stack our own way.  */
       if (YYMAXDEPTH <= yystacksize)
         goto yyexhaustedlab;
       yystacksize *= 2;
       if (YYMAXDEPTH < yystacksize)
         yystacksize = YYMAXDEPTH;
       {
         yytype_int16 *yyss1 = yyss;
         union yyalloc *yyptr =
           (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
         if (! yyptr)
           goto yyexhaustedlab;
         YYSTACK_RELOCATE (yyss_alloc, yyss);
         YYSTACK_RELOCATE (yyvs_alloc, yyvs);
 #  undef YYSTACK_RELOCATE
         if (yyss1 != yyssa)
           YYSTACK_FREE (yyss1);
       }
 # endif
 #endif /* no yyoverflow */
       yyssp = yyss + yysize - 1;
       yyvsp = yyvs + yysize - 1;
       YYDPRINTF ((stderr, "Stack size increased to %lu\n",
                   (unsigned long int) yystacksize));
       if (yyss + yystacksize - 1 <= yyssp)
         YYABORT;
     }
   YYDPRINTF ((stderr, "Entering state %d\n", yystate));
   if (yystate == YYFINAL)
     YYACCEPT;
   goto yybackup;
 /*-----------.
 | yybackup.  |
 `-----------*/
 yybackup:
   /* Do appropriate processing given the current state.  Read a
      lookahead token if we need one and don't already have one.  */
   /* First try to decide what to do without reference to lookahead token.  */
   yyn = yypact[yystate];
   if (yypact_value_is_default (yyn))
     goto yydefault;
   /* Not known => get a lookahead token if don't already have one.  */
   /* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
   if (yychar == YYEMPTY)
     {
       YYDPRINTF ((stderr, "Reading a token: "));
       yychar = yylex (&yylval, scanner, arg);
     }
   if (yychar <= YYEOF)
     {
       yychar = yytoken = YYEOF;
       YYDPRINTF ((stderr, "Now at end of input.\n"));
     }
   else
     {
       yytoken = YYTRANSLATE (yychar);
       YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
     }
   /* If the proper action on seeing token YYTOKEN is to reduce or to
      detect an error, take that action.  */
   yyn += yytoken;
   if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
     goto yydefault;
   yyn = yytable[yyn];
   if (yyn <= 0)
     {
       if (yytable_value_is_error (yyn))
         goto yyerrlab;
       yyn = -yyn;
       goto yyreduce;
     }
   /* Count tokens shifted since error; after three, turn off error
      status.  */
   if (yyerrstatus)
     yyerrstatus--;
   /* Shift the lookahead token.  */
   YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
   /* Discard the shifted token.  */
   yychar = YYEMPTY;
   yystate = yyn;
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   *++yyvsp = yylval;
   YY_IGNORE_MAYBE_UNINITIALIZED_END
   goto yynewstate;
 /*-----------------------------------------------------------.
 | yydefault -- do the default action for the current state.  |
 `-----------------------------------------------------------*/
 yydefault:
   yyn = yydefact[yystate];
   if (yyn == 0)
     goto yyerrlab;
   goto yyreduce;
 /*-----------------------------.
 | yyreduce -- Do a reduction.  |
 `-----------------------------*/
 yyreduce:
   /* yyn is the number of a rule to reduce with.  */
   yylen = yyr2[yyn];
   /* If YYLEN is nonzero, implement the default value of the action:
      '$$ = $1'.
      Otherwise, the following line sets YYVAL to garbage.
      This behavior is undocumented and Bison
      users should not rely upon it.  Assigning to YYVAL
      unconditionally makes the parser a bit smaller, and it avoids a
      GCC warning that YYVAL may be used uninitialized.  */
   yyval = yyvsp[1-yylen];
   YY_REDUCE_PRINT (yyn);
   switch (yyn)
     {
         case 2:
 #line 182 "eval/gwion.y" /* yacc.c:1646  */
     { arg->ast = (yyval.ast) = new_Ast((yyvsp[0].section), NULL, get_pos(scanner));  }
 #line 2095 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 3:
 #line 183 "eval/gwion.y" /* yacc.c:1646  */
     { arg->ast = (yyval.ast) = new_Ast((yyvsp[-1].section), (yyvsp[0].ast), get_pos(scanner)); }
 #line 2101 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 4:
 #line 187 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.section) = new_section_Stmt_List((yyvsp[0].stmt_list), get_pos(scanner)); }
 #line 2107 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 5:
 #line 188 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.section) = new_section_Func_Def ((yyvsp[0].func_def), get_pos(scanner)); }
 #line 2113 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 6:
 #line 189 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.section) = new_section_Class_Def((yyvsp[0].class_def), get_pos(scanner)); }
 #line 2119 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 7:
 #line 194 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.class_def) = new_class_def( (yyvsp[-5].ival), (yyvsp[-3].id_list), NULL, (yyvsp[-1].class_body), get_pos(scanner)); (yyval.class_def)->doc = get_doc(scanner); }
 #line 2125 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 8:
 #line 196 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.class_def) = new_class_def( (yyvsp[-6].ival), (yyvsp[-4].id_list), (yyvsp[-3].class_ext), (yyvsp[-1].class_body), get_pos(scanner)); (yyval.class_def)->doc = get_doc(scanner);}
 #line 2131 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 9:
 #line 206 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.class_ext) = new_class_ext( (yyvsp[0].id_list), NULL, get_pos(scanner)); }
 #line 2137 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 10:
 #line 211 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = ae_key_public; }
 #line 2143 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 11:
 #line 212 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = ae_key_private; }
 #line 2149 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 12:
 #line 213 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = ae_key_private; }
 #line 2155 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 13:
 #line 217 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.class_body) = (yyvsp[0].class_body); }
 #line 2161 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 14:
 #line 218 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.class_body) = NULL; }
 #line 2167 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 15:
 #line 222 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.class_body) = new_class_body( (yyvsp[0].section), get_pos(scanner)); }
 #line 2173 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 16:
 #line 223 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.class_body) = prepend_class_body( (yyvsp[-1].section), (yyvsp[0].class_body), get_pos(scanner)); }
 #line 2179 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 17:
 #line 227 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.section) = new_section_Stmt_List( (yyvsp[0].stmt_list), get_pos(scanner)); }
 #line 2185 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 18:
 #line 228 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.section) = new_section_Func_Def( (yyvsp[0].func_def), get_pos(scanner)); }
 #line 2191 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 19:
 #line 229 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.section) = new_section_Class_Def( (yyvsp[0].class_def), get_pos(scanner)); }
 #line 2197 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 20:
 #line 237 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.id_list) = new_id_list( (yyvsp[0].sval), get_pos(scanner)); }
 #line 2203 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 21:
 #line 238 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.id_list) = prepend_id_list( (yyvsp[-2].sval), (yyvsp[0].id_list), get_pos(scanner)); }
 #line 2209 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 22:
 #line 242 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.id_list) = new_id_list( (yyvsp[0].sval), get_pos(scanner)); }
 #line 2215 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 23:
 #line 243 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.id_list) = prepend_id_list( (yyvsp[-2].sval), (yyvsp[0].id_list), get_pos(scanner)); }
 #line 2221 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 24:
 #line 247 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt_list) = new_Stmt_List((yyvsp[0].stmt), NULL, get_pos(scanner));}
 #line 2227 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 25:
 #line 248 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt_list) = new_Stmt_List((yyvsp[-1].stmt), (yyvsp[0].stmt_list), get_pos(scanner));}
 #line 2233 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 26:
 #line 252 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = ae_key_static;   }
 #line 2239 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 27:
 #line 253 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = ae_key_abstract; }
 #line 2245 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 28:
 #line 254 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = ae_key_instance; }
 #line 2251 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 29:
 #line 258 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = ae_key_func; }
 #line 2257 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 30:
 #line 259 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = ae_key_variadic; }
 #line 2263 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 31:
 #line 268 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_Func_Ptr_Stmt(0, (yyvsp[-3].sval), (yyvsp[-5].type_decl), NULL, get_pos(scanner)); }
 #line 2269 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 32:
 #line 269 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_Func_Ptr_Stmt(ae_key_static, (yyvsp[-3].sval), (yyvsp[-5].type_decl), NULL, get_pos(scanner)); }
 #line 2275 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 33:
 #line 270 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_Func_Ptr_Stmt(0, (yyvsp[-4].sval), (yyvsp[-6].type_decl), (yyvsp[-1].arg_list), get_pos(scanner)); }
 #line 2281 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 34:
 #line 271 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_Func_Ptr_Stmt(ae_key_static, (yyvsp[-4].sval), (yyvsp[-6].type_decl), (yyvsp[-1].arg_list), get_pos(scanner)); }
 #line 2287 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 35:
 #line 275 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.type_decl) = (yyvsp[0].type_decl); }
 #line 2293 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 36:
 #line 276 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.type_decl) = add_type_decl_array( (yyvsp[-1].type_decl), (yyvsp[0].array_sub), get_pos(scanner)); }
 #line 2299 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 37:
 #line 280 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.arg_list) = new_Arg_List((yyvsp[-1].type_decl), (yyvsp[0].var_decl), NULL, get_pos(scanner)); /* $$->doc = get_arg_doc(scanner); */ }
 #line 2305 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 38:
 #line 281 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.arg_list) = new_Arg_List((yyvsp[-3].type_decl), (yyvsp[-2].var_decl), (yyvsp[0].arg_list), get_pos(scanner)); /* $$->doc = get_arg_doc(scanner); */ }
 #line 2311 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 39:
 #line 285 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_code( NULL, get_pos(scanner)); }
 #line 2317 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 40:
 #line 286 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_code( (yyvsp[-1].stmt_list), get_pos(scanner)); }
 #line 2323 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 52:
 #line 301 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_Union((yyvsp[0].union_stmt), 0); }
 #line 2329 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 53:
 #line 305 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_enum((yyvsp[-2].id_list), NULL, get_pos(scanner)); }
 #line 2335 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 54:
 #line 306 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_enum((yyvsp[-3].id_list), (yyvsp[-1].sval), get_pos(scanner)); }
 #line 2341 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 55:
 #line 310 "eval/gwion.y" /* yacc.c:1646  */
     {  (yyval.stmt) = new_stmt_from_gotolabel((yyvsp[-1].sval), 1, get_pos(scanner)); }
 #line 2347 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 56:
 #line 314 "eval/gwion.y" /* yacc.c:1646  */
     {  (yyval.stmt) = new_stmt_from_gotolabel((yyvsp[-1].sval), 0, get_pos(scanner)); }
 #line 2353 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 57:
 #line 318 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_case((yyvsp[-1].exp), get_pos(scanner)); }
 #line 2359 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 58:
 #line 319 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_case((yyvsp[-1].exp), get_pos(scanner)); }
 #line 2365 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 59:
 #line 323 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_switch((yyvsp[-2].exp), (yyvsp[0].stmt), get_pos(scanner));}
 #line 2371 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 60:
 #line 328 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_while( (yyvsp[-2].exp), (yyvsp[0].stmt), 0, get_pos(scanner)); }
 #line 2377 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 61:
 #line 330 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_while( (yyvsp[-2].exp), (yyvsp[-5].stmt), 1, get_pos(scanner)); }
 #line 2383 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 62:
 #line 332 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_for( (yyvsp[-3].stmt), (yyvsp[-2].stmt), NULL, (yyvsp[0].stmt), get_pos(scanner)); }
 #line 2389 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 63:
 #line 334 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_for( (yyvsp[-4].stmt), (yyvsp[-3].stmt), (yyvsp[-2].exp), (yyvsp[0].stmt), get_pos(scanner)); }
 #line 2395 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 64:
 #line 336 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_until( (yyvsp[-2].exp), (yyvsp[0].stmt), 0, get_pos(scanner)); }
 #line 2401 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 65:
 #line 338 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_until( (yyvsp[-2].exp), (yyvsp[-5].stmt), 1, get_pos(scanner)); }
 #line 2407 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 66:
 #line 340 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_loop( (yyvsp[-2].exp), (yyvsp[0].stmt), get_pos(scanner)); }
 #line 2413 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 67:
 #line 345 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_if( (yyvsp[-2].exp), (yyvsp[0].stmt), NULL, get_pos(scanner)); }
 #line 2419 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 68:
 #line 347 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_if( (yyvsp[-4].exp), (yyvsp[-2].stmt), (yyvsp[0].stmt), get_pos(scanner)); }
 #line 2425 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 69:
 #line 351 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_return( NULL, get_pos(scanner)); }
 #line 2431 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 70:
 #line 352 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_return( (yyvsp[-1].exp), get_pos(scanner)); }
 #line 2437 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 71:
 #line 353 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_break(get_pos(scanner)); }
 #line 2443 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 72:
 #line 354 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_stmt_from_continue(get_pos(scanner)); }
 #line 2449 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 73:
 #line 358 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_Stmt_from_Expression((yyvsp[-1].exp),   get_pos(scanner)); }
 #line 2455 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 74:
 #line 359 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_Stmt_from_Expression(NULL, get_pos(scanner)); }
 #line 2461 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 75:
 #line 360 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.stmt) = new_Stmt_from_Expression(NULL, get_pos(scanner)); append_doc(scanner, (yyvsp[0].sval)); }
 #line 2467 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 76:
 #line 364 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[0].exp); }
 #line 2473 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 77:
 #line 365 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = prepend_Expression((yyvsp[-2].exp), (yyvsp[0].exp), get_pos(scanner)); }
 #line 2479 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 78:
 #line 369 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = ae_op_arrow_left; }
 #line 2485 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 79:
 #line 370 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = ae_op_arrow_right; }
 #line 2491 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 80:
 #line 373 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[0].exp); }
 #line 2497 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 81:
 #line 374 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression((yyvsp[-2].exp), (yyvsp[-1].ival), (yyvsp[0].exp), get_pos(scanner)); }
 #line 2503 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 82:
 #line 378 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[0].exp); }
 #line 2509 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 83:
 #line 380 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), (yyvsp[-1].ival), (yyvsp[0].exp), get_pos(scanner)); }
 #line 2515 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 84:
 #line 383 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.type_list) = (yyvsp[-1].type_list); }
 #line 2521 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 85:
 #line 388 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_chuck; }
 #line 2527 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 86:
 #line 389 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_unchuck; }
 #line 2533 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 87:
 #line 390 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_at_chuck; }
 #line 2539 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 88:
 #line 391 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_plus_chuck; }
 #line 2545 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 89:
 #line 392 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_minus_chuck; }
 #line 2551 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 90:
 #line 393 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_times_chuck; }
 #line 2557 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 91:
 #line 394 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_divide_chuck; }
 #line 2563 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 92:
 #line 395 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_modulo_chuck; }
 #line 2569 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 93:
 #line 396 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_trig; }
 #line 2575 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 94:
 #line 397 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_untrig; }
 #line 2581 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 95:
 #line 398 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_rsl; }
 #line 2587 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 96:
 #line 399 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_rsr; }
 #line 2593 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 97:
 #line 400 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_rsand; }
 #line 2599 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 98:
 #line 401 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_rsor; }
 #line 2605 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 99:
 #line 402 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_rsxor; }
 #line 2611 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 100:
 #line 403 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_rand; }
 #line 2617 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 101:
 #line 404 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_ror; }
 #line 2623 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 102:
 #line 405 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_req; }
 #line 2629 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 103:
 #line 406 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_rneq; }
 #line 2635 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 104:
 #line 407 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_rgt; }
 #line 2641 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 105:
 #line 408 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_rge; }
 #line 2647 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 106:
 #line 409 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_rlt; }
 #line 2653 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 107:
 #line 410 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_rle; }
 #line 2659 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 108:
 #line 411 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_rinc; }
 #line 2665 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 109:
 #line 412 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_rdec; }
 #line 2671 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 110:
 #line 413 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_runinc; }
 #line 2677 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 111:
 #line 414 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_rundec; }
 #line 2683 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 112:
 #line 415 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_eq; }
 #line 2689 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 113:
 #line 416 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_assign; }
 #line 2695 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 114:
 #line 420 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.array_sub) = new_array_sub( (yyvsp[-1].exp), get_pos(scanner) ); }
 #line 2701 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 115:
 #line 422 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.array_sub) = prepend_array_sub( (yyvsp[0].array_sub), (yyvsp[-2].exp), get_pos(scanner)); }
 #line 2707 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 116:
 #line 426 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.array_sub) = new_array_sub( NULL, get_pos(scanner)); }
 #line 2713 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 117:
 #line 427 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.array_sub) = prepend_array_sub( (yyvsp[-2].array_sub), NULL, get_pos(scanner)); }
 #line 2719 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 119:
 #line 432 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp)= new_Decl_Expression((yyvsp[-1].type_decl), (yyvsp[0].var_decl_list), 0, get_pos(scanner)); }
 #line 2725 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 120:
 #line 433 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp)= new_Decl_Expression((yyvsp[-1].type_decl), (yyvsp[0].var_decl_list), 1, get_pos(scanner)); }
 #line 2731 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 121:
 #line 434 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp)= new_Decl_Expression((yyvsp[-1].type_decl), (yyvsp[0].var_decl_list), 2, get_pos(scanner)); }
 #line 2737 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 122:
 #line 435 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp)= new_Decl_Expression((yyvsp[-1].type_decl), (yyvsp[0].var_decl_list), 3, get_pos(scanner)); }
 #line 2743 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 123:
 #line 436 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp)= new_Decl_Expression((yyvsp[-1].type_decl), (yyvsp[0].var_decl_list), 4, get_pos(scanner)); }
 #line 2749 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 124:
 #line 437 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp)= new_Decl_Expression((yyvsp[-1].type_decl), (yyvsp[0].var_decl_list), 5, get_pos(scanner)); }
 #line 2755 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 125:
 #line 441 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.func_def) = new_Func_Def((yyvsp[-6].ival), (yyvsp[-5].ival), (yyvsp[-4].type_decl), (yyvsp[-3].sval), NULL, (yyvsp[0].stmt), get_pos(scanner)); (yyval.func_def)->type_decl->doc = get_doc(scanner); }
 #line 2761 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 126:
 #line 443 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.func_def) = new_Func_Def((yyvsp[-6].ival), (yyvsp[-5].ival), (yyvsp[-4].type_decl), (yyvsp[-3].sval), NULL, NULL, get_pos(scanner)); (yyval.func_def)->type_decl->doc = get_doc(scanner); }
 #line 2767 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 127:
 #line 445 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.func_def) = new_Func_Def((yyvsp[-7].ival), (yyvsp[-6].ival), (yyvsp[-5].type_decl), (yyvsp[-4].sval), (yyvsp[-2].arg_list), (yyvsp[0].stmt), get_pos(scanner)); (yyval.func_def)->type_decl->doc = get_doc(scanner); }
 #line 2773 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 128:
 #line 447 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.func_def) = new_Func_Def(ae_key_func, ae_key_instance, new_Type_Decl(new_id_list("void", get_pos(scanner)), 0, get_pos(scanner)), "dtor", NULL, (yyvsp[0].stmt), get_pos(scanner)); (yyval.func_def)->spec = ae_func_spec_dtor; (yyval.func_def)->type_decl->doc = get_doc(scanner);}
 #line 2779 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 129:
 #line 449 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.func_def) = new_Func_Def(ae_key_func, ae_key_static, (yyvsp[-4].type_decl), (yyvsp[-3].sval), NULL, (yyvsp[0].stmt), get_pos(scanner)); (yyval.func_def)->spec = ae_func_spec_op; (yyval.func_def)->type_decl->doc = get_doc(scanner); }
 #line 2785 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 130:
 #line 451 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.func_def) = new_Func_Def(ae_key_func, ae_key_static, (yyvsp[-5].type_decl), (yyvsp[-4].sval), (yyvsp[-2].arg_list), (yyvsp[0].stmt), get_pos(scanner)); (yyval.func_def)->spec = ae_func_spec_op; (yyval.func_def)->type_decl->doc = get_doc(scanner); }
 #line 2791 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 131:
 #line 453 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.func_def) = new_Func_Def((yyvsp[-6].ival), (yyvsp[-5].ival), (yyvsp[-4].type_decl), (yyvsp[-3].sval), NULL, (yyvsp[0].stmt), get_pos(scanner)); (yyval.func_def)->type_decl->doc = get_doc(scanner); (yyval.func_def)->types = (yyvsp[-8].id_list); }
 #line 2797 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 132:
 #line 455 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.func_def) = new_Func_Def((yyvsp[-7].ival), (yyvsp[-6].ival), (yyvsp[-5].type_decl), (yyvsp[-4].sval), (yyvsp[-2].arg_list), (yyvsp[0].stmt), get_pos(scanner)); (yyval.func_def)->type_decl->doc = get_doc(scanner); (yyval.func_def)->types = (yyvsp[-9].id_list); }
 #line 2803 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 133:
 #line 459 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.type_decl) = new_Type_Decl(new_id_list((yyvsp[0].sval), get_pos(scanner)), 0, get_pos(scanner)); }
 #line 2809 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 134:
 #line 460 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.type_decl) = new_Type_Decl(new_id_list((yyvsp[-1].sval), get_pos(scanner)), 1, get_pos(scanner)); }
 #line 2815 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 135:
 #line 461 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.type_decl) = new_Type_Decl((yyvsp[-1].id_list),  0, get_pos(scanner)); }
 #line 2821 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 136:
 #line 462 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.type_decl) = new_Type_Decl((yyvsp[-2].id_list),  1, get_pos(scanner)); }
 #line 2827 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 137:
 #line 467 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.decl_list) = new_Decl_List((yyvsp[-1].exp)->d.exp_decl, NULL); }
 #line 2833 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 138:
 #line 468 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.decl_list) = new_Decl_List((yyvsp[-2].exp)->d.exp_decl, (yyvsp[0].decl_list)); }
 #line 2839 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 139:
 #line 469 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.decl_list) = NULL; }
 #line 2845 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 140:
 #line 470 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.decl_list) = new_Decl_List(NULL, (yyvsp[0].decl_list)); }
 #line 2851 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 141:
 #line 474 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.union_stmt) = new_Union((yyvsp[-2].decl_list)); }
 #line 2857 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 142:
 #line 478 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.var_decl_list) = new_Var_Decl_List((yyvsp[0].var_decl), NULL, get_pos(scanner)); (yyval.var_decl_list)->doc = get_doc(scanner); }
 #line 2863 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 143:
 #line 479 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.var_decl_list) = new_Var_Decl_List((yyvsp[-2].var_decl), (yyvsp[0].var_decl_list), get_pos(scanner)); (yyval.var_decl_list)->doc = get_doc(scanner); }
 #line 2869 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 144:
 #line 483 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.var_decl) = new_Var_Decl((yyvsp[0].sval), NULL, get_pos(scanner)); }
 #line 2875 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 145:
 #line 484 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.var_decl) = new_Var_Decl((yyvsp[-1].sval),   (yyvsp[0].array_sub), get_pos(scanner)); }
 #line 2881 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 146:
 #line 485 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.var_decl) = new_Var_Decl((yyvsp[-1].sval),   (yyvsp[0].array_sub), get_pos(scanner)); }
 #line 2887 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 147:
 #line 490 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.c_val) = new_complex( (yyvsp[-1].exp), get_pos(scanner)); }
 #line 2893 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 148:
 #line 495 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.polar) = new_polar((yyvsp[-1].exp), get_pos(scanner)); }
 #line 2899 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 149:
 #line 498 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.vec) = new_Vec((yyvsp[-1].exp), get_pos(scanner)); }
 #line 2905 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 151:
 #line 503 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_If_Expression( (yyvsp[-4].exp), (yyvsp[-2].exp), (yyvsp[0].exp), get_pos(scanner)); }
 #line 2911 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 152:
 #line 507 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[0].exp); }
 #line 2917 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 153:
 #line 509 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_or, (yyvsp[0].exp), get_pos(scanner)); }
 #line 2923 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 154:
 #line 513 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[0].exp); }
 #line 2929 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 155:
 #line 515 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_and, (yyvsp[0].exp), get_pos(scanner)); }
 #line 2935 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 156:
 #line 519 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[0].exp); }
 #line 2941 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 157:
 #line 521 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_s_or, (yyvsp[0].exp), get_pos(scanner)); }
 #line 2947 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 158:
 #line 525 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[0].exp); }
 #line 2953 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 159:
 #line 527 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_s_xor, (yyvsp[0].exp), get_pos(scanner)); }
 #line 2959 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 160:
 #line 531 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[0].exp); }
 #line 2965 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 161:
 #line 533 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_s_and, (yyvsp[0].exp), get_pos(scanner)); }
 #line 2971 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 162:
 #line 537 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[0].exp); }
 #line 2977 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 163:
 #line 539 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_eq, (yyvsp[0].exp), get_pos(scanner)); }
 #line 2983 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 164:
 #line 541 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_neq, (yyvsp[0].exp), get_pos(scanner)); }
 #line 2989 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 165:
 #line 545 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[0].exp); }
 #line 2995 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 166:
 #line 547 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_lt, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3001 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 167:
 #line 549 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_gt, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3007 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 168:
 #line 551 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_le, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3013 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 169:
 #line 553 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_ge, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3019 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 170:
 #line 557 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[0].exp); }
 #line 3025 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 171:
 #line 559 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_shift_left, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3031 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 172:
 #line 561 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_shift_right, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3037 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 173:
 #line 565 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[0].exp); }
 #line 3043 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 174:
 #line 567 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_plus, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3049 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 175:
 #line 569 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_minus, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3055 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 176:
 #line 573 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[0].exp); }
 #line 3061 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 177:
 #line 575 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_times, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3067 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 178:
 #line 577 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_divide, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3073 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 179:
 #line 579 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_percent, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3079 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 180:
 #line 583 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[0].exp); }
 #line 3085 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 181:
 #line 585 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Binary_Expression( (yyvsp[-2].exp), op_tilda, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3091 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 183:
 #line 591 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Cast_Expression( (yyvsp[0].type_decl), (yyvsp[-2].exp), get_pos(scanner)); }
 #line 3097 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 184:
 #line 596 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[0].exp); }
 #line 3103 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 185:
 #line 598 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_exp_from_unary( op_plusplus, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3109 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 186:
 #line 600 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_exp_from_unary( op_minusminus, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3115 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 187:
 #line 602 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_exp_from_unary( (yyvsp[-1].ival), (yyvsp[0].exp), get_pos(scanner)); }
 #line 3121 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 188:
 #line 604 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_exp_from_unary( op_typeof, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3127 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 189:
 #line 606 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_exp_from_unary( op_sizeof, (yyvsp[0].exp), get_pos(scanner)); }
 #line 3133 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 190:
 #line 608 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_exp_from_unary2(op_new, (yyvsp[0].type_decl), NULL, get_pos(scanner)); }
 #line 3139 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 191:
 #line 610 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_exp_from_unary2(op_new, (yyvsp[-1].type_decl), (yyvsp[0].array_sub), get_pos(scanner)); }
 #line 3145 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 192:
 #line 612 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_exp_from_unary3( op_spork, (yyvsp[0].stmt), get_pos(scanner)); }
 #line 3151 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 193:
 #line 616 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_plus; }
 #line 3157 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 194:
 #line 617 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_minus; }
 #line 3163 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 195:
 #line 618 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_tilda; }
 #line 3169 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 196:
 #line 619 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_exclamation; }
 #line 3175 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 197:
 #line 620 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_times; }
 #line 3181 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 198:
 #line 621 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.ival) = op_spork; }
 #line 3187 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 200:
 #line 627 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Exp_Dur( (yyvsp[-2].exp), (yyvsp[0].exp), get_pos(scanner)); }
 #line 3193 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 201:
 #line 631 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.type_list) = new_type_list(new_id_list((yyvsp[0].sval), get_pos(scanner)), NULL, get_pos(scanner)); }
 #line 3199 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 202:
 #line 632 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.type_list) = new_type_list(new_id_list((yyvsp[-2].sval), get_pos(scanner)), (yyvsp[0].type_list), get_pos(scanner)); }
 #line 3205 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 204:
 #line 638 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Array( (yyvsp[-1].exp), (yyvsp[0].array_sub), get_pos(scanner)); }
 #line 3211 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 205:
 #line 640 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Func_Call( (yyvsp[-2].exp), NULL, get_pos(scanner)); }
 #line 3217 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 206:
 #line 642 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Func_Call( (yyvsp[-3].exp), (yyvsp[-1].exp), get_pos(scanner)); }
 #line 3223 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 207:
 #line 644 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_exp_from_member_dot( (yyvsp[-2].exp), (yyvsp[0].sval), get_pos(scanner)); }
 #line 3229 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 208:
 #line 646 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Postfix_Expression( (yyvsp[-1].exp), op_plusplus, get_pos(scanner)); }
 #line 3235 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 209:
 #line 648 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Postfix_Expression( (yyvsp[-1].exp), op_minusminus, get_pos(scanner)); }
 #line 3241 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 210:
 #line 650 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Func_Call( (yyvsp[-3].exp), NULL, get_pos(scanner)); (yyval.exp)->d.exp_func->types = (yyvsp[-2].type_list); }
 #line 3247 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 211:
 #line 652 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Func_Call( (yyvsp[-4].exp), (yyvsp[-1].exp), get_pos(scanner)); (yyval.exp)->d.exp_func->types = (yyvsp[-3].type_list); }
 #line 3253 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 212:
 #line 655 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Primary_Expression_from_ID(     (yyvsp[0].sval), get_pos(scanner)); }
 #line 3259 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 213:
 #line 656 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Primary_Expression_from_int(    (yyvsp[0].ival), get_pos(scanner)); }
 #line 3265 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 214:
 #line 657 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Primary_Expression_from_float(  (yyvsp[0].fval), get_pos(scanner)); }
 #line 3271 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 215:
 #line 658 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Primary_Expression_from_string( (yyvsp[0].sval), get_pos(scanner)); }
 #line 3277 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 216:
 #line 659 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_exp_from_char(                  (yyvsp[0].sval), get_pos(scanner)); }
 #line 3283 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 217:
 #line 660 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_exp_from_array_lit(             (yyvsp[0].array_sub), get_pos(scanner)); }
 #line 3289 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 218:
 #line 661 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_exp_from_array_lit(           (yyvsp[0].array_sub), get_pos(scanner)); }
 #line 3295 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 219:
 #line 662 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_exp_from_complex(               (yyvsp[0].c_val), get_pos(scanner)); }
 #line 3301 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 220:
 #line 663 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_exp_from_polar(                 (yyvsp[0].polar), get_pos(scanner)); }
 #line 3307 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 221:
 #line 664 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_exp_from_vec(                   (yyvsp[0].vec), get_pos(scanner)); }
 #line 3313 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 222:
 #line 665 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Hack_Expression(                (yyvsp[-1].exp), get_pos(scanner)); }
 #line 3319 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 223:
 #line 666 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = (yyvsp[-1].exp); }
 #line 3325 "eval/parser.c" /* yacc.c:1646  */
     break;
   case 224:
 #line 667 "eval/gwion.y" /* yacc.c:1646  */
     { (yyval.exp) = new_Primary_Expression_from_nil(       get_pos(scanner)); }
 #line 3331 "eval/parser.c" /* yacc.c:1646  */
     break;
 #line 3335 "eval/parser.c" /* yacc.c:1646  */
       default: break;
     }
   /* User semantic actions sometimes alter yychar, and that requires
      that yytoken be updated with the new translation.  We take the
      approach of translating immediately before every use of yytoken.
      One alternative is translating here after every semantic action,
      but that translation would be missed if the semantic action invokes
      YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
      if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
      incorrect destructor might then be invoked immediately.  In the
      case of YYERROR or YYBACKUP, subsequent parser actions might lead
      to an incorrect destructor call or verbose syntax error message
      before the lookahead is translated.  */
   YY_SYMBOL_PRINT ("-> $$ =", yyr1[yyn], &yyval, &yyloc);
   YYPOPSTACK (yylen);
   yylen = 0;
   YY_STACK_PRINT (yyss, yyssp);
   *++yyvsp = yyval;
   /* Now 'shift' the result of the reduction.  Determine what state
      that goes to, based on the state we popped back to and the rule
      number reduced by.  */
   yyn = yyr1[yyn];
   yystate = yypgoto[yyn - YYNTOKENS] + *yyssp;
   if (0 <= yystate && yystate <= YYLAST && yycheck[yystate] == *yyssp)
     yystate = yytable[yystate];
   else
     yystate = yydefgoto[yyn - YYNTOKENS];
   goto yynewstate;
 /*--------------------------------------.
 | yyerrlab -- here on detecting error.  |
 `--------------------------------------*/
 yyerrlab:
   /* Make sure we have latest lookahead translation.  See comments at
      user semantic actions for why this is necessary.  */
   yytoken = yychar == YYEMPTY ? YYEMPTY : YYTRANSLATE (yychar);
   /* If not already recovering from an error, report this error.  */
   if (!yyerrstatus)
     {
       ++yynerrs;
 #if ! YYERROR_VERBOSE
       yyerror (arg, YY_("syntax error"));
 #else
 # define YYSYNTAX_ERROR yysyntax_error (&yymsg_alloc, &yymsg, \
                                         yyssp, yytoken)
       {
         char const *yymsgp = YY_("syntax error");
         int yysyntax_error_status;
         yysyntax_error_status = YYSYNTAX_ERROR;
         if (yysyntax_error_status == 0)
           yymsgp = yymsg;
         else if (yysyntax_error_status == 1)
           {
             if (yymsg != yymsgbuf)
               YYSTACK_FREE (yymsg);
             yymsg = (char *) YYSTACK_ALLOC (yymsg_alloc);
             if (!yymsg)
               {
                 yymsg = yymsgbuf;
                 yymsg_alloc = sizeof yymsgbuf;
                 yysyntax_error_status = 2;
               }
             else
               {
                 yysyntax_error_status = YYSYNTAX_ERROR;
                 yymsgp = yymsg;
               }
           }
         yyerror (arg, yymsgp);
         if (yysyntax_error_status == 2)
           goto yyexhaustedlab;
       }
 # undef YYSYNTAX_ERROR
 #endif
     }
   if (yyerrstatus == 3)
     {
       /* If just tried and failed to reuse lookahead token after an
          error, discard it.  */
       if (yychar <= YYEOF)
         {
           /* Return failure if at end of input.  */
           if (yychar == YYEOF)
             YYABORT;
         }
       else
         {
           yydestruct ("Error: discarding",
                       yytoken, &yylval, arg);
           yychar = YYEMPTY;
         }
     }
   /* Else will try to reuse lookahead token after shifting the error
      token.  */
   goto yyerrlab1;
 /*---------------------------------------------------.
 | yyerrorlab -- error raised explicitly by YYERROR.  |
 `---------------------------------------------------*/
 yyerrorlab:
   /* Pacify compilers like GCC when the user code never invokes
      YYERROR and the label yyerrorlab therefore never appears in user
      code.  */
   if (/*CONSTCOND*/ 0)
      goto yyerrorlab;
   /* Do not reclaim the symbols of the rule whose action triggered
      this YYERROR.  */
   YYPOPSTACK (yylen);
   yylen = 0;
   YY_STACK_PRINT (yyss, yyssp);
   yystate = *yyssp;
   goto yyerrlab1;
 /*-------------------------------------------------------------.
 | yyerrlab1 -- common code for both syntax error and YYERROR.  |
 `-------------------------------------------------------------*/
 yyerrlab1:
   yyerrstatus = 3;      /* Each real token shifted decrements this.  */
   for (;;)
     {
       yyn = yypact[yystate];
       if (!yypact_value_is_default (yyn))
         {
           yyn += YYTERROR;
           if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
             {
               yyn = yytable[yyn];
               if (0 < yyn)
                 break;
             }
         }
       /* Pop the current state because it cannot handle the error token.  */
       if (yyssp == yyss)
         YYABORT;
       yydestruct ("Error: popping",
                   yystos[yystate], yyvsp, arg);
       YYPOPSTACK (1);
       yystate = *yyssp;
       YY_STACK_PRINT (yyss, yyssp);
     }
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   *++yyvsp = yylval;
   YY_IGNORE_MAYBE_UNINITIALIZED_END
   /* Shift the error token.  */
   YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp);
   yystate = yyn;
   goto yynewstate;
 /*-------------------------------------.
 | yyacceptlab -- YYACCEPT comes here.  |
 `-------------------------------------*/
 yyacceptlab:
   yyresult = 0;
   goto yyreturn;
 /*-----------------------------------.
 | yyabortlab -- YYABORT comes here.  |
 `-----------------------------------*/
 yyabortlab:
   yyresult = 1;
   goto yyreturn;
 #if !defined yyoverflow || YYERROR_VERBOSE
 /*-------------------------------------------------.
 | yyexhaustedlab -- memory exhaustion comes here.  |
 `-------------------------------------------------*/
 yyexhaustedlab:
   yyerror (arg, YY_("memory exhausted"));
   yyresult = 2;
   /* Fall through.  */
 #endif
 yyreturn:
   if (yychar != YYEMPTY)
     {
       /* Make sure we have latest lookahead translation.  See comments at
          user semantic actions for why this is necessary.  */
       yytoken = YYTRANSLATE (yychar);
       yydestruct ("Cleanup: discarding lookahead",
                   yytoken, &yylval, arg);
     }
   /* Do not reclaim the symbols of the rule whose action triggered
      this YYABORT or YYACCEPT.  */
   YYPOPSTACK (yylen);
   YY_STACK_PRINT (yyss, yyssp);
   while (yyssp != yyss)
     {
       yydestruct ("Cleanup: popping",
                   yystos[*yyssp], yyvsp, arg);
       YYPOPSTACK (1);
     }
 #ifndef yyoverflow
   if (yyss != yyssa)
     YYSTACK_FREE (yyss);
 #endif
 #if YYERROR_VERBOSE
   if (yymsg != yymsgbuf)
     YYSTACK_FREE (yymsg);
 #endif
   return yyresult;
 }
yystpcpy()
static char* yystpcpy (char * yydest, const char * yysrc) static
Definition at line 1604 of file parser.c.
References YYSIZE_T.
Referenced by yytnamerr().
 {
   char *yyd = yydest;
   const char *yys = yysrc;
   while ((*yyd++ = *yys++) != '\0')
     continue;
   return yyd - 1;
 }
yystrlen()
static YYSIZE_T yystrlen (const char * yystr) static
Definition at line 1587 of file parser.c.
References YYSIZE_T.
Referenced by yysyntax_error(), and yytnamerr().
 {
   YYSIZE_T yylen;
   for (yylen = 0; yystr[yylen]; yylen++)
     continue;
   return yylen;
 }
yysyntax_error()
static int yysyntax_error (YYSIZE_T * yymsg_alloc, char ** yymsg, yytype_int16 * yyssp, int yytoken) static
Definition at line 1674 of file parser.c.
References YY_, YY_NULLPTR, YYCASE_, yycheck, YYEMPTY, YYLAST, YYNTOKENS, yypact, yypact_value_is_default, YYSIZE_T, YYSTACK_ALLOC_MAXIMUM, yystrlen(), yytable, yytable_value_is_error, YYTERROR, yytname, and yytnamerr().
 {
   YYSIZE_T yysize0 = yytnamerr (YY_NULLPTR, yytname[yytoken]);
   YYSIZE_T yysize = yysize0;
   enum { YYERROR_VERBOSE_ARGS_MAXIMUM = 5 };
   /* Internationalized format string. */
   const char *yyformat = YY_NULLPTR;
   /* Arguments of yyformat. */
   char const *yyarg[YYERROR_VERBOSE_ARGS_MAXIMUM];
   /* Number of reported tokens (one for the "unexpected", one per
      "expected"). */
   int yycount = 0;
   /* There are many possibilities here to consider:
      - If this state is a consistent state with a default action, then
        the only way this function was invoked is if the default action
        is an error action.  In that case, don't check for expected
        tokens because there are none.
      - The only way there can be no lookahead present (in yychar) is if
        this state is a consistent state with a default action.  Thus,
        detecting the absence of a lookahead is sufficient to determine
        that there is no unexpected or expected token to report.  In that
        case, just report a simple "syntax error".
      - Don't assume there isn't a lookahead just because this state is a
        consistent state with a default action.  There might have been a
        previous inconsistent state, consistent state with a non-default
        action, or user semantic action that manipulated yychar.
      - Of course, the expected token list depends on states to have
        correct lookahead information, and it depends on the parser not
        to perform extra reductions after fetching a lookahead from the
        scanner and before detecting a syntax error.  Thus, state merging
        (from LALR or IELR) and default reductions corrupt the expected
        token list.  However, the list is correct for canonical LR with
        one exception: it will still contain any token that will not be
        accepted due to an error action in a later state.
   */
   if (yytoken != YYEMPTY)
     {
       int yyn = yypact[*yyssp];
       yyarg[yycount++] = yytname[yytoken];
       if (!yypact_value_is_default (yyn))
         {
           /* Start YYX at -YYN if negative to avoid negative indexes in
              YYCHECK.  In other words, skip the first -YYN actions for
              this state because they are default actions.  */
           int yyxbegin = yyn < 0 ? -yyn : 0;
           /* Stay within bounds of both yycheck and yytname.  */
           int yychecklim = YYLAST - yyn + 1;
           int yyxend = yychecklim < YYNTOKENS ? yychecklim : YYNTOKENS;
           int yyx;
           for (yyx = yyxbegin; yyx < yyxend; ++yyx)
             if (yycheck[yyx + yyn] == yyx && yyx != YYTERROR
                 && !yytable_value_is_error (yytable[yyx + yyn]))
               {
                 if (yycount == YYERROR_VERBOSE_ARGS_MAXIMUM)
                   {
                     yycount = 1;
                     yysize = yysize0;
                     break;
                   }
                 yyarg[yycount++] = yytname[yyx];
                 {
                   YYSIZE_T yysize1 = yysize + yytnamerr (YY_NULLPTR, yytname[yyx]);
                   if (! (yysize <= yysize1
                          && yysize1 <= YYSTACK_ALLOC_MAXIMUM))
                     return 2;
                   yysize = yysize1;
                 }
               }
         }
     }
   switch (yycount)
     {
 # define YYCASE_(N, S)                      \
       case N:                               \
         yyformat = S;                       \
       break
       YYCASE_(0, YY_("syntax error"));
       YYCASE_(1, YY_("syntax error, unexpected %s"));
       YYCASE_(2, YY_("syntax error, unexpected %s, expecting %s"));
       YYCASE_(3, YY_("syntax error, unexpected %s, expecting %s or %s"));
       YYCASE_(4, YY_("syntax error, unexpected %s, expecting %s or %s or %s"));
       YYCASE_(5, YY_("syntax error, unexpected %s, expecting %s or %s or %s or %s"));
 # undef YYCASE_
     }
   {
     YYSIZE_T yysize1 = yysize + yystrlen (yyformat);
     if (! (yysize <= yysize1 && yysize1 <= YYSTACK_ALLOC_MAXIMUM))
       return 2;
     yysize = yysize1;
   }
   if (*yymsg_alloc < yysize)
     {
       *yymsg_alloc = 2 * yysize;
       if (! (yysize <= *yymsg_alloc
              && *yymsg_alloc <= YYSTACK_ALLOC_MAXIMUM))
         *yymsg_alloc = YYSTACK_ALLOC_MAXIMUM;
       return 1;
     }
   /* Avoid sprintf, as that infringes on the user's name space.
      Don't have undefined behavior even if the translation
      produced a string with the wrong number of "%s"s.  */
   {
     char *yyp = *yymsg;
     int yyi = 0;
     while ((*yyp = *yyformat) != '\0')
       if (*yyp == '%' && yyformat[1] == 's' && yyi < yycount)
         {
           yyp += yytnamerr (yyp, yyarg[yyi++]);
           yyformat += 2;
         }
       else
         {
           yyp++;
           yyformat++;
         }
   }
   return 0;
 }
yytnamerr()
static YYSIZE_T yytnamerr (char * yyres, const char * yystr) static
Definition at line 1626 of file parser.c.
References YYSIZE_T, yystpcpy(), and yystrlen().
Referenced by yysyntax_error().
 {
   if (*yystr == '"')
     {
       YYSIZE_T yyn = 0;
       char const *yyp = yystr;
       for (;;)
         switch (*++yyp)
           {
           case '\'':
           case ',':
             goto do_not_strip_quotes;
           case '\\':
             if (*++yyp != '\\')
               goto do_not_strip_quotes;
             /* Fall through.  */
           default:
             if (yyres)
               yyres[yyn] = *yyp;
             yyn++;
             break;
           case '"':
             if (yyres)
               yyres[yyn] = '\0';
             return yyn;
           }
     do_not_strip_quotes: ;
     }
   if (! yyres)
     return yystrlen (yystr);
   return yystpcpy (yyres, yystr) - yyres;
 }
Variable Documentation
yycheck
const yytype_int16 yycheck[] static
Definition at line 1125 of file parser.c.
Referenced by yyparse(), and yysyntax_error().
yydefact
const yytype_uint8 yydefact[] static
Definition at line 886 of file parser.c.
Referenced by yyparse().
yydefgoto
const yytype_int16 yydefgoto[] static
Initial value:
=
{
      -1,    51,    52,   360,   328,    54,   361,   362,   363,   246,
     141,   364,   155,    56,    57,   266,   353,    58,    59,    60,
      61,    62,    63,    64,    65,    66,    67,    68,    69,   191,
      70,    71,   225,   188,    72,    73,    74,   365,    76,   263,
      77,   194,   195,    78,    79,    80,    81,    82,    83,    84,
      85,    86,    87,    88,    89,    90,    91,    92,    93,    94,
      95,    96,   301,    97,    98
}
Definition at line 945 of file parser.c.
Referenced by yyparse().
yypact
const yytype_int16 yypact[] static
Definition at line 837 of file parser.c.
Referenced by yyparse(), and yysyntax_error().
yypgoto
const yytype_int16 yypgoto[] static
Initial value:
=
{
    -229,   250,  -229,    26,  -229,  -229,   -54,   -49,  -229,  -134,
    -209,   131,   -41,    -5,  -229,   -67,  -228,  -127,   -14,  -229,
    -229,  -229,  -229,  -229,  -229,  -229,  -229,  -105,    -1,  -229,
    -229,   130,  -229,  -229,   -87,  -165,  -137,    37,    -9,  -151,
    -229,  -100,   -35,  -229,  -229,  -229,    -3,  -229,   132,   136,
     129,   137,   139,   -27,  -123,   -29,   -22,  -109,   105,   117,
    -229,  -229,    -2,   -13,   300
}
Definition at line 933 of file parser.c.
Referenced by yyparse().
yyr1
const yytype_uint8 yyr1[] static
Initial value:
=
{
       0,   117,   118,   118,   119,   119,   119,   120,   120,   121,
     122,   122,   122,   123,   123,   124,   124,   125,   125,   125,
     126,   126,   127,   127,   128,   128,   129,   129,   129,   130,
     130,   131,   131,   131,   131,   132,   132,   133,   133,   134,
     134,   135,   135,   135,   135,   135,   135,   135,   135,   135,
     135,   135,   135,   136,   136,   137,   138,   139,   139,   140,
     141,   141,   141,   141,   141,   141,   141,   142,   142,   143,
     143,   143,   143,   144,   144,   144,   145,   145,   146,   146,
     147,   147,   148,   148,   149,   150,   150,   150,   150,   150,
     150,   150,   150,   150,   150,   150,   150,   150,   150,   150,
     150,   150,   150,   150,   150,   150,   150,   150,   150,   150,
     150,   150,   150,   150,   151,   151,   152,   152,   153,   153,
     153,   153,   153,   153,   153,   154,   154,   154,   154,   154,
     154,   154,   154,   155,   155,   155,   155,   156,   156,   156,
     156,   157,   158,   158,   159,   159,   159,   160,   161,   162,
     163,   163,   164,   164,   165,   165,   166,   166,   167,   167,
     168,   168,   169,   169,   169,   170,   170,   170,   170,   170,
     171,   171,   171,   172,   172,   172,   173,   173,   173,   173,
     174,   174,   175,   175,   176,   176,   176,   176,   176,   176,
     176,   176,   176,   177,   177,   177,   177,   177,   177,   178,
     178,   179,   179,   180,   180,   180,   180,   180,   180,   180,
     180,   180,   181,   181,   181,   181,   181,   181,   181,   181,
     181,   181,   181,   181,   181
}
Definition at line 1340 of file parser.c.
Referenced by yyparse().
yyr2
const yytype_uint8 yyr2[] static
Initial value:
=
{
       0,     2,     1,     2,     1,     1,     1,     6,     7,     2,
       1,     1,     0,     1,     0,     1,     2,     1,     1,     1,
       1,     3,     1,     3,     1,     2,     1,     1,     0,     1,
       1,     7,     8,     8,     9,     1,     2,     2,     4,     2,
       3,     1,     1,     1,     1,     1,     1,     1,     1,     1,
       1,     1,     1,     5,     6,     2,     3,     3,     3,     5,
       5,     7,     6,     7,     5,     7,     5,     5,     7,     2,
       3,     2,     2,     2,     1,     1,     1,     3,     1,     1,
       1,     3,     1,     3,     3,     1,     1,     1,     1,     1,
       1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
       1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
       1,     1,     1,     1,     3,     4,     2,     3,     1,     2,
       3,     3,     4,     3,     4,     7,     7,     8,     4,     6,
       7,    11,    12,     1,     2,     3,     4,     2,     3,     2,
       3,     5,     1,     3,     1,     2,     2,     3,     3,     3,
       1,     5,     1,     3,     1,     3,     1,     3,     1,     3,
       1,     3,     1,     3,     3,     1,     3,     3,     3,     3,
       1,     3,     3,     1,     3,     3,     1,     3,     3,     3,
       1,     3,     1,     3,     1,     2,     2,     2,     2,     2,
       2,     3,     3,     1,     1,     1,     1,     1,     2,     1,
       3,     1,     3,     1,     2,     3,     4,     3,     2,     2,
       4,     5,     1,     1,     1,     1,     1,     1,     1,     1,
       1,     1,     3,     3,     2
}
Definition at line 1368 of file parser.c.
Referenced by yyparse().
yystos
const yytype_uint8 yystos[] static
Definition at line 1293 of file parser.c.
Referenced by yyparse().
yytable
const yytype_int16 yytable[] static
Definition at line 959 of file parser.c.
Referenced by yyparse(), and yysyntax_error().
yytname
const char* const yytname[] static
Definition at line 768 of file parser.c.
Referenced by yysyntax_error().
yytranslate
const yytype_uint8 yytranslate[] static
Definition at line 693 of file parser.c.