Gwion dev-docs: drvr/portaudio.c File Reference
portaudio.c File Reference
#include <portaudio.h>
#include "err_msg.h"
#include "vm.h"
#include "bbq.h"
#include "oo.h"
#include "type.h"
#include "dl.h"
#include "ugen.h"
#include "driver.h"
Macros
#define SAMPLE_RATE (48000)
#define FRAMES_PER_BUFFER (64)
Functions
static int callback (const void *inputBuffer, void *outputBuffer, unsigned long framesPerBuffer, const PaStreamCallbackTimeInfo *timeInfo, PaStreamCallbackFlags statusFlags, void *userData)
static m_bool ini (VM *vm, DriverInfo *di)
static void del (VM *vm)
static void run (VM *vm, DriverInfo *di)
Driver * pa_driver (VM *vm)
Variables
static m_uint bufsize
static PaStream * stream = NULL
static PaStreamParameters outputParameters
static PaStreamParameters inputParameters
Macro Definition Documentation
FRAMES_PER_BUFFER
#define FRAMES_PER_BUFFER (64)
Definition at line 12 of file portaudio.c.
SAMPLE_RATE
#define SAMPLE_RATE (48000)
Definition at line 11 of file portaudio.c.
Function Documentation
callback()
static int callback (const void * inputBuffer, void * outputBuffer, unsigned long framesPerBuffer, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags, void * userData) static
Definition at line 19 of file portaudio.c.
References VM::bbq, BBQ_::in, in, BBQ_::n_in, out, BBQ_::sp, vm, and vm_run().
Referenced by ini().
 {
   VM* vm = (VM*)userData;
   float *in  = (float*)inputBuffer;
   float *out = (float*)outputBuffer;
   m_bool i, j;
   for(i = 0; i < framesPerBuffer; i++) {
     for(j = 0; j < vm->bbq->n_in; j++)
       vm->bbq->in[j] = *in++;
     vm_run(vm);
     for(j = 0; j < vm->bbq->sp->nchan; j++)
       *out++ = vm->bbq->sp->out[j];
     vm->bbq->sp->pos++;
   }
   return paContinue;
 }
del()
static void del (VM * vm) static
Definition at line 102 of file portaudio.c.
References stream.
Referenced by pa_driver().
 {
   Pa_StopStream(stream);
   Pa_Terminate();
 }
ini()
static m_bool ini (VM * vm, DriverInfo * di) static
Definition at line 38 of file portaudio.c.
References containing_driver_info::bufsize, bufsize, callback(), containing_driver_info::format, inputParameters, outputParameters, containing_driver_info::sr, and stream.
Referenced by pa_driver().
 {
   if(Pa_Initialize() != paNoError)
     return -1;
   outputParameters.device = Pa_GetDefaultOutputDevice(); /* default output device */
   if (outputParameters.device == paNoDevice) {
     fprintf(stderr, "Error: No default output device.\n");
     goto error;
   }
   bufsize = di->bufsize;
   outputParameters.channelCount = 2;
   outputParameters.sampleFormat = di->format;
   outputParameters.suggestedLatency = Pa_GetDeviceInfo( outputParameters.device )->defaultLowOutputLatency;
   outputParameters.hostApiSpecificStreamInfo = NULL;
   inputParameters.device = Pa_GetDefaultInputDevice(); /* default output device */
   if (inputParameters.device == paNoDevice) {
     fprintf(stderr, "Error: No default input device.\n");
     goto error;
   }
   inputParameters.channelCount = 2;
   inputParameters.sampleFormat = paFloat32;
   inputParameters.suggestedLatency = Pa_GetDeviceInfo( inputParameters.device )->defaultLowOutputLatency;
   inputParameters.hostApiSpecificStreamInfo = NULL;
   if(Pa_OpenStream(
         &stream,
         &inputParameters,
         &outputParameters,
         di->sr,
         di->bufsize,
         paClipOff,
         callback,
         vm ) != paNoError)
     goto error;
   /*
   if(Pa_OpenDefaultStream(&stream,
                                   2,2,
                                   paFloat32,
                                   SAMPLE_RATE,
                                   paFramesPerBufferUnspecified,
   //                                256,
                                   callback,
                                   vm ) != paNoError)
   exit(3);
   */
 //      return -1;
   //return -1;
 //Pa_SetStreamFinishedCallback( stream, NULL);
 //Pa_SetStreamFinishedCallback( stream, &StreamFinished );
 //  di->out =2;
 //  di->in =2;
 //  vm->bbq->in = malloc(sizeof(m_float) * 2);
   printf("end of port audio\n");
   return 1;
 error:
   Pa_Terminate();
   return -1;
 }
pa_driver()
Driver* pa_driver (VM * vm)
Definition at line 115 of file portaudio.c.
References driver_wrapper::del, del(), driver_wrapper::ini, ini(), malloc(), no_wakeup(), driver_wrapper::run, run(), and VM::wakeup.
Referenced by no_wakeup(), select_driver(), and select_format().
 {
   Driver* d = malloc(sizeof(Driver));
   d->ini = ini;
   d->run = run;
   d->del = del;
   vm->wakeup = no_wakeup;
   return d;
 }
run()
static void run (VM * vm, DriverInfo * di) static
Definition at line 108 of file portaudio.c.
References VM::is_running, and stream.
Referenced by pa_driver().
 {
   Pa_StartStream(stream);
   while(vm->is_running)
     Pa_Sleep(1);
 }
Variable Documentation
bufsize
m_uint bufsize static
Definition at line 14 of file portaudio.c.
Referenced by ini().
inputParameters
PaStreamParameters inputParameters static
Definition at line 17 of file portaudio.c.
Referenced by ini().
outputParameters
PaStreamParameters outputParameters static
Definition at line 16 of file portaudio.c.
Referenced by ini().
stream
PaStream* stream = NULL static
Definition at line 15 of file portaudio.c.
Referenced by del(), ini(), and run().