Gwion dev-docs: driver_wrapper Struct Reference
--- layout: default title: structdriver__wrapper/ image: feature: abstract-1.jpg ---
driver_wrapper Struct Reference
#include <driver.h>
Data Fields
m_bool(* ini)(VM *vm, DriverInfo *info)
void(* run)(VM *vm, DriverInfo *info)
void(* del)(VM *vm)
Detailed Description
Definition at line 17 of file driver.h.
Field Documentation
del
void(* driver_wrapper::del) (VM *vm)
Definition at line 20 of file driver.h.
Referenced by alsa_driver(), dummy_driver(), free_Driver(), jack_driver(), pa_driver(), raw_driver(), silent_driver(), sio_driver(), and sndfile_driver().
ini
m_bool(* driver_wrapper::ini) (VM *vm, DriverInfo *info)
Definition at line 18 of file driver.h.
Referenced by alsa_driver(), dummy_driver(), jack_driver(), new_BBQ(), pa_driver(), raw_driver(), silent_driver(), sio_driver(), and sndfile_driver().
run
void(* driver_wrapper::run) (VM *vm, DriverInfo *info)
Definition at line 19 of file driver.h.
Referenced by alsa_driver(), dummy_driver(), jack_driver(), main(), pa_driver(), raw_driver(), silent_driver(), sio_driver(), and sndfile_driver().
The documentation for this struct was generated from the following file:
include/driver.h