Gwion dev-docs: include/symbol.h File Reference
--- layout: homepage title: symbol_8h/ image: feature: abstract-1.jpg ---
symbol.h File Reference
Typedefs
typedef const char * c_constr
typedef char * c_str
typedef struct S_Symbol_ * S_Symbol
Functions
S_Symbol insert_symbol (c_constr)
c_str S_name (S_Symbol)
void free_Symbols ()
Typedef Documentation
c_constr
typedef const char* c_constr
Definition at line 43 of file symbol.h.
c_str
typedef char* c_str
Definition at line 44 of file symbol.h.
S_Symbol
typedef struct S_Symbol_* S_Symbol
Definition at line 46 of file symbol.h.
Function Documentation
free_Symbols()
void free_Symbols ()
Definition at line 63 of file symbol.c.
References free_Symbol(), S_Symbol_::next, and SIZE.
Referenced by main().
 {
   int i;
   for(i = 0; i < SIZE; i++) {
     S_Symbol s = hashtable[i];
     if(s) {
       S_Symbol tmp, next = s;
       while(next) {
         tmp = next;
         next = next->next;
         free_Symbol(tmp);
       }
     }
   }
 }
insert_symbol()
S_Symbol insert_symbol (c_constr)
Definition at line 94 of file symbol.c.
References hash(), mksymbol(), S_Symbol_::next, SIZE, and streq().
Referenced by add_global_type(), add_global_value(), add_global_value_double(), alloc_str(), check_Cast_Expression(), check_Func_Def(), check_op(), compile(), emit_Func_Call1(), emit_Primary_Expression(), find_context(), find_template_match(), free_Section(), INSTR(), MFUN(), new_exp_from_member_dot(), new_Func_Def(), new_Func_Ptr_Stmt(), new_id_list(), new_Primary_Expression_from_ID(), new_stmt_from_enum(), new_stmt_from_gotolabel(), new_String(), new_Var_Decl(), S_name(), scan0_Class_Def(), scan2_Func_Call(), scan2_Func_Def(), str2list(), type_engine_check_prog(), and type_engine_init().
 {
   S_Symbol syms = NULL, sym;
   int index;
   if(!name)
     return NULL;
   index = hash(name) % SIZE;
   syms = hashtable[index];
   for(sym = syms; sym; sym = sym->next)
     if (streq(sym->name, name))
       return sym;
   sym = mksymbol(name, syms);
   hashtable[index] = sym;
   return sym;
 }
S_name()
c_str S_name (S_Symbol)
Definition at line 110 of file symbol.c.
References insert_symbol(), and S_Symbol_::name.
Referenced by alloc_str(), check_Cast_Expression(), check_Class_Def(), check_Decl_Expression(), check_Dot_Member(), check_Func_Call1(), check_Func_Def(), check_Func_Ptr(), check_Goto_Label(), check_op(), check_Primary_Expression(), compile(), emit_Dot_Member(), emit_Func_Call1(), emit_Func_Def(), emit_Goto_Label(), emit_symbol(), find_template_match(), find_type(), INSTR(), isres(), MFUN(), mkdoc_func(), new_String(), operator_set_func(), scan0_Class_Def(), scan0_Func_Ptr(), scan1_Decl_Expression(), scan1_Enum(), scan1_Func_Def(), scan1_Func_Ptr(), scan1_Stmt(), scan2_Decl_Expression(), scan2_Func_Call(), scan2_Func_Def(), scan2_Func_Ptr(), scan2_Goto_Label(), scan2_Stmt_Enum(), and type_path().
 {
   return sym->name;
 }