Gwion dev-docs: core/type.c File Reference
--- layout: default title: type_8c/ image: feature: abstract-1.jpg ---
type.c File Reference
#include <stdio.h>
#include <dlfcn.h>
#include <dirent.h>
#include <inttypes.h>
#include "err_msg.h"
#include "type.h"
#include "absyn.h"
#include "env.h"
#include "context.h"
#include "func.h"
#include "import.h"
#include "lang.h"
#include "ugen.h"
#include "object.h"
#include "string.h"
#include "bbq.h"
Functions
m_bool scan0_Ast (Env, Ast)
m_bool scan1_Ast (Env, Ast)
m_bool scan2_Ast (Env, Ast)
m_bool check_Func_Def (Env env, Func_Def f)
static Type check_Expression (Env env, Expression exp)
static m_bool check_Stmt (Env env, Stmt *stmt)
static Type check_Dot_Member (Env env, Dot_Member *member)
static m_bool check_Stmt_List (Env env, Stmt_List list)
Type check_Func_Call1 (Env env, Expression exp_func, Expression args, Func *m_func, int pos)
static Type check_Func_Call (Env env, Func_Call *exp_func)
static m_bool check_Class_Def (Env env, Class_Def class_def)
Func find_func_match (Func up, Expression args)
static int so_filter (const struct dirent *dir)
m_bool import_soundpipe (Env env)
void start_plug ()
void stop_plug ()
Env type_engine_init (VM *vm)
m_bool check_Context (Env env, Context context)
m_bool type_engine_check_prog (Env env, Ast ast, m_str filename)
static m_bool check_array_subscripts (Env env, Expression exp_list)
Type check_Decl_Expression (Env env, Decl_Expression *decl)
static Type check_array_lit (Env env, Primary_Expression *exp)
static Type check_Vec (Env env, Primary_Expression *exp)
static Type check_Primary_Expression (Env env, Primary_Expression *primary)
Type check_Array (Env env, Array *array)
m_bool compat_func (Func_Def lhs, Func_Def rhs, int pos)
static Type check_op (Env env, Operator op, Expression lhs, Expression rhs, Binary_Expression *binary)
static Type check_Binary_Expression (Env env, Binary_Expression *binary)
static Type check_Cast_Expression (Env env, Cast_Expression *cast)
static Type check_Postfix_Expression (Env env, Postfix_Expression *postfix)
static Type check_Dur (Env env, Exp_Dur *dur)
static Func find_func_match_actual (Func up, Expression args, m_bool implicit, m_bool specific)
static Type_List mk_type_list (Env env, Type type)
Func find_template_match (Env env, Value v, Func m_func, Type_List types, Expression func, Expression args)
static m_bool check_Func_Ptr (Env env, Func_Ptr *ptr)
static Type check_Unary (Env env, Unary_Expression *exp_unary)
check exp_unary expression
static Type check_exp_if (Env env, If_Expression *exp_if)
static m_bool check_Enum (Env env, Stmt_Enum stmt)
static m_bool check_Stmt_Code (Env env, Stmt_Code stmt, m_bool push)
static m_bool check_While (Env env, Stmt_While stmt)
static m_bool check_Until (Env env, Stmt_Until stmt)
static m_bool check_For (Env env, Stmt_For stmt)
static m_bool check_Loop (Env env, Stmt_Loop stmt)
static m_bool check_If (Env env, Stmt_If stmt)
static m_bool check_Return (Env env, Stmt_Return stmt)
static m_bool check_Continue (Env env, Stmt_Continue cont)
static m_bool check_Break (Env env, Stmt_Break cont)
static m_bool check_Switch (Env env, Stmt_Switch a)
static m_bool check_Case (Env env, Stmt_Case stmt)
static m_bool check_Goto_Label (Env env, Stmt_Goto_Label stmt)
Variables
struct Type_ t_void = { "void", 0, NULL, te_void}
struct Type_ t_function = { "@function", sizeof(m_uint), NULL, te_function }
struct Type_ t_func_ptr = { "@func_ptr", sizeof(m_uint), &t_function, te_func_ptr}
struct Type_ t_class = { "@Class", SZ_INT, NULL, te_class }
static Vector plugs = NULL
static Func_Call * current
Function Documentation
check_Array()
Type check_Array (Env env, Array * array)
Definition at line 721 of file type.c.
References Type_::array_depth, Type_::array_type, Array::base, CHECK_BO, check_Expression(), CHECK_OO, compat_func(), Array_Sub_::depth, err_msg(), Array_Sub_::exp_list, free(), Array::indices, isa(), Type_::name, Expression_::next, Type_::obj, Array::pos, Expression_::pos, t_int, Expression_::type, TYPE_, type_copy(), and verify_array().
Referenced by check_Expression().
 {
   Type t_base, t;
   m_uint depth;
   // verify there are no errors from the parser...
   CHECK_BO(verify_array(array->indices))
   t_base = check_Expression(env, array->base);
   CHECK_OO(t_base)
   if(array->indices->depth > t_base->array_depth) {
     err_msg(TYPE_,  array->pos,
             "array subscripts (%i) exceeds defined dimension (%i)",
             array->indices->depth, t_base->array_depth );
     free(t_base->obj);
     free(t_base);
     return NULL;
   }
   CHECK_OO(check_Expression(env, array->indices->exp_list))
   Expression e = array->indices->exp_list;
   depth = 0;
   while(e) {
     depth++;
     /*    if(isa( e->type, &t_int ) < 0 && isa( e->type, &t_string ) < 0)*/
     if(isa(e->type, &t_int) < 0) {
       err_msg(TYPE_,  e->pos,
               /*        "array index %i must be of type 'int' or 'string', not '%s'",*/
               "array index %i must be of type 'int', not '%s'",
               depth, e->type->name);
     free(t_base->obj);
     free(t_base);
       return NULL;
     }
     e = e->next;
   }
   t = NULL;
   if(depth == t_base->array_depth)
     t = array->base->type->array_type;
   else {
     t = type_copy(env, array->base->type);
     t->array_depth -= depth;
   }
   return t;
 }
check_array_lit()
static Type check_array_lit (Env env, Primary_Expression * exp) static
Definition at line 467 of file type.c.
References Primary_Expression::array, Type_::array_depth, Expression_::cast_to, check_Expression(), CHECK_OO, Env_::curr, Primary_Expression::d, err_msg(), Array_Sub_::exp_list, find_common_anc(), isa(), new_array_type(), Expression_::next, Primary_Expression::pos, Expression_::pos, t_array, t_float, t_int, Array_Sub_::type, Expression_::type, TYPE_, and verify_array().
Referenced by check_Primary_Expression().
 {
   Type t = NULL, type = NULL, common = NULL;
   if(verify_array(exp->d.array) < 0)
     return NULL;
   Expression e = exp->d.array->exp_list;
   // can't be []
   if(!e) {
     err_msg(TYPE_, exp->pos, "must provide values/expressions for array [...]" );
     return NULL;
   }
   // go through the array and type check each
   CHECK_OO(check_Expression(env, e))
   // loop
   while( e ) {
     // get the type
     t = e->type;
     // compare
     if(!type) {
       // first
       type = t;
     } else {
       // find common ancestor
       common = find_common_anc(t, type);
       // update type
       if(common) type = common;
       // no common
       else {
         // maybe one is int and other is float
         if(isa(t, &t_int) > 0 && isa(type, &t_float) > 0) {
           // cast from int to float
           e->cast_to = type;
         } else {
           // incompatible
           err_msg(TYPE_, e->pos, "array init [...] contains incompatible types..." );
           return NULL;
         }
       }
     }
     e = e->next;
   }
   t = new_array_type(
         env,  // the env
         &t_array,  // the array base class, usually &t_array
         /*    T_array,  // the array base class, usually &t_array*/
         type->array_depth + 1,  // the depth of the new type
         type->array_depth ? type->array_type : type,  // the 'array_type'
         env->curr  // the owner namespace
       );
   exp->d.array->type = t;
   return t;
 }
check_array_subscripts()
static m_bool check_array_subscripts (Env env, Expression exp_list) static
Definition at line 279 of file type.c.
References err_msg(), isa(), Type_::name, Expression_::next, Expression_::pos, t_int, Expression_::type, and TYPE_.
Referenced by check_Decl_Expression(), and check_Unary().
 {
   Expression exp = exp_list;
   while(exp) {
     if(isa(exp->type, &t_int) < 0) {
       err_msg(TYPE_, exp->pos,
               "incompatible array subscript type '%s'...", exp->type->name);
       return -1;
     }
     exp = exp->next;
   }
   return 1;
 }
check_Binary_Expression()
static Type check_Binary_Expression (Env env, Binary_Expression * binary) static
Definition at line 879 of file type.c.
References ae_meta_var, check_Expression(), CHECK_OO, check_op(), Expression_::emit_var, err_msg(), isa(), Binary_Expression::lhs, Expression_::meta, Type_::name, Binary_Expression::op, op2str(), op_assign, op_at_chuck, op_chuck, op_divide_chuck, op_minus_chuck, op_modulo_chuck, op_plus_chuck, op_rand, op_req, op_rge, op_rgt, op_rle, op_rlt, op_rneq, op_ror, op_rsand, op_rsl, op_rsor, op_rsr, op_rsxor, op_times_chuck, Expression_::pos, Binary_Expression::rhs, t_object, t_string, t_ugen, Expression_::type, and TYPE_.
Referenced by check_Expression().
 {
 #ifdef DEBUG_TYPE
   debug_msg("check", "binary expression '%p' '%p'", binary->lhs, binary->rhs);
 #endif
   Type ret = NULL;
   Expression cl = binary->lhs, cr = binary->rhs;
   CHECK_OO(check_Expression(env, cl))
   CHECK_OO(check_Expression(env, cr))
   switch(binary->op) {
   case op_assign:
     if(cl->meta != ae_meta_var) {
       err_msg(TYPE_, cr->pos,
               "cannot assign '%s' on types '%s' and'%s'...",
               op2str(binary->op), cl->type->name, cr->type->name);
       err_msg(TYPE_, cr->pos,
               "...(reason: --- left-side operand is not mutable)" );
       return NULL;
     }
     // mark to emit var instead of value
     cl->emit_var = 1;
     break;
   case op_at_chuck:
     if(isa(cl->type, &t_object) > 0 && isa(cr->type, &t_object) > 0) {
       /*      cr->emit_var = cl->emit_var = 1;*/
       cr->emit_var = 1;
       break;
     }
   case op_chuck:
     if(isa(cl->type, &t_ugen) > 0 && isa(cr->type, &t_ugen) > 0) {
       cr->emit_var = cl->emit_var = 0;
       break;
     }
     if(isa(cl->type, &t_string) > 0 && isa(cr->type, &t_string) > 0) {
       cr->emit_var = cl->emit_var = 0;
       break;
     }
   case op_plus_chuck:
   case op_minus_chuck:
   case op_times_chuck:
   case op_divide_chuck:
   case op_modulo_chuck:
   case op_rsand:
   case op_rsor:
   case op_rsxor:
   case op_rsl:
   case op_rsr:
   case op_rand:
   case op_ror:
   case op_req:
   case op_rneq:
   case op_rgt:
   case op_rge:
   case op_rlt:
   case op_rle:
     // make sure mutable
     if(cr->meta != ae_meta_var) {
       err_msg(TYPE_, cl->pos,
               "cannot assign '%s' on types '%s' and'%s'...",
               op2str(binary->op), cl->type->name, cr->type->name);
       err_msg(TYPE_, cl->pos,
               "...(reason: --- right-side operand is not mutable)" );
       return NULL;
     }
     // mark to emit var instead of value
     cr->emit_var = 1;
     break;
   default:
     break;
   }
   if(binary->op == op_at_chuck) {
     if(isa(binary->lhs->type, &t_void) > 0 && isa(binary->rhs->type, &t_object) > 0)
       return cl->type;
   }
   while(cr) {
     CHECK_OO((ret = check_op(env, binary->op, cl, cr, binary)))
     cr = cr->next;
   }
   return ret;
 }
check_Break()
static m_bool check_Break (Env env, Stmt_Break cont) static
Definition at line 1974 of file type.c.
References Env_::breaks, err_msg(), Stmt_Break_::pos, TYPE_, and vector_size().
Referenced by check_Stmt().
 {
   if(!vector_size(env->breaks)) {
     err_msg(TYPE_,  cont->pos,
             "'break' found outside of for/while/until..." );
     return -1;
   }
   return 1;
 }
check_Case()
static m_bool check_Case (Env env, Stmt_Case stmt) static
Definition at line 1999 of file type.c.
References check_Expression(), err_msg(), Type_::name, Stmt_Case_::pos, t_int, TYPE_, Stmt_Case_::val, and Type_::xid.
Referenced by check_Stmt().
 {
   Type t = check_Expression(env, stmt->val);
   if(!t) {
     err_msg(TYPE_, stmt->pos, "... in case");
     return -1;
   }
   if(t->xid !=  t_int.xid) {
     err_msg(TYPE_, stmt->pos, "invalid type in '%s' case expression. should be 'int'", t->name);
     return -1;
   }
   return 1;
 }
check_Cast_Expression()
static Type check_Cast_Expression (Env env, Cast_Expression * cast) static
Definition at line 964 of file type.c.
References check_Expression(), compat_func(), Env_::curr, Primary_Expression::d, Expression_::d, Func_::def, err_msg(), Cast_Expression::exp, Expression_::exp_primary, find_type(), free(), Type_::func, Cast_Expression::func, insert_symbol(), isa(), Value_::name, Type_::name, namespace_lookup_func(), namespace_lookup_value(), Type_::parent, Cast_Expression::pos, Func_Def_::pos, S_name(), t_null, t_object, Cast_Expression::type, TYPE_, type_path(), Primary_Expression::var, Type_Decl::xid, and ID_List_::xid.
Referenced by check_Expression().
 {
 #ifdef DEBUG_TYPE
   debug_msg("check", "cast expression");
 #endif// check the exp
   Type t = check_Expression( env, cast->exp );
   if(!t) return NULL;
   Type t2 = find_type(env, cast->type->xid);
   if(!t2) {
     m_str path = type_path(cast->type->xid);
     err_msg(TYPE_, cast->pos, "unknown type '%s' in cast expression.", path);
     free(path);
     return NULL;
   }
   if(isa(t2, &t_func_ptr) > 0) {
     Value v = namespace_lookup_value(env->curr, cast->exp->d.exp_primary->d.var,  1);
     Func  f = namespace_lookup_func(env->curr, insert_symbol(v->name),  1);
     if(compat_func(t2->func->def, f->def, f->def->pos)) {
       cast->func = f;
       return t2;
     }
   }
   /*  if( t->xid == t2->xid ||*/
   /*    ( t->xid == t_int.xid) && (t2->xid == t_int.xid)*/
   /*  )*/
   if(isa(t, &t_null) > 0 && isa(t2, &t_object) > 0)
     return t2;
   if(isa(t, &t_object) < 0)
       return isa(t, t2) > 0 ? t2 : NULL;
   // check if cast valid
   Type type = t;
   while(type) {
     if (t2 == type)
         return t2;
     type = type->parent;
   }
   /*  if( !type_engine_check_cast_valid( env, t2, t ) )*/
   err_msg(TYPE_, cast->pos, "invalid cast to '%s' from '%s'...", S_name( cast->type->xid->xid ), t->name );
   return NULL;
 }
check_Class_Def()
static m_bool check_Class_Def (Env env, Class_Def class_def) static
Definition at line 293 of file type.c.
References ae_section_class, ae_section_func, ae_section_stmt, Class_Def_::body, check_Func_Def(), check_Stmt_List(), Env_::class_def, Section::class_def, Env_::class_scope, Env_::class_stack, Env_::curr, Section::d, err_msg(), Class_Def_::ext, Class_Ext_::extend_id, find_type(), free(), free_Vector(), Section::func_def, Type_::has_constructor, Type_::info, Type_::is_complete, isprim(), Type_::name, Class_Def_::name, Class_Body_::next, Env_::nspc_stack, Type_::obj_size, NameSpace_::obj_v_table, NameSpace_::offset, Type_::parent, Class_Ext_::pos, S_name(), Class_Body_::section, Stmt_List_::stmt, Section::stmt_list, t_object, Class_Def_::type, Section::type, TYPE_, type_path(), vector_append(), vector_back(), vector_copy(), vector_pop(), and ID_List_::xid.
Referenced by check_Context().
 {
   Type the_class = NULL;
   Type t_parent = NULL;
   m_bool ret = 1;
   Class_Body body = class_def->body;
   if(class_def->ext) {
     if(class_def->ext->extend_id) {
       t_parent = find_type(env, class_def->ext->extend_id);
       if(!t_parent) {
         m_str path = type_path(class_def->ext->extend_id);
         err_msg(TYPE_, class_def->ext->pos,
                 "undefined parent class '%s' in definition of class '%s'", path, S_name(class_def->name->xid) );
         free(path);
         return -1;
       }
       if(isprim(t_parent) > 0) {
         err_msg(TYPE_, class_def->ext->pos,
                 "cannot extend primitive type '%s'", t_parent->name);
         err_msg(TYPE_, class_def->ext->pos,
                 "...(note: primitives types are 'int', 'float', 'time', and 'dur')" );
         return -1;
       }
       if(!t_parent->is_complete) {
         err_msg(TYPE_, class_def->ext->pos,
                 "cannot extend incomplete type '%s'", t_parent->name);
         err_msg(TYPE_, class_def->ext->pos,
                 "...(note: the parent's declaration must preceed child's)" );
         return -1;
       }
     }
     // TODO: interface
   }
   if( !t_parent )
     t_parent = &t_object;
   the_class = class_def->type;
   the_class->parent = t_parent;
   /*  the_class->ugen_info = t_parent->ugen_info;*/
   the_class->info->offset = t_parent->obj_size;
   free_Vector(the_class->info->obj_v_table);
   the_class->info->obj_v_table = vector_copy(t_parent->info->obj_v_table);
   vector_append(env->nspc_stack, (vtype)env->curr);
   env->curr = the_class->info;
   vector_append(env->class_stack, (vtype)env->class_def);
   env->class_def = the_class;
   env->class_scope = 0;
   while(body && ret > 0) {
     switch(body->section->type) {
     case ae_section_stmt:
       env->class_def->has_constructor |= (body->section->d.stmt_list->stmt != NULL);
       ret = check_Stmt_List(env, body->section->d.stmt_list);
       break;
     case ae_section_func:
       env->class_def->is_complete = 1;
       ret = check_Func_Def(env, body->section->d.func_def);
       env->class_def->is_complete = 0;
       break;
     case ae_section_class:
       ret = check_Class_Def( env, body->section->d.class_def);
       break;
     }
     body = body->next;
   }
   env->class_def = (Type)vector_back(env->class_stack);
   vector_pop(env->class_stack);
   env->curr = (NameSpace)vector_back(env->nspc_stack);
   vector_pop(env->nspc_stack);
   if(ret > 0) {
     the_class->obj_size = the_class->info->offset;
     the_class->is_complete = 1;
   } else {
 //   scope_rem(env->curr->type, class_def->type);
 //namespace_add_type(env->curr, insert_symbol(class_def->type->name), NULL);
 //free_Type(the_class);
 //free(class_def->type);
 //class_def->type = NULL;
     // delete the class definition
     /*      SAFE_RELEASE( class_def->type );*/
 //add_ref(class_def->type->obj);
 //add_ref(class_def->type->obj);
 //    rem_ref(class_def->type->obj, class_def->type);
     // set the thing to NULL
 //    the_class = NULL;
   }
   return ret;
 }
check_Context()
m_bool check_Context (Env env, Context context)
Definition at line 189 of file type.c.
References ae_section_class, ae_section_func, ae_section_stmt, CHECK_BB, check_Class_Def(), check_Func_Def(), check_Stmt_List(), Section::class_def, Section::d, Section::func_def, Ast_::next, Ast_::section, Section::stmt_list, Context_::tree, and Section::type.
Referenced by type_engine_check_prog().
 {
 #ifdef DEBUG_TYPE
   debug_msg("type", "context");
 #endif
   int ret = 1;
   Ast prog = context->tree;
   while(prog && ret > 0) {
     switch(prog->section->type) {
     case ae_section_stmt:
       ret = check_Stmt_List(env, prog->section->d.stmt_list);
       break;
     case ae_section_func:
       ret = check_Func_Def(env, prog->section->d.func_def);
       break;
     case ae_section_class:
       ret = check_Class_Def(env, prog->section->d.class_def);
       break;
     }
     CHECK_BB(ret);
     prog = prog->next;
   }
   /*
      if( !ret )
      {
   // TODO: remove the effects of the context in the env
   // ---> insert code here <----
   // flag the context with error, so more stuff gets deleted
   env->context->has_error = TRUE;
   }
   */
   return 1;
 }
check_Continue()
static m_bool check_Continue (Env env, Stmt_Continue cont) static
Definition at line 1965 of file type.c.
References Env_::breaks, err_msg(), Stmt_Continue_::pos, TYPE_, and vector_size().
Referenced by check_Stmt().
 {
   if(!vector_size(env->breaks)) {
     err_msg(TYPE_,  cont->pos,
             "'continue' found outside of for/while/until..." );
     return -1;
   }
   return 1;
 }
check_Decl_Expression()
Type check_Decl_Expression (Env env, Decl_Expression * decl)
Definition at line 388 of file type.c.
References Var_Decl_::array, check_array_subscripts(), check_Expression(), Value_::checked, NameSpace_::class_data_size, Env_::class_def, Env_::class_scope, Env_::curr, err_msg(), Array_Sub_::exp_list, find_value(), free(), Type_::info, Value_::is_member, Value_::is_static, Decl_Expression::is_static, Decl_Expression::list, Value_::m_type, Decl_Expression::m_type, Type_::name, namespace_add_value(), Var_Decl_List_::next, Type_::obj, Type_::obj_size, Value_::offset, NameSpace_::offset, Value_::owner_class, Type_::parent, Var_Decl_::pos, Decl_Expression::pos, S_name(), Var_Decl_List_::self, Type_::size, TYPE_, Var_Decl_::value, and Var_Decl_::xid.
Referenced by check_Expression(), check_Stmt(), and import_var().
 {
 #ifdef DEBUG_TYPE
   debug_msg("check", "decl");
 #endif
   Value value = NULL;
   Type type = NULL;
   Var_Decl_List list = decl->list;
   Var_Decl var_decl;
   while(list) {
     if(env->class_def && !env->class_scope &&
         (value = find_value(env->class_def->parent, list->self->xid))) {
       err_msg(TYPE_, list->self->pos,
               "in class '%s': '%s' has already been defined in parent class '%s'...",
               env->class_def->name, S_name(list->self->xid), value->owner_class->name);
 //      add_ref(env->class_def->obj);
 //      add_ref(env->class_def->obj);
       return NULL;
     }
     var_decl = list->self;
     value = list->self->value;
     if(!value) {
       err_msg(TYPE_, list->self->pos, "can't declare in GACK");
       return NULL;
     }
     type  = value->m_type;
     if(var_decl->array && var_decl->array->exp_list) {
       if(!check_Expression(env, var_decl->array->exp_list)) {
         free(type->obj);
         free(type);
         return NULL;
       }
       if(check_array_subscripts(env, var_decl->array->exp_list) < 0) {
         free(type->obj);
         free(type);
         return NULL;
       }
     }
     if(value->is_member) {
       value->offset = env->curr->offset;
       value->owner_class->obj_size += type->size;
       /* coverity[var_deref_op : FALSE] */
       env->class_def->obj_size += type->size;
       env->curr->offset += type->size;
     } else if( decl->is_static ) { // static
       if(!env->class_def || env->class_scope > 0 ) {
         err_msg(TYPE_, decl->pos,
                 "static variables must be declared at class scope..." );
         return NULL;
       }
       value->is_static = 1;
       // offset
       value->offset = env->class_def->info->class_data_size;
       // move the size
       env->class_def->info->class_data_size += type->size;
       /*      env->class_def->info->class_data_size++;*/
       /*
          if(is_obj && !is_ref)
          {
       // for now - no good for static, since we need separate
       // initialization which we don't have
       err_msg(TYPE_, var_decl->pos,
       "cannot declare static non-primitive objects (yet)..." );
       err_msg(TYPE_, var_decl->pos,
       "...(hint: declare as ref (@) & initialize outside for now)" );
       return NULL;
       }
       */
     }
     list->self->value->checked = 1;
     if(!env->class_def || env->class_scope)
       namespace_add_value(env->curr, list->self->xid, list->self->value);
     list = list->next;
   }
   return decl->m_type;
 }
check_Dot_Member()
static Type check_Dot_Member (Env env, Dot_Member * member) static
Definition at line 2146 of file type.c.
References Type_::actual_type, ae_meta_value, Type_::array_depth, Dot_Member::base, check_Expression(), Env_::class_def, err_msg(), find_value(), Env_::func, Type_::info, Value_::is_const, Func_::is_member, Value_::is_member, Value_::m_type, Expression_::meta, Type_::name, Dot_Member::pos, Expression_::pos, S_name(), Dot_Member::self, strcat(), Dot_Member::t_base, TYPE_, Type_::xid, and Dot_Member::xid.
Referenced by check_Expression().
 {
 #ifdef DEBUG_TYPE
   debug_msg("check", "dot member");
 #endif
   Value value = NULL;
   Type  the_base = NULL;
   m_bool base_static = 0;
   m_str str;
   member->t_base = check_Expression(env, member->base);
   if(!member->t_base)
     return NULL;
   base_static = member->t_base->xid == t_class.xid;
   the_base = base_static ? member->t_base->actual_type : member->t_base;
   /*  if(the_base == &t_vararg)*/
   /*  {*/
   /*    if(member->xid == insert_symbol("start") ||*/
   /*       member->xid == insert_symbol("end") )*/
   /*    return &t_void;*/
   /*  }*/
   if(!the_base->info && !member->t_base->array_depth) { // ?
     err_msg(TYPE_,  member->base->pos,
             "type '%s' does not have members - invalid use in dot expression of %s",
             the_base->name, S_name(member->xid));
     return NULL;
   }
   str = S_name(member->xid);
   if(!strcmp(str, "this")) {
     if(base_static) {
       err_msg(TYPE_,  member->pos,
               "keyword 'this' must be associated with object instance..." );
       return NULL;
     }
     if( env->func && !env->func->is_member ) {
       err_msg(TYPE_, member->pos,
               "keyword 'this' cannot be used inside static functions..." );
       return NULL;
     }
     return env->class_def;
   }
   value = find_value(the_base, member->xid);
   if(!value) {
     m_uint i;
     /*    m_str s = strdup(the_base->name);*/
     char s[1025];
     memset(s, 0, 1025);
     strncpy(s, the_base->name, 1024);
     for(i = 0; i < the_base->array_depth; i++)
       strcat(s, "[]");
     err_msg(TYPE_,  member->base->pos,
             "class '%s' has no member '%s'", s, S_name(member->xid));
     /*    free(s);*/
     return NULL;
   }
   if(base_static && value->is_member) {
     err_msg(TYPE_, member->pos,
             "cannot access member '%s.%s' without object instance...",
             the_base->name, S_name(member->xid) );
     return NULL;
   }
   if(value->is_const == 2) // for enum
     member->self->meta = ae_meta_value;
   return value->m_type;
 }
check_Dur()
static Type check_Dur (Env env, Exp_Dur * dur) static
Definition at line 1049 of file type.c.
References Exp_Dur::base, check_Expression(), err_msg(), isa(), Type_::name, Expression_::pos, t_dur, t_float, t_int, TYPE_, and Exp_Dur::unit.
Referenced by check_Expression().
 {
   Type base = check_Expression(env, dur->base);
   Type unit = check_Expression(env, dur->unit);
   if(!base || !unit)
     return NULL;
   if(isa(base, &t_int) < 0 && isa(base, &t_float) < 0) {
     err_msg(TYPE_, dur->base->pos,
             "invalid type '%s' in prefix of dur expression...\n"
             "    (must be of type 'int' or 'float')", base->name);
     return NULL;
   }
   if(isa(unit, &t_dur) < 0) {
     err_msg( TYPE_, dur->unit->pos,
              "invalid type '%s' in postfix of dur expression...\n"
              "    (must be of type 'dur')", unit->name);
     return NULL;
   }
   return unit;
 }
check_Enum()
static m_bool check_Enum (Env env, Stmt_Enum stmt) static
Definition at line 1758 of file type.c.
References NameSpace_::class_data_size, Env_::class_def, Env_::curr, Type_::info, Value_::is_static, Stmt_Enum_::list, namespace_lookup_value(), ID_List_::next, Value_::offset, Type_::size, t_int, and ID_List_::xid.
Referenced by check_Stmt().
 {
   ID_List list = stmt->list;
   Value v;
   NameSpace nspc = env->class_def ? env->class_def->info : env->curr;
   while(list) {
     v = namespace_lookup_value(nspc, list->xid, 0);
     if(env->class_def) {
       // enum in classes are static
       v->is_static = 1;
       v->offset = env->class_def->info->class_data_size;
       env->class_def->info->class_data_size += t_int.size;
     }
     list = list->next;
   }
   return 1;
 }
check_exp_if()
static Type check_exp_if (Env env, If_Expression * exp_if) static
Definition at line 1670 of file type.c.
References check_Expression(), If_Expression::cond, If_Expression::else_exp, err_msg(), find_common_anc(), If_Expression::if_exp, isa(), Type_::name, If_Expression::pos, t_int, and TYPE_.
Referenced by check_Expression().
 {
 #ifdef DEBUG_TYPE
   debug_msg("check", "debug exp if");
 #endif
   // check the components
   Type cond     = check_Expression(env, exp_if->cond);
   Type if_exp   = check_Expression(env, exp_if->if_exp);
   Type else_exp = check_Expression(env, exp_if->else_exp);
   // make sure everything good
   if(!cond || !if_exp || !else_exp)
     return NULL;
   // check the type
   if(isa(cond, &t_int) < 0)
     return NULL;
   // make sure the if and else have compatible types
   // TODO: the lesser of two types
   /*  if( !( *if_exp == *else_exp ) )*/
   if(!find_common_anc(if_exp, else_exp)) {
     err_msg(TYPE_, exp_if->pos,
             "incompatible types '%s' and '%s' in if expression...", if_exp->name, else_exp->name);
     return NULL;
   }
   return if_exp;
 }
check_Expression()
static Type check_Expression (Env env, Expression exp) static
Definition at line 1699 of file type.c.
References Array_Expression_type, Binary_Expression_type, Cast_Expression_type, check_Array(), check_Binary_Expression(), check_Cast_Expression(), check_Decl_Expression(), check_Dot_Member(), check_Dur(), check_exp_if(), check_Func_Call(), CHECK_OO, check_Postfix_Expression(), check_Primary_Expression(), check_Unary(), Expression_::d, Decl_Expression_type, Dot_Member_type, Dur_Expression_type, err_msg(), Expression_::exp_array, Expression_::exp_binary, Expression_::exp_cast, Expression_::exp_decl, Expression_::exp_dot, Expression_::exp_dur, Expression_::exp_func, Expression_::exp_if, Expression_::exp_postfix, Expression_::exp_primary, Expression_::exp_type, Expression_::exp_unary, Func_Call_type, If_Expression_type, Expression_::next, Expression_::pos, Postfix_Expression_type, Primary_Expression_type, Func_Call::ret_type, Expression_::type, TYPE_, and Unary_Expression_type.
Referenced by check_Array(), check_array_lit(), check_Binary_Expression(), check_Case(), check_Cast_Expression(), check_Decl_Expression(), check_Dot_Member(), check_Dur(), check_exp_if(), check_For(), check_Func_Call(), check_Func_Call1(), check_If(), check_Loop(), check_Postfix_Expression(), check_Primary_Expression(), check_Return(), check_Stmt(), check_Switch(), check_Unary(), check_Until(), check_Vec(), check_While(), and find_template_match().
 {
 #ifndef __clang__
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
 #endif
   Expression curr = exp;
   while(curr) {
     curr->type = NULL;
     switch(curr->exp_type) {
     case Primary_Expression_type:
       curr->type = check_Primary_Expression(env, curr->d.exp_primary);
       break;
     case Decl_Expression_type:
       curr->type = check_Decl_Expression(env, curr->d.exp_decl);
       break;
     case Unary_Expression_type:
       curr->type = check_Unary(env, curr->d.exp_unary);
       break;
     case Binary_Expression_type:
       curr->type = check_Binary_Expression(env, curr->d.exp_binary);
       break;
     case Postfix_Expression_type:
       curr->type = check_Postfix_Expression(env, curr->d.exp_postfix);
       break;
     case Dur_Expression_type:
       curr->type = check_Dur(env, curr->d.exp_dur);
       break;
     case Cast_Expression_type:
       curr->type = check_Cast_Expression(env, curr->d.exp_cast);
       break;
     case Func_Call_type:
       curr->type = check_Func_Call(env, curr->d.exp_func);
       curr->d.exp_func->ret_type = curr->type;
       break;
     case If_Expression_type:
       curr->type = check_exp_if(env, curr->d.exp_if);
       break;
     case Dot_Member_type:
       curr->type = check_Dot_Member(env, curr->d.exp_dot);
       break;
     case Array_Expression_type:
       curr->type = check_Array(env, curr->d.exp_array);
       break;
     default:
       err_msg(TYPE_, curr->pos, "internal error: unhandled expression type '%i'", curr->exp_type);
       exp->type = NULL;
       break;
     }
     CHECK_OO(curr->type)
     curr = curr->next;
   }
   return exp->type;
 #ifndef __clang__
 #pragma GCC diagnostic pop
 #endif
 }
check_For()
static m_bool check_For (Env env, Stmt_For stmt) static
Definition at line 1843 of file type.c.
References Stmt_For_::body, Env_::breaks, Stmt_For_::c1, Stmt_For_::c2, Stmt_For_::c3, check_Expression(), check_Stmt(), Stmt::d, EMIT_, err_msg(), isa(), Type_::name, Expression_::pos, Stmt_For_::pos, Stmt_For_::self, Stmt::stmt_exp, t_io, te_dur, te_float, te_int, te_time, Expression_::type, vector_append(), vector_pop(), and Type_::xid.
Referenced by check_Stmt().
 {
   if(check_Stmt(env, stmt->c1) < 0)
     return -1;
   if(check_Stmt(env, stmt->c2) < 0)
     return -1;
   // check for empty for loop conditional (added 1.3.0.0)
   if( stmt->c2 == NULL ) {
     // error
     err_msg(EMIT_, stmt->pos,
             "empty for loop condition..." );
     err_msg(EMIT_, stmt->pos,
             "...(note: explicitly use 'true' if it's the intent)" );
     err_msg(EMIT_, stmt->pos,
             "...(e.g., 'for( ; true; ){ /*...*/ }')" );
     return -1;
   }
   // ensure that conditional has valid type
   switch( stmt->c2->d.stmt_exp->type->xid ) {
   case te_int:
   case te_float:
   case te_dur:
   case te_time:
     break;
   default:
     // check for IO
     if(isa( stmt->c2->d.stmt_exp->type, &t_io ) > 0)
       break;
     // error
     err_msg(EMIT_,  stmt->c2->d.stmt_exp->pos,
             "invalid type '%s' in for condition", stmt->c2->d.stmt_exp->type->name);
     return -1;
   }
   // check the post
   if( stmt->c3 && !check_Expression(env, stmt->c3))
     return -1;
   // for break and continue statement
   vector_append(env->breaks, (vtype)stmt->self);
   // check body
   // TODO: restore break stack? (same for other loops)
   if(check_Stmt(env, stmt->body) < 0)
     return -1;
   // remove the loop from the stack
   vector_pop(env->breaks);
   return 1;
 }
check_Func_Call()
static Type check_Func_Call (Env env, Func_Call * exp_func) static
Definition at line 1434 of file type.c.
References Type_::actual_type, Func_Call::args, check_Expression(), check_Func_Call1(), CHECK_OO, Env_::curr, Primary_Expression::d, Expression_::d, Func_::def, err_msg(), Expression_::exp_dot, Expression_::exp_primary, Expression_::exp_type, find_template_match(), find_value(), free_Type_List(), Func_Call::func, Value_::func_ref, isa(), Func_Call::m_func, namespace_lookup_value(), Func_Call::pos, Primary_Expression_type, Func_Def_::ret_type, Dot_Member::t_base, TYPE_, Func_Call::types, Func_Def_::types, Primary_Expression::var, and Dot_Member::xid.
Referenced by check_Expression().
 {
   if(exp_func->types) {
     Value v;
     if(exp_func->func->exp_type == Primary_Expression_type) {
       v = namespace_lookup_value(env->curr, exp_func->func->d.exp_primary->d.var, 1);
     } else {
       Type t;
       CHECK_OO(check_Expression(env, exp_func->func))
       t = exp_func->func->d.exp_dot->t_base;
       if(isa(t, &t_class) > 0)
         t = t->actual_type;
       v = find_value(t, exp_func->func->d.exp_dot->xid);
       // added 06/12/16
       if(!v) {
         err_msg(TYPE_, exp_func->pos, "unknown template function.");
         return NULL;
       }
       if(!v->func_ref) {
         err_msg(TYPE_, exp_func->pos, "non-function template call.");
         return NULL;
       }
       if(!v->func_ref->def->types) {
         err_msg(TYPE_, exp_func->pos, "template call of non-template function.");
         free_Type_List(exp_func->types);
         exp_func->types = NULL;
         return NULL;
       }
     }
     // primary case
     Func ret = find_template_match(env, v, exp_func->m_func, exp_func->types,
                                    exp_func->func, exp_func->args);
     if(!ret) {
       err_msg(TYPE_, exp_func->pos, "arguments do not match for template call");
       free_Type_List(exp_func->types);
       return NULL;
     }
     exp_func->m_func = ret;
     return ret->def->ret_type;
   }
   current = exp_func;
   return check_Func_Call1(env, exp_func->func, exp_func->args,
                           &exp_func->m_func, exp_func->pos );
 }
check_Func_Call1()
Type check_Func_Call1 (Env env, Expression exp_func, Expression args, Func * m_func, int pos)
Definition at line 1269 of file type.c.
References Func_Def_::arg_list, Type_::array_depth, Func_Call::base, check_Expression(), CHECK_OO, Env_::curr, Primary_Expression::d, Expression_::d, Func_::def, Dot_Member_type, err_msg(), Expression_::exp_dot, Expression_::exp_primary, Expression_::exp_type, find_func_match(), find_template_match(), find_value(), free(), Type_::func, Value_::func_ref, Value_::is_const, isa(), malloc(), mk_type_list(), Type_::name, namespace_lookup_value(), Func_::next, Arg_List_::next, Expression_::next, ID_List_::next, Type_List_::next, Expression_::pos, Primary_Expression_type, Func_Def_::ret_type, S_name(), Dot_Member::t_base, Arg_List_::type, Expression_::type, TYPE_, Arg_List_::type_decl, type_path(), Func_Call::types, Func_Def_::types, Primary_Expression::value, Func_::value_ref, Primary_Expression::var, Arg_List_::var_decl, Dot_Member::xid, Var_Decl_::xid, Type_Decl::xid, and ID_List_::xid.
Referenced by check_Func_Call(), and check_op().
 {
 #ifdef DEBUG_TYPE
   debug_msg("check", "func call");
 #endif
   Func func = NULL;
   Func up = NULL;
   Type f;
   Value ptr = NULL; // 20/03/17
   exp_func->type = check_Expression(env, exp_func);
   f = exp_func->type;
   // primary func_ptr
 //printf("%s %p\n", f->name, exp_func->d.exp_primary->value->is_member);
   if(exp_func->exp_type == Primary_Expression_type &&
       exp_func->d.exp_primary->value &&
       !exp_func->d.exp_primary->value->is_const) {
 ptr = exp_func->d.exp_primary->value;
 //    f = namespace_lookup_type(env->curr, insert_symbol(exp_func->d.exp_primary->value->m_type->name), -1);
 //namespace_lookup_type(env->curr, insert_symbol(exp_func->d.exp_primary->value->m_type->name), -1);
     /*f = namespace_lookup_type(env->curr, insert_symbol(exp_func->d.exp_primary->value->name), -1);*/
 /*
     if(!f) {
       err_msg(TYPE_, exp_func->pos, "trying to call empty func pointer.");
       return NULL;
     }
 */
 //    if(!f->func) { // func ptr
 //      up = namespace_lookup_func(env->curr, insert_symbol(exp_func->d.exp_primary->value->m_type->name), -1);
 //      f->func = up;
 //    }
   }
   if(!f) {
     err_msg(TYPE_, exp_func->pos, "function call using a non-existing function");
     return NULL;
   }
   if(isa(f, &t_function) < 0) {
     err_msg(TYPE_, exp_func->pos, "function call using a non-function value");
     return NULL;
   }
   up = f->func;
   if(args)
     CHECK_OO(check_Expression(env, args))
   // look for a match
   func = find_func_match(up, args);
   if(!func) {
     Value value = NULL;
     if(!f->func) {
       if(exp_func->exp_type == Primary_Expression_type)
         value = namespace_lookup_value(env->curr, exp_func->d.exp_primary->d.var, 1);
       else if(exp_func->exp_type == Dot_Member_type)
         value = find_value(exp_func->d.exp_dot->t_base, exp_func->d.exp_dot->xid);
       if(!value) {
         err_msg(TYPE_, exp_func->pos, "function is template. not enough argument for automatic type guess. this message is incorrect");
         return NULL;
       }
       // template guess
       ID_List list = value->func_ref->def->types;
       m_uint type_number = 0;
       m_uint args_number = 0;
       while(list) {
         type_number++;
         list = list->next;
       }
       list = value->func_ref->def->types;
       Type_List tl[type_number ? type_number : 1];
       if(!type_number)
         tl[0] = NULL;
       while(list) { // iterate through types
         Arg_List arg = value->func_ref->def->arg_list;
         Expression template_arg = args;
         while(arg && template_arg) {
           m_str path = type_path(arg->type_decl->xid);
           if(!strcmp(S_name(list->xid), path)) {
             tl[args_number] = mk_type_list(env, template_arg->type);
             if(args_number)
               tl[args_number - 1]->next = tl[args_number];
             args_number++;
             free(path);
             break;
           }
           free(path);
           arg = arg->next;
           template_arg = template_arg->next;
         }
         list = list->next;
       }
       if(args_number < type_number) {
         err_msg(TYPE_, exp_func->pos, "not able to guess types for template call.");
         return NULL;
       }
       Func f = find_template_match(env, value, func, tl[0], exp_func, args);
       if(f) {
         *m_func = f;
         Type ret_type  = f->def->ret_type;
         current->types = tl[0];
         current->base = value->func_ref->def->types;
         return ret_type;
       }
       err_msg(TYPE_, exp_func->pos, "function is template. automatic type guess not fully implemented yet.\n\
           please provide template types. eg: '<type1, type2, ...>'");
       return NULL;
     }
     m_uint i;
     err_msg(TYPE_, exp_func->pos, "argument type(s) do not match for function. should be :");
     up = f->func;
     while(up) {
       Arg_List e = up->def->arg_list;
       fprintf(stderr, "\t");
       if(!e)
         fprintf(stderr, "\033[32mvoid\033[0m");
       while(e) {
         m_str path = type_path(e->type_decl->xid);
 #ifdef COLOR
         fprintf(stderr, " \033[32m%s\033[0m \033[1m%s\033[0m", e->type->name, S_name(e->var_decl->xid));
 #else
         fprintf(stderr, " %s %s", e->type->name, S_name(e->var_decl->xid));
 #endif
         for(i = 0; i < e->type->array_depth; i++)
           fprintf(stderr, "[]");
         e = e->next;
         if(e)
           fprintf(stderr, ",");
         free(path);
       }
       up = up->next;
       fprintf(stderr, ". (%s)\n", f->name);
       if(up)
         fprintf(stderr, "or :");
     }
     fprintf(stderr, "and not");
     fprintf(stderr, "\n\t");
     Expression e = args;
     while(e) {
 #ifdef COLOR
       fprintf(stderr, " \033[32m%s\033[0m", e->type->name);
 #else
       fprintf(stderr, " %s", e->type->name);
 #endif
       for(i = 0; i < e->type->array_depth; i++)
         fprintf(stderr, "[]");
       e = e->next;
       if(e)
         fprintf(stderr, ",");
     }
     fprintf(stderr, "\n");
     return NULL;
   }
   if(ptr) {
     Func f = malloc(sizeof(struct Func_));
     memcpy(f, func, sizeof(struct Func_));
     f->value_ref = ptr;
     func = f;
 //up->value_ref = exp_func->d.exp_primary->value;
   }
   *m_func = func;
   return func->def->ret_type;
 }
check_Func_Def()
m_bool check_Func_Def (Env env, Func_Def f)
Definition at line 2248 of file type.c.
References ae_func_builtin, ae_func_user, ae_key_abstract, ae_key_static, Func_Def_::arg_list, check_Stmt_Code(), Value_::checked, Env_::class_def, Func_::code, Func_Def_::code, compat_func(), Env_::context, Env_::curr, Stmt::d, Func_::def, Type_::def, Func_Def_::dl_func_ptr, err_msg(), find_value(), Env_::func, Func_Def_::func, Value_::func_num_overloads, Value_::func_ref, Class_Def_::iface, insert_symbol(), Func_::is_member, Func_Def_::is_variadic, isa(), Value_::m_type, Func_::name, NameSpace_::name, Value_::name, Type_::name, Func_Def_::name, namespace_add_value(), namespace_lookup_func(), namespace_lookup_value(), namespace_pop_value(), namespace_push_value(), VM_Code_::need_this, new_Value(), Func_::next, Arg_List_::next, Value_::obj, NameSpace_::obj_v_table, Value_::owner_class, Type_::parent, Arg_List_::pos, Func_Def_::pos, rem_ref(), Func_Def_::ret_type, S_name(), Func_Def_::s_type, VM_Code_::stack_depth, Func_Def_::stack_depth, Func_Def_::static_decl, Stmt::stmt_code, t_vararg, TYPE_, Func_Def_::types, Func_::up, Var_Decl_::value, Func_::value_ref, Arg_List_::var_decl, vector_append(), vector_set(), vector_size(), Func_::vt_index, and Var_Decl_::xid.
Referenced by check_Class_Def(), check_Context(), emit_Func_Call(), find_template_match(), and import_fun().
 {
 #ifdef DEBUG_TYPE
   debug_msg("check", "func def '%s'", f->func->name);
 #endif
   Value value = NULL;
   Func func = NULL;
   Type parent = NULL;
   Value override = NULL;
   Value  v = NULL;
   Value vararg = NULL;
   Func  parent_func = NULL;
   Arg_List arg_list = NULL;
   m_bool parent_match = 0;
   m_str func_name = S_name(f->name);
   //  m_str func_name = strdup(S_name(f->name)); // strdup might be unnnecessary. 27/11/16
   m_uint count = 1;
   m_bool has_code = 0;
   if(f->types) // templating, check at call time
     return 1;
   if(env->func) {
     err_msg(TYPE_, f->pos, "nested function definitions are not (yet) allowed");
     return -1;
   }
   func = f->func;
   value = func->value_ref;
   // look up the value in the parent class
   if(env->class_def)
     override = find_value(env->class_def->parent, f->name);
   else if(value->func_num_overloads) { // check if func has ame args
     m_uint i, j;
     if(!f->types)
       for(i = 0; i <= value->func_num_overloads; i++) {
         char name[1024];
         sprintf(name, "%s@%li@%s", S_name(f->name), i, env->curr->name);
         Func f1 = namespace_lookup_func(env->curr, insert_symbol(name), -1);
         for(j = 1; j <= value->func_num_overloads; j++) {
           if(i != j) {
             sprintf(name, "%s@%li@%s", S_name(f->name), j, env->curr->name);
             Func f2 = namespace_lookup_func(env->curr, insert_symbol(name), -1);
             if(compat_func(f1->def, f2->def, f2->def->pos) > 0) {
               err_msg(TYPE_, f2->def->pos, "global function '%s' already defined for those arguments", S_name(f->name));
               return -1;
             }
           }
         }
       }
   }
   if(env->class_def &&  override) {
     if(isa(override->m_type, &t_function) < 0) {
       err_msg(TYPE_, f->pos, "function name '%s' conflicts with previously defined value...",
               S_name(f->name));
       err_msg(TYPE_, f->pos, "from super class '%s'...", override->owner_class->name);
       goto error;
     }
   }
   if(override) {
     // make reference to parent
     // TODO: ref count
     func->up = override;
   }
   if(!env->class_def && f->static_decl == ae_key_abstract) {
     err_msg(TYPE_, f->pos, "non-class function cannot be declared as 'pure'...");
     err_msg(TYPE_, f->pos, "...at function '%s'", S_name(f->name) );
     goto error;
   }
   if(f->s_type == ae_func_user) has_code = (f->code != NULL);
   else has_code = (f->dl_func_ptr != NULL); // imported
   if(env->class_def && env->class_def->def && env->class_def->def->iface && has_code) {
     err_msg(TYPE_, f->pos, "interface function signatures cannot contain code..." );
     err_msg(TYPE_, f->pos, "...at function '%s'", S_name(f->name));
     goto error;
   }
   if(f->static_decl == ae_key_abstract && has_code) {
     err_msg(TYPE_, f->pos, "'pure' function signatures cannot contain code..." );
     err_msg(TYPE_, f->pos, "...at function '%s'", S_name(f->name));
     goto error;
   }
   if(f->static_decl != ae_key_abstract && !has_code) {
     err_msg(TYPE_, f->pos, "function declaration must contain code..." );
     err_msg(TYPE_, f->pos, "(unless in interface, or is declared 'pure')" );
     err_msg(TYPE_, f->pos, "...at function '%s'", S_name(f->name));
     goto error;
   }
   // TODO if overload, check arguments do not match
   // if overriding super class function, then check signatures
   if(env->class_def) {
     // get parent
     parent = env->class_def->parent;
     while( parent && !parent_match ) {
       if((v = find_value(env->class_def->parent, f->name))) {
         // see if the target is a function
         if(!isa( v->m_type, &t_function)) {
           err_msg(TYPE_, f->pos, "function name '%s' conflicts with previously defined value...",
                   S_name(f->name));
           err_msg(TYPE_, f->pos, "from super class '%s'...", v->owner_class->name );
           goto error;
         }
         // parent func
         parent_func = v->func_ref;
         // go through all overloading
         while(parent_func && !parent_match) {
           // match the prototypes
           if(compat_func(f, parent_func->def, f->pos) < 0) {
             // next
             parent_func = parent_func->next;
             // move on
             continue;
           }
           // see if parent function is static
           if( parent_func->def->static_decl == ae_key_static ) {
             err_msg(TYPE_, f->pos,
                     "function '%s.%s' resembles '%s.%s' but cannot override...",
                     env->class_def->name, S_name(f->name),
                     v->owner_class->name, S_name(f->name) );
             err_msg(TYPE_, f->pos,
                     "...(reason: '%s.%s' is declared as 'static')",
                     v->owner_class->name, S_name(f->name) );
             goto error;
           }
           // see if function is static
           if(f->static_decl == ae_key_static) {
             err_msg(TYPE_, f->pos,
                     "function '%s.%s' resembles '%s.%s' but cannot override...",
                     env->class_def->name, S_name(f->name),
                     v->owner_class->name, S_name(f->name));
             err_msg(TYPE_, f->pos,
                     "...(reason: '%s.%s' is declared as 'static')",
                     env->class_def->name, S_name(f->name));
             goto error;
           }
           // see if function is pure
           if(f->static_decl == ae_key_abstract) {
             err_msg(TYPE_, f->pos,
                     "function '%s.%s' resembles '%s.%s' but cannot override...",
                     env->class_def->name, S_name(f->name),
                     v->owner_class->name, S_name(f->name));
             err_msg(TYPE_, f->pos,
                     "...(reason: '%s.%s' is declared as 'pure')",
                     env->class_def->name, S_name(f->name));
             goto error;
           }
           // make sure returns are equal
           if(isa(f->ret_type, parent_func->def->ret_type) < 0) {
             err_msg(TYPE_, f->pos, "function signatures differ in return type..." );
             err_msg(TYPE_, f->pos,
                     "function '%s.%s' matches '%s.%s' but cannot override...",
                     env->class_def->name, S_name(f->name),
                     v->owner_class->name, S_name(f->name));
             goto error;
           }
           parent_match = 1;
           func->vt_index = parent_func->vt_index;
           vector_set(env->curr->obj_v_table, func->vt_index, (vtype)func);
           func_name = parent_func->name;
           func->name = func_name;
           value->name = func_name;
         }
       }
       // move to next parent
       parent = parent->parent;
     }
   }
   if(func->is_member && !parent_match) {
     func->vt_index = vector_size(env->curr->obj_v_table);
     vector_append(env->curr->obj_v_table, (vtype)func);
   }
   env->func = func;
   namespace_push_value(env->curr);
   arg_list = f->arg_list;
   while(arg_list) {
     v = arg_list->var_decl->value;
     if(namespace_lookup_value( env->curr, arg_list->var_decl->xid, 0)) {
       err_msg(TYPE_, arg_list->pos, "argument %i '%s' is already defined in this scope",
               count, S_name(arg_list->var_decl->xid) );
       err_msg(TYPE_, arg_list->pos, "in function '%s':", S_name(f->name));
       goto error;
     }
     v->checked  = 1;
     namespace_add_value(env->curr, arg_list->var_decl->xid, v );
     count++;
     arg_list = arg_list->next;
   }
   if(f->is_variadic) {
     vararg = new_Value(env->context, &t_vararg, "vararg");
     vararg->checked = 1;
     namespace_add_value(env->curr, insert_symbol("vararg"), vararg);
   }
   if(f->code && check_Stmt_Code(env, f->code->d.stmt_code, 0) < 0) {
     err_msg(TYPE_, f->pos, "...in function '%s'", S_name(f->name));
     goto error;
   }
   if(f->is_variadic)
     rem_ref(vararg->obj, vararg);
   if(f->s_type == ae_func_builtin) { // is this useful ?
     func->code->stack_depth = f->stack_depth;
     func->code->need_this = 1;
   }
 //  else
 //    func->code->need_this = 0;
   namespace_pop_value(env->curr);
   env->func = NULL;
   return 1;
 error:
   namespace_pop_value(env->curr);
   env->func = NULL;
   return -1;
 }
check_Func_Ptr()
static m_bool check_Func_Ptr (Env env, Func_Ptr * ptr) static
Definition at line 1479 of file type.c.
References add_ref(), Env_::curr, Type_::func, Func_Ptr::func, Func_Ptr::m_type, Type_::name, namespace_add_type(), namespace_lookup_type(), Type_::obj, Type_::parent, S_name(), Type_::size, t_func_ptr, and Func_Ptr::xid.
Referenced by check_Stmt().
 {
 #ifdef DEBUG_TYPE
   debug_msg("check", "func pointer '%s'", S_name(ptr->xid));
 #endif
   Type t     = namespace_lookup_type(env->curr, ptr->xid, 1);
   t->size    = SZ_INT;
   t->name    = S_name(ptr->xid);
   t->parent  = &t_func_ptr;
   namespace_add_type(env->curr, ptr->xid, t);
   add_ref(t->obj);
   ptr->m_type = t;
   t->func = ptr->func;
   return 1;
 }
check_Goto_Label()
static m_bool check_Goto_Label (Env env, Stmt_Goto_Label stmt) static
Definition at line 2013 of file type.c.
References Env_::class_def, Env_::curr, Stmt_Goto_Label_::data, err_msg(), Env_::func, Stmt_Goto_Label_::is_label, NameSpace_::label, map_get(), Stmt_Goto_Label_::name, Stmt_Goto_Label_::pos, S_name(), TYPE_, Stmt_Goto_Label_::v, and vector_append().
Referenced by check_Stmt().
 {
   Map m;
   m_uint* key = env->class_def && !env->func ? (m_uint*)env->class_def : (m_uint*)env->func;
   Stmt_Goto_Label ref;
   if(stmt->is_label)
     return 1;
   m = (Map)map_get(env->curr->label, (vtype)key);
   ref = (Stmt_Goto_Label)map_get(m, (vtype)stmt->name);
   if(!ref) {
     err_msg(TYPE_, stmt->pos, "label '%s' used but not defined", S_name(stmt->name));
     return -1;
   }
   vector_append(ref->data.v, (vtype)stmt);
   return 1;
 }
check_If()
static m_bool check_If (Env env, Stmt_If stmt) static
Definition at line 1914 of file type.c.
References check_Expression(), CHECK_OB, check_Stmt(), Stmt_If_::cond, Stmt_If_::else_body, err_msg(), Stmt_If_::if_body, isa(), Type_::name, Expression_::pos, t_io, t_object, te_dur, te_float, te_int, te_time, Expression_::type, TYPE_, and Type_::xid.
Referenced by check_Stmt().
 {
   CHECK_OB(check_Expression(env, stmt->cond))
   switch(stmt->cond->type->xid) {
   case te_int:
   case te_float:
   case te_dur:
   case te_time:
     break;
   default:
     // check for IO
     if( isa( stmt->cond->type, &t_io ) > 0)
       break;
     if(isa(stmt->cond->type, &t_object) > 0) // added 12/09/16
       break;
     // error
     err_msg(TYPE_, stmt->cond->pos,
             "invalid type '%s' in if condition", stmt->cond->type->name);
     return -1;
   }
   if(check_Stmt(env, stmt->if_body) < 0)
     return -1;
   if( stmt->else_body )
     if(check_Stmt(env, stmt->else_body) < 0)
       return -1;
   return 1;
 }
check_Loop()
static m_bool check_Loop (Env env, Stmt_Loop stmt) static
Definition at line 1894 of file type.c.
References Stmt_Loop_::body, Env_::breaks, Expression_::cast_to, check_Expression(), check_Stmt(), Stmt_Loop_::cond, err_msg(), isa(), Stmt_Loop_::pos, Stmt_Loop_::self, t_float, t_int, TYPE_, vector_append(), and vector_pop().
Referenced by check_Stmt().
 {
   Type type = check_Expression(env, stmt->cond);
   if(!type)
     return -1;
   if(isa( type, &t_float))
     stmt->cond->cast_to = &t_int;
   else if(isa( type, &t_int) < 0) { // must be int
     err_msg(TYPE_, stmt->pos,
             "loop * conditional must be of type 'int'..." );
     return -1;
   }
   vector_append(env->breaks, (vtype)stmt->self);
   if(check_Stmt(env, stmt->body) < 0)
     return -1;
   vector_pop(env->breaks);
   return 1;
 }
check_op()
static Type check_op (Env env, Operator op, Expression lhs, Expression rhs, Binary_Expression * binary) static
Definition at line 771 of file type.c.
References Type_::array_depth, Type_::array_type, check_Func_Call1(), compat_func(), Env_::curr, Primary_Expression::d, Expression_::d, Decl_Expression_type, Func_::def, Dot_Member_type, err_msg(), Expression_::exp_decl, Expression_::exp_dot, Expression_::exp_primary, Expression_::exp_type, find_value(), Type_::func, Binary_Expression::func, Value_::func_num_overloads, Value_::func_ref, get_return_type(), insert_symbol(), Value_::is_member, isa(), Binary_Expression::lhs, Decl_Expression::list, Value_::m_type, NameSpace_::name, Type_::name, Func_Def_::name, namespace_lookup_func(), namespace_lookup_value(), Binary_Expression::op, op2str(), op_at_chuck, op_chuck, op_shift_left, Value_::owner_class, Binary_Expression::pos, Func_Def_::pos, Primary_Expression_type, Binary_Expression::rhs, S_name(), Var_Decl_List_::self, strcat(), Dot_Member::t_base, t_null, t_object, t_varobj, Expression_::type, TYPE_, Var_Decl_::value, Func_::value_ref, Primary_Expression::var, and Dot_Member::xid.
Referenced by check_Binary_Expression().
 {
 #ifdef DEBUG_TYPE
   debug_msg("check", "'%s' %s '%s'", lhs->type->name, op2str(op), rhs->type->name);
 #endif
   Type t;
   if(op == op_chuck && isa(binary->rhs->type, &t_func_ptr) > 0) {
     err_msg(TYPE_, binary->pos, "use '@=>' to assign to function pointer.");
     return NULL;
   }
   if(op == op_at_chuck &&  isa(binary->lhs->type, &t_function) > 0 && isa(binary->rhs->type, &t_func_ptr) > 0) {
     Type r_nspc, l_nspc = NULL;
     m_uint i;
     Func f1, f2 = NULL;
     Value v;
     char name[1024];
     Type ret_type;
     if(isa(binary->lhs->type, &t_func_ptr) > 0) {
       err_msg(TYPE_, binary->pos, "can't assign function pointer to function pointer for the moment. sorry.");
       v = namespace_lookup_value(env->curr, binary->lhs->d.exp_primary->d.var, 1);
       return NULL;
     }
     if(binary->rhs->exp_type == Primary_Expression_type) {
       v = namespace_lookup_value(env->curr, binary->rhs->d.exp_primary->d.var, 1);
       f1 = (v->owner_class && v->is_member) ? v->func_ref :namespace_lookup_func(env->curr, insert_symbol(v->m_type->name), -1);
     } else if(binary->rhs->exp_type == Dot_Member_type) {
       v = find_value(binary->rhs->d.exp_dot->t_base, binary->rhs->d.exp_dot->xid);
       f1 = v->func_ref;
     } else if(binary->rhs->exp_type == Decl_Expression_type) {
       v = binary->rhs->d.exp_decl->list->self->value;
       f1 = v->m_type->func;
     } else {
       err_msg(TYPE_, binary->pos, "unhandled function pointer assignement (rhs).");
       return NULL;
     }
     r_nspc = (v->owner_class && v->is_member) ? v->owner_class : NULL; // get owner
     if(binary->lhs->exp_type == Primary_Expression_type) {
       v = namespace_lookup_value(env->curr, binary->lhs->d.exp_primary->d.var, 1);
       f2 = namespace_lookup_func(env->curr, insert_symbol(v->m_type->name), 1);
       l_nspc = (v->owner_class && v->is_member) ? v->owner_class : NULL; // get owner
     } else if(binary->lhs->exp_type == Dot_Member_type) {
       v = find_value(binary->lhs->d.exp_dot->t_base, binary->lhs->d.exp_dot->xid);
       f2 = v->func_ref;
       l_nspc = (v->owner_class && v->is_member) ? v->owner_class : NULL; // get owner
     } else {
       err_msg(TYPE_, binary->pos, "unhandled function pointer assignement (lhs).");
       return NULL;
     }
     if((r_nspc && l_nspc) && (r_nspc != l_nspc)) {
       err_msg(TYPE_, binary->pos, "can't assign member function to member function pointer of an other class");
       return NULL;
     }
     if(!r_nspc && l_nspc) {
       err_msg(TYPE_, binary->pos, "can't assign member function to non member function pointer");
       return NULL;
     }
     if(r_nspc && !l_nspc) {
       err_msg(TYPE_, binary->pos, "can't assign non member function to member function pointer");
       return NULL;
     }
     for(i = 0; i <= v->func_num_overloads; i++) {
       if(binary->lhs->exp_type == Primary_Expression_type) {
         m_str c = f2 && f2->def ? S_name(f2->def->name) : NULL;
         sprintf(name, "%s@%li@%s", c, i, env->curr->name);
         f2 = namespace_lookup_func(env->curr, insert_symbol(name), 1);
       }
       if(f1 && f2 && compat_func(f1->def, f2->def, f2->def->pos) > 0) {
         binary->func = f2;
         ret_type = f1->value_ref->m_type;
         return ret_type;
       }
     }
     err_msg(TYPE_, 0, "not match found for function '%s'", f2 ? S_name(f2->def->name) : "[broken]");
     return NULL;
   }
   // check for arrays
   if((lhs->type->array_depth == rhs->type->array_depth + 1) && op == op_shift_left && isa(lhs->type->array_type, rhs->type) > 0)
     return lhs->type;
   if((lhs->type->array_depth || rhs->type->array_depth) && (op == op_at_chuck && lhs->type->array_depth == rhs->type->array_depth))
     return rhs->type;
   if(isa(binary->rhs->type, &t_function) > 0 && binary->op == op_chuck)
     return check_Func_Call1(env, rhs, lhs, &binary->func, binary->pos);
   if(isa(binary->rhs->type, &t_object) > 0 && isa(binary->lhs->type, &t_null) > 0 && binary->op == op_at_chuck)
     return lhs->type;
   if(isa(binary->lhs->type, &t_varobj) > 0 && binary->op == op_at_chuck)
     return rhs->type;
   if(isa(binary->rhs->type, binary->lhs->type) > 0 && binary->op == op_at_chuck)
     return rhs->type;
   if((t = get_return_type(env, op, lhs->type, rhs->type)))
     return t;
   m_uint i;
   char la[256], ra[256];
   memset(la, 0, 256);
   memset(ra, 0, 256);
   for(i = 0; i < lhs->type->array_depth; i++)
     strcat(la, "[]");
   for(i = 0; i < rhs->type->array_depth; i++)
     strcat(ra, "[]");
   err_msg(TYPE_, 0, "not match found for operator '%s' on types '%s%s' and '%s%s'",
           op2str(op), lhs->type->name, la, rhs->type->name, ra);
   return NULL;
 }
check_Postfix_Expression()
static Type check_Postfix_Expression (Env env, Postfix_Expression * postfix) static
Definition at line 1007 of file type.c.
References check_Expression(), Expression_::emit_var, err_msg(), Postfix_Expression::exp, isa(), Type_::name, Postfix_Expression::op, op2str(), op_minusminus, op_plusplus, Postfix_Expression::pos, t_float, t_int, and TYPE_.
Referenced by check_Expression().
 {
   // check the exp
   Type t = check_Expression(env, postfix->exp);
   if( !t ) return NULL;
   // syntax
   switch( postfix->op ) {
   case op_plusplus:
   case op_minusminus:
     // see scan1
     // assignable?
     /*if(((postfix->exp->meta != ae_meta_var) || (postfix->exp->exp_type == Primary_Expression_type)) &&*/
     /*postfix->exp->d.exp_primary->value->is_const) {*/
     /*err_msg(TYPE_, postfix->exp->pos,*/
     /*"postfix operator '%s' cannot be used on non-mutable data-type...",*/
     /*op2str( postfix->op ) );*/
     /*return NULL;*/
     /*}*/
     postfix->exp->emit_var = 1;
     // TODO: mark somewhere we need to post increment
     // check type
     if(isa(t, &t_int) > 0 || isa(t, &t_float) > 0)
       return t;
     break;
   default:
     // no match
     err_msg( TYPE_, postfix->pos,
              "internal compiler error: unrecognized postfix '%i'", postfix->op );
     return NULL;
   }
   // no match
   err_msg( TYPE_, postfix->pos,
            "no suitable resolutation for postfix operator '%s' on type '%s'...",  op2str(postfix->op), t->name );
   return NULL;
 }
check_Primary_Expression()
static Type check_Primary_Expression (Env env, Primary_Expression * primary) static
Definition at line 556 of file type.c.
References ae_key_static, ae_meta_value, ae_meta_var, ae_primary_array, ae_primary_char, ae_primary_complex, ae_primary_float, ae_primary_hack, ae_primary_nil, ae_primary_num, ae_primary_polar, ae_primary_str, ae_primary_var, ae_primary_vec, Expression_::cast_to, check_array_lit(), check_Expression(), CHECK_OO, check_Vec(), Value_::checked, Env_::class_def, Primary_Expression::cmp, Env_::curr, Primary_Expression::d, Decl_Expression_type, Func_::def, err_msg(), Primary_Expression::exp, Expression_::exp_type, find_value(), Env_::func, Complex::im, Value_::is_const, Func_::is_member, Value_::is_member, Value_::is_static, isa(), Value_::m_type, Expression_::meta, Polar::mod, Type_::name, namespace_lookup_value(), Expression_::next, Polar::phase, Primary_Expression::polar, Complex::pos, Polar::pos, Primary_Expression::pos, Complex::re, S_name(), Primary_Expression::self, Func_Def_::static_decl, t_complex, t_float, t_int, t_now, t_null, t_polar, t_shred, t_string, t_void, Primary_Expression::type, Expression_::type, TYPE_, Primary_Expression::value, and Primary_Expression::var.
Referenced by check_Expression().
 {
 #ifdef DEBUG_TYPE
   debug_msg("check", "primary");
 #endif
   Type  t   = NULL;
   Value v   = NULL;
   m_str str;
   switch(primary->type) {
   case ae_primary_var:
     str = S_name(primary->d.var);      // first look for reserved words
     if(!strcmp(str, "this")) { // this
       // in class def
       if( !env->class_def ) {
         err_msg(TYPE_, primary->pos, "keyword 'this' can be used only inside class definition..." );
         return NULL;
       }
       // in member func
       if( env->func && !env->func->is_member ) {
         err_msg(TYPE_, primary->pos, "keyword 'this' cannot be used inside static functions..." );
         return NULL;
       }
       // not assignable
       primary->self->meta = ae_meta_value;
       // whatever the class is
       t = env->class_def;
     } else if(!strcmp(str, "me")) {
       primary->self->meta = ae_meta_value;
       t = &t_shred;
     } else if(!strcmp(str, "now")) {
       /*        primary->self->meta = ae_meta_value;*/
       primary->self->meta = ae_meta_var;
       t = &t_now;
     } else if(!strcmp(str, "NULL") || !strcmp(str, "null")) {
       /*        primary->self->meta = ae_meta_value;*/
       primary->self->meta = ae_meta_var;
       t = &t_null;
     } else if(!strcmp(str, "true") || !strcmp(str, "false") || !strcmp(str, "maybe")) {
       primary->self->meta = ae_meta_value;
       t = &t_int;
     } else {
       v = namespace_lookup_value(env->curr, primary->d.var, 1);
       if(!v)
         v = find_value(env->class_def, primary->d.var);
       if(v) {
         if(env->class_def && env->func) {
           if(env->func->def->static_decl == ae_key_static && v->is_member && !v->is_static ) {
             err_msg(TYPE_, primary->pos, "non-static member '%s' used from static function...", S_name(primary->d.var) );
             return NULL;
           }
         }
       }
       // check me
       if(!v || !v->checked) {
         str = S_name(primary->d.var);
         err_msg(TYPE_, primary->pos, "variable %s not legit at this point.",
                 str ? str : "", v);
         return NULL;
       }
       t = v->m_type;
       primary->value = v;
     }
     if(v && v->is_const == 2) // hack for enum
       primary->self->meta = ae_meta_value;
     break;
   case ae_primary_num:
     t = &t_int;
     break;
   case ae_primary_float:
     t = &t_float;
     break;
   case ae_primary_complex:
     if(!primary->d.cmp->im) {
       err_msg(TYPE_, primary->d.cmp->pos, "missing imaginary component of complex value...");
       return NULL;
     }
     if(primary->d.cmp->im->next) {
       err_msg(TYPE_, primary->d.cmp->pos, "extraneous component of complex value...");
       return NULL;
     }
     CHECK_OO(check_Expression(env, primary->d.cmp->re))
     /*      CHECK_OO(check_Expression(env, primary->cmp->im))*/
     if(isa(primary->d.cmp->re->type, &t_float) < 0) {
       if(isa(primary->d.cmp->re->type, &t_int) < 0) {
         err_msg(TYPE_, primary->d.cmp->pos,
                 "invalid type '%s' in real component of complex value...\n"
                 "    (must be of type 'int' or 'float')", primary->d.cmp->re->type->name);
         return NULL;
       }
       primary->d.cmp->re->cast_to = &t_float;
     }
     if(isa(primary->d.cmp->im->type, &t_float) < 0) {
       if(isa(primary->d.cmp->im->type, &t_int) < 0) {
         err_msg(TYPE_, primary->d.cmp->pos,
                 "invalid type '%s' in imaginary component of complex value...\n"
                 "    (must be of type 'int' or 'float')", primary->d.cmp->im->type->name);
         return NULL;
       }
       primary->d.cmp->im->cast_to = &t_float;
     }
     t = &t_complex;
     break;
   case ae_primary_polar:
     if(!primary->d.polar->phase) {
       err_msg(TYPE_, primary->d.polar->pos, "missing phase component of polar value...");
       return NULL;
     }
     if(primary->d.polar->phase->next) {
       err_msg(TYPE_, primary->d.polar->pos, "extraneous component of polar value...");
       return NULL;
     }
     CHECK_OO(check_Expression(env, primary->d.polar->mod))
     /*      CHECK_OO(check_Expression(env, primary->polar->phase))*/
     if(isa(primary->d.polar->mod->type, &t_float) < 0) {
       if(isa(primary->d.polar->mod->type, &t_int) < 0) {
         err_msg(TYPE_, primary->d.polar->pos,
                 "invalid type '%s' in modulus component of polar value...\n"
                 "    (must be of type 'int' or 'float')", primary->d.polar->mod->type->name);
         return NULL;
       }
       primary->d.polar->mod->cast_to = &t_float;
     }
     if(isa(primary->d.polar->phase->type, &t_float) < 0) {
       if(isa(primary->d.polar->phase->type, &t_int) < 0) {
         err_msg(TYPE_, primary->d.polar->pos,
                 "invalid type '%s' in phase component of polar value...\n"
                 "    (must be of type 'int' or 'float')", primary->d.polar->phase->type->name);
         return NULL;
       }
       primary->d.polar->phase->cast_to = &t_float;
     }
     t = &t_polar;
     break;
   case ae_primary_vec:
     t = check_Vec(env, primary);
     break;
   case ae_primary_nil:
     t = &t_void;
     break;
   case ae_primary_str:
     t = &t_string;
     break;
   case ae_primary_hack:
     if(primary->d.exp->exp_type == Decl_Expression_type) {
       err_msg(TYPE_, primary->pos, "cannot use <<< >>> on variable declarations...\n");
       return NULL;
     }
     CHECK_OO((t = check_Expression(env, primary->d.exp)))
     break;
   case ae_primary_array:
     t = check_array_lit(env, primary);
     break;
   case ae_primary_char:
     t = &t_int;
     break;
   default:
     err_msg(TYPE_, primary->pos, "internal error - unrecognized primary type '%i'...", primary->type);
     return NULL;
   }
   return primary->self->type = t;
 }
check_Return()
static m_bool check_Return (Env env, Stmt_Return stmt) static
Definition at line 1943 of file type.c.
References check_Expression(), CHECK_OB, Func_::def, err_msg(), Env_::func, isa(), isprim(), Type_::name, Stmt_Return_::pos, Func_Def_::ret_type, t_null, t_void, TYPE_, Stmt_Return_::val, and Type_::xid.
Referenced by check_Stmt().
 {
   Type ret_type = NULL;
   if(!env->func) {
     err_msg(TYPE_, stmt->pos, "'return' statement found outside function definition");
     return -1;
   }
   if(stmt->val) {
     CHECK_OB((ret_type = check_Expression(env, stmt->val)))
   } else
     ret_type = &t_void;
   if(ret_type->xid == t_null.xid && isprim(env->func->def->ret_type) < 0)
     return 1;
   if(isa(ret_type, env->func->def->ret_type) < 0) {
     err_msg(TYPE_, stmt->pos,
             "invalid return type '%s' -- expecting '%s'",
             ret_type->name, env->func->def->ret_type->name);
     return -1;
   }
   return 1;
 }
check_Stmt()
static m_bool check_Stmt (Env env, Stmt * stmt) static
Definition at line 2030 of file type.c.
References ae_stmt_break, ae_stmt_case, ae_stmt_code, ae_stmt_continue, ae_stmt_enum, ae_stmt_exp, ae_stmt_for, ae_stmt_funcptr, ae_stmt_gotolabel, ae_stmt_if, ae_stmt_loop, ae_stmt_return, ae_stmt_switch, ae_stmt_union, ae_stmt_until, ae_stmt_while, check_Break(), check_Case(), check_Continue(), check_Decl_Expression(), check_Enum(), check_Expression(), check_For(), check_Func_Ptr(), check_Goto_Label(), check_If(), check_Loop(), CHECK_OB, check_Return(), check_Stmt_Code(), check_Switch(), check_Until(), check_While(), Env_::class_def, Env_::class_scope, Env_::curr, Stmt::d, err_msg(), Union::l, Decl_Expression::m_type, namespace_pop_value(), namespace_push_value(), Decl_List_::next, Union::o, Type_::obj_size, Stmt::pos, Union::s, Decl_List_::self, Type_::size, Stmt::stmt_break, Stmt::stmt_case, Stmt::stmt_code, Stmt::stmt_continue, Stmt::stmt_enum, Stmt::stmt_exp, Stmt::stmt_for, Stmt::stmt_funcptr, Stmt::stmt_gotolabel, Stmt::stmt_if, Stmt::stmt_loop, Stmt::stmt_return, Stmt::stmt_switch, Stmt::stmt_union, Stmt::stmt_until, Stmt::stmt_while, Stmt::type, and TYPE_.
Referenced by check_For(), check_If(), check_Loop(), check_Stmt_List(), check_Switch(), check_Unary(), check_Until(), and check_While().
 {
 #ifdef DEBUG_TYPE
   debug_msg("check", "stmt");
 #endif
   m_bool ret = 1;
   Decl_List l;
   if( !stmt )
     return 1;
   switch( stmt->type ) {
   case ae_stmt_exp:
     if(stmt->d.stmt_exp)
       ret = (check_Expression(env, stmt->d.stmt_exp) ? 1 : -1);
     break;
   case ae_stmt_code:
     env->class_scope++;
     ret = check_Stmt_Code( env, stmt->d.stmt_code, 1);
     env->class_scope--;
     break;
   case ae_stmt_return:
     ret = check_Return(env, stmt->d.stmt_return);
     break;
   case ae_stmt_break:
     ret = check_Break(env, stmt->d.stmt_break);
     break;
   case ae_stmt_continue:
     ret = check_Continue(env, stmt->d.stmt_continue);
     break;
   case ae_stmt_if:
     env->class_scope++;
     namespace_push_value(env->curr);
     ret = check_If(env, stmt->d.stmt_if);
     namespace_pop_value(env->curr);
     env->class_scope--;
     break;
   case ae_stmt_while:
     env->class_scope++;
     namespace_push_value(env->curr);
     ret = check_While( env, stmt->d.stmt_while);
     namespace_pop_value(env->curr);
     env->class_scope--;
     break;
   case ae_stmt_until:
     env->class_scope++;
     namespace_push_value(env->curr);
     ret = check_Until( env, stmt->d.stmt_until);
     namespace_pop_value(env->curr);
     env->class_scope--;
     break;
   case ae_stmt_for:
     env->class_scope++;
     namespace_push_value(env->curr);
     ret = check_For( env, stmt->d.stmt_for);
     namespace_pop_value(env->curr);
     env->class_scope--;
     break;
   case ae_stmt_loop:
     env->class_scope++;
     namespace_push_value(env->curr);
     ret = check_Loop( env, stmt->d.stmt_loop);
     namespace_pop_value(env->curr);
     env->class_scope--;
     break;
   case ae_stmt_switch:
     env->class_scope++;
     namespace_push_value(env->curr);
     ret = check_Switch( env, stmt->d.stmt_switch);
     namespace_pop_value(env->curr);
     env->class_scope--;
     break;
   case ae_stmt_case:
     ret = check_Case(env, stmt->d.stmt_case);
     break;
   case ae_stmt_enum:
     ret = check_Enum(env, stmt->d.stmt_enum);
     break;
   case ae_stmt_gotolabel:
     ret = check_Goto_Label(env, stmt->d.stmt_gotolabel);
     break;
   case ae_stmt_funcptr:
     ret = check_Func_Ptr(env, stmt->d.stmt_funcptr);
     break;
   case ae_stmt_union:
     l = stmt->d.stmt_union->l;
     if(env->class_def) {
       stmt->d.stmt_union->o = env->class_def->obj_size;
     }
     while(l) {
       CHECK_OB(check_Decl_Expression(env, l->self))
       if(l->self->m_type->size > stmt->d.stmt_union->s)
         stmt->d.stmt_union->s = l->self->m_type->size;
       l = l->next;
     }
     ret = 1;
     break;
   default:
     err_msg(TYPE_, stmt->pos, "invalid statement type '%i'", stmt->type);
     return -1;
   }
   return ret;
 }
check_Stmt_Code()
static m_bool check_Stmt_Code (Env env, Stmt_Code stmt, m_bool push) static
Definition at line 1776 of file type.c.
References check_Stmt_List(), Env_::class_scope, Env_::curr, namespace_pop_value(), namespace_push_value(), and Stmt_Code_::stmt_list.
Referenced by check_Func_Def(), and check_Stmt().
 {
   m_bool ret;
   env->class_scope++;
   if(push)
     namespace_push_value(env->curr);
   ret = check_Stmt_List( env, stmt->stmt_list );
   if(push)
     namespace_pop_value(env->curr);
   env->class_scope--;
   return ret;
 }
check_Stmt_List()
static m_bool check_Stmt_List (Env env, Stmt_List list) static
Definition at line 2133 of file type.c.
References CHECK_BB, check_Stmt(), Stmt_List_::next, and Stmt_List_::stmt.
Referenced by check_Class_Def(), check_Context(), and check_Stmt_Code().
 {
 #ifdef DEBUG_TYPE
   debug_msg("check", "statement list");
 #endif
   Stmt_List curr = list;
   while(curr) {
     CHECK_BB(check_Stmt(env, curr->stmt))
     curr = curr->next;
   }
   return 1;
 }
check_Switch()
static m_bool check_Switch (Env env, Stmt_Switch a) static
Definition at line 1984 of file type.c.
References check_Expression(), check_Stmt(), err_msg(), Type_::name, Stmt_Switch_::pos, Stmt_Switch_::stmt, t_int, TYPE_, Stmt_Switch_::val, and Type_::xid.
Referenced by check_Stmt().
 {
   Type t = check_Expression(env, a->val);
   if(!t || t->xid !=  t_int.xid) {
     err_msg(TYPE_, a->pos, "invalid type '%s' in switch expression. should be 'int'", t ? t->name : "unknown");
     return -1;
   }
   if(check_Stmt(env, a->stmt) < 0) {
     err_msg(TYPE_, a->pos, "\t... in switch statement");
     return -1;
   }
   return 1;
 }
check_Unary()
static Type check_Unary (Env env, Unary_Expression * exp_unary) static
check exp_unary expression
Definition at line 1496 of file type.c.
References ae_meta_var, Unary_Expression::array, Type_::array_type, check_array_subscripts(), CHECK_BO, check_Expression(), CHECK_OO, check_Stmt(), Env_::class_scope, Unary_Expression::code, Env_::curr, Expression_::d, Array_Sub_::depth, Expression_::emit_var, err_msg(), Unary_Expression::exp, Array_Sub_::exp_list, Expression_::exp_primary, Expression_::exp_type, find_type(), free(), free_Array_Sub(), Env_::func, Func_Call_type, Value_::is_const, isa(), Expression_::meta, Type_::name, namespace_pop_value(), namespace_push_value(), new_array_type(), Type_::obj, Unary_Expression::op, op2str(), op_and, op_assign, op_at_chuck, op_at_unchuck, op_chuck, op_divide, op_divide_chuck, op_eq, op_exclamation, op_ge, op_gt, op_le, op_lt, op_minus, op_minus_chuck, op_minusminus, op_modulo_chuck, op_neq, op_new, op_or, op_percent, op_plus, op_plus_chuck, op_plusplus, op_rand, op_rdec, op_req, op_rge, op_rgt, op_rinc, op_rle, op_rlt, op_rneq, op_ror, op_rsand, op_rsl, op_rsor, op_rsr, op_rsxor, op_rundec, op_runinc, op_s_and, op_s_or, op_s_xor, op_shift_left, op_shift_right, op_sizeof, op_spork, op_tilda, op_times, op_times_chuck, op_trig, op_typeof, op_unchuck, op_untrig, Unary_Expression::pos, Primary_Expression_type, Type_Decl::ref, t_array, t_dur, t_float, t_int, t_object, t_shred, t_time, Unary_Expression::type, TYPE_, Primary_Expression::value, verify_array(), and Type_Decl::xid.
Referenced by check_Expression().
 {
   Type t = NULL;
   if(exp_unary->exp) {
     if(exp_unary->op == op_new) {
       err_msg(TYPE_, exp_unary->pos, "internal error: exp_unary expression not with 'new'");
       return NULL;
     }
     t = check_Expression(env, exp_unary->exp);
     if(!t)
       return NULL;
   }
   // check code stmt; this is to eventually support sporking of code (added 1.3.0.0)
   if(exp_unary->code)
     CHECK_BO(check_Stmt(env, exp_unary->code))
     switch(exp_unary->op) {
     case op_plusplus:
     case op_minusminus:
       // assignable?
       /* coverity[var_deref_op : FALSE] */
       if((exp_unary->exp->meta != ae_meta_var || exp_unary->exp->exp_type == Primary_Expression_type) &&
           exp_unary->exp->d.exp_primary->value->is_const)
         //if(exp_unary->exp->meta != ae_meta_var)
       {
         err_msg(TYPE_, exp_unary->pos,
                 "prefix exp_unary operator '%s' cannot "
                 "be used on non-mutable data-types...", op2str( exp_unary->op ) );
         return NULL;
       }
       // assign
       exp_unary->exp->emit_var = 1;
       // check type
       if(isa(t, &t_int) > 0 || isa(t, &t_float) > 0)
         return t;
       // TODO: check overloading
       break;
     case op_minus:
       if(isa(t, &t_int) || isa(t, &t_float) > 0)
         return t;
       break;
     case op_tilda:
     case op_exclamation:
       /* coverity[var_deref_model : FALSE] */
       if(isa(t, &t_int) > 0 || isa(t, &t_object) > 0 || isa(t, &t_float) > 0 || isa(t, &t_time) > 0 || isa(t,
         &t_dur) > 0)
         return &t_int;
       break;
     case op_spork:
       if(exp_unary->exp && exp_unary->exp->exp_type == Func_Call_type) return &t_shred;
       // spork shred (by code segment)
       else if(exp_unary->code) {
         // TODO : in class
         if(env->func) {
           env->class_scope++;
           namespace_push_value(env->curr);
           int ret = check_Stmt(env, exp_unary->code);
           namespace_pop_value(env->curr);
           env->class_scope--;
           if(ret < 0)
             return NULL;
           else return &t_shred;
           break;
         } else if(check_Stmt(env, exp_unary->code) < 0) {
           err_msg(TYPE_, exp_unary->pos, "problem in evaluating sporked code");
           break;
         }
         return &t_shred;
       }
       // got a problem
       else {
         err_msg(TYPE_,  exp_unary->pos, "only function calls can be sporked..." );
         return NULL;
       }
       break;
     case op_new:
       t = find_type(env, exp_unary->type->xid);
       if(!t) {
         err_msg(TYPE_,  exp_unary->pos,
                 "... in 'new' expression ..." );
         return NULL;
       }
       if(exp_unary->array) {
         CHECK_BO(verify_array(exp_unary->array))
         if(!exp_unary->array->exp_list) {
           err_msg(TYPE_, exp_unary->pos, "cannot use empty [] with 'new'..." );
           return NULL;
         }
         CHECK_OO(check_Expression(env, exp_unary->array->exp_list))
         CHECK_BO(check_array_subscripts(env, exp_unary->array->exp_list))
         t = new_array_type(env, &t_array, exp_unary->array->depth, t, env->curr);
       }
       if(isa(t->array_type ? t->array_type : t, &t_object) < 0) {
         err_msg(TYPE_,  exp_unary->pos,
                 "cannot instantiate/(new) primitive type '%s'...",
                 t->name);
         err_msg(TYPE_,  exp_unary->pos,
                 "...(primitive types: 'int', 'float', 'time', 'dur')" );
         if(exp_unary->array)
           free_Array_Sub(exp_unary->array);
         free(t->obj);
         free(t);
         return NULL;
       }
       if( exp_unary->type->ref && !exp_unary->array ) {
         err_msg(TYPE_,  exp_unary->pos,
                 "cannot instantiate/(new) single object references (@)..." );
         return NULL;
       }
       return t;
       break;
     // avoid comiler warning
     case op_assign:
     case op_plus:
     case op_times:
     case op_divide:
     case op_percent:
     case op_and:
     case op_or:
     case op_eq:
     case op_neq:
     case op_gt:
     case op_ge:
     case op_lt:
     case op_le:
     case op_shift_left:
     case op_shift_right:
     case op_s_or:
     case op_s_and:
     case op_s_xor:
     case op_typeof:
     case op_sizeof:
     case op_chuck:
     case op_plus_chuck:
     case op_minus_chuck:
     case op_times_chuck:
     case op_divide_chuck:
     case op_modulo_chuck:
     case op_rand:
     case op_ror:
     case op_req:
     case op_rneq:
     case op_rgt:
     case op_rge:
     case op_rlt:
     case op_rle:
     case op_rsl:
     case op_rsr:
     case op_rsand:
     case op_rsor:
     case op_rsxor:
     case op_unchuck:
     case op_rdec:
     case op_rinc:
     case op_runinc:
     case op_rundec:
     case op_at_chuck:
     case op_at_unchuck:
     case op_trig:
     case op_untrig:
       break;
     }
   err_msg(TYPE_, exp_unary->pos,
           "no suitable resolution for prefix exp_unary operator '%s' on type '%s...",
           op2str( exp_unary->op ), t->name );
   return NULL;
 }
check_Until()
static m_bool check_Until (Env env, Stmt_Until stmt) static
Definition at line 1818 of file type.c.
References Stmt_Until_::body, Env_::breaks, CHECK_BB, check_Expression(), CHECK_OB, check_Stmt(), Stmt_Until_::cond, err_msg(), isa(), Type_::name, Expression_::pos, Stmt_Until_::self, t_io, te_dur, te_float, te_int, te_time, Expression_::type, TYPE_, vector_append(), vector_pop(), and Type_::xid.
Referenced by check_Stmt().
 {
   CHECK_OB(check_Expression(env, stmt->cond))
   // ensure that conditional has valid type
   switch(stmt->cond->type->xid) {
   case te_int:
   case te_float:
   case te_dur:
   case te_time:
     break;
   default:
     if(isa(stmt->cond->type, &t_io) > 0)
       break;
     err_msg(TYPE_,  stmt->cond->pos,
             "invalid type '%s' in until condition", stmt->cond->type->name);
     return -1;
   }
   vector_append(env->breaks, (vtype)stmt->self);
   CHECK_BB(check_Stmt(env, stmt->body))
   vector_pop(env->breaks);
   return 1;
 }
check_Vec()
static Type check_Vec (Env env, Primary_Expression * exp) static
Definition at line 524 of file type.c.
References Vec_::args, Expression_::cast_to, check_Expression(), Primary_Expression::d, err_msg(), isa(), Type_::name, Expression_::next, Vec_::numdims, Primary_Expression::pos, t_float, t_int, t_vec3, t_vec4, TYPE_, and Primary_Expression::vec.
Referenced by check_Primary_Expression().
 {
   Type t = NULL;
   Vec val = exp->d.vec;
   if(val->numdims > 4) {
     err_msg(TYPE_, exp->pos,
             "vector dimensions not supported > 4...\n"
             "    --> format: @(x,y,z,w)" );
     return NULL;
   }
   Expression e = val->args;
   // count
   int count = 1;
   // loop over arguments
   while(e) {
     if(!(t = check_Expression(env, e)))
       return NULL;
     if(isa( t, &t_int) > 0) e->cast_to = &t_float;
     else if(isa( t, &t_float) < 0) {
       err_msg(TYPE_, exp->pos,
               "invalid type '%s' in vector value #%d...\n"
               "    (must be of type 'int' or 'float')", t->name, count );
       return NULL;
     }
     count++;
     e = e->next;
   }
   if(val->numdims < 4)
     return &t_vec3;
   return &t_vec4;
 }
check_While()
static m_bool check_While (Env env, Stmt_While stmt) static
Definition at line 1793 of file type.c.
References Stmt_While_::body, Env_::breaks, CHECK_BB, check_Expression(), CHECK_OB, check_Stmt(), Stmt_While_::cond, Env_::conts, err_msg(), isa(), Type_::name, Expression_::pos, Stmt_While_::self, t_io, te_dur, te_float, te_int, te_time, Expression_::type, TYPE_, vector_append(), vector_pop(), and Type_::xid.
Referenced by check_Stmt().
 {
   CHECK_OB(check_Expression(env, stmt->cond))
   switch(stmt->cond->type->xid) {
   case te_int:
   case te_float:
   case te_dur:
   case te_time:
     break;
   default:
     if(isa(stmt->cond->type, &t_io) > 0)
       break;
     err_msg(TYPE_,  stmt->cond->pos,
             "invalid type '%s' in while condition", stmt->cond->type->name);
     return -1;
   }
   vector_append(env->breaks, (vtype)stmt->self);
   vector_append(env->conts, (vtype)stmt->self);
   CHECK_BB(check_Stmt(env, stmt->body))
   vector_pop(env->breaks);
   vector_pop(env->conts);
   return 1;
 }
compat_func()
m_bool compat_func (Func_Def lhs, Func_Def rhs, int pos)
Definition at line 2218 of file type.c.
References Func_Def_::arg_list, Arg_List_::next, and Arg_List_::type.
Referenced by check_Array(), check_Cast_Expression(), check_Func_Def(), and check_op().
 {
   /*
     // make sure public/private/protected/function match
     if(lhs->func_decl != rhs->func_decl) {
       err_msg(TYPE_, pos, "function signatures differ in access modifiers..." );
       err_msg(TYPE_, pos, "(both must be one of public/private/protected/function)..." );
       return -1;
     }
   */
   Arg_List e1 = lhs->arg_list;
   Arg_List e2 = rhs->arg_list;
   //  m_uint count = 1;
   // check arguments against the definition
   while(e1 && e2) {
     // match types
     if( e1->type != e2->type ) {
       //          err_msg(TYPE_, pos, "function signatures differ in argument %i's type...", count );
       return -1;
     }
     e1 = e1->next;
     e2 = e2->next;
     //      count++;
   }
   if(e1 || e2)
     return -1;
   return 1;
 }
find_func_match()
Func find_func_match (Func up, Expression args)
Definition at line 1127 of file type.c.
References find_func_match_actual().
Referenced by check_Func_Call1(), and find_template_match().
 {
   Func func;
   func = find_func_match_actual(up, args, 0, 1);
   if(func) return func;
   func = find_func_match_actual(up, args, 1, 1);
   if(func) return func;
   func = find_func_match_actual(up, args, 0, 0);
   if(func) return func;
   func = find_func_match_actual(up, args, 1, 0);
   if(func) return func;
   return NULL;
 }
find_func_match_actual()
static Func find_func_match_actual (Func up, Expression args, m_bool implicit, m_bool specific) static
Hack
Definition at line 1070 of file type.c.
References Func_Def_::arg_list, Expression_::cast_to, Func_::def, Value_::func_ref, Func_Def_::is_variadic, isa(), Func_::next, Arg_List_::next, Expression_::next, t_float, t_int, t_null, t_object, Arg_List_::type, Expression_::type, Func_::up, and Type_::xid.
Referenced by find_func_match().
 {
   Expression e;
   Arg_List e1;
   m_uint count;
   Func func;
   int match = -1;
   // see if args is nil
   if(args && args->type == &t_void)
     args = NULL;
   while(up) {
     func = up;
     while(func) {
       e = args;
       e1 = func->def->arg_list;
       count = 1;
       while(e) {
         if(e1 == NULL) {
           if(func->def->is_variadic)
             return func;
           goto moveon;
         }
         match = specific ? e->type == e1->type : isa(e->type, e1->type);
         if(match <= 0) {
           if( implicit && e->type->xid == t_int.xid && e1->type->xid == t_float.xid )
             /*            if(implicit && isa(e->type, &t_int) > 0 && isa(e1->type, &t_float) > 0)*/
             e->cast_to = &t_float;
           /*            else */
           /*              goto moveon; // type mismatch*/
           else if(!(isa(e->type, &t_null) > 0 && isa(e1->type, &t_object) > 0))
             goto moveon; // type mismatch
         }
         e = e->next;
         e1 = e1->next;
         count++;
       }
       if( e1 == NULL ) return func;
 moveon:
       func = func->next;
     }
     // go up
     if( up->up )
       up = up->up->func_ref;
     else up = NULL;
   }
   // not found
   return NULL;
 }
find_template_match()
Func find_template_match (Env env, Value v, Func m_func, Type_List types, Expression func, Expression args)
Definition at line 1170 of file type.c.
References Func_Def_::arg_list, Func_Def_::base, check_Expression(), check_Func_Def(), Env_::class_def, Env_::class_scope, Env_::class_stack, Func_Def_::code, Env_::curr, Primary_Expression::d, Expression_::d, Func_::def, Expression_::exp_primary, find_func_match(), find_type(), find_value(), free_Func(), free_Func_Def(), Func_Def_::func, Func_Def_::func_decl, Value_::func_num_overloads, Value_::func_ref, Type_::info, insert_symbol(), Func_::is_template, Func_Def_::is_template, Func_Def_::is_variadic, Type_List_::list, NameSpace_::name, Value_::name, namespace_add_type(), namespace_lookup_value(), namespace_pop_type(), namespace_push_type(), new_Func_Def(), Func_::next, ID_List_::next, Type_List_::next, Env_::nspc_stack, Value_::owner_class, Expression_::pos, S_name(), scan1_Func_Def(), scan2_Func_Def(), Func_Def_::static_decl, Func_Def_::type_decl, Func_Def_::types, Primary_Expression::var, vector_append(), vector_back(), vector_pop(), and ID_List_::xid.
Referenced by check_Func_Call(), and check_Func_Call1().
 {
   m_uint i;
   Func_Def base;
   Value value;
   if(v->owner_class) {
     vector_append(env->nspc_stack, (vtype)env->curr);
     env->curr = v->owner_class->info;
     vector_append(env->class_stack, (vtype)env->class_def);
     env->class_def = v->owner_class;
     env->class_scope = 0; // should keep former value somewhere
   }
   for(i = 0; i < v->func_num_overloads + 1; i++) {
     char name[256];
     sprintf(name, "%s<template>@%li@%s", v->name, i, env->curr->name);
     if(v->owner_class) {
       value = find_value(v->owner_class, insert_symbol(name));
       if(!value)
         value = v;
     } else
       value = namespace_lookup_value(env->curr, insert_symbol(name), 1);
     if(!value)
       continue;
     base = value->func_ref->def;
     if(!base)
       continue;
     Func_Def def = new_Func_Def(base->func_decl, base->static_decl,
                                 base->type_decl, S_name(func->d.exp_primary->d.var),
                                 base->arg_list, base->code, func->pos);
     if(base->is_variadic)
       def->is_variadic = 1;
     Type_List list = types;
     ID_List base_t = base->types;
     def->is_template = 1;
     namespace_push_type(env->curr);
     while(base_t) {
       if(!list)
         break;
       ID_List tmp = base_t->next;;
       if(!list->list)
         break;
       namespace_add_type(env->curr, base_t->xid, find_type(env, list->list));
       base_t->next = NULL;
       base_t->next = tmp;
       if(list->next && !base_t->next) {
 //        err_msg(TYPE_, def->pos, "'%s' too many argument for template. skipping.", value->name);
         goto next;
       }
       base_t = base_t->next;
       if(!list->next && base_t) {
 //        err_msg(TYPE_, def->pos, "'%s' not enough argument for template.", value->name);
         goto next;
         //return NULL;
       }
       list = list->next;
     }
     m_int ret = scan1_Func_Def(env, def);
     namespace_pop_type(env->curr);
     if(ret < 0)
       goto next;
     if(scan2_Func_Def(env, def) < 0)
       goto next;
     if(check_Func_Def(env, def) < 0)
       goto next;
     if(!check_Expression(env, func))
       goto next;
     if(args)
       if(!check_Expression(env, args))
         goto next;
     def->func->next = NULL;
     m_func = find_func_match(def->func, args);
     if(m_func) {
       if(v->owner_class) {
         env->class_def = (Type)vector_back(env->class_stack);
         vector_pop(env->class_stack);
         env->curr = (NameSpace)vector_back(env->nspc_stack);
         vector_pop(env->nspc_stack);
       }
       m_func->is_template = 1;
       m_func->def->base = value->func_ref->def->types;
       return m_func;
     }
 next:
     namespace_pop_type(env->curr);
     if(def->func) {
       free_Func(def->func);
     }
     free_Func_Def(def);
   }
   if(v->owner_class) {
     env->class_def = (Type)vector_back(env->class_stack);
     vector_pop(env->class_stack);
     env->curr = (NameSpace)vector_back(env->nspc_stack);
     vector_pop(env->nspc_stack);
   }
   return NULL;
 }
import_soundpipe()
m_bool import_soundpipe (Env env)
Referenced by so_filter(), and type_engine_init().
mk_type_list()
static Type_List mk_type_list (Env env, Type type) static
Definition at line 1149 of file type.c.
References Env_::curr, free_Vector(), Env_::global_nspc, Type_::info, NameSpace_::name, Type_::name, new_type_list(), new_Vector(), NameSpace_::parent, prepend_id_list(), vector_append(), vector_at(), and vector_size().
Referenced by check_Func_Call1().
 {
   m_uint i;
   NameSpace nspc = type->info;
   Vector v = new_Vector();
   vector_append(v, (vtype)type->name);
   while(nspc && nspc != env->curr && nspc != env->global_nspc) {
     vector_append(v, (vtype)strdup(nspc->name));
     nspc = nspc->parent;
   }
   ID_List id = NULL;
   Type_List list = NULL;
   for(i = vector_size(v); i > 0; i--)
     id = prepend_id_list((m_str)vector_at(v, i - 1), id, 0);
   list = new_type_list(id, NULL, 0);
   free_Vector(v);
   return list;
 }
scan0_Ast()
m_bool scan0_Ast (Env , Ast)
Definition at line 163 of file scan0.c.
References ae_key_public, ae_section_class, ae_section_func, ae_section_stmt, CHECK_OB, Section::class_def, Env_::context, Section::d, Class_Def_::decl, err_msg(), Env_::global_nspc, Class_Def_::home, Ast_::next, Class_Def_::pos, Ast_::pos, Context_::public_class_def, SCAN0_, scan0_Class_Def(), scan0_Stmt_List(), Ast_::section, Section::stmt_list, and Section::type.
Referenced by type_engine_check_prog().
 {
   m_bool ret = 1;
   CHECK_OB(prog)
   while( prog && ret > 0) {
     switch( prog->section->type ) {
     case ae_section_stmt:
       ret = scan0_Stmt_List(env, prog->section->d.stmt_list);
       break;
     case ae_section_func:
       break;
     case ae_section_class:
       if( prog->section->d.class_def->decl == ae_key_public ) {
         if(env->context->public_class_def != NULL) {
           err_msg(SCAN0_, prog->section->d.class_def->pos,
                   "more than one 'public' class defined..." );
           return -1;
         }
 //        prog->section->d.class_def->home = env->user_nspc ? env->user_nspc : env->global_nspc;
         prog->section->d.class_def->home = env->global_nspc;
         env->context->public_class_def = prog->section->d.class_def;
       }
       ret = scan0_Class_Def( env, prog->section->d.class_def );
       break;
     default:
       err_msg(SCAN0_, prog->pos,
               "internal error: unrecognized program section in type checker pre-scan..." );
       ret = -1;
       break;
     }
     prog = prog->next;
   }
   return ret;
 }
scan1_Ast()
m_bool scan1_Ast (Env , Ast)
Definition at line 693 of file scan1.c.
References ae_section_class, ae_section_func, ae_section_stmt, CHECK_BB, Section::class_def, Section::d, Section::func_def, Ast_::next, scan1_Class_Def(), scan1_Func_Def(), scan1_Stmt_List(), Ast_::section, Section::stmt_list, and Section::type.
Referenced by type_engine_check_prog().
 {
 #ifdef DEBUG_SCAN1
   debug_msg("scan1", "Ast");
 #endif
   Ast prog = ast;
   m_bool ret = 1;
   while(prog && ret > 0) {
     switch(prog->section->type) {
     case ae_section_stmt:
       ret = scan1_Stmt_List(env, prog->section->d.stmt_list);
       break;
     case ae_section_func:
       ret = scan1_Func_Def(env, prog->section->d.func_def);
       break;
     case ae_section_class:
       ret = scan1_Class_Def(env, prog->section->d.class_def);
       break;
     }
     CHECK_BB(ret);
     prog = prog->next;
   }
   return ret;
 }
scan2_Ast()
m_bool scan2_Ast (Env , Ast)
Definition at line 1005 of file scan2.c.
References ae_section_class, ae_section_func, ae_section_stmt, CHECK_BB, Section::class_def, Section::d, Section::func_def, Ast_::next, scan2_Class_Def(), scan2_Func_Def(), scan2_Stmt_List(), Ast_::section, Section::stmt_list, and Section::type.
Referenced by type_engine_check_prog().
 {
 #ifdef DEBUG_SCAN2
   debug_msg("scan2", "Ast");
 #endif
   Ast prog = ast;
   m_bool ret = 1;
   while(prog && ret > 0) {
     switch(prog->section->type) {
     case ae_section_stmt:
       ret = scan2_Stmt_List(env, prog->section->d.stmt_list);
       break;
     case ae_section_func:
       ret = scan2_Func_Def(env, prog->section->d.func_def);
       break;
     case ae_section_class:
       ret = scan2_Class_Def(env, prog->section->d.class_def);
       break;
     }
     CHECK_BB(ret)
     prog = prog->next;
   }
   return ret;
 }
so_filter()
static int so_filter (const struct dirent * dir) static
Definition at line 38 of file type.c.
References import_soundpipe().
Referenced by type_engine_init().
 {
   return strstr(dir->d_name, ".so") ? 1 : 0;
 }
start_plug()
void start_plug ()
Definition at line 46 of file type.c.
References new_Vector().
Referenced by type_engine_init().
 {
   plugs = new_Vector();
 }
stop_plug()
void stop_plug ()
Definition at line 51 of file type.c.
References free_Vector(), vector_at(), and vector_size().
Referenced by free_VM().
 {
   m_uint i;
   if(!plugs)
     return;
   for(i = 0; i < vector_size(plugs); i++)
     dlclose((void*)vector_at(plugs, i));
   free_Vector(plugs);
 }
type_engine_check_prog()
m_bool type_engine_check_prog (Env env, Ast ast, m_str filename)
Definition at line 226 of file type.c.
References add_ref(), CHECK_BB, check_Context(), env_reset(), Context_::filename, free(), free_Ast(), Env_::global_nspc, insert_symbol(), Env_::known_ctx, load_context(), map_set(), namespace_commit(), namespace_rollback(), new_Context(), Context_::obj, rem_ref(), scan0_Ast(), scan1_Ast(), scan2_Ast(), and unload_context().
Referenced by compile(), and SFUN().
 {
   m_bool ret = -1;
   //  Context context = new_Context(ast, strndup(filename, strlen(filename)));
   Context context = new_Context(ast, filename);
   env_reset(env);
   if(load_context(context, env) < 0) {
     ret = -1;
     goto done;
   }
   if(scan0_Ast(env, ast) < 0) {
     ret = -1;
     goto cleanup;
   }
   /*if(scan1_Ast(env, ast) < 0)*/
   /*m_bool ret = */
   ret = scan1_Ast(env, ast);
   if(ret < 0) {
     ret = -3;
     goto cleanup;
   }
   if(scan2_Ast(env, ast) < 0) {
     ret = -1;
     goto cleanup;
   }
   if(check_Context(env, context) < 0 ) {
     ret = -5;
     goto cleanup;
   }
   ret = 1;
 cleanup:
 //    add_ref(context->obj);
   if(ret > 0) {
     namespace_commit(env->global_nspc);
     map_set(env->known_ctx, (vtype)insert_symbol(context->filename), (vtype)context);
     add_ref(context->obj);
   } else {
     namespace_rollback(env->global_nspc);
     //rem_ref(context->obj, context);
   }
   CHECK_BB(unload_context(context, env)) // no real need to check that
   if(ret < 0) {
     free_Ast(ast);
     //rem_ref(context->nspc->obj, context->nspc);
     rem_ref(context->obj, context); // breaks function pointer for now
     free(filename);
   }
 done:
   return ret;
 }
type_engine_init()
Env type_engine_init (VM * vm)
Definition at line 61 of file type.c.
References VM::adc, adc_tick(), add_global_type(), add_global_value(), add_global_value_double(), assign_ugen(), VM::bbq, VM::blackhole, CHECK_BO, Env_::context, VM::dac, dac_tick(), Ast_::doc, err_msg(), Context_::filename, free(), Env_::global_context, Env_::global_nspc, import_analys(), import_array(), import_complex(), import_event(), import_fileio(), import_float(), import_int(), import_lib(), import_machine(), import_modules(), import_object(), import_shred(), import_soundpipe(), import_string(), import_ugen(), import_vec3(), import_vec4(), insert_symbol(), Env_::known_ctx, map_set(), namespace_commit(), new_Env(), new_M_UGen(), Context_::nspc, so_filter(), BBQ_::sp, start_plug(), start_type_xid(), t_dur, t_float, t_ugen, UGen_::tick, Context_::tree, TYPE_, VM::ugen, M_Object_::ugen, and vector_append().
Referenced by main().
 {
   Env env = new_Env();
   /* add primitive types */
   CHECK_BO(add_global_type(env, &t_void))
   CHECK_BO(import_int(env))
   /* coverity[leaked_storage : FALSE] */
   CHECK_BO(import_float(env))
   CHECK_BO(import_complex(env))
   CHECK_BO(import_vec3(env))
   CHECK_BO(import_vec4(env))
   // base object types
   CHECK_BO(import_object(env))
   CHECK_BO(import_string(env))
   CHECK_BO(import_shred(env))
   CHECK_BO(import_event(env))
   CHECK_BO(import_ugen(env))
   CHECK_BO(import_array(env))
 //  CHECK_BO(import_io(env))
   start_type_xid();
   // event child
   CHECK_BO(import_fileio(env))
   // libs
   CHECK_BO(import_lib(env))
   CHECK_BO(import_machine(env))
   // SOUNDPIPE
   CHECK_BO(import_soundpipe(env))
   CHECK_BO(import_analys(env))
   // additionnal UGen modules
   CHECK_BO(import_modules(env))
   vm->dac       = new_M_UGen();
   vm->adc       = new_M_UGen();
   vm->blackhole = new_M_UGen();
   assign_ugen(vm->dac->ugen, 2, 2, 0, vm->bbq->sp);
   assign_ugen(vm->adc->ugen, 2, 2, 0, vm->bbq);
   assign_ugen(vm->blackhole->ugen, 1, 1, 0, vm->bbq->sp);
   vm->dac->ugen->tick = dac_tick;
   vm->adc->ugen->tick = adc_tick;
   vector_append(vm->ugen, (vtype)vm->blackhole->ugen);
   vector_append(vm->ugen, (vtype)vm->dac->ugen);
   vector_append(vm->ugen, (vtype)vm->adc->ugen);
   add_global_value(env, "adc",               &t_ugen,   1, vm->adc);
   add_global_value(env, "dac",               &t_ugen,   1, vm->dac);
   add_global_value(env, "blackhole",         &t_ugen,   1, vm->blackhole);
   add_global_value_double(env, "d_zero",     &t_dur,    0.);
   add_global_value_double(env, "samp",       &t_dur,    1.);
   add_global_value_double(env, "samplerate", &t_float,  (m_float)(vm->bbq->sp->sr));
   add_global_value_double(env, "ms",         &t_dur,    (m_float)(vm->bbq->sp->sr) / 1000.);
   add_global_value_double(env, "second",     &t_dur,    (m_float)vm->bbq->sp->sr);
   add_global_value_double(env, "minute",     &t_dur,    (m_float)60 * vm->bbq->sp->sr);
   add_global_value_double(env, "hour",       &t_dur,    (m_float)60 * 60 * vm->bbq->sp->sr);
   add_global_value_double(env, "day",        &t_dur,    (m_float)24 * 60 * 60 * vm->bbq->sp->sr);
   add_global_value_double(env, "week",       &t_dur,    (m_float)7 * 24 * 60 * 60 * vm->bbq->sp->sr);
   /* TODO ? reserved words */
   /* commit */
   namespace_commit(env->global_nspc);
   // doc
   namespace_commit(env->context->nspc);
   map_set(env->known_ctx, (vtype)insert_symbol(env->global_context->filename), (vtype)env->global_context);
   env->global_context->tree = calloc(1, sizeof(struct Ast_));
   env->global_context->tree->doc = "this is the main context, where basic type and global variables are declared";
   // user namespace
   /*  env->user_nspc = new_NameSpace();*/
   /*  env->user_nspc->name = "[user]";*/
   /*  env->user_nspc->parent = env->global_nspc;*/
   /*  add_ref(env->global_nspc->obj);*/
   /*  add_ref(env->user_nspc->obj);*/
   /*  env->curr = env->user_nspc;*/
   // plugins
   //  void* handler;
   start_plug();
   m_str dirname = GWION_ADD_DIR;
   struct dirent **namelist;
   int n;
   n = scandir(GWION_ADD_DIR, &namelist, so_filter, alphasort);
   if (n > 0) {
     while (n--) {
       char c[256];
       sprintf(c, "%s/%s", dirname, namelist[n]->d_name);
       void* handler = dlopen(c, RTLD_LAZY);
       {
         if(!handler) {
 //          dlclose(handler);
           m_str err = dlerror();
           err_msg(TYPE_, 0, "error in %s.", err);
           free(err);
           goto next;
         }
       }
       m_bool (*import)(Env) = (m_bool (*)(Env)) (intptr_t)dlsym(handler, "import");
       if(import) {
         if(import(env) > 0)
           vector_append(plugs, (vtype)handler);
         else {
           dlclose(handler);
           goto next;
         }
       } else {
         m_str err = dlerror();
         err_msg(TYPE_, 0, "%s: no import function.", err);
         dlclose(handler);
         /*      if(err)
                 free(err); */
         goto next;
       }
 next:
       free(namelist[n]);
     }
     free(namelist);
   }
   namespace_commit(env->global_nspc);
   return env;
 }
Variable Documentation
current
Func_Call* current static
Definition at line 1169 of file type.c.
plugs
Vector plugs = NULL static
Definition at line 45 of file type.c.
t_class
struct Type_ t_class = { "@Class", SZ_INT, NULL, te_class }
Definition at line 36 of file type.c.
Referenced by add_global_type(), emit_Case(), emit_Dot_Member(), emit_symbol(), free_NameSpace(), free_Type(), INSTR(), mkadt_nspc(), mkdoc_nspc(), scan0_Class_Def(), and scan0_Func_Ptr().
t_func_ptr
struct Type_ t_func_ptr = { "@func_ptr", sizeof(m_uint), &t_function, te_func_ptr}
Definition at line 35 of file type.c.
Referenced by check_Func_Ptr(), emit_Binary_Expression(), emit_Cast_Expression(), emit_Dot_Member(), free_NameSpace(), free_Type(), INSTR(), and scan0_Func_Ptr().
t_function
struct Type_ t_function = { "@function", sizeof(m_uint), NULL, te_function }
Definition at line 34 of file type.c.
Referenced by emit_Binary_Expression(), emit_Cast_Expression(), emit_Dot_Member(), free_NameSpace(), free_Type(), INSTR(), and scan2_Func_Def().
t_void
struct Type_ t_void = { "void", 0, NULL, te_void}
Definition at line 33 of file type.c.
Referenced by check_Primary_Expression(), check_Return(), emit_Expression(), emit_Func_Def(), INSTR(), and kindof().