Gwion dev-docs: core/value.c File Reference
--- layout: default title: value_8c/ image: feature: abstract-1.jpg ---
value.c File Reference
#include <stdlib.h>
#include <complex.h>
#include "type.h"
Functions
Value new_Value (Context context, Type type, m_str name)
void free_Value (Value a)
Function Documentation
free_Value()
void free_Value (Value a)
Definition at line 24 of file value.c.
References free(), isprim(), Value_::m_type, and Value_::ptr.
Referenced by free_Var_Decl(), rem_ref(), and scan2_Func_Def().
 {
   if(a->ptr) {
     if(isprim(a->m_type) > 0)
       free(a->ptr);
   }
   free(a);
 }
new_Value()
Value new_Value (Context context, Type type, m_str name)
Definition at line 5 of file value.c.
References Value_::checked, e_value_obj, Value_::func_num_overloads, Value_::func_ref, Value_::is_const, Value_::is_context_global, Value_::is_static, Value_::m_type, Value_::name, new_VM_Object(), Value_::obj, Value_::offset, Value_::owner, Value_::owner_class, Value_::ptr, and Value_::type.
Referenced by add_global_type(), add_global_value(), add_global_value_double(), check_Func_Def(), scan0_Class_Def(), scan0_Func_Ptr(), scan1_Enum(), scan2_Decl_Expression(), and scan2_Func_Def().
 {
   Value a               = (Value)calloc(1, sizeof(struct Value_));
   a->type               = 0;
   a->m_type             = type;
   a->name               = name;
   a->ptr                = NULL;
   a->func_ref           = NULL;
   a->offset             = 0;
   a->func_num_overloads = 0;
   a->checked            = 0;
   a->is_const           = 0;
   a->is_static          = 0;
   a->is_context_global  = 0;
   a->owner              = NULL;
   a->owner_class        = NULL;
   a->obj                = new_VM_Object(e_value_obj);
   return a;
 }