Gwion dev-docs: core/vm.c File Reference
--- layout: default title: vm_8c/ image: feature: abstract-1.jpg ---
vm.c File Reference
#include <stdlib.h>
#include <time.h>
#include "vm.h"
#include "err_msg.h"
#include "type.h"
#include "instr.h"
#include "ugen.h"
#include "driver.h"
Functions
void stop_plug ()
VM_Code new_VM_Code (Vector instr, m_uint stack_depth, m_bool need_this, m_str name, m_str filename)
void free_VM_Code (VM_Code a)
VM_Shred new_VM_Shred (VM_Code c)
void free_VM_Shred (VM_Shred shred)
BBQ new_BBQ (VM *vm, DriverInfo *di, Driver **driver)
static void free_BBQ (BBQ a)
VM * new_VM (m_bool loop)
void free_VM (VM *vm)
void vm_add_shred (VM *vm, VM_Shred shred)
void vm_run (VM *vm)
Function Documentation
free_BBQ()
static void free_BBQ (BBQ a) static
Definition at line 121 of file vm.c.
References free(), BBQ_::in, and BBQ_::sp.
Referenced by free_VM().
 {
   sp_destroy(&a->sp);
   free(a->in);
   free(a);
 }
free_VM()
void free_VM (VM * vm)
Definition at line 146 of file vm.c.
References VM::bbq, VM::emit, VM::env, free(), free_BBQ(), free_Shreduler(), free_Vector(), Env_::obj, Emitter_::obj, rem_ref(), VM::shred, VM::shreduler, stop_plug(), and VM::ugen.
Referenced by main().
 {
   if(vm->env)
     rem_ref(vm->env->obj, vm->env);
   if(vm->emit)
     rem_ref(vm->emit->obj, vm->emit);
   stop_plug();
   free_Vector(vm->shred);
   free_Vector(vm->ugen);
   if(vm->bbq)
     free_BBQ(vm->bbq);
   free_Shreduler(vm->shreduler);
   free(vm);
 }
free_VM_Code()
void free_VM_Code (VM_Code a)
Definition at line 29 of file vm.c.
References Branch_Switch(), Instr_::execute, VM_Code_::filename, free(), free_Vector(), Gack(), VM_Code_::instr, Instr_Array_Alloc(), Instr_Array_Init(), VM_Code_::name, Instr_::ptr, vector_at(), vector_back(), and vector_size().
Referenced by emit_Class_Def(), free_Func(), free_NameSpace(), free_VM_Shred(), and INSTR().
 {
   m_uint i;
   if(!strcmp(a->name, "[dtor]")) { // dtor from release. free only EOC
     free((void*)vector_back(a->instr));
     free_Vector(a->instr);
   } else if(a->instr) {
       for(i = 0; i < vector_size(a->instr); i++) {
         Instr instr = (Instr)vector_at(a->instr, i);
         if(instr->execute == Instr_Array_Init || instr->execute == Instr_Array_Alloc ||
             instr->execute == Gack || instr->execute == Branch_Switch)
           free(instr->ptr);
       free((Instr)vector_at(a->instr, i));
     }
     free_Vector(a->instr);
   }
   free(a->name);
   free(a->filename);
   free(a);
 }
free_VM_Shred()
void free_VM_Shred (VM_Shred shred)
Definition at line 82 of file vm.c.
References VM_Shred_::_mem, VM_Shred_::_reg, VM_Shred_::base, VM_Shred_::code, VM_Shred_::filename, free(), free_VM_Code(), VM_Shred_::me, VM_Shred_::name, and release().
Referenced by free_NameSpace(), and shreduler_remove().
 {
   release(shred->me, shred);
   if(strstr(shred->name, "spork~"))
     free(shred->_mem);
   else
     free(shred->base);
   free(shred->_reg);
   free_VM_Code(shred->code);
   free(shred->name);
   free(shred->filename);
   free(shred);
 }
new_BBQ()
BBQ new_BBQ (VM * vm, DriverInfo * di, Driver ** driver)
Definition at line 96 of file vm.c.
References free(), containing_driver_info::func, containing_driver_info::in, BBQ_::in, driver_wrapper::ini, malloc(), BBQ_::n_in, containing_driver_info::out, BBQ_::sp, and containing_driver_info::sr.
Referenced by main(), and no_wakeup().
 {
   BBQ a = malloc(sizeof(struct BBQ_));
   Driver* d;
   if(!(d = di->func(vm)))
     goto error;
   if(d->ini(vm, di) < 0) {
     goto error;
   }
   sp_createn(&a->sp, di->out);
   free(a->sp->out);
   a->sp->out   = calloc(di->out, sizeof(SPFLOAT));
   a->in   = calloc(di->in, sizeof(SPFLOAT));
   a->n_in = di->in;
   a->sp->sr = di->sr;
   *driver = d;
   sp_srand(a->sp, time(NULL));
   return a;
 error:
   free(a);
   return NULL;
 }
new_VM()
VM* new_VM (m_bool loop)
Definition at line 128 of file vm.c.
References VM::adc, VM::bbq, VM::blackhole, VM::dac, VM::emit, VM::env, VM::is_running, malloc(), new_Shreduler(), new_Vector(), VM::shred, VM::shreduler, shreduler_set_loop(), VM::ugen, vm, and VM::wakeup.
Referenced by main().
 {
   VM* vm         = (VM*)malloc(sizeof(VM));
   vm->shred      = new_Vector();
   vm->ugen       = new_Vector();
   vm->shreduler  = new_Shreduler(vm);
   vm->env        = NULL;
   vm->emit       = NULL;
   vm->is_running = 0;
   vm->bbq        = NULL;
   vm->adc        = NULL;
   vm->dac        = NULL;
   vm->blackhole  = NULL;
   vm->wakeup     = NULL;
   shreduler_set_loop(vm->shreduler, loop < 0 ? 0 : 1);
   return vm;
 }
new_VM_Code()
VM_Code new_VM_Code (Vector instr, m_uint stack_depth, m_bool need_this, m_str name, m_str filename)
Definition at line 16 of file vm.c.
References VM_Code_::filename, VM_Code_::instr, malloc(), VM_Code_::name, VM_Code_::native_func, VM_Code_::native_func_type, NATIVE_UNKNOWN, VM_Code_::need_this, VM_Code_::stack_depth, and vector_copy().
Referenced by emit_to_code(), free_NameSpace(), mk_xtor(), release(), scan0_Class_Def(), and scan2_Func_Def().
 {
   VM_Code code           = malloc(sizeof(struct VM_Code_));
   code->instr            = instr ?  vector_copy(instr) : NULL;
   code->stack_depth      = stack_depth;
   code->need_this        = need_this;
   code->name             = strdup(name);
   code->filename         = strdup(filename);
   code->native_func      = 0;
   code->native_func_type = NATIVE_UNKNOWN;
   return code;
 }
new_VM_Shred()
VM_Shred new_VM_Shred (VM_Code c)
Definition at line 50 of file vm.c.
References VM_Shred_::_reg, VM_Shred_::args, VM_Shred_::base, VM_Shred_::child, VM_Shred_::code, VM_Shred_::filename, VM_Shred_::is_done, VM_Shred_::is_running, VM_Shred_::me, VM_Shred_::mem, VM_Code_::name, VM_Shred_::name, VM_Shred_::next, VM_Shred_::next_pc, VM_Shred_::parent, VM_Shred_::pc, VM_Shred_::prev, VM_Shred_::reg, SIZEOF_MEM, SIZEOF_REG, VM_Shred_::vm_ref, VM_Shred_::wake_time, and VM_Shred_::xid.
Referenced by compile(), free_NameSpace(), INSTR(), and release().
 {
   VM_Shred shred    = calloc(1, sizeof(struct VM_Shred_));
   shred->base       = calloc(SIZEOF_MEM, sizeof(char));
   shred->_reg       = calloc(SIZEOF_REG, sizeof(char));
   shred->reg        = shred->_reg;
   shred->mem        = shred->base;
   shred->pc         = 0;
   shred->next_pc    = 0;
   shred->code       = c;
   shred->is_done    = 0;
   shred->is_running = 1;
   shred->wake_time  = 0.;
   shred->xid        = -1;
   shred->prev       = NULL;
   shred->next       = NULL;
   shred->name       = strdup(c->name);
   shred->me         = NULL;
   shred->child      = NULL;
   shred->parent     = NULL;
   shred->vm_ref     = NULL;
   shred->args       = NULL;
   shred->me         = NULL;
   shred->filename   = NULL;
   shred->child      = NULL;
 #ifdef DEBUG_STACK
   shred->mem_index  = 0;
   shred->reg_index  = 0;
 #endif
   return shred;
 }
stop_plug()
void stop_plug ()
Definition at line 51 of file type.c.
References free_Vector(), vector_at(), and vector_size().
Referenced by free_VM().
 {
   m_uint i;
   if(!plugs)
     return;
   for(i = 0; i < vector_size(plugs); i++)
     dlclose((void*)vector_at(plugs, i));
   free_Vector(plugs);
 }
vm_add_shred()
void vm_add_shred (VM * vm, VM_Shred shred)
Definition at line 161 of file vm.c.
References get_now(), VM::shred, shredule(), VM::shreduler, vector_append(), vector_size(), vm, VM_Shred_::vm_ref, and VM_Shred_::xid.
Referenced by compile(), INSTR(), and release().
 {
   shred->vm_ref = vm;
   if(shred->xid == -1) {
     shred->xid = vector_size(vm->shred);
     vector_append(vm->shred, (vtype)shred);
   }
   shredule(vm->shreduler, shred, get_now(vm->shreduler) + .5);
 }
vm_run()
void vm_run (VM * vm)
Definition at line 171 of file vm.c.
References VM::blackhole, UGen_::channel, VM_Shred_::code, VM::dac, UGen_::done, err_msg(), Instr_::execute, VM_Code_::instr, VM_Shred_::is_done, VM::is_running, VM_Shred_::is_running, VM_Shred_::mem, UGen_::n_in, VM_Shred_::next_pc, VM_Shred_::pc, VM_Shred_::reg, VM::shreduler, shreduler_get(), shreduler_remove(), VM::ugen, M_Object_::ugen, ugen_compute(), vector_at(), vector_size(), VM_, and VM_Shred_::xid.
Referenced by alsa_run(), callback(), dummy_run(), gwion_cb(), raw_run(), silent_run(), sndfile_run(), and write_callback().
 {
   m_uint   i;
   VM_Shred shred;
   Instr    instr;
   while((shred = shreduler_get(vm->shreduler))) {
 #ifdef DEBUG_VM
     debug_msg("vm", "shred [%i]: stack: { %i:%i}. pc: (%i,%i / %i)", shred->xid, *shred->reg,
               *shred->mem, shred->pc, shred->next_pc, vector_size(shred->code->instr));
 #endif
     while(shred->is_running) {
       shred->pc = shred->next_pc;
       shred->next_pc++;
       instr = (Instr)vector_at(shred->code->instr, shred->pc);
 #ifdef DEBUG_VM
       if(!instr) {
         err_msg(VM_, 0, "internal error: no instruction");
         debug_msg("vm", "shred [%i]: pc: (%i,%i / %i)", shred->xid,
                   shred->pc, shred->next_pc, vector_size(shred->code->instr));
         break;
       } else if(!instr->execute) {
         err_msg(VM_, 0, "internal error: instruction has no execute function");
         shred->is_done = 1;
         continue;
       } else
 #endif
         instr->execute(vm, shred, instr);
 #ifdef DEBUG_STACK
       /*  else */
       debug_msg("stack", "shred[%i] mem[%i] reg[%i]", shred->xid, shred->mem_index, shred->reg_index);
 #endif
 #ifdef DEBUG_VM
       /*  else */
       debug_msg("vm", "shred [%i]: pc: (%i,%i / %i)", shred->xid, shred->pc, shred->next_pc, vector_size(shred->code->instr));
 #endif
       if(shred->is_done) {
         if(shreduler_remove(vm->shreduler, shred, 1) < 0) {
           goto next;
 //          continue;
         }
       }
     }
 next:
     ;
   }
   if(!vm->is_running) {
     return;
   }
   for(i = 0; i < vector_size(vm->ugen); i++) {
     UGen u = (UGen)vector_at(vm->ugen, i);
     u->done = 0;
     if(u->channel) {
       for(int j = 0; j < u->n_in; j++)
         u->channel[j]->ugen->done = 0;
       for(int j = 0; j < u->n_out; j++)
         u->channel[j]->ugen->done = 0;
     }
   }
   ugen_compute(vm->blackhole->ugen);
   ugen_compute(vm->dac->ugen);
 }