Gwion dev-docs: core/import.c File Reference
import.c File Reference
#include <string.h>
#include "err_msg.h"
#include "env.h"
#include "func.h"
#include "import.h"
Macros
#define CHECK_EB(a) if(!env->class_def) { err_msg(TYPE_, 0, "import error: import_xxx invoked between begin/end"); return -1; }
#define CHECK_EO(a) if(!env->class_def) { err_msg(TYPE_, 0, "import error: import_xxx invoked between begin/end"); return NULL; }
#define CHECK_FN(a) if(a < 0) { if(func_def->func) rem_ref(func_def->func->obj, func_def->func); free_Func_Def(func_def); return NULL;}
Functions
void free_Expression (Expression exp)
m_bool scan1_Decl_Expression (Env env, Decl_Expression *decl)
m_bool scan2_Decl_Expression (Env env, Decl_Expression *decl)
Type check_Decl_Expression (Env env, Decl_Expression *decl)
m_bool scan1_Func_Def (Env env, Func_Def f)
m_bool scan2_Func_Def (Env env, Func_Def f)
m_bool check_Func_Def (Env env, Func_Def f)
ID_List str2list (m_str path, m_uint *array_depth)
static m_bool mk_xtor (Type type, m_uint d, e_native_func e)
Type import_class_begin (Env env, Type type, NameSpace where, f_ctor pre_ctor, f_dtor dtor)
m_bool import_class_end (Env env)
static m_int import_var (Env env, const m_str type, const m_str name, const m_bool is_static, const m_bool is_const, const m_bool is_ref, m_uint *addr, const m_str doc)
m_int import_mvar (Env env, const m_str type, const m_str name, const m_bool is_const, const m_bool is_ref, const m_str doc)
m_int import_svar (Env env, const m_str type, const m_str name, m_bool is_const, m_bool is_ref, m_uint *addr, const m_str doc)
static Arg_List make_dll_arg_list (DL_Func *dl_fun)
Func_Def make_dll_as_fun (DL_Func *dl_fun, m_bool is_static)
static Func import_fun (Env env, DL_Func *mfun, m_bool is_static)
Func import_mfun (Env env, DL_Func *fun)
Func import_sfun (Env env, DL_Func *fun)
Macro Definition Documentation
CHECK_EB
#define CHECK_EB (a) if(!env->class_def) { err_msg(TYPE_, 0, "import error: import_xxx invoked between begin/end"); return -1; }
Definition at line 7 of file import.c.
Referenced by import_var().
CHECK_EO
#define CHECK_EO (a) if(!env->class_def) { err_msg(TYPE_, 0, "import error: import_xxx invoked between begin/end"); return NULL; }
Definition at line 8 of file import.c.
Referenced by import_fun().
CHECK_FN
#define CHECK_FN (a) if(a < 0) { if(func_def->func) rem_ref(func_def->func->obj, func_def->func); free_Func_Def(func_def); return NULL;}
Definition at line 309 of file import.c.
Referenced by import_fun().
Function Documentation
check_Decl_Expression()
Type check_Decl_Expression (Env env, Decl_Expression * decl)
Definition at line 388 of file type.c.
References Var_Decl_::array, check_array_subscripts(), check_Expression(), Value_::checked, NameSpace_::class_data_size, Env_::class_def, Env_::class_scope, Env_::curr, err_msg(), Array_Sub_::exp_list, find_value(), free(), Type_::info, Value_::is_member, Value_::is_static, Decl_Expression::is_static, Decl_Expression::list, Value_::m_type, Decl_Expression::m_type, Type_::name, namespace_add_value(), Var_Decl_List_::next, Type_::obj, Type_::obj_size, Value_::offset, NameSpace_::offset, Value_::owner_class, Type_::parent, Var_Decl_::pos, Decl_Expression::pos, S_name(), Var_Decl_List_::self, Type_::size, TYPE_, Var_Decl_::value, and Var_Decl_::xid.
Referenced by check_Expression(), check_Stmt(), and import_var().
 {
 #ifdef DEBUG_TYPE
   debug_msg("check", "decl");
 #endif
   Value value = NULL;
   Type type = NULL;
   Var_Decl_List list = decl->list;
   Var_Decl var_decl;
   while(list) {
     if(env->class_def && !env->class_scope &&
         (value = find_value(env->class_def->parent, list->self->xid))) {
       err_msg(TYPE_, list->self->pos,
               "in class '%s': '%s' has already been defined in parent class '%s'...",
               env->class_def->name, S_name(list->self->xid), value->owner_class->name);
 //      add_ref(env->class_def->obj);
 //      add_ref(env->class_def->obj);
       return NULL;
     }
     var_decl = list->self;
     value = list->self->value;
     if(!value) {
       err_msg(TYPE_, list->self->pos, "can't declare in GACK");
       return NULL;
     }
     type  = value->m_type;
     if(var_decl->array && var_decl->array->exp_list) {
       if(!check_Expression(env, var_decl->array->exp_list)) {
         free(type->obj);
         free(type);
         return NULL;
       }
       if(check_array_subscripts(env, var_decl->array->exp_list) < 0) {
         free(type->obj);
         free(type);
         return NULL;
       }
     }
     if(value->is_member) {
       value->offset = env->curr->offset;
       value->owner_class->obj_size += type->size;
       /* coverity[var_deref_op : FALSE] */
       env->class_def->obj_size += type->size;
       env->curr->offset += type->size;
     } else if( decl->is_static ) { // static
       if(!env->class_def || env->class_scope > 0 ) {
         err_msg(TYPE_, decl->pos,
                 "static variables must be declared at class scope..." );
         return NULL;
       }
       value->is_static = 1;
       // offset
       value->offset = env->class_def->info->class_data_size;
       // move the size
       env->class_def->info->class_data_size += type->size;
       /*      env->class_def->info->class_data_size++;*/
       /*
          if(is_obj && !is_ref)
          {
       // for now - no good for static, since we need separate
       // initialization which we don't have
       err_msg(TYPE_, var_decl->pos,
       "cannot declare static non-primitive objects (yet)..." );
       err_msg(TYPE_, var_decl->pos,
       "...(hint: declare as ref (@) & initialize outside for now)" );
       return NULL;
       }
       */
     }
     list->self->value->checked = 1;
     if(!env->class_def || env->class_scope)
       namespace_add_value(env->curr, list->self->xid, list->self->value);
     list = list->next;
   }
   return decl->m_type;
 }
check_Func_Def()
m_bool check_Func_Def (Env env, Func_Def f)
Definition at line 2248 of file type.c.
Referenced by emit_Func_Call(), and import_fun().
 {
 #ifdef DEBUG_TYPE
   debug_msg("check", "func def '%s'", f->func->name);
 #endif
   Value value = NULL;
   Func func = NULL;
   Type parent = NULL;
   Value override = NULL;
   Value  v = NULL;
   Value vararg = NULL;
   Func  parent_func = NULL;
   Arg_List arg_list = NULL;
   m_bool parent_match = 0;
   m_str func_name = S_name(f->name);
   //  m_str func_name = strdup(S_name(f->name)); // strdup might be unnnecessary. 27/11/16
   m_uint count = 1;
   m_bool has_code = 0;
   if(f->types) // templating, check at call time
     return 1;
   if(env->func) {
     err_msg(TYPE_, f->pos, "nested function definitions are not (yet) allowed");
     return -1;
   }
   func = f->func;
   value = func->value_ref;
   // look up the value in the parent class
   if(env->class_def)
     override = find_value(env->class_def->parent, f->name);
   else if(value->func_num_overloads) { // check if func has ame args
     m_uint i, j;
     if(!f->types)
       for(i = 0; i <= value->func_num_overloads; i++) {
         char name[1024];
         sprintf(name, "%s@%li@%s", S_name(f->name), i, env->curr->name);
         Func f1 = namespace_lookup_func(env->curr, insert_symbol(name), -1);
         for(j = 1; j <= value->func_num_overloads; j++) {
           if(i != j) {
             sprintf(name, "%s@%li@%s", S_name(f->name), j, env->curr->name);
             Func f2 = namespace_lookup_func(env->curr, insert_symbol(name), -1);
             if(compat_func(f1->def, f2->def, f2->def->pos) > 0) {
               err_msg(TYPE_, f2->def->pos, "global function '%s' already defined for those arguments", S_name(f->name));
               return -1;
             }
           }
         }
       }
   }
   if(env->class_def &&  override) {
     if(isa(override->m_type, &t_function) < 0) {
       err_msg(TYPE_, f->pos, "function name '%s' conflicts with previously defined value...",
               S_name(f->name));
       err_msg(TYPE_, f->pos, "from super class '%s'...", override->owner_class->name);
       goto error;
     }
   }
   if(override) {
     // make reference to parent
     // TODO: ref count
     func->up = override;
   }
   if(!env->class_def && f->static_decl == ae_key_abstract) {
     err_msg(TYPE_, f->pos, "non-class function cannot be declared as 'pure'...");
     err_msg(TYPE_, f->pos, "...at function '%s'", S_name(f->name) );
     goto error;
   }
   if(f->s_type == ae_func_user) has_code = (f->code != NULL);
   else has_code = (f->dl_func_ptr != NULL); // imported
   if(env->class_def && env->class_def->def && env->class_def->def->iface && has_code) {
     err_msg(TYPE_, f->pos, "interface function signatures cannot contain code..." );
     err_msg(TYPE_, f->pos, "...at function '%s'", S_name(f->name));
     goto error;
   }
   if(f->static_decl == ae_key_abstract && has_code) {
     err_msg(TYPE_, f->pos, "'pure' function signatures cannot contain code..." );
     err_msg(TYPE_, f->pos, "...at function '%s'", S_name(f->name));
     goto error;
   }
   if(f->static_decl != ae_key_abstract && !has_code) {
     err_msg(TYPE_, f->pos, "function declaration must contain code..." );
     err_msg(TYPE_, f->pos, "(unless in interface, or is declared 'pure')" );
     err_msg(TYPE_, f->pos, "...at function '%s'", S_name(f->name));
     goto error;
   }
   // TODO if overload, check arguments do not match
   // if overriding super class function, then check signatures
   if(env->class_def) {
     // get parent
     parent = env->class_def->parent;
     while( parent && !parent_match ) {
       if((v = find_value(env->class_def->parent, f->name))) {
         // see if the target is a function
         if(!isa( v->m_type, &t_function)) {
           err_msg(TYPE_, f->pos, "function name '%s' conflicts with previously defined value...",
                   S_name(f->name));
           err_msg(TYPE_, f->pos, "from super class '%s'...", v->owner_class->name );
           goto error;
         }
         // parent func
         parent_func = v->func_ref;
         // go through all overloading
         while(parent_func && !parent_match) {
           // match the prototypes
           if(compat_func(f, parent_func->def, f->pos) < 0) {
             // next
             parent_func = parent_func->next;
             // move on
             continue;
           }
           // see if parent function is static
           if( parent_func->def->static_decl == ae_key_static ) {
             err_msg(TYPE_, f->pos,
                     "function '%s.%s' resembles '%s.%s' but cannot override...",
                     env->class_def->name, S_name(f->name),
                     v->owner_class->name, S_name(f->name) );
             err_msg(TYPE_, f->pos,
                     "...(reason: '%s.%s' is declared as 'static')",
                     v->owner_class->name, S_name(f->name) );
             goto error;
           }
           // see if function is static
           if(f->static_decl == ae_key_static) {
             err_msg(TYPE_, f->pos,
                     "function '%s.%s' resembles '%s.%s' but cannot override...",
                     env->class_def->name, S_name(f->name),
                     v->owner_class->name, S_name(f->name));
             err_msg(TYPE_, f->pos,
                     "...(reason: '%s.%s' is declared as 'static')",
                     env->class_def->name, S_name(f->name));
             goto error;
           }
           // see if function is pure
           if(f->static_decl == ae_key_abstract) {
             err_msg(TYPE_, f->pos,
                     "function '%s.%s' resembles '%s.%s' but cannot override...",
                     env->class_def->name, S_name(f->name),
                     v->owner_class->name, S_name(f->name));
             err_msg(TYPE_, f->pos,
                     "...(reason: '%s.%s' is declared as 'pure')",
                     env->class_def->name, S_name(f->name));
             goto error;
           }
           // make sure returns are equal
           if(isa(f->ret_type, parent_func->def->ret_type) < 0) {
             err_msg(TYPE_, f->pos, "function signatures differ in return type..." );
             err_msg(TYPE_, f->pos,
                     "function '%s.%s' matches '%s.%s' but cannot override...",
                     env->class_def->name, S_name(f->name),
                     v->owner_class->name, S_name(f->name));
             goto error;
           }
           parent_match = 1;
           func->vt_index = parent_func->vt_index;
           vector_set(env->curr->obj_v_table, func->vt_index, (vtype)func);
           func_name = parent_func->name;
           func->name = func_name;
           value->name = func_name;
         }
       }
       // move to next parent
       parent = parent->parent;
     }
   }
   if(func->is_member && !parent_match) {
     func->vt_index = vector_size(env->curr->obj_v_table);
     vector_append(env->curr->obj_v_table, (vtype)func);
   }
   env->func = func;
   namespace_push_value(env->curr);
   arg_list = f->arg_list;
   while(arg_list) {
     v = arg_list->var_decl->value;
     if(namespace_lookup_value( env->curr, arg_list->var_decl->xid, 0)) {
       err_msg(TYPE_, arg_list->pos, "argument %i '%s' is already defined in this scope",
               count, S_name(arg_list->var_decl->xid) );
       err_msg(TYPE_, arg_list->pos, "in function '%s':", S_name(f->name));
       goto error;
     }
     v->checked  = 1;
     namespace_add_value(env->curr, arg_list->var_decl->xid, v );
     count++;
     arg_list = arg_list->next;
   }
   if(f->is_variadic) {
     vararg = new_Value(env->context, &t_vararg, "vararg");
     vararg->checked = 1;
     namespace_add_value(env->curr, insert_symbol("vararg"), vararg);
   }
   if(f->code && check_Stmt_Code(env, f->code->d.stmt_code, 0) < 0) {
     err_msg(TYPE_, f->pos, "...in function '%s'", S_name(f->name));
     goto error;
   }
   if(f->is_variadic)
     rem_ref(vararg->obj, vararg);
   if(f->s_type == ae_func_builtin) { // is this useful ?
     func->code->stack_depth = f->stack_depth;
     func->code->need_this = 1;
   }
 //  else
 //    func->code->need_this = 0;
   namespace_pop_value(env->curr);
   env->func = NULL;
   return 1;
 error:
   namespace_pop_value(env->curr);
   env->func = NULL;
   return -1;
 }
free_Expression()
void free_Expression (Expression exp)
Definition at line 773 of file absyn.c.
References Array_Expression_type, Binary_Expression_type, Cast_Expression_type, Expression_::d, Decl_Expression_type, Dot_Member_type, Dur_Expression_type, Expression_::exp_array, Expression_::exp_binary, Expression_::exp_cast, Expression_::exp_decl, Expression_::exp_dot, Expression_::exp_dur, Expression_::exp_func, Expression_::exp_if, Expression_::exp_postfix, Expression_::exp_primary, Expression_::exp_type, Expression_::exp_unary, free(), free_Array_Expression(), free_Binary_Expression(), free_Cast_Expression(), free_Decl_Expression(), free_Dot_Member_Expression(), free_Dur_Expression(), free_Func_Call(), free_If_Expression(), free_Postfix_Expression(), free_Primary_Expression(), free_Unary_Expression(), Func_Call_type, If_Expression_type, Expression_::next, Postfix_Expression_type, Primary_Expression_type, and Unary_Expression_type.
Referenced by free_Array_Expression(), free_Array_Sub(), free_Binary_Expression(), free_Cast_Expression(), free_complex(), free_Dot_Member_Expression(), free_Dur_Expression(), free_Func_Call(), free_If_Expression(), free_polar(), free_Postfix_Expression(), free_Primary_Expression(), free_Stmt(), free_Stmt_Case(), free_Stmt_For(), free_Stmt_If(), free_Stmt_Loop(), free_Stmt_Return(), free_Stmt_Switch(), free_Stmt_Until(), free_Stmt_While(), free_Unary_Expression(), free_Vec(), import_var(), and prepend_array_sub().
 {
   Expression tmp, curr = exp;
   while(curr) {
     switch(curr->exp_type) {
     case Decl_Expression_type:
       free_Decl_Expression(curr->d.exp_decl);
       break;
     case Binary_Expression_type:
       free_Binary_Expression(curr->d.exp_binary);
       break;
     case Unary_Expression_type:
       free_Unary_Expression(curr->d.exp_unary);
       break;
     case Primary_Expression_type:
       free_Primary_Expression(curr->d.exp_primary);
       break;
     case Cast_Expression_type:
       free_Cast_Expression(curr->d.exp_cast);
       break;
     case Postfix_Expression_type:
       free_Postfix_Expression(curr->d.exp_postfix);
       break;
     case Func_Call_type:
       free_Func_Call(curr->d.exp_func);
       break;
     case Array_Expression_type:
       free_Array_Expression(curr->d.exp_array);
       break;
     case If_Expression_type:
       free_If_Expression(curr->d.exp_if);
       break;
     case Dot_Member_type:
       free_Dot_Member_Expression(curr->d.exp_dot);
       break;
     case Dur_Expression_type:
       free_Dur_Expression(curr->d.exp_dur);
       break;
     default:
       printf("free Expression: unhandled exp type %i\n", curr->exp_type);
       break;
     }
     tmp = curr;
     curr = curr->next;
     free(tmp);
   }
 }
import_class_begin()
Type import_class_begin (Env env, Type type, NameSpace where, f_ctor pre_ctor, f_dtor dtor)
Definition at line 98 of file import.c.
References add_ref(), Env_::class_def, Env_::class_stack, Env_::curr, err_msg(), NameSpace_::filename, free_Vector(), Type_::has_constructor, Type_::has_destructor, Type_::info, Type_::is_complete, mk_xtor(), NameSpace_::name, Type_::name, NATIVE_CTOR, NATIVE_DTOR, new_NameSpace(), Env_::nspc_stack, NameSpace_::obj, Type_::obj, Type_::obj_size, NameSpace_::obj_v_table, NameSpace_::offset, Type_::owner, NameSpace_::parent, Type_::parent, TYPE_, vector_append(), and vector_copy().
Referenced by import_ana(), import_array(), import_asc(), import_ass(), import_centroid(), import_complex(), import_event(), import_fc(), import_fft(), import_fileio(), import_freq(), import_fullrect(), import_gain(), import_halfrect(), import_impulse(), import_kurtosis(), import_lib(), import_machine(), import_object(), import_rms(), import_rolloff(), import_shred(), import_sinosc(), import_skewness(), import_spread(), import_step(), import_string(), import_ugen(), import_vec3(), import_vec4(), and import_zerox().
 {
   if(type->info) {
     err_msg(TYPE_, 0, "during import: class '%s' already imported...", type->name);
     return NULL;
   }
   type->info = new_NameSpace();
   type->info->filename = "global_nspc";
   // add reference
   /*    SAFE_ADD_REF(type->info);*/
   add_ref(type->info->obj);
   type->info->name = type->name;
   type->info->parent = where;
   add_ref(type->info->parent->obj);
   if(pre_ctor)
     type->has_constructor = mk_xtor(type, (m_uint)pre_ctor, NATIVE_CTOR);
   if(dtor)
     type->has_destructor  = mk_xtor(type, (m_uint)dtor,     NATIVE_DTOR);
   if(type->parent) {
     type->info->offset = type->parent->obj_size;
     free_Vector(type->info->obj_v_table);
     type->info->obj_v_table = vector_copy(type->parent->info->obj_v_table);
   }
   type->owner = where;
   /*    SAFE_ADD_REF(type->owner);*/
   add_ref(type->owner->obj);
 //  type->size = SZ_INT;
 //    type->size = 1;
   // set the object size
   type->obj_size = 0; // TODO
   type->is_complete = 1;
 //    type_type = type_copy(env, &t_class);
 //    type_type->actual_type = type;
   // SAFE_REF_ASSIGN( type_type->actual_type, type );
   vector_append(env->nspc_stack, (vtype)env->curr);
   env->curr = type->info;
   vector_append(env->class_stack, (vtype)env->class_def);
   env->class_def = type;
 //    type->obj = new_VM_Object(e_type_obj);
   // ref count
   add_ref(type->obj);
   return type;
 }
import_class_end()
m_bool import_class_end (Env env)
Definition at line 144 of file import.c.
References Env_::class_def, Env_::class_stack, Env_::curr, err_msg(), Type_::info, Env_::nspc_stack, Type_::obj_size, NameSpace_::offset, TYPE_, vector_back(), and vector_pop().
Referenced by import_ana(), import_array(), import_asc(), import_ass(), import_centroid(), import_complex(), import_event(), import_fc(), import_fft(), import_fileio(), import_freq(), import_fullrect(), import_gain(), import_halfrect(), import_impulse(), import_kurtosis(), import_lib(), import_machine(), import_object(), import_rms(), import_rolloff(), import_shred(), import_sinosc(), import_skewness(), import_spread(), import_step(), import_string(), import_ugen(), import_vec3(), import_vec4(), and import_zerox().
 {
   if(!env->class_def) {
     err_msg(TYPE_, 0, "import: too many class_end called..." );
     return -1;
   }
   env->class_def->obj_size = env->class_def->info->offset;
   env->class_def = (Type)vector_back(env->class_stack);
   vector_pop(env->class_stack);
   env->curr = (NameSpace)vector_back(env->nspc_stack);
   vector_pop(env->nspc_stack);
   return 1;
 }
import_fun()
static Func import_fun (Env env, DL_Func * mfun, m_bool is_static) static
Definition at line 310 of file import.c.
References CHECK_EO, CHECK_FN, check_Func_Def(), CHECK_OO, Env_::class_def, Func_Def_::func, make_dll_as_fun(), scan1_Func_Def(), and scan2_Func_Def().
Referenced by import_mfun(), and import_sfun().
{
   Func_Def func_def;
   CHECK_OO(mfun) // probably deserve an err msg
   CHECK_EO(env->class_def)
   CHECK_OO((func_def = make_dll_as_fun(mfun, is_static)))
   CHECK_FN(scan1_Func_Def(env, func_def))
   CHECK_FN(scan2_Func_Def(env, func_def))
   CHECK_FN(check_Func_Def(env, func_def))
   return func_def->func;
 }
import_mfun()
Func import_mfun (Env env, DL_Func * fun)
Definition at line 322 of file import.c.
References import_fun().
Referenced by import_ana(), import_array(), import_event(), import_fc(), import_fft(), import_fileio(), import_gain(), import_impulse(), import_rolloff(), import_shred(), import_sinosc(), import_step(), import_string(), import_ugen(), import_vec3(), and import_vec4().
 { return import_fun(env, fun, 0); }
import_mvar()
m_int import_mvar (Env env, const m_str type, const m_str name, const m_bool is_const, const m_bool is_ref, const m_str doc)
Definition at line 202 of file import.c.
References import_var().
Referenced by import_ana(), import_complex(), import_event(), import_fc(), import_fileio(), import_object(), import_shred(), import_string(), import_vec3(), and import_vec4().
 { return import_var(env, type, name, 0, is_const, is_ref, NULL, doc); }
import_sfun()
Func import_sfun (Env env, DL_Func * fun)
Definition at line 323 of file import.c.
References import_fun().
Referenced by import_fileio(), import_lib(), import_machine(), and import_shred().
 { return import_fun(env, fun, 1); }
import_svar()
m_int import_svar (Env env, const m_str type, const m_str name, m_bool is_const, m_bool is_ref, m_uint * addr, const m_str doc)
Definition at line 205 of file import.c.
References import_var().
 { return import_var(env, type, name, 1, is_const, is_ref, addr, doc); }
import_var()
static m_int import_var (Env env, const m_str type, const m_str name, const m_bool is_static, const m_bool is_const, const m_bool is_ref, m_uint * addr, const m_str doc) static
Definition at line 158 of file import.c.
References Var_Decl_::addr, Var_Decl_::array, Type_Decl::array, check_Decl_Expression(), CHECK_EB, Env_::class_def, Expression_::d, Array_Sub_::depth, Value_::doc, err_msg(), Expression_::exp_decl, free_Expression(), Value_::is_const, Value_::is_import, Type_::name, new_array_sub(), new_Decl_Expression(), new_Type_Decl(), new_Var_Decl(), new_Var_Decl_List(), Value_::offset, scan1_Decl_Expression(), scan2_Decl_Expression(), str2list(), TYPE_, and Var_Decl_::value.
Referenced by import_mvar(), and import_svar().
{
   m_int ret = -1;
   m_uint array_depth;
   ID_List path;
   Type_Decl* type_decl;
   Var_Decl var_decl;
   Var_Decl_List var_decl_list;
   Expression exp_decl;
   CHECK_EB(env->class_def)
   if(!(path = str2list(type, &array_depth))) {
     err_msg(TYPE_, 0, "... during mvar import '%s.%s'...", env->class_def->name, name );
     return -1;
   }
   type_decl = new_Type_Decl(path, is_ref, 0);
   if(array_depth) {
     type_decl->array = new_array_sub(NULL, 0);
     type_decl->array->depth = array_depth;
   }
   var_decl = new_Var_Decl(name, NULL, 0);
   if(array_depth) {
     var_decl->array = new_array_sub(NULL, 0);
     var_decl->array->depth = array_depth;
   }
   var_decl_list = new_Var_Decl_List(var_decl, NULL, 0);
   exp_decl = new_Decl_Expression(type_decl, var_decl_list, 0, 0);
   var_decl->addr = (void *)addr;
   if(scan1_Decl_Expression(env, exp_decl->d.exp_decl) < 0)
     goto error;
   if(scan2_Decl_Expression(env, exp_decl->d.exp_decl) < 0)
     goto error;
   var_decl->value->is_const = is_const;
   if(!check_Decl_Expression(env, exp_decl->d.exp_decl))
     goto error;
   if(doc)
     var_decl->value->doc = doc;
   var_decl->value->is_import = 1;
   ret = var_decl->value->offset;
 error:
   free_Expression(exp_decl);
   return ret;
 }
make_dll_arg_list()
static Arg_List make_dll_arg_list (DL_Func * dl_fun) static
Definition at line 209 of file import.c.
References DL_Func::args, DL_Value::doc, Arg_List_::doc, err_msg(), free_Arg_List(), free_DL_Value(), free_ID_List(), free_Type_Decl(), free_Vector(), DL_Value::name, new_Arg_List(), new_array_sub(), new_Type_Decl(), new_Var_Decl(), prepend_array_sub(), str2list(), DL_Value::type, TYPE_, type_path(), vector_at(), and vector_size().
Referenced by make_dll_as_fun().
 {
   Arg_List arg_list    = NULL;
   Type_Decl* type_decl = NULL;
   Var_Decl var_decl    = NULL;
   ID_List type_path    = NULL;
   ID_List type_path2    = NULL;
 //  ID_List name_path    = NULL;
   Array_Sub array_sub  = NULL;
   DL_Value* arg        = NULL;
   m_uint array_depth = 0;
   m_uint array_depth2 = 0;
   m_int i = 0, j;
   for(i = vector_size(dl_fun->args) - 1; i >= 0; i--) {
     array_depth = array_depth2 = 0;
     array_sub = NULL;
     arg = (DL_Value*)vector_at(dl_fun->args, i);
     type_path = str2list(arg->type, &array_depth);
     if(!type_path) {
       err_msg(TYPE_,  0, "...at argument '%i'...", i + 1 );
       free_Vector(dl_fun->args);
       if(arg_list)
         free_Arg_List(arg_list);
       return NULL;
     }
     type_decl = new_Type_Decl( type_path, 0, 0 );
     type_path2 = str2list(arg->name, &array_depth2 );
     free_ID_List(type_path2);
     if(array_depth && array_depth2) {
       err_msg(TYPE_,  0, "array subscript specified incorrectly for built-in module" );
       // TODO: cleanup
       free_Type_Decl(type_decl);
       if(arg_list)
         free_Arg_List(arg_list);
       return NULL;
     }
     // TODO: arrays?
     if(array_depth2)
       array_depth = array_depth2;
     if(array_depth) {
       array_sub = new_array_sub( NULL, 0 );
       for(j = 1; j < array_depth; j++ )
         array_sub = prepend_array_sub( array_sub, NULL, 0 );
     }
     var_decl = new_Var_Decl(arg->name, array_sub, 0 );
     arg_list = new_Arg_List( type_decl, var_decl, arg_list, 0 );
     arg_list->doc = arg->doc;
     free_DL_Value(arg); /* could be free(arg) */
   }
   return arg_list;
 }
make_dll_as_fun()
Func_Def make_dll_as_fun (DL_Func * dl_fun, m_bool is_static)
Definition at line 262 of file import.c.
References add_type_decl_array(), ae_func_builtin, ae_key_func, ae_key_instance, ae_key_static, DL_Func::d, Func_Def_::dl_func_ptr, err_msg(), free_DL_Func(), make_dll_arg_list(), DL_Func::mfun, DL_Func::name, new_array_sub(), new_Func_Def(), new_Type_Decl(), prepend_array_sub(), Func_Def_::s_type, str2list(), DL_Func::type, TYPE_, and type_path().
Referenced by import_fun().
 {
   Func_Def func_def = NULL;
   ae_Keyword func_decl = ae_key_func;
   ae_Keyword static_decl = is_static ? ae_key_static : ae_key_instance;
   ID_List type_path = NULL;
   Type_Decl* type_decl = NULL;
   m_str name = NULL;
   Arg_List arg_list = NULL;
   m_uint i, array_depth = 0;
   type_path = str2list(dl_fun->type, &array_depth);
   if(!type_path) {
     // error
     err_msg(TYPE_, 0, "...during function import '%s' (type)...", dl_fun->name);
     goto error;
   }
   type_decl = new_Type_Decl(type_path, 0, 0);
   if(!type_decl) {
     // error
     err_msg(TYPE_, 0, "...during function import '%s' (type)...", dl_fun->name);
     goto error;
   }
   if(array_depth) {
     Array_Sub array_sub = new_array_sub(NULL, 0);
     for(i = 1; i < array_depth; i++ )
       array_sub = prepend_array_sub(array_sub, NULL, 0);
     type_decl = add_type_decl_array(type_decl, array_sub, 0);
   }
   name = dl_fun->name;
   arg_list = make_dll_arg_list(dl_fun);
   func_def = new_Func_Def(func_decl, static_decl, type_decl, name, arg_list, NULL, 0);
   func_def->s_type = ae_func_builtin;
   func_def->dl_func_ptr = (void*)(m_uint)dl_fun->d.mfun;
   free_DL_Func(dl_fun);
   return func_def;
 error:
   // clean up
   // if( !func_def ) delete_type_decl( type_decl );
   // else delete_func_def( func_def );
   return NULL;
 }
mk_xtor()
static m_bool mk_xtor (Type type, m_uint d, e_native_func e) static
Definition at line 78 of file import.c.
References NameSpace_::dtor, Type_::has_constructor, Type_::has_destructor, Type_::info, Type_::name, NATIVE_CTOR, new_VM_Code(), and NameSpace_::pre_ctor.
Referenced by import_class_begin().
{
     VM_Code* code;
     m_str name, filename;
     if(e == NATIVE_CTOR) {
       type->has_constructor = 1;
       name = "ctor";
       filename = "[internal ctor definition]";
       code = &type->info->pre_ctor;
     } else {
       type->has_destructor = 1;
       name = type->name;
       filename = "[internal dtor definition]";
       code = &type->info->dtor;
     }
     *code = new_VM_Code(NULL, SZ_INT, 1, name, filename);
     (*code)->native_func = (m_uint)d;
     (*code)->native_func_type = e;
     return 1;
 }
scan1_Decl_Expression()
m_bool scan1_Decl_Expression (Env env, Decl_Expression * decl)
Definition at line 14 of file scan1.c.
References add_ref(), Var_Decl_::array, CHECK_BB, err_msg(), Array_Sub_::exp_list, find_type(), Decl_Expression::list, Decl_Expression::m_type, Var_Decl_List_::next, Decl_Expression::num_decl, Type_::obj, Decl_Expression::pos, Type_Decl::ref, S_name(), SCAN1_, scan1_Expression(), Var_Decl_List_::self, Decl_Expression::type, verify_array(), Type_Decl::xid, and ID_List_::xid.
Referenced by import_var(), and scan1_Expression().
 {
 #ifdef DEBUG_SCAN1
   debug_msg("scan1", "decl ref:%i", decl->type->ref);
 #endif
   Var_Decl_List list = decl->list;
   Var_Decl var_decl = NULL;
   Type t = find_type(env, decl->type->xid);
   if(!t) {
     err_msg(SCAN1_, decl->pos, "type '%s' unknown in declaration ", S_name(decl->type->xid->xid));
     return -1;
   }
   /*
      if(t->def && t->def->iface)
      {
      err_msg(SCAN1_, decl->pos, "type '%s' is interface. cannot instantiate", S_name(decl->type->xid->xid));
      return -1;
      }
      */
   while(list) {
     var_decl = list->self;
     decl->num_decl++;
     if(var_decl->array) {
       CHECK_BB(verify_array(var_decl->array))
       if(var_decl->array->exp_list)
         CHECK_BB(scan1_Expression( env, var_decl->array->exp_list ))
         /* no need to scan subscripts at this point */
       }
     list = list->next;
   }
   decl->m_type = t;
   add_ref(decl->m_type->obj);
   return 1;
 }
scan1_Func_Def()
m_bool scan1_Func_Def (Env env, Func_Def f)
Definition at line 569 of file scan1.c.
Referenced by emit_Func_Call(), find_template_match(), and import_fun().
 {
 #ifdef DEBUG_SCAN1
   debug_msg("scan1", "func def");
 #endif
   if(f->spec == ae_func_spec_dtor && !env->class_def) {
     err_msg(SCAN1_, f->pos, "dtor must be in class def!!");
     goto error;
   }
   if(f->types)  // templating. nothing to be done here
     return 1;
   if(env->class_def && env->class_def->def && env->class_def->def->iface)
     f->static_decl = ae_key_abstract;
   Arg_List arg_list = NULL;
   m_uint count = 0;
   f->ret_type = find_type(env, f->type_decl->xid);
   if(!f->ret_type) {
     err_msg(SCAN1_, f->pos, "scan1: unknown return type '%s' of func '%s'",
             S_name(f->type_decl->xid->xid), S_name(f->name));
 //free(f);
 //    free_Func_Def(f);
     return -1;
 //    goto error;
   }
   // check if array
   if(f->type_decl->array) {
     CHECK_BB(verify_array(f->type_decl->array))
     Type t = NULL;
     Type t2 = f->ret_type;
     // should be partial and empty []
     if(f->type_decl->array->exp_list) {
       err_msg(SCAN1_, f->type_decl->array->pos, "in function '%s':", S_name(f->name) );
       err_msg(SCAN1_, f->type_decl->array->pos, "return array type must be defined with empty []'s" );
       goto error;
     }
     // create the new array type
     t = new_array_type(env, &t_array, f->type_decl->array->depth, t2, env->curr);
     // TODO: verify
     f->type_decl->ref = 1;
     f->ret_type = t;
     /*    SAFE_REF_ASSIGN( f->ret_type, t );*/
   }
   arg_list = f->arg_list;
   count = 1;
   while(arg_list) {
     arg_list->type = find_type(env, arg_list->type_decl->xid);
 // check this
     if(!arg_list->type)
       /*if(!arg_list->type && !(arg_list->type = namespace_lookup_type(env->curr, f->type_decl->xid->xid, 1)))*/
       /*if(!arg_list->type || !(arg_list->type = namespace_lookup_type(env->curr, f->type_decl->xid->xid, 1)))*/
     {
       m_str path = type_path(arg_list->type_decl->xid);
       err_msg(SCAN1_, arg_list->pos, "'%s' unknown type in argument %i of func %s", path, count, S_name(f->name));
       free(path);
       goto error;
     }
     count++;
     arg_list = arg_list->next;
   }
   // if operator,
   if(f->spec == ae_func_spec_op) {
     // check argument number
     if(count > 3 || count == 1) {
       err_msg(SCAN1_, f->pos, "operators can only have one or two arguments\n");
       goto error;
     }
     // and name
     if(name2op(S_name(f->name)) < 0) {
       err_msg(SCAN1_, f->pos, "%s is not a valid operator name\n", S_name(f->name));
       goto error;
     }
   }
   if(f->code && scan1_Stmt_Code(env, f->code->d.stmt_code, 0) < 0) {
     err_msg(SCAN1_, f->pos, "...in function '%s'\n", S_name(f->name));
     goto error;
   }
   return 1;
 error:
 //  free_Func_Def(f);
   return -1;
 }
scan2_Decl_Expression()
m_bool scan2_Decl_Expression (Env env, Decl_Expression * decl)
Definition at line 12 of file scan2.c.
References add_ref(), Var_Decl_::addr, Var_Decl_::array, Value_::checked, Env_::class_def, Env_::class_scope, Env_::context, context_add_value(), Env_::curr, Array_Sub_::depth, Value_::doc, Var_Decl_List_::doc, err_msg(), Array_Sub_::exp_list, Env_::func, Value_::is_context_global, Value_::is_member, Decl_Expression::is_static, isa(), isprim(), isres(), Decl_Expression::list, Decl_Expression::m_type, Type_::name, namespace_add_value(), namespace_lookup_value(), new_array_type(), new_Value(), Var_Decl_List_::next, Value_::obj, Type_::obj, Value_::owner, Value_::owner_class, Var_Decl_::pos, Decl_Expression::pos, Value_::ptr, Type_Decl::ref, S_name(), SCAN2_, scan2_Expression(), Var_Decl_List_::self, Type_::size, t_array, t_shred, Decl_Expression::type, Var_Decl_::value, verify_array(), and Var_Decl_::xid.
Referenced by import_var(), scan2_Expression(), and scan2_Stmt().
 {
 #ifdef DEBUG_SCAN2
   debug_msg("scan2", "Declaration");
 #endif
   Var_Decl_List list = decl->list;
   Type type = decl->m_type;
   if(isa(type, &t_shred) > 0)
     decl->type->ref = 1;
   if(!type->size) {
     err_msg(SCAN2_, decl->pos,
             "cannot declare variables of size '0' (i.e. 'void')..." );
     return -1;
   }
   if(!decl->type->ref) {
     if(env->class_def && (type == env->class_def) && !env->class_scope) {
       err_msg(SCAN2_, decl->pos,
               "...(note: object of type '%s' declared inside itself)", type->name);
       return -1;
     }
   }
   /*  if((isprim(type) > 0 || isa(type, &t_string ) > 0) && decl->type->ref)  // TODO: string*/
   if((isprim(type) > 0) && decl->type->ref) { // TODO: string
     err_msg(SCAN2_, decl->pos,
             "cannot declare references (@) of primitive type '%s'...", type->name);
     err_msg(SCAN2_, decl->pos,
             "...(primitive types: 'int', 'float', 'time', 'dur')" );
     return -1;
   }
   while(list) {
     if(isres(env, list->self->xid, list->self->pos) > 0) {
       err_msg(SCAN2_, list->self->pos, "... in variable declaration", S_name(list->self->xid));
       return -1;
     }
     if(namespace_lookup_value(env->curr, list->self->xid, 0)) {
       err_msg(SCAN2_, list->self->pos, "variable %s has already been defined in the same scope...", S_name(list->self->xid));
       return -1;
     }
     if( list->self->array != NULL ) {
       if(verify_array(list->self->array) < 0)
         return -1;
       Type t2 = type;
       if(list->self->array->exp_list) {
         if(scan2_Expression(env, list->self->array->exp_list) < 0)
           return -1;
       }
       type = new_array_type(env, &t_array, list->self->array->depth, t2, env->curr);
       if(!list->self->array->exp_list)
         decl->type->ref = 1;
       /*      SAFE_REF_ASSIGN( decl->ck_type, type );*/
       if(env->class_def)
         add_ref(type->obj);
       decl->m_type = type;
     }
     list->self->value = new_Value(env->context, type, S_name(list->self->xid));
     list->self->value->checked = 0;
     list->self->value->owner = env->curr;
     list->self->value->owner_class = env->func ? NULL : env->class_def;
     list->self->value->is_member = (env->class_def && !env->class_scope && !env->func && !decl->is_static);
     list->self->value->is_context_global = !env->class_def && !env->func;
     list->self->value->ptr = list->self->addr;
     namespace_add_value(env->curr, list->self->xid, list->self->value);
 //  add_ref(list->self->value->obj);
     // doc
     if(!env->class_def && !env->func)
       context_add_value(env->context, list->self->value, list->self->value->obj);
     if(list->doc)
       list->self->value->doc = list->doc;
     list = list->next;
   }
   return 1;
 }
scan2_Func_Def()
m_bool scan2_Func_Def (Env env, Func_Def f)
Definition at line 687 of file scan2.c.
Referenced by emit_Func_Call(), find_template_match(), and import_fun().
 {
   Type     type     = NULL;
   Value    value    = NULL;
   Func     func     = NULL;
   Value    overload = NULL;
   Arg_List arg_list = NULL;
   Value    v;
   m_str func_name = S_name(f->name);
   m_str orig_name = func_name;
   m_uint count = 0;
   if(env->func) {
     err_msg(SCAN2_, f->pos, "nested function definitions are not (yet) allowed");
     goto error;
   }
   if(f->types) {
     func = new_Func(func_name, f);
     overload = namespace_lookup_value(env->curr,  f->name, 0);
     if(overload)
       func->next = overload->func_ref->next;
     func->is_member = (env->class_def && (f->static_decl != ae_key_static));
     value = new_Value(env->context, &t_function, func_name);
     value->is_const = 1;
     value->owner = env->curr;
     value->owner_class = env->class_def;
     value->is_member = func->is_member;
     value->is_context_global = (env->class_def == NULL);
     value->func_ref = func;
     add_ref(value->func_ref->obj);
     func->value_ref = value;
     add_ref(value->obj);
     f->func = func;
     value->checked = 1;
     if(overload)
       overload->func_num_overloads++;
     else
       namespace_add_value(env->curr, insert_symbol(orig_name), value);
     char name[256];
     sprintf(name, "%s<template>@%li@%s", S_name(f->name),
             overload ? overload->func_num_overloads : 0, env->curr->name);
     namespace_add_value(env->curr, insert_symbol(name), value);
     return 1;
   }
   // overload
   overload = namespace_lookup_value(env->curr,  f->name, 0);
   if(overload) {
     if(isa(overload->m_type, &t_function) < 0) {
       err_msg(SCAN2_, f->pos, "function name '%s' is already used by another value", S_name(f->name));
       goto error;
     } else {
       if(!overload->func_ref) {
         err_msg(SCAN2_, f->pos, "internal error: missing function '%s'", overload->name );
         return -1;
       }
     }
   }
   char tmp[256];
   memset(tmp, 0, 256);
   m_uint len = strlen(func_name) + strlen("0") + strlen(env->curr->name) + 3;
   if(overload) {
     len = strlen(func_name) + ((overload->func_num_overloads + 1) % 10) + strlen(env->curr->name) + 3;
     snprintf(tmp, len + 1, "%s@%li@%s", func_name, ++overload->func_num_overloads, env->curr->name);
   } else
     snprintf(tmp, len + 1, "%s@0@%s", func_name, env->curr->name);
   func_name = strdup(tmp);
   func = new_Func(func_name, f);
 //  func = new_Func(func_name, tmp);
   func->is_member = (env->class_def && (f->static_decl != ae_key_static));
   if(f->s_type == ae_func_builtin) { // actual builtin func import
     func->code = new_VM_Code(NULL, func->def->stack_depth, 1, S_name(f->name), "builtin func code");
     func->code->need_this = func->is_member;
     func->code->native_func = (m_uint)func->def->dl_func_ptr;
   }
   type = calloc(1, sizeof(struct Type_));
   type->xid = te_function;
   type->name = strdup(tmp);
   type->parent = &t_function;
   type->size = SZ_INT;
   type->func = func;
   type->obj = new_VM_Object(e_type_obj);
   value = new_Value(env->context, type, func_name);
   value->is_const = 1;
   value->owner = env->curr;
   value->owner_class = env->class_def;
   value->is_member = func->is_member;
   value->is_context_global = (env->class_def == NULL);
   value->func_ref = func;
   add_ref(value->func_ref->obj);
   func->value_ref = value;
   f->func = func;
   add_ref(f->func->obj);
   if(overload) {
     func->next = overload->func_ref->next;
     overload->func_ref->next = func;
   }
   if(!f->ret_type) // template return value
     f->ret_type = find_type(env, f->type_decl->xid);
   if(isprim(f->ret_type) > 0 && f->type_decl->ref) { // TODO: string
     err_msg(SCAN2_,  f->type_decl->pos,
             "FUNC cannot declare references (@) of primitive type '%s'...\n", f->ret_type->name );
     err_msg(SCAN2_, f->type_decl->pos,
             "...(primitive types: 'int', 'float', 'time', 'dur')" );
     goto error;
   }
   arg_list = f->arg_list;
   count = 1;
   f->stack_depth = func->is_member ? SZ_INT : 0;
   namespace_push_value(env->curr);
   while(arg_list) {
     if(!arg_list->type) // template
       arg_list->type = find_type(env, arg_list->type_decl->xid);
     if(!arg_list->type->size) {
       err_msg(SCAN2_, arg_list->pos, "cannot declare variables of size '0' (i.e. 'void')...");
       namespace_pop_value(env->curr);
       goto error;
     }
     // check if reserved
     if(isres(env, arg_list->var_decl->xid, arg_list->pos) > 0) {
       err_msg(SCAN2_,  arg_list->pos, "in function '%s'", S_name(f->name) );
       namespace_pop_value(env->curr);
       goto error;
     }
     // primitive
     if( (isprim( arg_list->type ) > 0)
         && arg_list->type_decl->ref ) { // TODO: string
       err_msg(SCAN2_, arg_list->type_decl->pos,
               "cannot declare references (@) of primitive type '%s'...",
               arg_list->type->name);
       err_msg(SCAN2_, arg_list->type_decl->pos,
               "...(primitive types: 'int', 'float', 'time', 'dur')" );
       namespace_pop_value(env->curr);
       goto error;
     }
     if(arg_list->var_decl->array) {
       CHECK_BB(verify_array(arg_list->var_decl->array))
       Type t = arg_list->type;
       Type t2 = t;
       if(arg_list->var_decl->array->exp_list) { // should be partial and empty []
         err_msg(SCAN2_, arg_list->pos, "in function '%s':", S_name(f->name) );
         err_msg(SCAN2_, arg_list->pos, "argument %i '%s' must be defined with empty []'s",
                 count, S_name(arg_list->var_decl->xid) );
         namespace_pop_value(env->curr);
         goto error;
       }
       // create the new array type
       t = new_array_type(env, &t_array, arg_list->var_decl->array->depth, t2, env->curr);
       // set ref
       arg_list->type_decl->ref = 1;
       arg_list->type = t;
       /*      SAFE_REF_ASSIGN( arg_list->type, t );*/
     }
     // make new value
     v = calloc(1, sizeof(struct Value_));
     v->m_type = arg_list->type;
     //v->doc = arg_list->doc;
     v->name = S_name(arg_list->var_decl->xid);
     // remember the owner
     v->owner = env->curr;
     // function args not owned
     // v->owner_class = NULL;
     //  v->is_member = 0;
     namespace_add_value(env->curr, arg_list->var_decl->xid, v);
     // stack
     v->offset = f->stack_depth;
     f->stack_depth += arg_list->type->size;
     // remember
     if(arg_list->var_decl->value)
       free_Value(arg_list->var_decl->value);
     arg_list->var_decl->value = v;
     // count
     count++;
     // next arg
     arg_list = arg_list->next;
   }
   namespace_pop_value(env->curr);
   if(f->is_variadic)
     f->stack_depth += SZ_INT;
   else if(f->spec == ae_func_spec_op) {
     m_bool ret;
     m_str str = strdup(S_name(f->name));
     str = strsep(&str, "@");
     ret = name2op(str);
     free(str);
     if(ret == -1) {
       err_msg(SCAN2_, f->pos, "Invalid operator.");
       return -1;
     } else
       ret = add_binary_op(env, ret, f->arg_list->var_decl->value->m_type, f->arg_list->next->var_decl->value->m_type, f->ret_type, NULL, 1, 0);
     if(!env->class_def)
       context_add_func(env->context, func, func->obj);
     return ret;
   }
   value->checked = 1;
   // while making doc
   if(!env->class_def)
     context_add_func(env->context, func, func->obj);
   if(!overload)
     namespace_add_value(env->curr, insert_symbol(orig_name), value);
   else {
     namespace_add_value(env->curr, insert_symbol(func->name), value);
     if(overload->func_ref->def->ret_type) // template func don't check ret_type case
       if(!f->is_template) // template func don't check ret_type case
         if(f->ret_type->xid != overload->func_ref->def->ret_type->xid) {
           err_msg(SCAN2_,  f->pos, "function signatures differ in return type... '%s' and '%s'",
                   f->ret_type->name, overload->func_ref->def->ret_type->name );
           if(env->class_def)
             err_msg(SCAN2_, f->pos,
                     "function '%s.%s' matches '%s.%s' but cannot overload...",
                     env->class_def->name, S_name(f->name),
                     value->owner_class->name, S_name(f->name) );
 //return -1;
 //          goto error;
         }
   }
   namespace_add_func( env->curr, insert_symbol(func->name), func ); // template. is it necessary ?
   env->func = func;
   namespace_push_value(env->curr);
   if(f->code && scan2_Stmt_Code(env, f->code->d.stmt_code, 0) < 0) {
     err_msg(SCAN2_, f->pos, "...in function '%s'", S_name(f->name) );
     goto error;
   }
   namespace_pop_value(env->curr);
   env->func = NULL;
   if(f->spec == ae_func_spec_dtor) {
     f->func->is_dtor = 1;
     add_ref(f->func->value_ref->obj);
   }
   if(f->type_decl->doc)
     func->doc = f->type_decl->doc;
   return 1;
 error:
   if(func) {
     env->func = NULL;
     scope_rem(env->curr->func, f->name);
     func->def = NULL;
     f->func = NULL;
     rem_ref(func->obj, func);
   }
   if(value) {
     free(value->m_type->name);
     free(value->name);
     rem_ref(value->m_type->obj, value->m_type);
     rem_ref(value->obj, value);
   }
   return -1;
 }
str2list()
ID_List str2list (m_str path, m_uint * array_depth)
Definition at line 22 of file import.c.
References err_msg(), free(), free_ID_List(), insert_symbol(), last, prepend_id_list(), UTIL_, and ID_List_::xid.
Referenced by import_var(), make_dll_arg_list(), and make_dll_as_fun().
 {
   m_uint len = 0;
   m_int  i, j;
   char curr[256];
   ID_List list = NULL;
   char last = '\0';
   m_uint depth = 0;
   memset(curr, 0, 256);
   while(path[len] != '\0')
     len++;
   while(len > 2 && path[len - 1] == ']' && path[len - 2] == '[') {
     depth++;
     len -= 2;
   }
   for(i = len - 1; i >= 0; i--) {
     char c = path[i];
     if(c != '.') {
       if( (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')
           || (c == '_') || (c >= '0' && c <= '9') || (i == 0 && c == '@'))
         curr[i] = c;
       else {
         err_msg(UTIL_,  0, "illegal character '%c' in path '%s'...", c, path);
         free_ID_List(list);
         return NULL;
       }
     }
     if(c == '.' || i == 0) {
       if((i != 0 && last != '.' && last != '\0') ||
           (i == 0 && c != '.')) {
         m_int size = strlen(curr);
         for(j = 0; j < size / 2; j++) {
           char s = curr[j];
           curr[j] = curr[size - j - 1];
           curr[size - j - 1] = s;
         }
         list = prepend_id_list(curr, list, 0);
         memset(curr, 0, sizeof(curr));
       } else {
         err_msg(UTIL_,  0, "path '%s' must not begin or end with '.'", path);
         free_ID_List(list);
         return NULL;
       }
     }
     last = c;
   }
   path = strndup(path, len);
   list->xid = insert_symbol(path);
   if(array_depth)
     *array_depth = depth;
   free(path);
   return list;
 }